@startuml
!pragma layout smetana
"Closeable" <|-- "org.apache.kafka.common.network.Authenticator"
class org.apache.kafka.common.network.Authenticator {
authenticate() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#40]]]
handleAuthenticationFailure() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#47]]]
principal() : KafkaPrincipal [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#53]]]
principalSerde() : Optional<KafkaPrincipalSerde> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#58]]]
complete() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#63]]]
reauthenticate(ReauthenticationContext) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#86]]]
serverSessionExpirationTimeNanos() : Long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#102]]]
clientSessionReauthenticationTimeNanos() : Long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#119]]]
reauthenticationLatencyMs() : Long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#134]]]
pollResponseReceivedDuringReauthentication() : Optional<NetworkReceive> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#152]]]
connectedClientSupportsReauthentication() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/Authenticator.java.html#163]]]
} 
@enduml
