@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.network.ClientInformation"
class org.apache.kafka.common.network.ClientInformation {
+ClientInformation(String;String) : ClientInformation [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#29]]]
+softwareName() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#34]]]
+softwareVersion() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#38]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#43]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#49]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/ClientInformation.java.html#54]]]
} 
@enduml
