@startuml
!pragma layout smetana
ChannelMetadataRegistry <|-- org.apache.kafka.common.network.DefaultChannelMetadataRegistry
class org.apache.kafka.common.network.DefaultChannelMetadataRegistry {
+ registerCipherInformation(CipherInformation) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/DefaultChannelMetadataRegistry.java.html#9]]]
+ cipherInformation() : CipherInformation [[[././qc/clients/src/main/java/org/apache/kafka/common/network/DefaultChannelMetadataRegistry.java.html#16]]]
+ registerClientInformation(ClientInformation) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/DefaultChannelMetadataRegistry.java.html#21]]]
+ clientInformation() : ClientInformation [[[././qc/clients/src/main/java/org/apache/kafka/common/network/DefaultChannelMetadataRegistry.java.html#26]]]
+ close() : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/DefaultChannelMetadataRegistry.java.html#31]]]
} 
@enduml
