@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.common.network.KafkaChannel
class org.apache.kafka.common.network.KafkaChannel {
+  KafkaChannel(String;TransportLayer;Supplier<Authenticator>;int;MemoryPool;ChannelMetadataRegistry)
+  close()
+  principal()
+  principalSerde()
+  prepare()
+  disconnect()
+  state(ChannelState)
+  state()
+  finishConnect()
+  isConnected()
+  id()
+  selectionKey()
+  mute()
+  maybeUnmute()
+  handleChannelMuteEvent(ChannelMuteEvent)
+  muteState()
+  delayCloseOnAuthenticationFailure()
+  completeCloseOnAuthenticationFailure()
+  isMuted()
+  isInMutableState()
+  ready()
+  hasSend()
+  socketAddress()
+  socketDescription()
+  setSend(NetworkSend)
+  maybeCompleteSend()
+  read()
+  currentReceive()
+  maybeCompleteReceive()
+  write()
+  addNetworkThreadTimeNanos(long)
+  getAndResetNetworkThreadTimeNanos()
+  receive(NetworkReceive)
+  hasBytesBuffered()
+  equals(Object)
+  hashCode()
+  toString()
+  successfulAuthentications()
+  maybeBeginServerReauthentication(NetworkReceive;Supplier<Long>)
+  maybeBeginClientReauthentication(Supplier<Long>)
+  reauthenticationLatencyMs()
+  serverAuthenticationSessionExpired(long)
+  pollResponseReceivedDuringReauthentication()
+  connectedClientSupportsReauthentication()
+  swapAuthenticatorsAndBeginReauthentication(ReauthenticationContext)
+  channelMetadataRegistry()
} 
@enduml
