@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.common.network.KafkaChannel"
class org.apache.kafka.common.network.KafkaChannel {
+KafkaChannel(String;TransportLayer;Supplier<Authenticator>;int;MemoryPool;ChannelMetadataRegistry) : KafkaChannel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#138]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#153]]]
+principal() : KafkaPrincipal [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#163]]]
+principalSerde() : Optional<KafkaPrincipalSerde> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#167]]]
+prepare() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#176]]]
+disconnect() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#202]]]
+state(ChannelState) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#211]]]
+state() : ChannelState [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#215]]]
+finishConnect() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#219]]]
+isConnected() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#239]]]
+id() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#243]]]
+selectionKey() : SelectionKey [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#247]]]
mute() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#254]]]
maybeUnmute() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#267]]]
+handleChannelMuteEvent(ChannelMuteEvent) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#276]]]
+muteState() : ChannelMuteState [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#316]]]
-delayCloseOnAuthenticationFailure() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#324]]]
completeCloseOnAuthenticationFailure() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#332]]]
+isMuted() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#341]]]
+isInMutableState() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#345]]]
+ready() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#356]]]
+hasSend() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#360]]]
+socketAddress() : InetAddress [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#372]]]
+socketDescription() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#376]]]
+setSend(NetworkSend) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#383]]]
+maybeCompleteSend() : NetworkSend [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#390]]]
+read() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#401]]]
+currentReceive() : NetworkReceive [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#415]]]
+maybeCompleteReceive() : NetworkReceive [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#419]]]
+write() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#429]]]
+addNetworkThreadTimeNanos(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#440]]]
+getAndResetNetworkThreadTimeNanos() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#448]]]
-receive(NetworkReceive) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#454]]]
+hasBytesBuffered() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#469]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#474]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#486]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#491]]]
+successfulAuthentications() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#502]]]
+maybeBeginServerReauthentication(NetworkReceive;Supplier<Long>) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#534]]]
+maybeBeginClientReauthentication(Supplier<Long>) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#591]]]
+reauthenticationLatencyMs() : Long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#622]]]
+serverAuthenticationSessionExpired(long) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#635]]]
+pollResponseReceivedDuringReauthentication() : Optional<NetworkReceive> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#652]]]
connectedClientSupportsReauthentication() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#663]]]
-swapAuthenticatorsAndBeginReauthentication(ReauthenticationContext) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#667]]]
+channelMetadataRegistry() : ChannelMetadataRegistry [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java.html#675]]]
} 
@enduml
