@startuml
!pragma layout smetana
"TransportLayer" <|-- "org.apache.kafka.common.network.PlaintextTransportLayer"
class org.apache.kafka.common.network.PlaintextTransportLayer {
+PlaintextTransportLayer(SelectionKey) : PlaintextTransportLayer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#38]]]
+ready() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#44]]]
+finishConnect() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#49]]]
+disconnect() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#57]]]
+socketChannel() : SocketChannel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#62]]]
+selectionKey() : SelectionKey [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#67]]]
+isOpen() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#72]]]
+isConnected() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#77]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#82]]]
+handshake() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#92]]]
+read(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#102]]]
+read(ByteBuffer[]) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#114]]]
+read(ByteBuffer[];int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#127]]]
+write(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#139]]]
+write(ByteBuffer[]) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#151]]]
+write(ByteBuffer[];int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#165]]]
+hasPendingWrites() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#174]]]
+peerPrincipal() : Principal [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#182]]]
+addInterestOps(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#190]]]
+removeInterestOps(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#199]]]
+isMute() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#204]]]
+hasBytesBuffered() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#209]]]
+transferFrom(FileChannel;long;long) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/PlaintextTransportLayer.java.html#214]]]
} 
@enduml
