@startuml
!pragma layout smetana
"ChannelBuilder" <|-- "org.apache.kafka.common.network.SaslChannelBuilder"
class org.apache.kafka.common.network.SaslChannelBuilder {
+SaslChannelBuilder(Mode;Map<String,JaasContext>;SecurityProtocol;ListenerName;boolean;String;boolean;CredentialCache;DelegationTokenCache;String;Time;LogContext;Supplier<ApiVersionsResponse>) : SaslChannelBuilder [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#102]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#141]]]
+reconfigurableConfigs() : Set<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#189]]]
+validateReconfiguration(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#194]]]
+reconfigure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#200]]]
+listenerName() : ListenerName [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#206]]]
+buildChannel(String;SelectionKey;int;MemoryPool;ChannelMetadataRegistry) : KafkaChannel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#211]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#245]]]
buildTransportLayer(String;SelectionKey;SocketChannel;ChannelMetadataRegistry) : TransportLayer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#255]]]
buildServerAuthenticator(Map<String,?>;Map<String,AuthenticateCallbackHandler>;String;TransportLayer;Map<String,Subject>;Map<String,Long>;ChannelMetadataRegistry) : SaslServerAuthenticator [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#267]]]
buildClientAuthenticator(Map<String,?>;AuthenticateCallbackHandler;String;String;String;TransportLayer;Subject) : SaslClientAuthenticator [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#280]]]
loginManagers() : Map<String,LoginManager> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#291]]]
-defaultKerberosRealm() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#295]]]
-createClientCallbackHandler(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#300]]]
-createServerCallbackHandlers(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#309]]]
-createConnectionsMaxReauthMsMap(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#330]]]
defaultLoginClass() : Class<?extendsLogin> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#341]]]
-clientCallbackHandlerClass() : Class<?extendsAuthenticateCallbackHandler> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#349]]]
-maybeAddNativeGssapiCredentials(Subject) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#366]]]
gssManager() : GSSManager [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#397]]]
subject(String) : Subject [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java.html#402]]]
} 
@enduml
