@startuml
!pragma layout smetana
ChannelBuilder <|-- org.apache.kafka.common.network.SslChannelBuilder
class org.apache.kafka.common.network.SslChannelBuilder {
+ SslChannelBuilder(Mode;ListenerName;boolean;LogContext) : SslChannelBuilder [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#38]]]
+ configure(Map<String,?>) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#48]]]
+ reconfigurableConfigs() : Set<String> [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#64]]]
+ validateReconfiguration(Map<String,?>) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#69]]]
+ reconfigure(Map<String,?>) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#74]]]
+ listenerName() : ListenerName [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#79]]]
+ buildChannel(String;SelectionKey;int;MemoryPool;ChannelMetadataRegistry) : KafkaChannel [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#84]]]
+ close() : void [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#99]]]
buildTransportLayer(SslFactory;String;SelectionKey;ChannelMetadataRegistry) : SslTransportLayer [[[././qc/clients/src/main/java/org/apache/kafka/common/network/SslChannelBuilder.java.html#103]]]
} 
@enduml
