@startuml
!pragma layout smetana
"TransportLayer" <|-- "org.apache.kafka.common.network.SslTransportLayer"
class org.apache.kafka.common.network.SslTransportLayer {
+create(String;SelectionKey;SSLEngine;ChannelMetadataRegistry) : SslTransportLayer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#91]]]
SslTransportLayer(String;SelectionKey;SSLEngine;ChannelMetadataRegistry) : SslTransportLayer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#97]]]
startHandshake() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#111]]]
+ready() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#128]]]
+finishConnect() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#136]]]
+disconnect() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#147]]]
+socketChannel() : SocketChannel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#152]]]
+selectionKey() : SelectionKey [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#157]]]
+isOpen() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#162]]]
+isConnected() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#167]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#175]]]
+hasPendingWrites() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#216]]]
readFromSocketChannel() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#225]]]
flush(ByteBuffer) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#236]]]
+handshake() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#269]]]
-doHandshake() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#324]]]
-renegotiationException() : SSLHandshakeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#415]]]
-closingException() : IllegalStateException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#419]]]
-runDelegatedTasks() : HandshakeStatus [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#427]]]
-handshakeFinished() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#442]]]
-handshakeWrap(boolean) : SSLEngineResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#474]]]
-handshakeUnwrap(boolean;boolean) : SSLEngineResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#505]]]
+read(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#548]]]
+read(ByteBuffer[]) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#654]]]
+read(ByteBuffer[];int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#668]]]
+write(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#698]]]
+write(ByteBuffer[];int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#742]]]
+write(ByteBuffer[]) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#773]]]
+peerPrincipal() : Principal [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#782]]]
+sslSession() : SSLSession [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#795]]]
+addInterestOps(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#804]]]
+removeInterestOps(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#818]]]
delegatedTask() : Runnable [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#831]]]
-readFromAppBuffer(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#839]]]
netReadBufferSize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#852]]]
netWriteBufferSize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#856]]]
applicationBufferSize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#860]]]
netReadBuffer() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#864]]]
appReadBuffer() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#869]]]
-handshakeFailure(SSLException;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#878]]]
-maybeProcessHandshakeFailure(SSLException;boolean;IOException) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#913]]]
-maybeThrowSslAuthenticationException() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#928]]]
-handshakeWrapAfterFailure(boolean) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#945]]]
-clearWriteBuffer() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#962]]]
+isMute() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#970]]]
+hasBytesBuffered() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#975]]]
-updateBytesBuffered(boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#983]]]
+transferFrom(FileChannel;long;long) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java.html#991]]]
} 
@enduml
