@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerValidationUtils"
class org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerValidationUtils {
+validateClaimForExistenceAndType(OAuthBearerUnsecuredJws;boolean;String;Class<?>...) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#12]]]
+validateIssuedAt(OAuthBearerUnsecuredJws;boolean;long;int) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#28]]]
+validateExpirationTime(OAuthBearerUnsecuredJws;long;int) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#48]]]
+validateTimeConsistency(OAuthBearerUnsecuredJws) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#68]]]
+validateScope(OAuthBearerToken;List<String>) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#85]]]
-confirmNonNegative(int) : int [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#99]]]
-doesNotExistResult(boolean;String) : OAuthBearerValidationResult [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#106]]]
-OAuthBearerValidationUtils() : OAuthBearerValidationUtils [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/unsecured/OAuthBearerValidationUtils.java.html#111]]]
} 
@enduml
