@startuml
!pragma layout smetana
KafkaException <|-- org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerConfigException
class org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerConfigException {
+  OAuthBearerConfigException(String)
+  OAuthBearerConfigException(String;Throwable)
} 
@enduml
