@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.ClientRequest"
class org.apache.kafka.clients.ClientRequest {
+ClientRequest(String;AbstractRequest.Builder<?>;int;String;long;boolean;int;RequestCompletionHandler) : ClientRequest [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#47]]]
+toString() : String [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#66]]]
+expectResponse() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#77]]]
+apiKey() : ApiKeys [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#81]]]
+makeHeader(short) : RequestHeader [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#85]]]
+requestBuilder() : AbstractRequest.Builder<?> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#96]]]
+destination() : String [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#100]]]
+callback() : RequestCompletionHandler [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#104]]]
+createdTimeMs() : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#108]]]
+correlationId() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#112]]]
+requestTimeoutMs() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ClientRequest.java.html#116]]]
} 
@enduml
