@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.GroupRebalanceConfig
class org.apache.kafka.clients.GroupRebalanceConfig {
+  GroupRebalanceConfig(AbstractConfig;ProtocolType)
+  GroupRebalanceConfig(int;int;int;String;Optional<String>;long;boolean)
} 
@enduml
