@startuml
!pragma layout smetana
"MetadataUpdater" <|-- "org.apache.kafka.clients.ManualMetadataUpdater"
class org.apache.kafka.clients.ManualMetadataUpdater {
+ManualMetadataUpdater() : ManualMetadataUpdater [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#45]]]
+ManualMetadataUpdater(List<Node>) : ManualMetadataUpdater [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#49]]]
+setNodes(List<Node>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#53]]]
+fetchNodes() : List<Node> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#58]]]
+isUpdateDue(long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#63]]]
+maybeUpdate(long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#68]]]
+handleServerDisconnect(long;String;Optional<AuthenticationException>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#73]]]
+handleFailedRequest(long;Optional<KafkaException>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#79]]]
+handleSuccessfulResponse(RequestHeader;long;MetadataResponse) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#84]]]
+close() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/ManualMetadataUpdater.java.html#89]]]
} 
@enduml
