@startuml
!pragma layout smetana
"Closeable" <|-- "org.apache.kafka.clients.MetadataUpdater"
class org.apache.kafka.clients.MetadataUpdater {
fetchNodes() : List<Node> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#41]]]
isUpdateDue(long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#46]]]
maybeUpdate(long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#58]]]
handleServerDisconnect(long;String;Optional<AuthenticationException>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#70]]]
handleFailedRequest(long;Optional<KafkaException>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#78]]]
handleSuccessfulResponse(RequestHeader;long;MetadataResponse) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#86]]]
close() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/MetadataUpdater.java.html#92]]]
} 
@enduml
