@startuml
!pragma layout smetana
"Closeable" <|-- "org.apache.kafka.clients.Metadata"
class org.apache.kafka.clients.Metadata {
+Metadata(long;long;LogContext;ClusterResourceListeners) : Metadata [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#88]]]
+fetch() : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#111]]]
+timeToAllowUpdate(long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#121]]]
+timeToNextUpdate(long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#133]]]
+metadataExpireMs() : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#138]]]
+requestUpdate() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#145]]]
+requestUpdateForNewTopics() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#150]]]
+updateLastSeenEpochIfNewer(TopicPartition;int) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#167]]]
+lastSeenLeaderEpoch(TopicPartition) : Optional<Integer> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#192]]]
+updateRequested() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#201]]]
partitionMetadataIfCurrent(TopicPartition) : Optional<MetadataResponse.PartitionMetadata> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#208]]]
+topicIds() : Map<String,Uuid> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#223]]]
+currentLeader(TopicPartition) : LeaderAndEpoch [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#227]]]
+bootstrap(List<InetSocketAddress>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#238]]]
+updateWithCurrentRequestVersion(MetadataResponse;boolean;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#249]]]
+update(int;MetadataResponse;boolean;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#263]]]
-maybeSetMetadataError(Cluster) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#294]]]
-checkInvalidTopics(Cluster) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#300]]]
-checkUnauthorizedTopics(Cluster) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#307]]]
-handleMetadataResponse(MetadataResponse;boolean;long) : MetadataCache [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#317]]]
-updateLatestMetadata(MetadataResponse.PartitionMetadata;boolean;Uuid;Uuid) : Optional<MetadataResponse.PartitionMetadata> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#388]]]
+maybeThrowAnyException() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#428]]]
maybeThrowFatalException() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#437]]]
+maybeThrowExceptionForTopic(String) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#450]]]
-clearErrorsAndMaybeThrowException(Supplier<KafkaException>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#454]]]
-recoverableException() : KafkaException [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#463]]]
-recoverableExceptionForTopic(String) : KafkaException [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#472]]]
-clearRecoverableErrors() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#481]]]
+failedUpdate(long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#490]]]
+fatalError(KafkaException) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#500]]]
+updateVersion() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#507]]]
+lastSuccessfulUpdate() : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#514]]]
+close() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#522]]]
+isClosed() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#531]]]
+newMetadataRequestAndVersion(long) : MetadataRequestAndVersion [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#535]]]
newMetadataRequestBuilder() : MetadataRequest.Builder [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#557]]]
newMetadataRequestBuilderForNewTopics() : MetadataRequest.Builder [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#567]]]
retainTopic(String;boolean;long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/Metadata.java.html#571]]]
} 
@enduml
