@startuml
!pragma layout smetana
"KafkaClient" <|-- "org.apache.kafka.clients.NetworkClient"
class org.apache.kafka.clients.NetworkClient {
+NetworkClient(Selectable;Metadata;String;int;long;long;int;int;int;long;long;Time;boolean;ApiVersions;LogContext) : NetworkClient [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#131]]]
+NetworkClient(Selectable;Metadata;String;int;long;long;int;int;int;long;long;Time;boolean;ApiVersions;Sensor;LogContext) : NetworkClient [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#164]]]
+NetworkClient(Selectable;MetadataUpdater;String;int;long;long;int;int;int;long;long;Time;boolean;ApiVersions;LogContext) : NetworkClient [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#200]]]
+NetworkClient(MetadataUpdater;Metadata;Selectable;String;int;long;long;int;int;int;long;long;Time;boolean;ApiVersions;Sensor;LogContext;HostResolver) : NetworkClient [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#235]]]
+ready(Node;long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#296]]]
canConnect(Node;long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#311]]]
+disconnect(String) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#322]]]
-cancelInFlightRequests(String;long;Collection<ClientResponse>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#335]]]
+close(String) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#369]]]
+connectionDelay(Node;long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#387]]]
+throttleDelayMs(Node;long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#393]]]
+pollDelayMs(Node;long) : long [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#403]]]
+connectionFailed(Node) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#416]]]
+authenticationException(Node) : AuthenticationException [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#428]]]
+isReady(Node;long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#440]]]
-canSendRequest(String;long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#452]]]
+send(ClientRequest;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#463]]]
sendInternalMetadataRequest(MetadataRequest.Builder;String;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#468]]]
-doSend(ClientRequest;boolean;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#473]]]
-doSend(ClientRequest;boolean;long;AbstractRequest) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#521]]]
+poll(long;long) : List<ClientResponse> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#550]]]
-completeResponses(List<ClientResponse>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#584]]]
+inFlightRequestCount() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#598]]]
+hasInFlightRequests() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#603]]]
+inFlightRequestCount(String) : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#611]]]
+hasInFlightRequests(String) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#616]]]
+hasReadyNodes(long) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#621]]]
+wakeup() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#629]]]
+initiateClose() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#634]]]
+active() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#641]]]
-ensureActive() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#645]]]
+close() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#654]]]
+leastLoadedNode(long) : Node [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#675]]]
+parseResponse(ByteBuffer;RequestHeader) : AbstractResponse [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#731]]]
-processDisconnection(List<ClientResponse>;String;long;ChannelState) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#757]]]
-handleTimedOutRequests(List<ClientResponse>;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#796]]]
-handleAbortedSends(List<ClientResponse>) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#806]]]
-handleTimedOutConnections(List<ClientResponse>;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#819]]]
-handleCompletedSends(List<ClientResponse>;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#838]]]
-maybeThrottle(AbstractResponse;short;String;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#858]]]
-handleCompletedReceives(List<ClientResponse>;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#873]]]
-handleApiVersionsResponse(List<ClientResponse>;InFlightRequest;long;ApiVersionsResponse) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#898]]]
-handleDisconnections(List<ClientResponse>;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#938]]]
-handleConnections() : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#949]]]
-handleInitiateApiVersionRequests(long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#965]]]
-initiateConnect(Node;long) : void [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#990]]]
+newClientRequest(String;AbstractRequest.Builder<?>;long;boolean) : ClientRequest [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#1190]]]
nextCorrelationId() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#1198]]]
+newClientRequest(String;AbstractRequest.Builder<?>;long;boolean;int;RequestCompletionHandler) : ClientRequest [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#1207]]]
+discoverBrokerVersions() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java.html#1217]]]
} 
@enduml
