@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.api.Processor
class org.apache.kafka.streams.processor.api.Processor {
+  init(ProcessorContext<KOut,VOut>)
+  process(Record<KIn,VIn>)
+  close()
} 
@enduml
