@startuml
!pragma layout smetana
"Transformation<R>" <|-- "org.apache.kafka.connect.transforms.Cast"
class org.apache.kafka.connect.transforms.Cast {
+configure(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#99]]]
+apply(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#107]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#120]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#125]]]
-applySchemaless(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#129]]]
-applyWithSchema(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#143]]]
-getOrBuildSchema(Schema) : Schema [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#165]]]
-convertFieldType(Schema.Type) : SchemaBuilder [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#201]]]
-encodeLogicalType(Schema;Object) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#224]]]
-castValueToType(Schema;Object;Schema.Type) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#236]]]
-castToInt8(Object) : byte [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#279]]]
-castToInt16(Object) : short [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#290]]]
-castToInt32(Object) : int [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#301]]]
-castToInt64(Object) : long [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#312]]]
-castToFloat32(Object) : float [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#323]]]
-castToFloat64(Object) : double [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#334]]]
-castToBoolean(Object) : boolean [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#345]]]
-castToString(Object) : String [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#356]]]
operatingSchema(R) : Schema [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#371]]]
operatingValue(R) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#373]]]
newRecord(R;Schema;Object) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#375]]]
-parseFieldTypes(List<String>) : Map<String,Schema.Type> [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#377]]]
-validCastType(Schema.Type;FieldType) : Schema.Type [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#410]]]
} 
@enduml
