@startuml
!pragma layout smetana
"Transformation<R>" <|-- "org.apache.kafka.connect.transforms.Cast"
class org.apache.kafka.connect.transforms.Cast {
+configure(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#114]]]
+apply(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#122]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#135]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#140]]]
-applySchemaless(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#144]]]
-applyWithSchema(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#158]]]
-getOrBuildSchema(Schema) : Schema [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#180]]]
-convertFieldType(Schema.Type) : SchemaBuilder [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#216]]]
-encodeLogicalType(Schema;Object) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#239]]]
-castValueToType(Schema;Object;Schema.Type) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#251]]]
-castToInt8(Object) : byte [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#294]]]
-castToInt16(Object) : short [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#305]]]
-castToInt32(Object) : int [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#316]]]
-castToInt64(Object) : long [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#327]]]
-castToFloat32(Object) : float [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#338]]]
-castToFloat64(Object) : double [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#349]]]
-castToBoolean(Object) : boolean [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#360]]]
-castToString(Object) : String [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#371]]]
operatingSchema(R) : Schema [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#386]]]
operatingValue(R) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#388]]]
newRecord(R;Schema;Object) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#390]]]
-parseFieldTypes(List<String>) : Map<String,Schema.Type> [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#392]]]
-validCastType(Schema.Type;FieldType) : Schema.Type [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/Cast.java.html#425]]]
} 
@enduml
