@startuml
!pragma layout smetana
"Transformation<R>" <|-- "org.apache.kafka.connect.transforms.ExtractField"
class org.apache.kafka.connect.transforms.ExtractField {
+configure(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#49]]]
+apply(R) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#55]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#73]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#77]]]
operatingSchema(R) : Schema [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#81]]]
operatingValue(R) : Object [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#83]]]
newRecord(R;Schema;Object) : R [[[./../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java.html#85]]]
} 
@enduml
