@startuml
!pragma layout smetana
Transformation<R> <|-- org.apache.kafka.connect.transforms.Flatten
class org.apache.kafka.connect.transforms.Flatten {
+  configure(Map<String,?>)
+  apply(R)
+  close()
+  config()
+  operatingSchema(R)
+  operatingValue(R)
+  newRecord(R;Schema;Object)
+  applySchemaless(R)
+  applySchemaless(Map<String,Object>;String;Map<String,Object>)
+  applyWithSchema(R)
+  buildUpdatedSchema(Schema;String;SchemaBuilder;boolean;Struct)
+  convertFieldSchema(Schema;boolean;Object)
+  buildWithSchema(Struct;String;Struct)
+  fieldName(String;String)
} 
@enduml
