@startuml
!pragma layout smetana
Transformation<R> <|-- org.apache.kafka.connect.transforms.HoistField
class org.apache.kafka.connect.transforms.HoistField {
+  configure(Map<String,?>)
+  apply(R)
+  close()
+  config()
+  operatingSchema(R)
+  operatingValue(R)
+  newRecord(R;Schema;Object)
} 
@enduml
