@startuml
!pragma layout smetana
Transformation_R_ <|-- org.apache.kafka.connect.transforms.SetSchemaMetadata
class org.apache.kafka.connect.transforms.SetSchemaMetadata {
+  configure(Map<String,?>)
+  apply(R)
+  config()
+  close()
+  operatingSchema(R)
+  operatingValue(R)
+  newRecord(R;Schema)
+  updateSchemaIn(Object;Schema)
} 
@enduml
