@startuml
!pragma layout smetana
URLClassLoader <|-- org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader
class org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader {
+ DelegatingClassLoader(List<String>;ClassLoader) : DelegatingClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#85]]]
+ DelegatingClassLoader(List<String>) : DelegatingClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#101]]]
+ connectors() : Set<PluginDesc<Connector>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#110]]]
+ sinkConnectors() : Set<PluginDesc<SinkConnector>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#116]]]
+ sourceConnectors() : Set<PluginDesc<SourceConnector>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#120]]]
+ converters() : Set<PluginDesc<Converter>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#124]]]
+ headerConverters() : Set<PluginDesc<HeaderConverter>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#128]]]
+ transformations() : Set<PluginDesc<Transformation<?>>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#132]]]
+ predicates() : Set<PluginDesc<Predicate<?>>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#136]]]
+ configProviders() : Set<PluginDesc<ConfigProvider>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#140]]]
+ restExtensions() : Set<PluginDesc<ConnectRestExtension>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#144]]]
+ connectorClientConfigPolicies() : Set<PluginDesc<ConnectorClientConfigOverridePolicy>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#148]]]
+ pluginClassLoader(String) : PluginClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#153]]]
+ connectorLoader(Connector) : ClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#167]]]
+ connectorLoader(String) : ClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#171]]]
newPluginClassLoader(URL;URL[];ClassLoader) : PluginClassLoader [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#183]]]
initLoaders() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#207]]]
- initPluginLoader(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#216]]]
- registerPlugin(Path) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#246]]]
- scanUrlsAndAddPlugins(ClassLoader;URL[]) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#265]]]
- loadJdbcDrivers(ClassLoader) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#295]]]
- scanPluginPath(ClassLoader;URL[]) : PluginScanResult [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#325]]]
- getPredicatePluginDesc(ClassLoader;Reflections) : Collection<PluginDesc<Predicate<?>>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#350]]]
- getTransformationPluginDesc(ClassLoader;Reflections) : Collection<PluginDesc<Transformation<?>>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#355]]]
loadClass(String;boolean) : Class<?> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#416]]]
- addAllAliases() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#427]]]
+ getResource(String) : URL [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#480]]]
+ getResources(String) : Enumeration<URL> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#491]]]
serviceLoaderManifestForPlugin(String) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java.html#502]]]
} 
@enduml
