@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.connect.runtime.isolation.LoaderSwap
class org.apache.kafka.connect.runtime.isolation.LoaderSwap {
+  LoaderSwap(ClassLoader)
+  close()
} 
@enduml
