@startuml
!pragma layout smetana
StoreSupplier_KeyValueStore_Bytes,byte[]__ <|-- org.apache.kafka.streams.state.KeyValueBytesStoreSupplier
class org.apache.kafka.streams.state.KeyValueBytesStoreSupplier {
} 
@enduml
