@startuml
!pragma layout smetana
"StateStore" <|-- "org.apache.kafka.streams.state.KeyValueStore"
class org.apache.kafka.streams.state.KeyValueStore {
put(K;V) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java.html#39]]]
putIfAbsent(K;V) : V [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java.html#39]]]
putAll(List<KeyValue<K,V>>) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java.html#39]]]
delete(K) : V [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java.html#39]]]
} 
@enduml
