@startuml
!pragma layout smetana
"Iterator<KeyValue<K,V>>" <|-- "org.apache.kafka.streams.state.KeyValueIterator"
class org.apache.kafka.streams.state.KeyValueIterator {
close() : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueIterator.java.html#37]]]
peekNextKey() : K [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/KeyValueIterator.java.html#43]]]
} 
@enduml
