@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.ReadOnlySessionStore"
class org.apache.kafka.streams.state.ReadOnlySessionStore {
findSessions(K;long;long) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#61]]]
findSessions(K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#95]]]
backwardFindSessions(K;long;long) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#129]]]
backwardFindSessions(K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#163]]]
findSessions(K;K;long;long) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#200]]]
findSessions(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#238]]]
backwardFindSessions(K;K;long;long) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#276]]]
backwardFindSessions(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#314]]]
fetchSession(K;long;long) : AGG [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#332]]]
fetchSession(K;Instant;Instant) : AGG [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#349]]]
fetch(K) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#368]]]
backwardFetch(K) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#382]]]
fetch(K;K) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#401]]]
backwardFetch(K;K) : KeyValueIterator<Windowed<K>,AGG> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlySessionStore.java.html#417]]]
} 
@enduml
