@startuml
!pragma layout smetana
StateStore <|-- org.apache.kafka.streams.state.SessionStore
class org.apache.kafka.streams.state.SessionStore {
findSessions(long;long) : KeyValueIterator<Windowed<K>,AGG> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#17]]]
findSessions(K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#24]]]
backwardFindSessions(K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#36]]]
findSessions(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#47]]]
backwardFindSessions(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,AGG> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#60]]]
fetchSession(K;Instant;Instant) : AGG [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#73]]]
remove(Windowed<K>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#84]]]
put(Windowed<K>;AGG) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java.html#87]]]
} 
@enduml
