@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.StoreBuilder"
class org.apache.kafka.streams.state.StoreBuilder {
withCachingEnabled() : StoreBuilder<T> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#33]]]
withCachingDisabled() : StoreBuilder<T> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#39]]]
withLoggingEnabled(Map<String,String>) : StoreBuilder<T> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#47]]]
withLoggingDisabled() : StoreBuilder<T> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#55]]]
build() : T [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#62]]]
logConfig() : Map<String,String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#72]]]
loggingEnabled() : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#77]]]
name() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StoreBuilder.java.html#85]]]
} 
@enduml
