@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.StreamsMetadata"
class org.apache.kafka.streams.state.StreamsMetadata {
+StreamsMetadata(HostInfo;Set<String>;Set<TopicPartition>;Set<String>;Set<TopicPartition>) : StreamsMetadata [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#56]]]
+hostInfo() : HostInfo [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#75]]]
+stateStoreNames() : Set<String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#84]]]
+topicPartitions() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#93]]]
+standbyTopicPartitions() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#102]]]
+standbyStateStoreNames() : Set<String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#111]]]
+host() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#115]]]
+port() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#120]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#125]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#142]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/StreamsMetadata.java.html#147]]]
} 
@enduml
