@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.state.StreamsMetadata
class org.apache.kafka.streams.state.StreamsMetadata {
+  StreamsMetadata(HostInfo;Set<String>;Set<TopicPartition>;Set<String>;Set<TopicPartition>)
+  hostInfo()
+  stateStoreNames()
+  topicPartitions()
+  standbyTopicPartitions()
+  standbyStateStoreNames()
+  host()
+  port()
+  equals(Object)
+  hashCode()
+  toString()
} 
@enduml
