@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.ValueAndTimestamp"
class org.apache.kafka.streams.state.ValueAndTimestamp {
-ValueAndTimestamp(V;long) : ValueAndTimestamp [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#32]]]
+value() : V [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#65]]]
+timestamp() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#69]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#74]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#79]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/ValueAndTimestamp.java.html#92]]]
} 
@enduml
