@startuml
!pragma layout smetana
KeyValueIterator<Long,V> <|-- org.apache.kafka.streams.state.WindowStoreIterator
class org.apache.kafka.streams.state.WindowStoreIterator {
+  close()
} 
@enduml
