@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.examples.pageview.PageViewUntypedDemo
class org.apache.kafka.streams.examples.pageview.PageViewUntypedDemo {
+main(String[]) : void [[[./../../../../../../../../../../../.././qc/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedDemo.java.html#31]]]
} 
@enduml
