@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.protocol.MessageUtil"
class org.apache.kafka.common.protocol.MessageUtil {
+byteBufferToArray(ByteBuffer) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#41]]]
+deepToString(Iterator<?>) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#52]]]
+jsonNodeToByte(JsonNode;String) : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#65]]]
+jsonNodeToShort(JsonNode;String) : short [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#84]]]
+jsonNodeToUnsignedShort(JsonNode;String) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#93]]]
+jsonNodeToUnsignedInt(JsonNode;String) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#102]]]
+jsonNodeToInt(JsonNode;String) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#111]]]
+jsonNodeToLong(JsonNode;String) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#137]]]
+jsonNodeToBinary(JsonNode;String) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#163]]]
+jsonNodeToDouble(JsonNode;String) : double [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#175]]]
+duplicate(byte[]) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#183]]]
+compareRawTaggedFields(List<RawTaggedField>;List<RawTaggedField>) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#193]]]
+toByteBuffer(Message;short) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#204]]]
+toVersionPrefixedByteBuffer(short;Message) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#213]]]
+toVersionPrefixedBytes(short;Message) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java.html#223]]]
} 
@enduml
