@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.protocol.ObjectSerializationCache"
class org.apache.kafka.common.protocol.ObjectSerializationCache {
+ObjectSerializationCache() : ObjectSerializationCache [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java.html#35]]]
+setArraySizeInBytes(Object;Integer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java.html#39]]]
+getArraySizeInBytes(Object) : Integer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java.html#43]]]
+cacheSerializedValue(Object;byte[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java.html#47]]]
+getSerializedValue(Object) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java.html#51]]]
} 
@enduml
