@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.snapshot.RawSnapshotReader
class org.apache.kafka.snapshot.RawSnapshotReader {
snapshotId() : OffsetAndEpoch [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RawSnapshotReader.java.html#11]]]
sizeInBytes() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RawSnapshotReader.java.html#14]]]
slice(long;int) : UnalignedRecords [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RawSnapshotReader.java.html#17]]]
records() : Records [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RawSnapshotReader.java.html#20]]]
} 
@enduml
