@startuml
!pragma layout smetana
"SnapshotReader<T>" <|-- "org.apache.kafka.snapshot.RecordsSnapshotReader"
class org.apache.kafka.snapshot.RecordsSnapshotReader {
-RecordsSnapshotReader(OffsetAndEpoch;RecordsIterator<T>) : RecordsSnapshotReader [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#37]]]
+snapshotId() : OffsetAndEpoch [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#46]]]
+lastContainedLogOffset() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#51]]]
+lastContainedLogEpoch() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#56]]]
+lastContainedLogTimestamp() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#61]]]
+hasNext() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#78]]]
+next() : Batch<T> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#87]]]
+close() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#99]]]
-nextBatch() : Optional<Batch<T>> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/RecordsSnapshotReader.java.html#118]]]
} 
@enduml
