@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.snapshot.SnapshotWriter"
class org.apache.kafka.snapshot.SnapshotWriter {
snapshotId() : OffsetAndEpoch [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#12]]]
lastContainedLogOffset() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#15]]]
lastContainedLogEpoch() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#18]]]
isFrozen() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#21]]]
append(List<T>) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#24]]]
freeze() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#27]]]
close() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/snapshot/SnapshotWriter.java.html#30]]]
} 
@enduml
