@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.server.common.serialization.BytesApiMessageSerde"
class org.apache.kafka.server.common.serialization.BytesApiMessageSerde {
+serialize(ApiMessageAndVersion) : byte[] [[[./../../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/common/serialization/BytesApiMessageSerde.java.html#45]]]
+deserialize(byte[]) : ApiMessageAndVersion [[[./../../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/common/serialization/BytesApiMessageSerde.java.html#54]]]
+apiMessageFor(short) : ApiMessage [[[./../../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/common/serialization/BytesApiMessageSerde.java.html#66]]]
} 
@enduml
