@startuml
!pragma layout smetana
"Iterable<Header>" <|-- "org.apache.kafka.connect.header.Headers"
class org.apache.kafka.connect.header.Headers {
size() : int [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#39]]]
isEmpty() : boolean [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#46]]]
allWithName(String) : Iterator<Header> [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#54]]]
lastWithName(String) : Header [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#62]]]
add(Header) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#70]]]
add(String;SchemaAndValue) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#79]]]
add(String;Object;Schema) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#89]]]
addString(String;String) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#98]]]
addBoolean(String;boolean) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#107]]]
addByte(String;byte) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#116]]]
addShort(String;short) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#125]]]
addInt(String;int) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#134]]]
addLong(String;long) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#143]]]
addFloat(String;float) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#152]]]
addDouble(String;double) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#161]]]
addBytes(String;byte[]) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#170]]]
addList(String;List<?>;Schema) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#181]]]
addMap(String;Map<?,?>;Schema) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#192]]]
addStruct(String;Struct) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#202]]]
addDecimal(String;BigDecimal) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#211]]]
addDate(String;java.util.Date) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#220]]]
addTime(String;java.util.Date) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#229]]]
addTimestamp(String;java.util.Date) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#238]]]
remove(String) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#246]]]
retainLatest(String) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#254]]]
retainLatest() : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#261]]]
clear() : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#268]]]
duplicate() : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#274]]]
apply(HeaderTransform) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#283]]]
apply(String;HeaderTransform) : Headers [[[./../../../../../../../../../../.././qc/connect/api/src/main/java/org/apache/kafka/connect/header/Headers.java.html#293]]]
} 
@enduml
