@startuml
!pragma layout smetana
"ConnectClusterState" <|-- "org.apache.kafka.connect.runtime.health.ConnectClusterStateImpl"
class org.apache.kafka.connect.runtime.health.ConnectClusterStateImpl {
+ConnectClusterStateImpl(long;ConnectClusterDetails;Herder) : ConnectClusterStateImpl [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#45]]]
+connectors() : Collection<String> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#56]]]
+connectorHealth(String) : ConnectorHealth [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#67]]]
+connectorConfig(String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#84]]]
+clusterDetails() : ConnectClusterDetails [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#98]]]
-taskStates(List<ConnectorStateInfo.TaskState>) : Map<Integer,TaskState> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/health/ConnectClusterStateImpl.java.html#102]]]
} 
@enduml
