@startuml
!pragma layout smetana
WrappedStateStore_KeyValueStore_Bytes,byte[]_,byte[],byte[]_KeyValueStore_Bytes,byte[]_ <|-- org.apache.kafka.streams.state.internals.CachingKeyValueStore
class org.apache.kafka.streams.state.internals.CachingKeyValueStore {
CachingKeyValueStore(KeyValueStore<Bytes,byte[]>;boolean) : CachingKeyValueStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#76]]]
+init(ProcessorContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#85]]]
+init(StateStoreContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#95]]]
+getPosition() : Position [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#105]]]
-initInternal(InternalProcessorContext<?,?>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#193]]]
-putAndMaybeForward(ThreadCache.DirtyEntry;InternalProcessorContext<?,?>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#203]]]
+setFlushListener(CacheFlushListener<byte[],byte[]>;boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#239]]]
+put(Bytes;byte[]) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#248]]]
-putInternal(Bytes;byte[]) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#262]]]
+putIfAbsent(Bytes;byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#280]]]
+putAll(List<KeyValue<Bytes,byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#298]]]
+delete(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#313]]]
-deleteInternal(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#325]]]
+get(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#332]]]
-getInternal(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#350]]]
+range(Bytes;Bytes) : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#372]]]
+reverseRange(Bytes;Bytes) : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#389]]]
+all() : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#406]]]
+reverseAll() : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#425]]]
+approximateNumEntries() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#434]]]
+flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#446]]]
+flushCache() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#459]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CachingKeyValueStore.java.html#471]]]
} 
@enduml
