@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.state.internals.CacheFlushListener
class org.apache.kafka.streams.state.internals.CacheFlushListener {
+  apply(Record<K,Change<V>>)
} 
@enduml
