@startuml
!pragma layout smetana
ReadOnlyWindowStore_K,V_ <|-- org.apache.kafka.streams.state.internals.CompositeReadOnlyWindowStore
class org.apache.kafka.streams.state.internals.CompositeReadOnlyWindowStore {
+CompositeReadOnlyWindowStore(StateStoreProvider;QueryableStoreType<ReadOnlyWindowStore<K,V>>;String) : CompositeReadOnlyWindowStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#22]]]
+fetch(K;long) : V [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#31]]]
+fetch(K;Instant;Instant) : WindowStoreIterator<V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#50]]]
+backwardFetch(K;Instant;Instant) : WindowStoreIterator<V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#73]]]
+fetch(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#96]]]
+backwardFetch(K;K;Instant;Instant) : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#110]]]
+all() : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#124]]]
+backwardAll() : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#135]]]
+fetchAll(Instant;Instant) : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#146]]]
+backwardFetchAll(Instant;Instant) : KeyValueIterator<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/CompositeReadOnlyWindowStore.java.html#158]]]
} 
@enduml
