@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.ContextualRecord"
class org.apache.kafka.streams.state.internals.ContextualRecord {
+ContextualRecord(byte[];ProcessorRecordContext) : ContextualRecord [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#31]]]
+recordContext() : ProcessorRecordContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#36]]]
+value() : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#40]]]
residentMemorySizeEstimate() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#44]]]
deserialize(ByteBuffer) : ContextualRecord [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#48]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#55]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#68]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java.html#73]]]
} 
@enduml
