@startuml
!pragma layout smetana
"WindowStore<Bytes,byte[]>" <|-- "org.apache.kafka.streams.state.internals.InMemoryWindowStore"
class org.apache.kafka.streams.state.internals.InMemoryWindowStore {
+InMemoryWindowStore(String;long;long;boolean;String) : InMemoryWindowStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#70]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#84]]]
+init(ProcessorContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#90]]]
+init(StateStoreContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#130]]]
+getPosition() : Position [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#137]]]
+put(Bytes;byte[];long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#142]]]
+fetch(Bytes;long) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#171]]]
+fetch(Bytes;long;long) : WindowStoreIterator<byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#190]]]
+backwardFetch(Bytes;long;long) : WindowStoreIterator<byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#195]]]
fetch(Bytes;long;long;boolean) : WindowStoreIterator<byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#199]]]
+fetch(Bytes;Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#230]]]
+backwardFetch(Bytes;Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#238]]]
fetch(Bytes;Bytes;long;long;boolean) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#245]]]
+fetchAll(long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#288]]]
+backwardFetchAll(long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#293]]]
fetchAll(long;long;boolean) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#297]]]
+all() : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#327]]]
+backwardAll() : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#341]]]
+persistent() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#355]]]
+isOpen() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#360]]]
+flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#380]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#385]]]
-removeExpiredSegments() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#397]]]
-maybeUpdateSeqnumForDups() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#405]]]
-wrapForDups(Bytes;int) : Bytes [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#411]]]
-getKey(Bytes) : Bytes [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#419]]]
-registerNewWindowStoreIterator(Bytes;Iterator<Map.Entry<Long,ConcurrentNavigableMap<Bytes,byte[]>>>;boolean) : WrappedInMemoryWindowStoreIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#425]]]
-registerNewWindowedKeyValueIterator(Bytes;Bytes;Iterator<Map.Entry<Long,ConcurrentNavigableMap<Bytes,byte[]>>>;boolean) : WrappedWindowedKeyValueIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java.html#438]]]
} 
@enduml
