@startuml
!pragma layout smetana
SessionStore_Bytes,byte[]_ <|-- org.apache.kafka.streams.state.internals.InMemorySessionStore
class org.apache.kafka.streams.state.internals.InMemorySessionStore {
InMemorySessionStore(String;long;String) : InMemorySessionStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#68]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#78]]]
+init(ProcessorContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#84]]]
+init(StateStoreContext;StateStore) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#127]]]
+getPosition() : Position [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#134]]]
+put(Windowed<Bytes>;byte[]) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#139]]]
+remove(Windowed<Bytes>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#167]]]
+fetchSession(Bytes;long;long) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#189]]]
+findSessions(long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#210]]]
+findSessions(Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#221]]]
+backwardFindSessions(Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#236]]]
+findSessions(Bytes;Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#253]]]
+backwardFindSessions(Bytes;Bytes;long;long) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#272]]]
+fetch(Bytes) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#293]]]
+backwardFetch(Bytes) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#303]]]
+fetch(Bytes;Bytes) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#313]]]
+backwardFetch(Bytes;Bytes) : KeyValueIterator<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#320]]]
+persistent() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#328]]]
+isOpen() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#333]]]
+flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#353]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#358]]]
-removeExpiredSegments() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#371]]]
-registerNewIterator(Bytes;Bytes;long;Iterator<Entry<Long,ConcurrentNavigableMap<Bytes,ConcurrentNavigableMap<Long,byte[]>>>>;boolean) : InMemorySessionStoreIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java.html#381]]]
} 
@enduml
