@startuml
!pragma layout smetana
AbstractSegments_KeyValueSegment_ <|-- org.apache.kafka.streams.state.internals.KeyValueSegments
class org.apache.kafka.streams.state.internals.KeyValueSegments {
+  KeyValueSegments(String;String;long;long)
+  getOrCreateSegment(long;ProcessorContext)
+  openExisting(ProcessorContext;long)
} 
@enduml
