@startuml
!pragma layout smetana
"KeyValueIterator<K,byte[]>" <|-- "org.apache.kafka.streams.state.internals.KeyValueToTimestampedKeyValueIteratorAdapter"
class org.apache.kafka.streams.state.internals.KeyValueToTimestampedKeyValueIteratorAdapter {
KeyValueToTimestampedKeyValueIteratorAdapter(KeyValueIterator<K,byte[]>) : KeyValueToTimestampedKeyValueIteratorAdapter [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/KeyValueToTimestampedKeyValueIteratorAdapter.java.html#34]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/KeyValueToTimestampedKeyValueIteratorAdapter.java.html#39]]]
+peekNextKey() : K [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/KeyValueToTimestampedKeyValueIteratorAdapter.java.html#44]]]
+hasNext() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/KeyValueToTimestampedKeyValueIteratorAdapter.java.html#49]]]
+next() : KeyValue<K,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/KeyValueToTimestampedKeyValueIteratorAdapter.java.html#54]]]
} 
@enduml
