@startuml
!pragma layout smetana
KeyValueIterator_K,V_ <|-- org.apache.kafka.streams.state.internals.KeyValueIteratorFacade
class org.apache.kafka.streams.state.internals.KeyValueIteratorFacade {
+  KeyValueIteratorFacade(KeyValueIterator<K,ValueAndTimestamp<V>>)
+  hasNext()
+  peekNextKey()
+  next()
+  close()
} 
@enduml
