@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.LeftOrRightValue"
class org.apache.kafka.streams.state.internals.LeftOrRightValue {
-LeftOrRightValue(V1;V2) : LeftOrRightValue [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#31]]]
+getLeftValue() : V1 [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#81]]]
+getRightValue() : V2 [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#85]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#90]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#97]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LeftOrRightValue.java.html#110]]]
} 
@enduml
