@startuml
!pragma layout smetana
WrappingNullableSerde_LeftOrRightValue_V1,V2_,Void,Object_ <|-- org.apache.kafka.streams.state.internals.LeftOrRightValueSerde
class org.apache.kafka.streams.state.internals.LeftOrRightValueSerde {
+  LeftOrRightValueSerde(Serde<V1>;Serde<V2>)
} 
@enduml
