@startuml
!pragma layout smetana
"WrappedStateStore<KeyValueStore<Bytes,byte[]>,Bytes,byte[]>KeyValueStore<Bytes,byte[]>" <|-- "org.apache.kafka.streams.state.internals.ListValueStore"
class org.apache.kafka.streams.state.internals.ListValueStore {
ListValueStore(KeyValueStore<Bytes,byte[]>) : ListValueStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#47]]]
+put(Bytes;byte[]) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#52]]]
+putIfAbsent(Bytes;byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#63]]]
-putInternal(Bytes;byte[];byte[]) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#82]]]
+putAll(List<KeyValue<Bytes,byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#94]]]
+delete(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#99]]]
+get(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#106]]]
+range(Bytes;Bytes) : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#111]]]
+all() : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#116]]]
+approximateNumEntries() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ListValueStore.java.html#121]]]
} 
@enduml
