@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.LRUCacheEntry"
class org.apache.kafka.streams.state.internals.LRUCacheEntry {
LRUCacheEntry(byte[]) : LRUCacheEntry [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#34]]]
LRUCacheEntry(byte[];Headers;boolean;long;long;int;String) : LRUCacheEntry [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#38]]]
markClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#57]]]
isDirty() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#61]]]
size() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#65]]]
value() : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#69]]]
+context() : ProcessorRecordContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#73]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#78]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/LRUCacheEntry.java.html#92]]]
} 
@enduml
