@startuml
!pragma layout smetana
"MemoryLRUCache" <|-- "org.apache.kafka.streams.state.internals.MemoryNavigableLRUCache"
class org.apache.kafka.streams.state.internals.MemoryNavigableLRUCache {
+MemoryNavigableLRUCache(String;int) : MemoryNavigableLRUCache [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#39]]]
+range(Bytes;Bytes) : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#44]]]
+reverseRange(Bytes;Bytes) : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#60]]]
-getIterator(TreeMap<Bytes,byte[]>;Bytes;Bytes;boolean) : Iterator<Bytes> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#75]]]
+all() : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#102]]]
+reverseAll() : KeyValueIterator<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#107]]]
-toTreeMap() : TreeMap<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MemoryNavigableLRUCache.java.html#111]]]
} 
@enduml
