@startuml
!pragma layout smetana
AbstractMergedSortedCacheStoreIterator_Long,Long,byte[],byte[]_WindowStoreIterator_byte[]_ <|-- org.apache.kafka.streams.state.internals.MergedSortedCacheWindowStoreIterator
class org.apache.kafka.streams.state.internals.MergedSortedCacheWindowStoreIterator {
+  MergedSortedCacheWindowStoreIterator(PeekingKeyValueIterator<Bytes,LRUCacheEntry>;KeyValueIterator<Long,byte[]>;boolean)
+  MergedSortedCacheWindowStoreIterator(PeekingKeyValueIterator<Bytes,LRUCacheEntry>;KeyValueIterator<Long,byte[]>;boolean;Function<byte[],Long>)
+  deserializeStorePair(KeyValue<Long,byte[]>)
+  deserializeCacheKey(Bytes)
+  deserializeCacheValue(LRUCacheEntry)
+  deserializeStoreKey(Long)
+  compare(Bytes;Long)
} 
@enduml
