@startuml
!pragma layout smetana
"AbstractMergedSortedCacheStoreIterator<Windowed<Bytes>,Windowed<Bytes>,byte[],byte[]>" <|-- "org.apache.kafka.streams.state.internals.MergedSortedCacheSessionStoreIterator"
class org.apache.kafka.streams.state.internals.MergedSortedCacheSessionStoreIterator {
MergedSortedCacheSessionStoreIterator(PeekingKeyValueIterator<Bytes,LRUCacheEntry>;KeyValueIterator<Windowed<Bytes>,byte[]>;SegmentedCacheFunction;boolean) : MergedSortedCacheSessionStoreIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#33]]]
+deserializeStorePair(KeyValue<Windowed<Bytes>,byte[]>) : KeyValue<Windowed<Bytes>,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#42]]]
deserializeCacheKey(Bytes) : Windowed<Bytes> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#47]]]
deserializeCacheValue(LRUCacheEntry) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#56]]]
+deserializeStoreKey(Windowed<Bytes>) : Windowed<Bytes> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#61]]]
+compare(Bytes;Windowed<Bytes>) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MergedSortedCacheSessionStoreIterator.java.html#66]]]
} 
@enduml
