@startuml
!pragma layout smetana
AbstractMergedSortedCacheStoreIterator_Bytes,Bytes,byte[],byte[]_ <|-- org.apache.kafka.streams.state.internals.MergedSortedCacheKeyValueBytesStoreIterator
class org.apache.kafka.streams.state.internals.MergedSortedCacheKeyValueBytesStoreIterator {
+  MergedSortedCacheKeyValueBytesStoreIterator(PeekingKeyValueIterator<Bytes,LRUCacheEntry>;KeyValueIterator<Bytes,byte[]>;boolean)
+  deserializeStorePair(KeyValue<Bytes,byte[]>)
+  deserializeCacheKey(Bytes)
+  deserializeCacheValue(LRUCacheEntry)
+  deserializeStoreKey(Bytes)
+  compare(Bytes;Bytes)
} 
@enduml
