@startuml
!pragma layout smetana
AbstractMergedSortedCacheStoreIterator_Windowed_Bytes_,Windowed_Bytes_,byte[],byte[]_ <|-- org.apache.kafka.streams.state.internals.MergedSortedCacheSessionStoreIterator
class org.apache.kafka.streams.state.internals.MergedSortedCacheSessionStoreIterator {
+  MergedSortedCacheSessionStoreIterator(PeekingKeyValueIterator<Bytes,LRUCacheEntry>;KeyValueIterator<Windowed<Bytes>,byte[]>;SegmentedCacheFunction;boolean)
+  deserializeStorePair(KeyValue<Windowed<Bytes>,byte[]>)
+  deserializeCacheKey(Bytes)
+  deserializeCacheValue(LRUCacheEntry)
+  deserializeStoreKey(Windowed<Bytes>)
+  compare(Bytes;Windowed<Bytes>)
} 
@enduml
