@startuml
!pragma layout smetana
"WindowStoreIterator<V>" <|-- "org.apache.kafka.streams.state.internals.MeteredWindowStoreIterator"
class org.apache.kafka.streams.state.internals.MeteredWindowStoreIterator {
MeteredWindowStoreIterator(WindowStoreIterator<byte[]>;Sensor;StreamsMetrics;Function<byte[],V>;Time) : MeteredWindowStoreIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MeteredWindowStoreIterator.java.html#36]]]
+hasNext() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MeteredWindowStoreIterator.java.html#50]]]
+next() : KeyValue<Long,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MeteredWindowStoreIterator.java.html#55]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MeteredWindowStoreIterator.java.html#61]]]
+peekNextKey() : Long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/MeteredWindowStoreIterator.java.html#70]]]
} 
@enduml
