@startuml
!pragma layout smetana
KeyValueIterator_Windowed_K_,V_ <|-- org.apache.kafka.streams.state.internals.MeteredWindowedKeyValueIterator
class org.apache.kafka.streams.state.internals.MeteredWindowedKeyValueIterator {
+  MeteredWindowedKeyValueIterator(KeyValueIterator<Windowed<Bytes>,byte[]>;Sensor;StreamsMetrics;Function<byte[],K>;Function<byte[],V>;Time)
+  hasNext()
+  next()
+  windowedKey(Windowed<Bytes>)
+  close()
+  peekNextKey()
} 
@enduml
