@startuml
!pragma layout smetana
MeteredWindowStore_K,ValueAndTimestamp_V__TimestampedWindowStore_K,V_ <|-- org.apache.kafka.streams.state.internals.MeteredTimestampedWindowStore
class org.apache.kafka.streams.state.internals.MeteredTimestampedWindowStore {
+  MeteredTimestampedWindowStore(WindowStore<Bytes,byte[]>;long;String;Time;Serde<K>;Serde<ValueAndTimestamp<V>>)
+  prepareValueSerde(Serde<ValueAndTimestamp<V>>;SerdeGetter)
} 
@enduml
