@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.Murmur3"
class org.apache.kafka.streams.state.internals.Murmur3 {
+hash32(long;long) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#480]]]
+hash32(long) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#480]]]
+hash32(long;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#480]]]
+hash32(long;long;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#480]]]
+hash32(byte[]) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash32(byte[];int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash32(byte[];int;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash32(byte[];int;int;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
-mix32(int;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
-fmix32(int;int) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(byte[]) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(long) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(int) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(short) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(byte[];int;int) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash64(byte[];int;int;int) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash128(byte[]) : long[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
+hash128(byte[];int;int;int) : long[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
-fmix64(long) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
-orBytes(byte;byte;byte;byte) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Murmur3.java.html#1]]]
} 
@enduml
