@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.state.internals.PrefixedSessionKeySchemas
class org.apache.kafka.streams.state.internals.PrefixedSessionKeySchemas {
+  extractPrefix(byte[])
} 
@enduml
