@startuml
!pragma layout smetana
AbstractRocksDBSegmentedBytesStore_KeyValueSegment_ <|-- org.apache.kafka.streams.state.internals.RocksDBSegmentedBytesStore
class org.apache.kafka.streams.state.internals.RocksDBSegmentedBytesStore {
+  RocksDBSegmentedBytesStore(String;String;long;long;KeySchema)
} 
@enduml
