@startuml
!pragma layout smetana
"RocksDBWindowStoreTimestampedBytesStore" <|-- "org.apache.kafka.streams.state.internals.RocksDBTimestampedWindowStore"
class org.apache.kafka.streams.state.internals.RocksDBTimestampedWindowStore {
RocksDBTimestampedWindowStore(SegmentedBytesStore;boolean;long) : RocksDBTimestampedWindowStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBTimestampedWindowStore.java.html#23]]]
} 
@enduml
