@startuml
!pragma layout smetana
SessionBytesStoreSupplier <|-- org.apache.kafka.streams.state.internals.RocksDbTimeOrderedSessionBytesStoreSupplier
class org.apache.kafka.streams.state.internals.RocksDbTimeOrderedSessionBytesStoreSupplier {
+  RocksDbTimeOrderedSessionBytesStoreSupplier(String;long;boolean)
+  name()
+  get()
+  metricsScope()
+  segmentIntervalMs()
+  retentionPeriod()
} 
@enduml
