@startuml
!pragma layout smetana
"KeyValueBytesStoreSupplier" <|-- "org.apache.kafka.streams.state.internals.RocksDbKeyValueBytesStoreSupplier"
class org.apache.kafka.streams.state.internals.RocksDbKeyValueBytesStoreSupplier {
+RocksDbKeyValueBytesStoreSupplier(String;boolean) : RocksDbKeyValueBytesStoreSupplier [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDbKeyValueBytesStoreSupplier.java.html#28]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDbKeyValueBytesStoreSupplier.java.html#35]]]
+get() : KeyValueStore<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDbKeyValueBytesStoreSupplier.java.html#40]]]
+metricsScope() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDbKeyValueBytesStoreSupplier.java.html#47]]]
} 
@enduml
