@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.Segments"
class org.apache.kafka.streams.state.internals.Segments {
segmentId(long) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#25]]]
segmentName(long) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#27]]]
getSegmentForTimestamp(long) : S [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#29]]]
getOrCreateSegmentIfLive(long;ProcessorContext;long) : S [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#31]]]
getOrCreateSegment(long;ProcessorContext) : S [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#33]]]
openExisting(ProcessorContext;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#35]]]
segments(long;long;boolean) : List<S> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#37]]]
allSegments(boolean) : List<S> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#39]]]
flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#41]]]
close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/Segments.java.html#43]]]
} 
@enduml
