@startuml
!pragma layout smetana
"CacheFunction" <|-- "org.apache.kafka.streams.state.internals.SegmentedCacheFunction"
class org.apache.kafka.streams.state.internals.SegmentedCacheFunction {
SegmentedCacheFunction(KeySchema;long) : SegmentedCacheFunction [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#32]]]
+key(Bytes) : Bytes [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#38]]]
+cacheKey(Bytes) : Bytes [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#43]]]
cacheKey(Bytes;long) : Bytes [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#47]]]
bytesFromCacheKey(Bytes) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#54]]]
+segmentId(Bytes) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#60]]]
segmentId(long) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#64]]]
getSegmentInterval() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#68]]]
compareSegmentedKeys(Bytes;Bytes) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SegmentedCacheFunction.java.html#72]]]
} 
@enduml
