@startuml
!pragma layout smetana
"AbstractStoreBuilder<K,V,SessionStore<K,V>>" <|-- "org.apache.kafka.streams.state.internals.SessionStoreBuilder"
class org.apache.kafka.streams.state.internals.SessionStoreBuilder {
+SessionStoreBuilder(SessionBytesStoreSupplier;Serde<K>;Serde<V>;Time) : SessionStoreBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SessionStoreBuilder.java.html#17]]]
+build() : SessionStore<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SessionStoreBuilder.java.html#27]]]
-maybeWrapCaching(SessionStore<Bytes,byte[]>) : SessionStore<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SessionStoreBuilder.java.html#36]]]
-maybeWrapLogging(SessionStore<Bytes,byte[]>) : SessionStore<Bytes,byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SessionStoreBuilder.java.html#43]]]
+retentionPeriod() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/SessionStoreBuilder.java.html#50]]]
} 
@enduml
