@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.ThreadCache"
class org.apache.kafka.streams.state.internals.ThreadCache {
+ThreadCache(LogContext;long;StreamsMetricsImpl) : ThreadCache [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#53]]]
+puts() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#59]]]
+gets() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#63]]]
+evicts() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#67]]]
+flushes() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#71]]]
+resize(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#75]]]
+nameSpaceFromTaskIdAndStore(String;String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#100]]]
+taskIDfromCacheName(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#107]]]
+underlyingStoreNamefromCacheName(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#115]]]
+addDirtyEntryFlushListener(String;DirtyEntryFlushListener) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#124]]]
+flush(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#129]]]
+get(String;Bytes) : LRUCacheEntry [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#143]]]
+put(String;Bytes;LRUCacheEntry) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#157]]]
+putIfAbsent(String;Bytes;LRUCacheEntry) : LRUCacheEntry [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#165]]]
+putAll(String;List<KeyValue<Bytes,LRUCacheEntry>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#177]]]
+delete(String;Bytes) : LRUCacheEntry [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#183]]]
+range(String;Bytes;Bytes) : MemoryLRUCacheBytesIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#192]]]
+range(String;Bytes;Bytes;boolean) : MemoryLRUCacheBytesIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#196]]]
+reverseRange(String;Bytes;Bytes) : MemoryLRUCacheBytesIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#204]]]
+all(String) : MemoryLRUCacheBytesIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#212]]]
+reverseAll(String) : MemoryLRUCacheBytesIterator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#220]]]
+size() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#228]]]
-isOverflowing(long) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#239]]]
sizeBytes() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#243]]]
close(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#254]]]
-maybeEvict(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#261]]]
-getCache(String) : NamedCache [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#281]]]
-getOrCreateCache(String) : NamedCache [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java.html#285]]]
} 
@enduml
