@startuml
!pragma layout smetana
WrappingNullableDeserializer_TimestampedKeyAndJoinSide_K_,K,Void_ <|-- org.apache.kafka.streams.state.internals.TimestampedKeyAndJoinSideDeserializer
class org.apache.kafka.streams.state.internals.TimestampedKeyAndJoinSideDeserializer {
TimestampedKeyAndJoinSideDeserializer(Deserializer<K>) : TimestampedKeyAndJoinSideDeserializer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#19]]]
+setIfUnset(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#25]]]
+configure(Map<String,?>;boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#34]]]
+deserialize(String;byte[]) : TimestampedKeyAndJoinSide<K> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#39]]]
-rawTimestamp(byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#47]]]
-rawKey(byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#53]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyAndJoinSideDeserializer.java.html#60]]]
} 
@enduml
