@startuml
!pragma layout smetana
AbstractStoreBuilder_K,ValueAndTimestamp_V_,TimestampedKeyValueStore_K,V__ <|-- org.apache.kafka.streams.state.internals.TimestampedKeyValueStoreBuilder
class org.apache.kafka.streams.state.internals.TimestampedKeyValueStoreBuilder {
+ TimestampedKeyValueStoreBuilder(KeyValueBytesStoreSupplier;Serde<K>;Serde<V>;Time) : TimestampedKeyValueStoreBuilder [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyValueStoreBuilder.java.html#32]]]
+ build() : TimestampedKeyValueStore<K,V> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyValueStoreBuilder.java.html#47]]]
- maybeWrapCaching(KeyValueStore<Bytes,byte[]>) : KeyValueStore<Bytes,byte[]> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyValueStoreBuilder.java.html#64]]]
- maybeWrapLogging(KeyValueStore<Bytes,byte[]>) : KeyValueStore<Bytes,byte[]> [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedKeyValueStoreBuilder.java.html#71]]]
} 
@enduml
