@startuml
!pragma layout smetana
"StateStore" <|-- "org.apache.kafka.streams.state.internals.TimeOrderedKeyValueBuffer"
class org.apache.kafka.streams.state.internals.TimeOrderedKeyValueBuffer {
setSerdesIfNull(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#81]]]
evictWhile(Supplier<Boolean>;Consumer<Eviction<K,V>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#83]]]
priorValueForBuffered(K) : Maybe<ValueAndTimestamp<V>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#85]]]
put(long;Record<K,Change<V>>;ProcessorRecordContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#87]]]
numRecords() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#89]]]
bufferSize() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#91]]]
minTimestamp() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBuffer.java.html#93]]]
} 
@enduml
