@startuml
!pragma layout smetana
AbstractStoreBuilder_K,ValueAndTimestamp_V_,TimestampedKeyValueStore_K,V__ <|-- org.apache.kafka.streams.state.internals.TimestampedKeyValueStoreBuilder
class org.apache.kafka.streams.state.internals.TimestampedKeyValueStoreBuilder {
+  TimestampedKeyValueStoreBuilder(KeyValueBytesStoreSupplier;Serde<K>;Serde<V>;Time)
+  build()
+  maybeWrapCaching(KeyValueStore<Bytes,byte[]>)
+  maybeWrapLogging(KeyValueStore<Bytes,byte[]>)
} 
@enduml
