@startuml
!pragma layout smetana
"AbstractSegments<TimestampedSegment>" <|-- "org.apache.kafka.streams.state.internals.TimestampedSegments"
class org.apache.kafka.streams.state.internals.TimestampedSegments {
TimestampedSegments(String;String;long;long) : TimestampedSegments [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedSegments.java.html#30]]]
+getOrCreateSegment(long;ProcessorContext) : TimestampedSegment [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedSegments.java.html#39]]]
+openExisting(ProcessorContext;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/TimestampedSegments.java.html#57]]]
} 
@enduml
