@startuml
!pragma layout smetana
WrappingNullableDeserializer_ValueAndTimestamp_V_,Void,V_ <|-- org.apache.kafka.streams.state.internals.ValueAndTimestampDeserializer
class org.apache.kafka.streams.state.internals.ValueAndTimestampDeserializer {
+  ValueAndTimestampDeserializer(Deserializer<V>)
+  configure(Map<String,?>;boolean)
+  deserialize(String;byte[])
+  close()
+  rawValue(byte[])
+  rawTimestamp(byte[])
+  timestamp(byte[])
+  setIfUnset(SerdeGetter)
} 
@enduml
