@startuml
!pragma layout smetana
WrappingNullableSerde_ValueAndTimestamp_V_,Void,V_ <|-- org.apache.kafka.streams.state.internals.ValueAndTimestampSerde
class org.apache.kafka.streams.state.internals.ValueAndTimestampSerde {
+  ValueAndTimestampSerde(Serde<V>)
} 
@enduml
