@startuml
!pragma layout smetana
"WrappingNullableSerde<ValueAndTimestamp<V>,Void,V>" <|-- "org.apache.kafka.streams.state.internals.ValueAndTimestampSerde"
class org.apache.kafka.streams.state.internals.ValueAndTimestampSerde {
+ValueAndTimestampSerde(Serde<V>) : ValueAndTimestampSerde [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampSerde.java.html#11]]]
} 
@enduml
