@startuml
!pragma layout smetana
"WrappingNullableDeserializer<ValueAndTimestamp<V>,Void,V>" <|-- "org.apache.kafka.streams.state.internals.ValueAndTimestampDeserializer"
class org.apache.kafka.streams.state.internals.ValueAndTimestampDeserializer {
ValueAndTimestampDeserializer(Deserializer<V>) : ValueAndTimestampDeserializer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#37]]]
+configure(Map<String,?>;boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#44]]]
+deserialize(String;byte[]) : ValueAndTimestamp<V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#51]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#63]]]
rawValue(byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#68]]]
-rawTimestamp(byte[]) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#76]]]
timestamp(byte[]) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#83]]]
+setIfUnset(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/ValueAndTimestampDeserializer.java.html#88]]]
} 
@enduml
