@startuml
!pragma layout smetana
KeyValueIterator_Windowed_Bytes_,byte[]_ <|-- org.apache.kafka.streams.state.internals.WrappedSessionStoreIterator
class org.apache.kafka.streams.state.internals.WrappedSessionStoreIterator {
+  WrappedSessionStoreIterator(KeyValueIterator<Bytes,byte[]>)
+  WrappedSessionStoreIterator(KeyValueIterator<Bytes,byte[]>;Function<Bytes,Windowed<Bytes>>)
+  close()
+  peekNextKey()
+  hasNext()
+  next()
} 
@enduml
