@startuml
!pragma layout smetana
ConfigDef.Validator <|-- org.apache.kafka.connect.transforms.util.RegexValidator
class org.apache.kafka.connect.transforms.util.RegexValidator {
+  ensureValid(String;Object)
+  toString()
} 
@enduml
