@startuml
!pragma layout smetana
AbstractConfig <|-- org.apache.kafka.connect.transforms.util.SimpleConfig
class org.apache.kafka.connect.transforms.util.SimpleConfig {
+  SimpleConfig(ConfigDef;Map<?,?>)
} 
@enduml
