@startuml
!pragma layout smetana
RetriableException <|-- org.apache.kafka.common.errors.AuthorizerNotReadyException
class org.apache.kafka.common.errors.AuthorizerNotReadyException {
+  AuthorizerNotReadyException()
} 
@enduml
