@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.errors.DuplicateResourceException
class org.apache.kafka.common.errors.DuplicateResourceException {
+  DuplicateResourceException(String)
+  DuplicateResourceException(String;Throwable)
+  DuplicateResourceException(String;String)
+  DuplicateResourceException(String;String;Throwable)
+  resource()
} 
@enduml
