@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.errors.DuplicateSequenceException
class org.apache.kafka.common.errors.DuplicateSequenceException {
+ DuplicateSequenceException(String) : DuplicateSequenceException [[[././qc/clients/src/main/java/org/apache/kafka/common/errors/DuplicateSequenceException.java.html#6]]]
} 
@enduml
