@startuml
!pragma layout smetana
"RetriableException" <|-- "org.apache.kafka.common.errors.FetchSessionIdNotFoundException"
class org.apache.kafka.common.errors.FetchSessionIdNotFoundException {
+FetchSessionIdNotFoundException() : FetchSessionIdNotFoundException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/FetchSessionIdNotFoundException.java.html#8]]]
+FetchSessionIdNotFoundException(String) : FetchSessionIdNotFoundException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/FetchSessionIdNotFoundException.java.html#11]]]
} 
@enduml
