@startuml
!pragma layout smetana
"ApiException" <|-- "org.apache.kafka.common.errors.InvalidProducerEpochException"
class org.apache.kafka.common.errors.InvalidProducerEpochException {
+InvalidProducerEpochException(String) : InvalidProducerEpochException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/InvalidProducerEpochException.java.html#9]]]
} 
@enduml
