@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.errors.InvalidSessionTimeoutException
class org.apache.kafka.common.errors.InvalidSessionTimeoutException {
+  InvalidSessionTimeoutException(String;Throwable)
+  InvalidSessionTimeoutException(String)
} 
@enduml
