@startuml
!pragma layout smetana
RetriableException <|-- org.apache.kafka.common.errors.NotEnoughReplicasAfterAppendException
class org.apache.kafka.common.errors.NotEnoughReplicasAfterAppendException {
+  NotEnoughReplicasAfterAppendException(String)
} 
@enduml
