@startuml
!pragma layout smetana
"InvalidOffsetException" <|-- "org.apache.kafka.common.errors.OffsetOutOfRangeException"
class org.apache.kafka.common.errors.OffsetOutOfRangeException {
+OffsetOutOfRangeException(String) : OffsetOutOfRangeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/OffsetOutOfRangeException.java.html#27]]]
+OffsetOutOfRangeException(String;Throwable) : OffsetOutOfRangeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/OffsetOutOfRangeException.java.html#31]]]
} 
@enduml
