@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.errors.PositionOutOfRangeException
class org.apache.kafka.common.errors.PositionOutOfRangeException {
+PositionOutOfRangeException(String) : PositionOutOfRangeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/PositionOutOfRangeException.java.html#8]]]
+PositionOutOfRangeException(String;Throwable) : PositionOutOfRangeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/PositionOutOfRangeException.java.html#12]]]
} 
@enduml
