@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.errors.RebalanceInProgressException
class org.apache.kafka.common.errors.RebalanceInProgressException {
+  RebalanceInProgressException()
+  RebalanceInProgressException(String;Throwable)
+  RebalanceInProgressException(String)
+  RebalanceInProgressException(Throwable)
} 
@enduml
