@startuml
!pragma layout smetana
"ApiException" <|-- "org.apache.kafka.common.errors.RecordTooLargeException"
class org.apache.kafka.common.errors.RecordTooLargeException {
+RecordTooLargeException() : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#14]]]
+RecordTooLargeException(String;Throwable) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#18]]]
+RecordTooLargeException(String) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#22]]]
+RecordTooLargeException(Throwable) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#26]]]
+RecordTooLargeException(String;Map<TopicPartition,Long>) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#30]]]
+recordTooLargePartitions() : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#35]]]
} 
@enduml
