@startuml
!pragma layout smetana
"ApiException" <|-- "org.apache.kafka.common.errors.RecordTooLargeException"
class org.apache.kafka.common.errors.RecordTooLargeException {
+RecordTooLargeException() : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#31]]]
+RecordTooLargeException(String;Throwable) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#35]]]
+RecordTooLargeException(String) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#39]]]
+RecordTooLargeException(Throwable) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#43]]]
+RecordTooLargeException(String;Map<TopicPartition,Long>) : RecordTooLargeException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#47]]]
+recordTooLargePartitions() : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/RecordTooLargeException.java.html#52]]]
} 
@enduml
