@startuml
!pragma layout smetana
AuthenticationException <|-- org.apache.kafka.common.errors.SaslAuthenticationException
class org.apache.kafka.common.errors.SaslAuthenticationException {
+  SaslAuthenticationException(String)
+  SaslAuthenticationException(String;Throwable)
} 
@enduml
