@startuml
!pragma layout smetana
"ApiException" <|-- "org.apache.kafka.common.errors.TopicExistsException"
class org.apache.kafka.common.errors.TopicExistsException {
+TopicExistsException(String) : TopicExistsException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/TopicExistsException.java.html#23]]]
+TopicExistsException(String;Throwable) : TopicExistsException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/errors/TopicExistsException.java.html#27]]]
} 
@enduml
