@startuml
!pragma layout smetana
OutOfOrderSequenceException <|-- org.apache.kafka.common.errors.UnknownProducerIdException
class org.apache.kafka.common.errors.UnknownProducerIdException {
+ UnknownProducerIdException(String) : UnknownProducerIdException [[[././qc/clients/src/main/java/org/apache/kafka/common/errors/UnknownProducerIdException.java.html#8]]]
} 
@enduml
