@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.oauthbearer.secured.Retryable
class org.apache.kafka.common.security.oauthbearer.secured.Retryable {
+  call()
} 
@enduml
