@startuml
!pragma layout smetana
"StreamsMetrics" <|-- "org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl"
class org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl {
+StreamsMetricsImpl(Metrics;String;String;Time) : StreamsMetricsImpl [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#147]]]
+version() : Version [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#161]]]
+rocksDBMetricsRecordingTrigger() : RocksDBMetricsRecordingTrigger [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#165]]]
+clientLevelSensor(String;RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#223]]]
+threadLevelSensor(String;String;RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#237]]]
-threadSensorPrefix(String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#247]]]
+clientLevelTagMap() : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#251]]]
+threadLevelTagMap(String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#257]]]
+removeAllClientLevelSensorsAndMetrics() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#263]]]
-removeAllClientLevelMetrics() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#268]]]
-removeAllClientLevelSensors() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#276]]]
+removeAllThreadLevelSensors(String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#284]]]
+removeAllThreadLevelMetrics(String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#294]]]
+taskLevelTagMap(String;String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#303]]]
+nodeLevelTagMap(String;String;String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#309]]]
+topicLevelTagMap(String;String;String;String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#317]]]
+storeLevelTagMap(String;String;String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#326]]]
+taskLevelSensor(String;String;String;RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#334]]]
+removeAllTaskLevelSensors(String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#345]]]
-taskSensorPrefix(String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#355]]]
+nodeLevelSensor(String;String;String;String;Sensor.RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#360]]]
+removeAllNodeLevelSensors(String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#372]]]
-nodeSensorPrefix(String;String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#384]]]
+topicLevelSensor(String;String;String;String;String;Sensor.RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#389]]]
+removeAllTopicLevelSensors(String;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#402]]]
-topicSensorPrefix(String;String;String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#415]]]
+cacheLevelSensor(String;String;String;String;Sensor.RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#423]]]
+cacheLevelTagMap(String;String;String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#435]]]
+removeAllCacheLevelSensors(String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#445]]]
-cacheSensorPrefix(String;String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#455]]]
+storeLevelSensor(String;String;String;RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#460]]]
+removeAllStoreLevelSensorsAndMetrics(String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#496]]]
-removeAllStoreLevelSensors(String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#503]]]
-removeAllStoreLevelMetrics(String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#513]]]
-storeSensorPrefix(String;String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#523]]]
+addSensor(String;Sensor.RecordingLevel) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#531]]]
+addSensor(String;Sensor.RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#536]]]
+metrics() : Map<MetricName,?extendsMetric> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#541]]]
-customizedTags(String;String;String;String...) : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#545]]]
-customInvocationRateAndCountSensor(String;String;String;String;Map<String,String>;Sensor.RecordingLevel) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#562]]]
+addLatencyRateTotalSensor(String;String;String;Sensor.RecordingLevel;String...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#581]]]
+addRateTotalSensor(String;String;String;Sensor.RecordingLevel;String...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#604]]]
-externalChildSensorName(String;String;String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#621]]]
+addAvgAndMaxToSensor(Sensor;String;Map<String,String>;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#627]]]
+addMinAndMaxToSensor(Sensor;String;Map<String,String>;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#651]]]
+addAvgAndMaxLatencyToSensor(Sensor;String;Map<String,String>;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#676]]]
+addAvgAndMinAndMaxToSensor(Sensor;String;Map<String,String>;String;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#698]]]
+addInvocationRateAndCountToSensor(Sensor;String;Map<String,String>;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#716]]]
+addInvocationRateToSensor(Sensor;String;Map<String,String>;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#734]]]
+addInvocationRateAndCountToSensor(Sensor;String;Map<String,String>;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#750]]]
+addRateOfSumAndSumMetricsToSensor(Sensor;String;Map<String,String>;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#764]]]
+addRateOfSumMetricToSensor(Sensor;String;Map<String,String>;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#774]]]
+addSumMetricToSensor(Sensor;String;Map<String,String>;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#783]]]
+addSumMetricToSensor(Sensor;String;Map<String,String>;String;boolean;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#791]]]
+addValueMetricToSensor(Sensor;String;Map<String,String>;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#808]]]
+addAvgAndSumMetricsToSensor(Sensor;String;Map<String,String>;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#816]]]
+addTotalCountAndSumMetricsToSensor(Sensor;String;Map<String,String>;String;String;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#829]]]
+maybeMeasureLatency(Runnable;Time;Sensor) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#846]]]
-getSensors(Map<String,Deque<String>>;String;String;RecordingLevel;Sensor...) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#876]]]
+removeSensor(Sensor) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#892]]]
parentSensors() : Map<Sensor,Sensor> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#903]]]
-groupNameFromScope(String) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java.html#907]]]
} 
@enduml
