@startuml
!pragma layout smetana
AbstractMap_K,V_ <|-- org.apache.kafka.server.util.TranslatedValueMapView
class org.apache.kafka.server.util.TranslatedValueMapView {
+ TranslatedValueMapView(Map<K,B>;Function<B,V>) : TranslatedValueMapView [[[././qc/server-common/src/main/java/org/apache/kafka/server/util/TranslatedValueMapView.java.html#68]]]
+ containsKey(Object) : boolean [[[././qc/server-common/src/main/java/org/apache/kafka/server/util/TranslatedValueMapView.java.html#76]]]
+ get(Object) : V [[[././qc/server-common/src/main/java/org/apache/kafka/server/util/TranslatedValueMapView.java.html#81]]]
+ entrySet() : Set<Entry<K,V>> [[[././qc/server-common/src/main/java/org/apache/kafka/server/util/TranslatedValueMapView.java.html#88]]]
+ isEmpty() : boolean [[[././qc/server-common/src/main/java/org/apache/kafka/server/util/TranslatedValueMapView.java.html#93]]]
} 
@enduml
