@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.util.ConnectUtils"
class org.apache.kafka.connect.util.ConnectUtils {
+checkAndConvertTimestamp(Long) : Long [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#46]]]
+lookupKafkaClusterId(WorkerConfig) : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#55]]]
lookupKafkaClusterId(Admin) : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#62]]]
+ensureProperty(Map<String,?superString>;String;String;String;boolean) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#98]]]
ensurePropertyAndGetWarning(Map<String,?superString>;String;String;String;boolean) : Optional<String> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#118]]]
+addMetricsContextProperties(Map<String,Object>;WorkerConfig;String) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#149]]]
+isSinkConnector(Connector) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#160]]]
+isSourceConnector(Connector) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#164]]]
+maybeWrap(Throwable;String) : ConnectException [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConnectUtils.java.html#194]]]
} 
@enduml
