@startuml
!pragma layout smetana
"Callback<U>" <|-- "org.apache.kafka.connect.util.ConvertingFutureCallback"
class org.apache.kafka.connect.util.ConvertingFutureCallback {
+ConvertingFutureCallback() : ConvertingFutureCallback [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#21]]]
+ConvertingFutureCallback(Callback<T>) : ConvertingFutureCallback [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#25]]]
+convert(U) : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#30]]]
+onCompletion(Throwable;U) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#33]]]
+cancel(boolean) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#52]]]
+isCancelled() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#72]]]
+isDone() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#77]]]
+get() : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#82]]]
+get(long;TimeUnit) : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#88]]]
-result() : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#95]]]
} 
@enduml
