@startuml
!pragma layout smetana
"Callback<U>" <|-- "org.apache.kafka.connect.util.ConvertingFutureCallback"
class org.apache.kafka.connect.util.ConvertingFutureCallback {
+ConvertingFutureCallback() : ConvertingFutureCallback [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#36]]]
+ConvertingFutureCallback(Callback<T>) : ConvertingFutureCallback [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#40]]]
+convert(U) : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#45]]]
+onCompletion(Throwable;U) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#48]]]
+cancel(boolean) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#67]]]
+isCancelled() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#87]]]
+isDone() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#92]]]
+get() : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#97]]]
+get(long;TimeUnit) : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#103]]]
-result() : T [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/ConvertingFutureCallback.java.html#110]]]
} 
@enduml
