@startuml
!pragma layout smetana
ConvertingFutureCallback<T,T> <|-- org.apache.kafka.connect.util.FutureCallback
class org.apache.kafka.connect.util.FutureCallback {
+  FutureCallback(Callback<T>)
+  FutureCallback()
+  convert(T)
} 
@enduml
