@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.connect.util.SharedTopicAdmin"
class org.apache.kafka.connect.util.SharedTopicAdmin {
+SharedTopicAdmin(Map<String,Object>) : SharedTopicAdmin [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#54]]]
SharedTopicAdmin(Map<String,Object>;Function<Map<String,Object>,TopicAdmin>) : SharedTopicAdmin [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#59]]]
+get() : TopicAdmin [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#71]]]
+topicAdmin() : TopicAdmin [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#81]]]
+bootstrapServers() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#91]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#102]]]
+close(Duration) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#114]]]
+toString() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#125]]]
createAdmin(TopicAdmin) : TopicAdmin [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/SharedTopicAdmin.java.html#136]]]
} 
@enduml
