@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.connect.util.TopicAdmin
class org.apache.kafka.connect.util.TopicAdmin {
+ defineTopic(String) : NewTopicBuilder [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#194]]]
+ TopicAdmin(Map<String,Object>) : TopicAdmin [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#204]]]
TopicAdmin(Object;Admin) : TopicAdmin [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#209]]]
TopicAdmin(Object;Admin;boolean) : TopicAdmin [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#214]]]
+ createTopic(NewTopic) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#221]]]
+ createTopics(NewTopic...) : Set<String> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#228]]]
+ createOrFindTopic(NewTopic) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#233]]]
+ createOrFindTopics(NewTopic...) : TopicCreationResponse [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#239]]]
+ describeTopics(String...) : Map<String,TopicDescription> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#309]]]
+ verifyTopicCleanupPolicyOnlyCompact(String;String;String) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#354]]]
+ topicCleanupPolicy(String) : Set<String> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#384]]]
+ describeTopicConfig(String) : Config [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#408]]]
+ describeTopicConfigs(String...) : Map<String,Config> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#413]]]
+ endOffsets(Set<TopicPartition>) : Map<TopicPartition,Long> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#466]]]
+ retryEndOffsets(Set<TopicPartition>;Duration;long) : Map<TopicPartition,Long> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#511]]]
+ close() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#528]]]
+ close(Duration) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java.html#532]]]
} 
@enduml
