@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.Cluster
class org.apache.kafka.common.Cluster {
+Cluster(String;Collection<Node>;Collection<PartitionInfo>;Set<String>;Set<String>) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#36]]]
+Cluster(String;Collection<Node>;Collection<PartitionInfo>;Set<String>;Set<String>;Node) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#45]]]
+Cluster(String;Collection<Node>;Collection<PartitionInfo>;Set<String>;Set<String>;Set<String>;Node) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#55]]]
+Cluster(String;Collection<Node>;Collection<PartitionInfo>;Set<String>;Set<String>;Set<String>;Node;Map<String,Uuid>) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#66]]]
-Cluster(String;boolean;Collection<Node>;Collection<PartitionInfo>;Set<String>;Set<String>;Set<String>;Node;Map<String,Uuid>) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#77]]]
+empty() : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#166]]]
+bootstrap(List<InetSocketAddress>) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#172]]]
+withPartitions(Map<TopicPartition,PartitionInfo>) : Cluster [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#182]]]
+nodes() : List<Node> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#191]]]
+nodeById(int) : Node [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#196]]]
+nodeIfOnline(TopicPartition;int) : Optional<Node> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#201]]]
+leaderFor(TopicPartition) : Node [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#211]]]
+partition(TopicPartition) : PartitionInfo [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#220]]]
+partitionsForTopic(String) : List<PartitionInfo> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#225]]]
+partitionCountForTopic(String) : Integer [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#230]]]
+availablePartitionsForTopic(String) : List<PartitionInfo> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#236]]]
+partitionsForNode(int) : List<PartitionInfo> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#241]]]
+topics() : Set<String> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#246]]]
+unauthorizedTopics() : Set<String> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#250]]]
+invalidTopics() : Set<String> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#254]]]
+internalTopics() : Set<String> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#258]]]
+isBootstrapConfigured() : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#262]]]
+clusterResource() : ClusterResource [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#266]]]
+controller() : Node [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#270]]]
+topicIds() : Collection<Uuid> [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#274]]]
+topicId(String) : Uuid [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#278]]]
+topicName(Uuid) : String [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#282]]]
+toString() : String [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#287]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#293]]]
+hashCode() : int [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/Cluster.java.html#308]]]
} 
@enduml
