@startuml
!pragma layout smetana
ApiException <|-- org.apache.kafka.common.InvalidRecordException
class org.apache.kafka.common.InvalidRecordException {
+  InvalidRecordException(String)
+  InvalidRecordException(String;Throwable)
} 
@enduml
