@startuml
!pragma layout smetana
"ApiException" <|-- "org.apache.kafka.common.InvalidRecordException"
class org.apache.kafka.common.InvalidRecordException {
+InvalidRecordException(String) : InvalidRecordException [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/InvalidRecordException.java.html#10]]]
+InvalidRecordException(String;Throwable) : InvalidRecordException [[[./../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/InvalidRecordException.java.html#14]]]
} 
@enduml
