@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.PartitionInfo
class org.apache.kafka.common.PartitionInfo {
+  PartitionInfo(String;int;Node;Node[];Node[])
+  PartitionInfo(String;int;Node;Node[];Node[];Node[])
+  topic()
+  partition()
+  leader()
+  replicas()
+  inSyncReplicas()
+  offlineReplicas()
+  toString()
+  formatNodeIds(Node[])
} 
@enduml
