@startuml
!pragma layout smetana
"AbstractRequestResponse" <|-- "org.apache.kafka.common.requests.AbstractResponse"
class org.apache.kafka.common.requests.AbstractResponse {
AbstractResponse(ApiKeys) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#38]]]
+toSend(ResponseHeader;short) : Send [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#42]]]
serializeWithHeader(ResponseHeader;short) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#51]]]
serialize(short) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#56]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#65]]]
errorCounts(Errors) : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#67]]]
errorCounts(Stream<Errors>) : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#71]]]
errorCounts(Collection<Errors>) : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#75]]]
apiErrorCounts(Map<?,ApiError>) : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#82]]]
updateErrorCounts(Map<Errors,Integer>;Errors) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#89]]]
+parseResponse(ByteBuffer;RequestHeader) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#98]]]
+parseResponse(ApiKeys;ByteBuffer;short) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#114]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#263]]]
+apiKey() : ApiKeys [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#267]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#271]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java.html#273]]]
} 
@enduml
