@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.AddPartitionsToTxnRequest
class org.apache.kafka.common.requests.AddPartitionsToTxnRequest {
+AddPartitionsToTxnRequest(AddPartitionsToTxnRequestData;short) : AddPartitionsToTxnRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AddPartitionsToTxnRequest.java.html#86]]]
+partitions() : List<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AddPartitionsToTxnRequest.java.html#91]]]
+data() : AddPartitionsToTxnRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AddPartitionsToTxnRequest.java.html#100]]]
+getErrorResponse(int;Throwable) : AddPartitionsToTxnResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AddPartitionsToTxnRequest.java.html#105]]]
+parse(ByteBuffer;short) : AddPartitionsToTxnRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AddPartitionsToTxnRequest.java.html#113]]]
} 
@enduml
