@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.AlterUserScramCredentialsRequest
class org.apache.kafka.common.requests.AlterUserScramCredentialsRequest {
+  AlterUserScramCredentialsRequest(AlterUserScramCredentialsRequestData;short)
+  parse(ByteBuffer;short)
+  data()
+  getErrorResponse(int;Throwable)
} 
@enduml
