@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.AlterPartitionRequest"
class org.apache.kafka.common.requests.AlterPartitionRequest {
+AlterPartitionRequest(AlterPartitionRequestData;short) : AlterPartitionRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionRequest.java.html#17]]]
+data() : AlterPartitionRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionRequest.java.html#23]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionRequest.java.html#29]]]
+parse(ByteBuffer;short) : AlterPartitionRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionRequest.java.html#35]]]
} 
@enduml
