@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.AlterReplicaLogDirsResponse
class org.apache.kafka.common.requests.AlterReplicaLogDirsResponse {
+AlterReplicaLogDirsResponse(AlterReplicaLogDirsResponseData) : AlterReplicaLogDirsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#19]]]
+data() : AlterReplicaLogDirsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#25]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#30]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#35]]]
+parse(ByteBuffer;short) : AlterReplicaLogDirsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#43]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterReplicaLogDirsResponse.java.html#48]]]
} 
@enduml
