@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.AlterPartitionReassignmentsResponse"
class org.apache.kafka.common.requests.AlterPartitionReassignmentsResponse {
+AlterPartitionReassignmentsResponse(AlterPartitionReassignmentsResponseData) : AlterPartitionReassignmentsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#18]]]
+parse(ByteBuffer;short) : AlterPartitionReassignmentsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#23]]]
+data() : AlterPartitionReassignmentsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#29]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#34]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#39]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/AlterPartitionReassignmentsResponse.java.html#44]]]
} 
@enduml
