@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.ApiVersionsRequest
class org.apache.kafka.common.requests.ApiVersionsRequest {
+ApiVersionsRequest(ApiVersionsRequestData;short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#49]]]
+ApiVersionsRequest(ApiVersionsRequestData;short;Short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#53]]]
+hasUnsupportedRequestVersion() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#65]]]
+isValid() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#69]]]
+data() : ApiVersionsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#79]]]
+getErrorResponse(int;Throwable) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#84]]]
+parse(ByteBuffer;short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#103]]]
} 
@enduml
