@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.ApiVersionsResponse"
class org.apache.kafka.common.requests.ApiVersionsResponse {
+ApiVersionsResponse(ApiVersionsResponseData) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#34]]]
+data() : ApiVersionsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#40]]]
+apiVersion(short) : ApiVersion [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#44]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#49]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#54]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#59]]]
+parse(ByteBuffer;short) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#63]]]
+defaultApiVersionsResponse(ApiMessageType.ListenerType) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#81]]]
+defaultApiVersionsResponse(int;ApiMessageType.ListenerType) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#87]]]
+createApiVersionsResponse(int;ApiVersionCollection) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#94]]]
+createApiVersionsResponse(int;RecordVersion;Features<SupportedVersionRange>;Map<String,Short>;long;NodeApiVersions;ListenerType) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#106]]]
+createApiVersionsResponse(int;ApiVersionCollection;Features<SupportedVersionRange>;Map<String,Short>;long) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#132]]]
+filterApis(RecordVersion;ApiMessageType.ListenerType) : ApiVersionCollection [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#151]]]
+collectApis(Set<ApiKeys>) : ApiVersionCollection [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#164]]]
+intersectForwardableApis(ApiMessageType.ListenerType;RecordVersion;Map<ApiKeys,ApiVersion>) : ApiVersionCollection [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#173]]]
-createApiVersionsResponseData(int;Errors;ApiVersionCollection;Features<SupportedVersionRange>;Map<String,Short>;long) : ApiVersionsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#203]]]
-createSupportedFeatureKeys(Features<SupportedVersionRange>) : SupportedFeatureKeyCollection [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#222]]]
-createFinalizedFeatureKeys(Map<String,Short>) : FinalizedFeatureKeyCollection [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#237]]]
+intersect(ApiVersion;ApiVersion) : Optional<ApiVersion> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#252]]]
+toApiVersion(ApiKeys) : ApiVersion [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsResponse.java.html#268]]]
} 
@enduml
