@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.ApiVersionsRequest"
class org.apache.kafka.common.requests.ApiVersionsRequest {
+ApiVersionsRequest(ApiVersionsRequestData;short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#64]]]
+ApiVersionsRequest(ApiVersionsRequestData;short;Short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#68]]]
+hasUnsupportedRequestVersion() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#80]]]
+isValid() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#84]]]
+data() : ApiVersionsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#94]]]
+getErrorResponse(int;Throwable) : ApiVersionsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#99]]]
+parse(ByteBuffer;short) : ApiVersionsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ApiVersionsRequest.java.html#118]]]
} 
@enduml
