@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.BeginQuorumEpochResponse
class org.apache.kafka.common.requests.BeginQuorumEpochResponse {
+  BeginQuorumEpochResponse(BeginQuorumEpochResponseData)
+  singletonResponse(Errors;TopicPartition;Errors;int;int)
+  errorCounts()
+  data()
+  throttleTimeMs()
+  parse(ByteBuffer;short)
} 
@enduml
