@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.BrokerHeartbeatResponse"
class org.apache.kafka.common.requests.BrokerHeartbeatResponse {
+BrokerHeartbeatResponse(BrokerHeartbeatResponseData) : BrokerHeartbeatResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#32]]]
+data() : BrokerHeartbeatResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#38]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#43]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#48]]]
+parse(ByteBuffer;short) : BrokerHeartbeatResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#54]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatResponse.java.html#59]]]
} 
@enduml
