@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.BrokerHeartbeatRequest
class org.apache.kafka.common.requests.BrokerHeartbeatRequest {
+  BrokerHeartbeatRequest(BrokerHeartbeatRequestData;short)
+  data()
+  getErrorResponse(int;Throwable)
+  parse(ByteBuffer;short)
} 
@enduml
