@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.BrokerHeartbeatRequest"
class org.apache.kafka.common.requests.BrokerHeartbeatRequest {
+BrokerHeartbeatRequest(BrokerHeartbeatRequestData;short) : BrokerHeartbeatRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatRequest.java.html#50]]]
+data() : BrokerHeartbeatRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatRequest.java.html#56]]]
+getErrorResponse(int;Throwable) : BrokerHeartbeatResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatRequest.java.html#61]]]
+parse(ByteBuffer;short) : BrokerHeartbeatRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/BrokerHeartbeatRequest.java.html#68]]]
} 
@enduml
