@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.ControlledShutdownResponse"
class org.apache.kafka.common.requests.ControlledShutdownResponse {
+ControlledShutdownResponse(ControlledShutdownResponseData) : ControlledShutdownResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#42]]]
+error() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#47]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#52]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#57]]]
+parse(ByteBuffer;short) : ControlledShutdownResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#61]]]
+data() : ControlledShutdownResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#66]]]
+prepareResponse(Errors;Set<TopicPartition>) : ControlledShutdownResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ControlledShutdownResponse.java.html#70]]]
} 
@enduml
