@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.CreateAclsRequest"
class org.apache.kafka.common.requests.CreateAclsRequest {
CreateAclsRequest(CreateAclsRequestData;short) : CreateAclsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#62]]]
+aclCreations() : List<AclCreation> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#68]]]
+data() : CreateAclsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#73]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#78]]]
+parse(ByteBuffer;short) : CreateAclsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#86]]]
-validate(CreateAclsRequestData) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#90]]]
+aclBinding(AclCreation) : AclBinding [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#107]]]
+aclCreation(AclBinding) : AclCreation [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#120]]]
-aclResult(Throwable) : AclCreationResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#131]]]
} 
@enduml
