@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.CreateAclsRequest"
class org.apache.kafka.common.requests.CreateAclsRequest {
CreateAclsRequest(CreateAclsRequestData;short) : CreateAclsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#47]]]
+aclCreations() : List<AclCreation> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#53]]]
+data() : CreateAclsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#58]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#63]]]
+parse(ByteBuffer;short) : CreateAclsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#71]]]
-validate(CreateAclsRequestData) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#75]]]
+aclBinding(AclCreation) : AclBinding [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#92]]]
+aclCreation(AclBinding) : AclCreation [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#105]]]
-aclResult(Throwable) : AclCreationResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/CreateAclsRequest.java.html#116]]]
} 
@enduml
