@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.DeleteTopicsResponse
class org.apache.kafka.common.requests.DeleteTopicsResponse {
+  DeleteTopicsResponse(DeleteTopicsResponseData)
+  throttleTimeMs()
+  data()
+  errorCounts()
+  parse(ByteBuffer;short)
+  shouldClientThrottle(short)
} 
@enduml
