@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.DescribeClientQuotasRequest
class org.apache.kafka.common.requests.DescribeClientQuotasRequest {
+DescribeClientQuotasRequest(DescribeClientQuotasRequestData;short) : DescribeClientQuotasRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java.html#62]]]
+filter() : ClientQuotaFilter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java.html#67]]]
+data() : DescribeClientQuotasRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java.html#94]]]
+getErrorResponse(int;Throwable) : DescribeClientQuotasResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java.html#99]]]
+parse(ByteBuffer;short) : DescribeClientQuotasRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java.html#108]]]
} 
@enduml
