@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.DescribeUserScramCredentialsResponse
class org.apache.kafka.common.requests.DescribeUserScramCredentialsResponse {
+DescribeUserScramCredentialsResponse(DescribeUserScramCredentialsResponseData) : DescribeUserScramCredentialsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#16]]]
+data() : DescribeUserScramCredentialsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#22]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#27]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#32]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#37]]]
+parse(ByteBuffer;short) : DescribeUserScramCredentialsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsResponse.java.html#41]]]
} 
@enduml
