@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.DescribeUserScramCredentialsRequest"
class org.apache.kafka.common.requests.DescribeUserScramCredentialsRequest {
-DescribeUserScramCredentialsRequest(DescribeUserScramCredentialsRequestData;short) : DescribeUserScramCredentialsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsRequest.java.html#35]]]
+parse(ByteBuffer;short) : DescribeUserScramCredentialsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsRequest.java.html#41]]]
+data() : DescribeUserScramCredentialsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsRequest.java.html#47]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/DescribeUserScramCredentialsRequest.java.html#52]]]
} 
@enduml
