@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.DescribeDelegationTokenResponse
class org.apache.kafka.common.requests.DescribeDelegationTokenResponse {
+  DescribeDelegationTokenResponse(int;int;Errors;List<DelegationToken>)
+  DescribeDelegationTokenResponse(int;int;Errors)
+  DescribeDelegationTokenResponse(DescribeDelegationTokenResponseData)
+  parse(ByteBuffer;short)
+  errorCounts()
+  data()
+  throttleTimeMs()
+  error()
+  tokens()
+  hasError()
+  shouldClientThrottle(short)
} 
@enduml
