@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.EndQuorumEpochRequest"
class org.apache.kafka.common.requests.EndQuorumEpochRequest {
-EndQuorumEpochRequest(EndQuorumEpochRequestData;short) : EndQuorumEpochRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#52]]]
+data() : EndQuorumEpochRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#58]]]
+getErrorResponse(int;Throwable) : EndQuorumEpochResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#63]]]
+parse(ByteBuffer;short) : EndQuorumEpochRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#68]]]
+singletonRequest(TopicPartition;int;int;List<Integer>) : EndQuorumEpochRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#72]]]
+singletonRequest(TopicPartition;String;int;int;List<Integer>) : EndQuorumEpochRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java.html#79]]]
} 
@enduml
