@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.FetchRequest"
class org.apache.kafka.common.requests.FetchRequest {
-optionalEpoch(int) : Optional<Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#107]]]
+FetchRequest(FetchRequestData;short) : FetchRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#282]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#289]]]
+replicaId() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#317]]]
+maxWait() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#321]]]
+minBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#325]]]
+maxBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#329]]]
+fetchData(Map<Uuid,String>) : Map<TopicIdPartition,PartitionData> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#335]]]
+forgottenTopics(Map<Uuid,String>) : List<TopicIdPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#373]]]
+isFromFollower() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#397]]]
+isolationLevel() : IsolationLevel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#401]]]
+metadata() : FetchMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#405]]]
+rackId() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#409]]]
+parse(ByteBuffer;short) : FetchRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#413]]]
+data() : FetchRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/FetchRequest.java.html#418]]]
} 
@enduml
