@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.LeaveGroupResponse
class org.apache.kafka.common.requests.LeaveGroupResponse {
+LeaveGroupResponse(LeaveGroupResponseData) : LeaveGroupResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#21]]]
+LeaveGroupResponse(List<MemberResponse>;Errors;int;short) : LeaveGroupResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#26]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#49]]]
+memberResponses() : List<MemberResponse> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#53]]]
+error() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#57]]]
+topLevelError() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#61]]]
-getError(Errors;List<MemberResponse>) : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#65]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#80]]]
+data() : LeaveGroupResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#93]]]
+parse(ByteBuffer;short) : LeaveGroupResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#97]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#102]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#107]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#113]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/LeaveGroupResponse.java.html#118]]]
} 
@enduml
