@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.ListPartitionReassignmentsResponse"
class org.apache.kafka.common.requests.ListPartitionReassignmentsResponse {
+ListPartitionReassignmentsResponse(ListPartitionReassignmentsResponseData) : ListPartitionReassignmentsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#31]]]
+parse(ByteBuffer;short) : ListPartitionReassignmentsResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#36]]]
+data() : ListPartitionReassignmentsResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#42]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#47]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#52]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListPartitionReassignmentsResponse.java.html#57]]]
} 
@enduml
