@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.ListGroupsRequest
class org.apache.kafka.common.requests.ListGroupsRequest {
+  ListGroupsRequest(ListGroupsRequestData;short)
+  getErrorResponse(int;Throwable)
+  parse(ByteBuffer;short)
+  data()
} 
@enduml
