@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.ListGroupsResponse
class org.apache.kafka.common.requests.ListGroupsResponse {
+  ListGroupsResponse(ListGroupsResponseData)
+  data()
+  throttleTimeMs()
+  errorCounts()
+  parse(ByteBuffer;short)
+  shouldClientThrottle(short)
} 
@enduml
