@startuml
!pragma layout smetana
AbstractResponse <|-- org.apache.kafka.common.requests.ListPartitionReassignmentsResponse
class org.apache.kafka.common.requests.ListPartitionReassignmentsResponse {
+  ListPartitionReassignmentsResponse(ListPartitionReassignmentsResponseData)
+  parse(ByteBuffer;short)
+  data()
+  shouldClientThrottle(short)
+  throttleTimeMs()
+  errorCounts()
} 
@enduml
