@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.ListGroupsRequest
class org.apache.kafka.common.requests.ListGroupsRequest {
+ ListGroupsRequest(ListGroupsRequestData;short) : ListGroupsRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/ListGroupsRequest.java.html#43]]]
+ getErrorResponse(int;Throwable) : ListGroupsResponse [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/ListGroupsRequest.java.html#49]]]
+ parse(ByteBuffer;short) : ListGroupsRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/ListGroupsRequest.java.html#59]]]
+ data() : ListGroupsRequestData [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/ListGroupsRequest.java.html#64]]]
} 
@enduml
