@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.ListOffsetsRequest"
class org.apache.kafka.common.requests.ListOffsetsRequest {
-ListOffsetsRequest(ListOffsetsRequestData;short) : ListOffsetsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#81]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#97]]]
+data() : ListOffsetsRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#127]]]
+replicaId() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#131]]]
+isolationLevel() : IsolationLevel [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#135]]]
+topics() : List<ListOffsetsTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#139]]]
+duplicatePartitions() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#143]]]
+parse(ByteBuffer;short) : ListOffsetsRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#147]]]
+toListOffsetsTopics(Map<TopicPartition,ListOffsetsPartition>) : List<ListOffsetsTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#151]]]
+singletonRequestData(String;int;long;int) : ListOffsetsTopic [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/ListOffsetsRequest.java.html#161]]]
} 
@enduml
