@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.MetadataRequest"
class org.apache.kafka.common.requests.MetadataRequest {
+MetadataRequest(MetadataRequestData;short) : MetadataRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#131]]]
+data() : MetadataRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#137]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#142]]]
+isAllTopics() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#162]]]
+topics() : List<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#168]]]
+topicIds() : List<Uuid> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#178]]]
+allowAutoTopicCreation() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#190]]]
+parse(ByteBuffer;short) : MetadataRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#194]]]
+convertToMetadataRequestTopic(Collection<String>) : List<MetadataRequestTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#198]]]
+convertTopicIdsToMetadataRequestTopic(Collection<Uuid>) : List<MetadataRequestTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java.html#204]]]
} 
@enduml
