@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.OffsetDeleteResponse"
class org.apache.kafka.common.requests.OffsetDeleteResponse {
+OffsetDeleteResponse(OffsetDeleteResponseData) : OffsetDeleteResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#49]]]
+data() : OffsetDeleteResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#55]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#60]]]
+parse(ByteBuffer;short) : OffsetDeleteResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#71]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#76]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetDeleteResponse.java.html#81]]]
} 
@enduml
