@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.OffsetDeleteRequest
class org.apache.kafka.common.requests.OffsetDeleteRequest {
+  OffsetDeleteRequest(OffsetDeleteRequestData;short)
+  getErrorResponse(int;Errors)
+  getErrorResponse(int;Throwable)
+  parse(ByteBuffer;short)
+  data()
} 
@enduml
