@startuml
!pragma layout smetana
AbstractRequest <|-- org.apache.kafka.common.requests.OffsetFetchRequest
class org.apache.kafka.common.requests.OffsetFetchRequest {
+ partitions() : List<TopicPartition> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#191]]]
+ groupId() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#204]]]
+ requireStable() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#208]]]
+ groupIdsToPartitions() : Map<String,List<TopicPartition>> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#212]]]
+ groupIdsToTopics() : Map<String,List<OffsetFetchRequestTopics>> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#229]]]
+ groupIds() : List<String> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#236]]]
- OffsetFetchRequest(OffsetFetchRequestData;short) : OffsetFetchRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#243]]]
+ getErrorResponse(Errors) : OffsetFetchResponse [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#248]]]
+ getErrorResponse(int;Errors) : OffsetFetchResponse [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#252]]]
+ getErrorResponse(int;Throwable) : OffsetFetchResponse [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#287]]]
+ parse(ByteBuffer;short) : OffsetFetchRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#291]]]
+ isAllPartitions() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#295]]]
+ isAllPartitionsForGroup(String) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#299]]]
+ data() : OffsetFetchRequestData [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/OffsetFetchRequest.java.html#310]]]
} 
@enduml
