@startuml
!pragma layout smetana
AbstractRequestResponse <|-- org.apache.kafka.common.requests.RequestHeader
class org.apache.kafka.common.requests.RequestHeader {
+ RequestHeader(ApiKeys;short;String;int) : RequestHeader [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#18]]]
+ RequestHeader(RequestHeaderData;short) : RequestHeader [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#27]]]
+ apiKey() : ApiKeys [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#32]]]
+ apiVersion() : short [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#36]]]
+ headerVersion() : short [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#40]]]
+ clientId() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#44]]]
+ correlationId() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#48]]]
+ data() : RequestHeaderData [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#52]]]
+ write(ByteBuffer;ObjectSerializationCache) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#56]]]
+ size(ObjectSerializationCache) : int [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#60]]]
+ toResponseHeader() : ResponseHeader [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#64]]]
+ parse(ByteBuffer) : RequestHeader [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#68]]]
+ toString() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#95]]]
+ equals(Object) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#104]]]
+ hashCode() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java.html#112]]]
} 
@enduml
