@startuml
!pragma layout smetana
"AuthorizableRequestContext" <|-- "org.apache.kafka.common.requests.RequestContext"
class org.apache.kafka.common.requests.RequestContext {
+RequestContext(RequestHeader;String;InetAddress;KafkaPrincipal;ListenerName;SecurityProtocol;ClientInformation;boolean) : RequestContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#47]]]
+RequestContext(RequestHeader;String;InetAddress;KafkaPrincipal;ListenerName;SecurityProtocol;ClientInformation;boolean;Optional<KafkaPrincipalSerde>) : RequestContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#66]]]
+parseRequest(ByteBuffer) : RequestAndSize [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#86]]]
+buildResponseSend(AbstractResponse) : Send [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#110]]]
+buildResponseEnvelopePayload(AbstractResponse) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#128]]]
-isUnsupportedApiVersionsRequest() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#132]]]
+apiVersion() : short [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#136]]]
+listenerName() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#144]]]
+securityProtocol() : SecurityProtocol [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#149]]]
+principal() : KafkaPrincipal [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#154]]]
+clientAddress() : InetAddress [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#159]]]
+requestType() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#164]]]
+requestVersion() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#169]]]
+clientId() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#174]]]
+correlationId() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#179]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java.html#184]]]
} 
@enduml
