@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.SaslAuthenticateRequest"
class org.apache.kafka.common.requests.SaslAuthenticateRequest {
+SaslAuthenticateRequest(SaslAuthenticateRequestData;short) : SaslAuthenticateRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateRequest.java.html#58]]]
+data() : SaslAuthenticateRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateRequest.java.html#64]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateRequest.java.html#69]]]
+parse(ByteBuffer;short) : SaslAuthenticateRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateRequest.java.html#77]]]
} 
@enduml
