@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.SaslAuthenticateResponse"
class org.apache.kafka.common.requests.SaslAuthenticateResponse {
+SaslAuthenticateResponse(SaslAuthenticateResponseData) : SaslAuthenticateResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#35]]]
+error() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#44]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#49]]]
+errorMessage() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#53]]]
+sessionLifetimeMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#57]]]
+saslAuthBytes() : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#61]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#66]]]
+data() : SaslAuthenticateResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#71]]]
+parse(ByteBuffer;short) : SaslAuthenticateResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SaslAuthenticateResponse.java.html#75]]]
} 
@enduml
