@startuml
!pragma layout smetana
AbstractControlRequest <|-- org.apache.kafka.common.requests.StopReplicaRequest
class org.apache.kafka.common.requests.StopReplicaRequest {
- StopReplicaRequest(StopReplicaRequestData;short) : StopReplicaRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#86]]]
+ getErrorResponse(int;Throwable) : StopReplicaResponse [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#92]]]
+ topicStates() : Iterable<StopReplicaTopicState> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#113]]]
+ partitionStates() : Map<TopicPartition,StopReplicaPartitionState> [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#138]]]
+ controllerId() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#173]]]
+ controllerEpoch() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#178]]]
+ brokerEpoch() : long [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#183]]]
+ parse(ByteBuffer;short) : StopReplicaRequest [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#187]]]
+ data() : StopReplicaRequestData [[[././qc/clients/src/main/java/org/apache/kafka/common/requests/StopReplicaRequest.java.html#192]]]
} 
@enduml
