@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.SyncGroupResponse"
class org.apache.kafka.common.requests.SyncGroupResponse {
+SyncGroupResponse(SyncGroupResponseData) : SyncGroupResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#16]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#22]]]
+error() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#26]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#31]]]
+data() : SyncGroupResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#36]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#41]]]
+parse(ByteBuffer;short) : SyncGroupResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#45]]]
+shouldClientThrottle(short) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/SyncGroupResponse.java.html#50]]]
} 
@enduml
