@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.TxnOffsetCommitRequest"
class org.apache.kafka.common.requests.TxnOffsetCommitRequest {
+TxnOffsetCommitRequest(TxnOffsetCommitRequestData;short) : TxnOffsetCommitRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#106]]]
+offsets() : Map<TopicPartition,CommittedOffset> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#111]]]
getTopics(Map<TopicPartition,CommittedOffset>) : List<TxnOffsetCommitRequestTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#126]]]
+data() : TxnOffsetCommitRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#150]]]
getErrorResponseTopics(List<TxnOffsetCommitRequestTopic>;Errors) : List<TxnOffsetCommitResponseTopic> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#154]]]
+getErrorResponse(int;Throwable) : TxnOffsetCommitResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#173]]]
+parse(ByteBuffer;short) : TxnOffsetCommitRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/TxnOffsetCommitRequest.java.html#182]]]
} 
@enduml
