@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.UpdateMetadataResponse"
class org.apache.kafka.common.requests.UpdateMetadataResponse {
+UpdateMetadataResponse(UpdateMetadataResponseData) : UpdateMetadataResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#31]]]
+error() : Errors [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#36]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#41]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#46]]]
+parse(ByteBuffer;short) : UpdateMetadataResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#50]]]
+data() : UpdateMetadataResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/UpdateMetadataResponse.java.html#55]]]
} 
@enduml
