@startuml
!pragma layout smetana
"AbstractRequest" <|-- "org.apache.kafka.common.requests.VoteRequest"
class org.apache.kafka.common.requests.VoteRequest {
-VoteRequest(VoteRequestData;short) : VoteRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#52]]]
+data() : VoteRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#58]]]
+getErrorResponse(int;Throwable) : AbstractResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#63]]]
+parse(ByteBuffer;short) : VoteRequest [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#68]]]
+singletonRequest(TopicPartition;int;int;int;long) : VoteRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#72]]]
+singletonRequest(TopicPartition;String;int;int;int;long) : VoteRequestData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java.html#85]]]
} 
@enduml
