@startuml
!pragma layout smetana
"AbstractResponse" <|-- "org.apache.kafka.common.requests.WriteTxnMarkersResponse"
class org.apache.kafka.common.requests.WriteTxnMarkersResponse {
+WriteTxnMarkersResponse(Map<Long,Map<TopicPartition,Errors>>) : WriteTxnMarkersResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#24]]]
+WriteTxnMarkersResponse(WriteTxnMarkersResponseData) : WriteTxnMarkersResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#51]]]
+data() : WriteTxnMarkersResponseData [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#57]]]
+errorsByProducerId() : Map<Long,Map<TopicPartition,Errors>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#61]]]
+throttleTimeMs() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#77]]]
+errorCounts() : Map<Errors,Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#82]]]
+parse(ByteBuffer;short) : WriteTxnMarkersResponse [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/requests/WriteTxnMarkersResponse.java.html#93]]]
} 
@enduml
