@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.AbortTransactionResult
class org.apache.kafka.clients.admin.AbortTransactionResult {
+  AbortTransactionResult(Map<TopicPartition,KafkaFuture<Void>>)
+  all()
} 
@enduml
