@startuml
!pragma layout smetana
"AbstractOptions<AbortTransactionOptions>" <|-- "org.apache.kafka.clients.admin.AbortTransactionOptions"
class org.apache.kafka.clients.admin.AbortTransactionOptions {
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/AbortTransactionOptions.java.html#10]]]
} 
@enduml
