@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.AbstractOptions"
class org.apache.kafka.clients.admin.AbstractOptions {
+timeoutMs(Integer) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/AbstractOptions.java.html#33]]]
+timeoutMs() : Integer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/AbstractOptions.java.html#42]]]
} 
@enduml
