@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.clients.admin.Admin"
class org.apache.kafka.clients.admin.Admin {
create(Properties) : Admin [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#132]]]
create(Map<String,Object>) : Admin [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#142]]]
close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#152]]]
close(Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#166]]]
createTopics(Collection<NewTopic>) : CreateTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#179]]]
createTopics(Collection<NewTopic>;CreateTopicsOptions) : CreateTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#200]]]
deleteTopics(Collection<String>) : DeleteTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#211]]]
deleteTopics(Collection<String>;DeleteTopicsOptions) : DeleteTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#225]]]
deleteTopics(TopicCollection) : DeleteTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#239]]]
deleteTopics(TopicCollection;DeleteTopicsOptions) : DeleteTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#264]]]
listTopics() : ListTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#274]]]
listTopics(ListTopicsOptions) : ListTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#284]]]
describeTopics(Collection<String>) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#295]]]
describeTopics(Collection<String>;DescribeTopicsOptions) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#306]]]
describeTopics(TopicCollection) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#319]]]
describeTopics(TopicCollection;DescribeTopicsOptions) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#332]]]
describeCluster() : DescribeClusterResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#342]]]
describeCluster(DescribeClusterOptions) : DescribeClusterResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#352]]]
describeAcls(AclBindingFilter) : DescribeAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#363]]]
describeAcls(AclBindingFilter;DescribeAclsOptions) : DescribeAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#379]]]
createAcls(Collection<AclBinding>) : CreateAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#390]]]
createAcls(Collection<AclBinding>;CreateAclsOptions) : CreateAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#408]]]
deleteAcls(Collection<AclBindingFilter>) : DeleteAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#419]]]
deleteAcls(Collection<AclBindingFilter>;DeleteAclsOptions) : DeleteAclsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#434]]]
describeConfigs(Collection<ConfigResource>) : DescribeConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#448]]]
describeConfigs(Collection<ConfigResource>;DescribeConfigsOptions) : DescribeConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#469]]]
alterConfigs(Map<ConfigResource,Config>) : AlterConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#485]]]
alterConfigs(Map<ConfigResource,Config>;AlterConfigsOptions) : AlterConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#504]]]
incrementalAlterConfigs(Map<ConfigResource,Collection<AlterConfigOp>>) : AlterConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#517]]]
incrementalAlterConfigs(Map<ConfigResource,Collection<AlterConfigOp>>;AlterConfigsOptions) : AlterConfigsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#546]]]
alterReplicaLogDirs(Map<TopicPartitionReplica,String>) : AlterReplicaLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#565]]]
alterReplicaLogDirs(Map<TopicPartitionReplica,String>;AlterReplicaLogDirsOptions) : AlterReplicaLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#583]]]
describeLogDirs(Collection<Integer>) : DescribeLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#597]]]
describeLogDirs(Collection<Integer>;DescribeLogDirsOptions) : DescribeLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#610]]]
describeReplicaLogDirs(Collection<TopicPartitionReplica>) : DescribeReplicaLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#623]]]
describeReplicaLogDirs(Collection<TopicPartitionReplica>;DescribeReplicaLogDirsOptions) : DescribeReplicaLogDirsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#636]]]
createPartitions(Map<String,NewPartitions>) : CreatePartitionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#650]]]
createPartitions(Map<String,NewPartitions>;CreatePartitionsOptions) : CreatePartitionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#691]]]
deleteRecords(Map<TopicPartition,RecordsToDelete>) : DeleteRecordsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#705]]]
deleteRecords(Map<TopicPartition,RecordsToDelete>;DeleteRecordsOptions) : DeleteRecordsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#718]]]
createDelegationToken() : CreateDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#729]]]
createDelegationToken(CreateDelegationTokenOptions) : CreateDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#755]]]
renewDelegationToken(byte[]) : RenewDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#767]]]
renewDelegationToken(byte[];RenewDelegationTokenOptions) : RenewDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#797]]]
expireDelegationToken(byte[]) : ExpireDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#808]]]
expireDelegationToken(byte[];ExpireDelegationTokenOptions) : ExpireDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#838]]]
describeDelegationToken() : DescribeDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#848]]]
describeDelegationToken(DescribeDelegationTokenOptions) : DescribeDelegationTokenResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#871]]]
describeConsumerGroups(Collection<String>;DescribeConsumerGroupsOptions) : DescribeConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#880]]]
describeConsumerGroups(Collection<String>) : DescribeConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#892]]]
listConsumerGroups(ListConsumerGroupsOptions) : ListConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#902]]]
listConsumerGroups() : ListConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#912]]]
listConsumerGroupOffsets(String;ListConsumerGroupOffsetsOptions) : ListConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#922]]]
listConsumerGroupOffsets(String) : ListConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#931]]]
deleteConsumerGroups(Collection<String>;DeleteConsumerGroupsOptions) : DeleteConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#941]]]
deleteConsumerGroups(Collection<String>) : DeleteConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#948]]]
deleteConsumerGroupOffsets(String;Set<TopicPartition>;DeleteConsumerGroupOffsetsOptions) : DeleteConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#960]]]
deleteConsumerGroupOffsets(String;Set<TopicPartition>) : DeleteConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#971]]]
electLeaders(ElectionType;Set<TopicPartition>) : ElectLeadersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#985]]]
electLeaders(ElectionType;Set<TopicPartition>;ElectLeadersOptions) : ElectLeadersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1025]]]
alterPartitionReassignments(Map<TopicPartition,Optional<NewPartitionReassignment>>) : AlterPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1038]]]
alterPartitionReassignments(Map<TopicPartition,Optional<NewPartitionReassignment>>;AlterPartitionReassignmentsOptions) : AlterPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1066]]]
listPartitionReassignments() : ListPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1077]]]
listPartitionReassignments(Set<TopicPartition>) : ListPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1087]]]
listPartitionReassignments(Set<TopicPartition>;ListPartitionReassignmentsOptions) : ListPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1109]]]
listPartitionReassignments(ListPartitionReassignmentsOptions) : ListPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1132]]]
listPartitionReassignments(Optional<Set<TopicPartition>>;ListPartitionReassignmentsOptions) : ListPartitionReassignmentsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1141]]]
removeMembersFromConsumerGroup(String;RemoveMembersFromConsumerGroupOptions) : RemoveMembersFromConsumerGroupResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1153]]]
alterConsumerGroupOffsets(String;Map<TopicPartition,OffsetAndMetadata>) : AlterConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1165]]]
alterConsumerGroupOffsets(String;Map<TopicPartition,OffsetAndMetadata>;AlterConsumerGroupOffsetsOptions) : AlterConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1179]]]
listOffsets(Map<TopicPartition,OffsetSpec>) : ListOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1190]]]
listOffsets(Map<TopicPartition,OffsetSpec>;ListOffsetsOptions) : ListOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1202]]]
describeClientQuotas(ClientQuotaFilter) : DescribeClientQuotasResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1216]]]
describeClientQuotas(ClientQuotaFilter;DescribeClientQuotasOptions) : DescribeClientQuotasResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1241]]]
alterClientQuotas(Collection<ClientQuotaAlteration>) : AlterClientQuotasResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1254]]]
alterClientQuotas(Collection<ClientQuotaAlteration>;AlterClientQuotasOptions) : AlterClientQuotasResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1281]]]
describeUserScramCredentials() : DescribeUserScramCredentialsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1290]]]
describeUserScramCredentials(List<String>) : DescribeUserScramCredentialsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1303]]]
describeUserScramCredentials(List<String>;DescribeUserScramCredentialsOptions) : DescribeUserScramCredentialsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1330]]]
alterUserScramCredentials(List<UserScramCredentialAlteration>) : AlterUserScramCredentialsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1340]]]
alterUserScramCredentials(List<UserScramCredentialAlteration>;AlterUserScramCredentialsOptions) : AlterUserScramCredentialsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1371]]]
describeFeatures() : DescribeFeaturesResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1381]]]
describeFeatures(DescribeFeaturesOptions) : DescribeFeaturesResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1400]]]
updateFeatures(Map<String,FeatureUpdate>;UpdateFeaturesOptions) : UpdateFeaturesResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1447]]]
describeMetadataQuorum() : DescribeMetadataQuorumResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1457]]]
describeMetadataQuorum(DescribeMetadataQuorumOptions) : DescribeMetadataQuorumResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1476]]]
unregisterBroker(int) : UnregisterBrokerResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1491]]]
unregisterBroker(int;UnregisterBrokerOptions) : UnregisterBrokerResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1518]]]
describeProducers(Collection<TopicPartition>) : DescribeProducersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1527]]]
describeProducers(Collection<TopicPartition>;DescribeProducersOptions) : DescribeProducersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1540]]]
describeTransactions(Collection<String>) : DescribeTransactionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1549]]]
describeTransactions(Collection<String>;DescribeTransactionsOptions) : DescribeTransactionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1561]]]
abortTransaction(AbortTransactionSpec) : AbortTransactionResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1570]]]
abortTransaction(AbortTransactionSpec;AbortTransactionOptions) : AbortTransactionResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1585]]]
listTransactions() : ListTransactionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1593]]]
listTransactions(ListTransactionsOptions) : ListTransactionsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1607]]]
fenceProducers(Collection<String>) : FenceProducersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1618]]]
fenceProducers(Collection<String>;FenceProducersOptions) : FenceProducersResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1629]]]
metrics() : Map<MetricName,?extendsMetric> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java.html#1635]]]
} 
@enduml
