@startuml
!pragma layout smetana
"AbstractOptions<AlterUserScramCredentialsOptions>" <|-- "org.apache.kafka.clients.admin.AlterUserScramCredentialsOptions"
class org.apache.kafka.clients.admin.AlterUserScramCredentialsOptions {
} 
@enduml
