@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.ConsumerGroupListing"
class org.apache.kafka.clients.admin.ConsumerGroupListing {
+ConsumerGroupListing(String;boolean) : ConsumerGroupListing [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#39]]]
+ConsumerGroupListing(String;boolean;Optional<ConsumerGroupState>) : ConsumerGroupListing [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#50]]]
+groupId() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#59]]]
+isSimpleConsumerGroup() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#66]]]
+state() : Optional<ConsumerGroupState> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#73]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#78]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#87]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#92]]]
} 
@enduml
