@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.ConsumerGroupListing"
class org.apache.kafka.clients.admin.ConsumerGroupListing {
+ConsumerGroupListing(String;boolean) : ConsumerGroupListing [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#17]]]
+ConsumerGroupListing(String;boolean;Optional<ConsumerGroupState>) : ConsumerGroupListing [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#22]]]
+groupId() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#29]]]
+isSimpleConsumerGroup() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#34]]]
+state() : Optional<ConsumerGroupState> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#39]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#44]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#53]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ConsumerGroupListing.java.html#58]]]
} 
@enduml
