@startuml
!pragma layout smetana
"AbstractOptions<CreateDelegationTokenOptions>" <|-- "org.apache.kafka.clients.admin.CreateDelegationTokenOptions"
class org.apache.kafka.clients.admin.CreateDelegationTokenOptions {
+renewers(List<KafkaPrincipal>) : CreateDelegationTokenOptions [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#19]]]
+renewers() : List<KafkaPrincipal> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#24]]]
+owner(KafkaPrincipal) : CreateDelegationTokenOptions [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#28]]]
+owner() : Optional<KafkaPrincipal> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#33]]]
+maxlifeTimeMs(long) : CreateDelegationTokenOptions [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#37]]]
+maxlifeTimeMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/CreateDelegationTokenOptions.java.html#42]]]
} 
@enduml
