@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.DeleteConsumerGroupOffsetsResult
class org.apache.kafka.clients.admin.DeleteConsumerGroupOffsetsResult {
DeleteConsumerGroupOffsetsResult(KafkaFuture<Map<TopicPartition,Errors>>;Set<TopicPartition>) : DeleteConsumerGroupOffsetsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupOffsetsResult.java.html#20]]]
+partitionResult(TopicPartition) : KafkaFuture<Void> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupOffsetsResult.java.html#26]]]
+all() : KafkaFuture<Void> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupOffsetsResult.java.html#43]]]
-maybeCompleteExceptionally(Map<TopicPartition,Errors>;TopicPartition;KafkaFutureImpl<Void>) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupOffsetsResult.java.html#61]]]
} 
@enduml
