@startuml
!pragma layout smetana
AbstractOptions_DeleteAclsOptions_ <|-- org.apache.kafka.clients.admin.DeleteAclsOptions
class org.apache.kafka.clients.admin.DeleteAclsOptions {
+  timeoutMs(Integer)
} 
@enduml
