@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.DeletedRecords"
class org.apache.kafka.clients.admin.DeletedRecords {
+DeletedRecords(long) : DeletedRecords [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeletedRecords.java.html#14]]]
+lowWatermark() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeletedRecords.java.html#19]]]
} 
@enduml
