@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.DeleteConsumerGroupsResult"
class org.apache.kafka.clients.admin.DeleteConsumerGroupsResult {
DeleteConsumerGroupsResult(Map<String,KafkaFuture<Void>>) : DeleteConsumerGroupsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupsResult.java.html#16]]]
+deletedGroups() : Map<String,KafkaFuture<Void>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupsResult.java.html#21]]]
+all() : KafkaFuture<Void> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DeleteConsumerGroupsResult.java.html#28]]]
} 
@enduml
