@startuml
!pragma layout smetana
AbstractOptions_DescribeUserScramCredentialsOptions_ <|-- org.apache.kafka.clients.admin.DescribeUserScramCredentialsOptions
class org.apache.kafka.clients.admin.DescribeUserScramCredentialsOptions {
} 
@enduml
