@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.DescribeMetadataQuorumResult
class org.apache.kafka.clients.admin.DescribeMetadataQuorumResult {
+  DescribeMetadataQuorumResult(KafkaFuture<QuorumInfo>)
+  quorumInfo()
} 
@enduml
