@startuml
!pragma layout smetana
AbstractOptions_DescribeClusterOptions_ <|-- org.apache.kafka.clients.admin.DescribeClusterOptions
class org.apache.kafka.clients.admin.DescribeClusterOptions {
+  timeoutMs(Integer)
+  includeAuthorizedOperations(boolean)
+  includeAuthorizedOperations()
} 
@enduml
