@startuml
!pragma layout smetana
AbstractOptions<DescribeAclsOptions> <|-- org.apache.kafka.clients.admin.DescribeAclsOptions
class org.apache.kafka.clients.admin.DescribeAclsOptions {
+  timeoutMs(Integer)
} 
@enduml
