@startuml
!pragma layout smetana
"AbstractOptions<DescribeReplicaLogDirsOptions>" <|-- "org.apache.kafka.clients.admin.DescribeReplicaLogDirsOptions"
class org.apache.kafka.clients.admin.DescribeReplicaLogDirsOptions {
} 
@enduml
