@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.DescribeTopicsResult"
class org.apache.kafka.clients.admin.DescribeTopicsResult {
DescribeTopicsResult(Map<String,KafkaFuture<TopicDescription>>) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#41]]]
DescribeTopicsResult(Map<Uuid,KafkaFuture<TopicDescription>>;Map<String,KafkaFuture<TopicDescription>>) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#46]]]
ofTopicIds(Map<Uuid,KafkaFuture<TopicDescription>>) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#55]]]
ofTopicNames(Map<String,KafkaFuture<TopicDescription>>) : DescribeTopicsResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#59]]]
+topicIdValues() : Map<Uuid,KafkaFuture<TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#69]]]
+topicNameValues() : Map<String,KafkaFuture<TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#79]]]
+values() : Map<String,KafkaFuture<TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#90]]]
+all() : KafkaFuture<Map<String,TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#103]]]
+allTopicNames() : KafkaFuture<Map<String,TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#113]]]
+allTopicIds() : KafkaFuture<Map<Uuid,TopicDescription>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java.html#123]]]
} 
@enduml
