@startuml
!pragma layout smetana
AbstractOptions_DescribeClientQuotasOptions_ <|-- org.apache.kafka.clients.admin.DescribeClientQuotasOptions
class org.apache.kafka.clients.admin.DescribeClientQuotasOptions {
} 
@enduml
