@startuml
!pragma layout smetana
AbstractOptions<ListTransactionsOptions> <|-- org.apache.kafka.clients.admin.ListTransactionsOptions
class org.apache.kafka.clients.admin.ListTransactionsOptions {
+  filterStates(Collection<TransactionState>)
+  filterProducerIds(Collection<Long>)
+  filteredStates()
+  filteredProducerIds()
+  toString()
+  equals(Object)
+  hashCode()
} 
@enduml
