@startuml
!pragma layout smetana
AbstractOptions_ListOffsetsOptions_ <|-- org.apache.kafka.clients.admin.ListOffsetsOptions
class org.apache.kafka.clients.admin.ListOffsetsOptions {
+  ListOffsetsOptions()
+  ListOffsetsOptions(IsolationLevel)
+  isolationLevel()
} 
@enduml
