@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.LogDirDescription
class org.apache.kafka.clients.admin.LogDirDescription {
+ LogDirDescription(ApiException;Map<TopicPartition,ReplicaInfo>) : LogDirDescription [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#20]]]
+ LogDirDescription(ApiException;Map<TopicPartition,ReplicaInfo>;long;long) : LogDirDescription [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#24]]]
+ error() : ApiException [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#32]]]
+ replicaInfos() : Map<TopicPartition,ReplicaInfo> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#37]]]
+ totalBytes() : OptionalLong [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#42]]]
+ usableBytes() : OptionalLong [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#47]]]
+ toString() : String [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/LogDirDescription.java.html#52]]]
} 
@enduml
