@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.NewPartitions
class org.apache.kafka.clients.admin.NewPartitions {
+  NewPartitions(int;List<List<Integer>>)
+  increaseTo(int)
+  increaseTo(int;List<List<Integer>>)
+  totalCount()
+  assignments()
+  toString()
} 
@enduml
