@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.ReplicaInfo"
class org.apache.kafka.clients.admin.ReplicaInfo {
+ReplicaInfo(long;long;boolean) : ReplicaInfo [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ReplicaInfo.java.html#28]]]
+size() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ReplicaInfo.java.html#37]]]
+offsetLag() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ReplicaInfo.java.html#47]]]
+isFuture() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ReplicaInfo.java.html#58]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/ReplicaInfo.java.html#63]]]
} 
@enduml
