@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.ScramCredentialInfo
class org.apache.kafka.clients.admin.ScramCredentialInfo {
+  ScramCredentialInfo(ScramMechanism;int)
+  mechanism()
+  iterations()
+  toString()
+  equals(Object)
+  hashCode()
} 
@enduml
