@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.UserScramCredentialAlteration"
class org.apache.kafka.clients.admin.UserScramCredentialAlteration {
UserScramCredentialAlteration(String) : UserScramCredentialAlteration [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialAlteration.java.html#34]]]
+user() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialAlteration.java.html#42]]]
} 
@enduml
