@startuml
!pragma layout smetana
UserScramCredentialAlteration <|-- org.apache.kafka.clients.admin.UserScramCredentialUpsertion
class org.apache.kafka.clients.admin.UserScramCredentialUpsertion {
+  UserScramCredentialUpsertion(String;ScramCredentialInfo;String)
+  UserScramCredentialUpsertion(String;ScramCredentialInfo;byte[])
+  UserScramCredentialUpsertion(String;ScramCredentialInfo;byte[];byte[])
+  credentialInfo()
+  salt()
+  password()
+  generateRandomSalt()
} 
@enduml
