@startuml
!pragma layout smetana
UserScramCredentialAlteration <|-- org.apache.kafka.clients.admin.UserScramCredentialUpsertion
class org.apache.kafka.clients.admin.UserScramCredentialUpsertion {
+UserScramCredentialUpsertion(String;ScramCredentialInfo;String) : UserScramCredentialUpsertion [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#18]]]
+UserScramCredentialUpsertion(String;ScramCredentialInfo;byte[]) : UserScramCredentialUpsertion [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#23]]]
+UserScramCredentialUpsertion(String;ScramCredentialInfo;byte[];byte[]) : UserScramCredentialUpsertion [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#28]]]
+credentialInfo() : ScramCredentialInfo [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#36]]]
+salt() : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#41]]]
+password() : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#46]]]
-generateRandomSalt() : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialUpsertion.java.html#50]]]
} 
@enduml
