@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.UserScramCredentialsDescription
class org.apache.kafka.clients.admin.UserScramCredentialsDescription {
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#16]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#25]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#30]]]
+UserScramCredentialsDescription(String;List<ScramCredentialInfo>) : UserScramCredentialsDescription [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#38]]]
+name() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#44]]]
+credentialInfos() : List<ScramCredentialInfo> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/UserScramCredentialsDescription.java.html#49]]]
} 
@enduml
