@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.examples.wordcount.WordCountProcessorDemo"
class org.apache.kafka.streams.examples.wordcount.WordCountProcessorDemo {
+main(String[]) : void [[[./../../../../../../../../../../../.././qc/streams/examples/src/main/java/org/apache/kafka/streams/examples/wordcount/WordCountProcessorDemo.java.html#69]]]
} 
@enduml
