@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.config.AbstractConfig
class org.apache.kafka.common.config.AbstractConfig {
+  AbstractConfig(ConfigDef;Map<?,?>;Map<String,?>;boolean)
+  AbstractConfig(ConfigDef;Map<?,?>)
+  AbstractConfig(ConfigDef;Map<?,?>;boolean)
+  postProcessParsedConfig(Map<String,Object>)
+  get(String)
+  ignore(String)
+  getShort(String)
+  getInt(String)
+  getLong(String)
+  getDouble(String)
+  getList(String)
+  getBoolean(String)
+  getString(String)
+  typeOf(String)
+  documentationOf(String)
+  getPassword(String)
+  getClass(String)
+  unused()
+  originals()
+  originals(Map<String,Object>)
+  originalsStrings()
+  originalsWithPrefix(String)
+  originalsWithPrefix(String;boolean)
+  valuesWithPrefixOverride(String)
+  valuesWithPrefixAllOrNothing(String)
+  values()
+  nonInternalValues()
+  logAll()
+  logUnused()
+  extractPotentialVariables(Map<?,?>)
+  resolveConfigVariables(Map<String,?>;Map<String,Object>)
+  configProviderProperties(String;Map<String,?>)
+  instantiateConfigProviders(Map<String,String>;Map<String,?>)
+  providerClassProperty(String)
+  equals(Object)
+  hashCode()
} 
@enduml
