@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.config.ConfigValue
class org.apache.kafka.common.config.ConfigValue {
+ ConfigValue(String) : ConfigValue [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#16]]]
+ ConfigValue(String;Object;List<Object>;List<String>) : ConfigValue [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#20]]]
+ name() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#28]]]
+ value() : Object [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#32]]]
+ recommendedValues() : List<Object> [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#36]]]
+ errorMessages() : List<String> [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#40]]]
+ visible() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#44]]]
+ value(Object) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#48]]]
+ recommendedValues(List<Object>) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#52]]]
+ addErrorMessage(String) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#56]]]
+ visible(boolean) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#60]]]
+ equals(Object) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#65]]]
+ hashCode() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#77]]]
+ toString() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/config/ConfigValue.java.html#82]]]
} 
@enduml
