@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.config.ConfigDef
class org.apache.kafka.common.config.ConfigDef {
+  ConfigDef()
+  ConfigDef(ConfigDef)
+  names()
+  defaultValues()
+  define(ConfigKey)
+  define(String;Type;Object;Validator;Importance;String;String;int;Width;String;List<String>;Recommender)
+  define(String;Type;Object;Validator;Importance;String;String;int;Width;String;List<String>)
+  define(String;Type;Object;Validator;Importance;String;String;int;Width;String;Recommender)
+  define(String;Type;Object;Validator;Importance;String;String;int;Width;String)
+  define(String;Type;Object;Importance;String;String;int;Width;String;List<String>;Recommender)
+  define(String;Type;Object;Importance;String;String;int;Width;String;List<String>)
+  define(String;Type;Object;Importance;String;String;int;Width;String;Recommender)
+  define(String;Type;Object;Importance;String;String;int;Width;String)
+  define(String;Type;Importance;String;String;int;Width;String;List<String>;Recommender)
+  define(String;Type;Importance;String;String;int;Width;String;List<String>)
+  define(String;Type;Importance;String;String;int;Width;String;Recommender)
+  define(String;Type;Importance;String;String;int;Width;String)
+  define(String;Type;Object;Validator;Importance;String)
+  define(String;Type;Object;Importance;String)
+  define(String;Type;Importance;String)
+  defineInternal(String;Type;Object;Importance)
+  defineInternal(String;Type;Object;Validator;Importance;String)
+  configKeys()
+  groups()
+  withClientSslSupport()
+  withClientSaslSupport()
+  parse(Map<?,?>)
+  parseValue(ConfigKey;Object;boolean)
+  validate(Map<String,String>)
+  validateAll(Map<String,String>)
+  parseForValidate(Map<String,String>;Map<String,ConfigValue>)
+  validate(Map<String,Object>;Map<String,ConfigValue>)
+  undefinedDependentConfigs()
+  getConfigsWithNoParent()
+  parseForValidate(String;Map<String,String>;Map<String,Object>;Map<String,ConfigValue>)
+  validate(String;Map<String,Object>;Map<String,ConfigValue>)
+  parseType(String;Object;Type)
+  convertToString(Object;Type)
+  convertToStringMapWithPasswordValues(Map<String,?>)
+  headers()
+  getConfigValue(ConfigKey;String)
+  niceMemoryUnits(long)
+  niceTimeUnits(long)
+  toHtmlTable()
+  addHeader(StringBuilder;String)
+  addColumnValue(StringBuilder;String)
+  toHtmlTable(Map<String,String>)
+  toRst()
+  toEnrichedRst()
+  getConfigKeyRst(ConfigKey;StringBuilder)
+  sortedConfigs()
+  compare(ConfigKey;ConfigKey;Map<String,Integer>)
+  embed(String;String;int;ConfigDef)
+  embeddedValidator(String;Validator)
+  embeddedDependents(String;List<String>)
+  embeddedRecommender(String;Recommender)
+  toHtml()
+  toHtml(int;Function<String,String>)
+  toHtml(Map<String,String>)
+  toHtml(int;Function<String,String>;Map<String,String>)
+  addConfigDetail(StringBuilder;String;String)
} 
@enduml
