@startuml
!pragma layout smetana
"InputStream" <|-- "java.io.PipedInputStream"
class java.io.PipedInputStream {
+PipedInputStream(PipedOutputStream) : PipedInputStream [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#105]]]
+PipedInputStream(PipedOutputStream;int) : PipedInputStream [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#123]]]
+PipedInputStream() : PipedInputStream [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#137]]]
+PipedInputStream(int) : PipedInputStream [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#153]]]
-initPipe(int) : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#157]]]
+connect(PipedOutputStream) : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#187]]]
receive(int) : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#200]]]
receive(byte[];int;int) : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#225]]]
-checkStateForReceive() : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#256]]]
-awaitSpace() : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#266]]]
receivedLast() : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#284]]]
+read() : int [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#303]]]
+read(byte[];int;int) : int [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#367]]]
+available() : int [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#426]]]
+close() : void [[[./../.././qc/secujava/java.io.PipedInputStream.java.html#443]]]
} 
@enduml
