@startuml
!pragma layout smetana
"java.io.Serializable" <|-- "java.lang.Class"
class java.lang.Class {
-registerNatives() : void [[[./../.././qc/secujava/java.lang.Class.java.html#332]]]
-Class(ClassLoader;Class<?>) : Class [[[./../.././qc/secujava/java.lang.Class.java.html#346]]]
+toString() : String [[[./../.././qc/secujava/java.lang.Class.java.html#376]]]
+toGenericString() : String [[[./../.././qc/secujava/java.lang.Class.java.html#446]]]
typeVarBounds(TypeVariable<?>) : String [[[./../.././qc/secujava/java.lang.Class.java.html#498]]]
+forName(String) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#590]]]
-forName(String;Class<?>) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#598]]]
+forName(String;boolean;ClassLoader) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#740]]]
-forName(String;boolean;ClassLoader;Class<?>) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#757]]]
-forName0(String;boolean;ClassLoader;Class<?>) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#777]]]
+forName(Module;String) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#876]]]
-forName(Module;String;Class<?>) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#888]]]
+newInstance() : T [[[./../.././qc/secujava/java.lang.Class.java.html#1021]]]
+isInstance(Object) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1129]]]
+isAssignableFrom(Class<?>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1182]]]
+isInterface() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1199]]]
+isArray() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1216]]]
+isPrimitive() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1275]]]
+isAnnotation() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1294]]]
+isSynthetic() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#1319]]]
+getName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#1446]]]
-initClassName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#1454]]]
+getClassLoader() : ClassLoader [[[./../.././qc/secujava/java.lang.Class.java.html#1499]]]
getClassLoader0() : ClassLoader [[[./../.././qc/secujava/java.lang.Class.java.html#1512]]]
+getModule() : Module [[[./../.././qc/secujava/java.lang.Class.java.html#1545]]]
getClassData() : Object [[[./../.././qc/secujava/java.lang.Class.java.html#1561]]]
+getTypeParameters() : TypeVariable<Class<T>>[] [[[./../.././qc/secujava/java.lang.Class.java.html#1595]]]
+getSuperclass() : Class<?superT> [[[./../.././qc/secujava/java.lang.Class.java.html#1626]]]
+getGenericSuperclass() : Type [[[./../.././qc/secujava/java.lang.Class.java.html#1688]]]
+getPackage() : Package [[[./../.././qc/secujava/java.lang.Class.java.html#1721]]]
+getPackageName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#1781]]]
+getInterfaces() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#1887]]]
-getInterfaces(boolean) : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#1892]]]
-getInterfaces0() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#1908]]]
+getGenericInterfaces() : Type[] [[[./../.././qc/secujava/java.lang.Class.java.html#2005]]]
+getComponentType() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2030]]]
-elementType() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2050]]]
+getModifiers() : int [[[./../.././qc/secujava/java.lang.Class.java.html#2136]]]
+accessFlags() : Set<AccessFlag> [[[./../.././qc/secujava/java.lang.Class.java.html#2183]]]
+getSigners() : Object[] [[[./../.././qc/secujava/java.lang.Class.java.html#2213]]]
setSigners(Object[]) : void [[[./../.././qc/secujava/java.lang.Class.java.html#2221]]]
+getEnclosingMethod() : Method [[[./../.././qc/secujava/java.lang.Class.java.html#2296]]]
-getEnclosingMethod0() : Object[] [[[./../.././qc/secujava/java.lang.Class.java.html#2354]]]
-getEnclosingMethodInfo() : EnclosingMethodInfo [[[./../.././qc/secujava/java.lang.Class.java.html#2356]]]
-toClass(Type) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2416]]]
+getEnclosingConstructor() : Constructor<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2492]]]
+getDeclaringClass() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2577]]]
-getDeclaringClass0() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2591]]]
+getEnclosingClass() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#2620]]]
+getSimpleName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2687]]]
-getSimpleName0() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2696]]]
+getTypeName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2719]]]
+getCanonicalName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2785]]]
-getCanonicalName0() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2794]]]
+isAnonymousClass() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2841]]]
+isLocalClass() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2861]]]
+isMemberClass() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2881]]]
-getSimpleBinaryName() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2896]]]
-getSimpleBinaryName0() : String [[[./../.././qc/secujava/java.lang.Class.java.html#2905]]]
-isTopLevelClass() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2914]]]
-isLocalOrAnonymousClass() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2925]]]
-hasEnclosingMethodInfo() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#2932]]]
+getClasses() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#2988]]]
+getFields() : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#3093]]]
+getMethods() : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#3263]]]
+getConstructors() : Constructor<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#3335]]]
+getField(String) : Field [[[./../.././qc/secujava/java.lang.Class.java.html#3429]]]
+getMethod(String;Class<?>...) : Method [[[./../.././qc/secujava/java.lang.Class.java.html#3631]]]
+getConstructor(Class<?>...) : Constructor<T> [[[./../.././qc/secujava/java.lang.Class.java.html#3710]]]
+getDeclaredClasses() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#3795]]]
+getDeclaredFields() : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#3889]]]
+getRecordComponents() : RecordComponent[] [[[./../.././qc/secujava/java.lang.Class.java.html#4002]]]
+getDeclaredMethods() : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#4130]]]
+getDeclaredConstructors() : Constructor<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#4221]]]
+getDeclaredField(String) : Field [[[./../.././qc/secujava/java.lang.Class.java.html#4311]]]
+getDeclaredMethod(String;Class<?>...) : Method [[[./../.././qc/secujava/java.lang.Class.java.html#4423]]]
getDeclaredPublicMethods(String;Class<?>...) : List<Method> [[[./../.././qc/secujava/java.lang.Class.java.html#4457]]]
+getDeclaredConstructor(Class<?>...) : Constructor<T> [[[./../.././qc/secujava/java.lang.Class.java.html#4554]]]
+getResourceAsStream(String) : InputStream [[[./../.././qc/secujava/java.lang.Class.java.html#4677]]]
+getResource(String) : URL [[[./../.././qc/secujava/java.lang.Class.java.html#4826]]]
-isOpenToCaller(String;Class<?>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#4871]]]
+getProtectionDomain() : java.security.ProtectionDomain [[[./../.././qc/secujava/java.lang.Class.java.html#4934]]]
protectionDomain() : java.security.ProtectionDomain [[[./../.././qc/secujava/java.lang.Class.java.html#4944]]]
-getProtectionDomain0() : java.security.ProtectionDomain [[[./../.././qc/secujava/java.lang.Class.java.html#4964]]]
getPrimitiveClass(String) : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#4973]]]
-checkMemberAccess(SecurityManager;int;Class<?>;boolean) : void [[[./../.././qc/secujava/java.lang.Class.java.html#4996]]]
-checkPackageAccess(SecurityManager;ClassLoader;boolean) : void [[[./../.././qc/secujava/java.lang.Class.java.html#5030]]]
-checkPackageAccessForPermittedSubclasses(SecurityManager;ClassLoader;Class<?>[]) : void [[[./../.././qc/secujava/java.lang.Class.java.html#5068]]]
-resolveName(String) : String [[[./../.././qc/secujava/java.lang.Class.java.html#5096]]]
-reflectionData() : ReflectionData<T> [[[./../.././qc/secujava/java.lang.Class.java.html#5191]]]
-newReflectionData(SoftReference<ReflectionData<T>>;int) : ReflectionData<T> [[[./../.././qc/secujava/java.lang.Class.java.html#5205]]]
-getGenericSignature0() : String [[[./../.././qc/secujava/java.lang.Class.java.html#5225]]]
-getFactory() : GenericsFactory [[[./../.././qc/secujava/java.lang.Class.java.html#5231]]]
-getGenericInfo() : ClassRepository [[[./../.././qc/secujava/java.lang.Class.java.html#5238]]]
getRawAnnotations() : byte[] [[[./../.././qc/secujava/java.lang.Class.java.html#5253]]]
getRawTypeAnnotations() : byte[] [[[./../.././qc/secujava/java.lang.Class.java.html#5255]]]
getExecutableTypeAnnotationBytes(Executable) : byte[] [[[./../.././qc/secujava/java.lang.Class.java.html#5256]]]
getConstantPool() : ConstantPool [[[./../.././qc/secujava/java.lang.Class.java.html#5260]]]
-privateGetDeclaredFields(boolean) : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#5271]]]
-privateGetPublicFields() : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#5293]]]
-addAll(Collection<Field>;Field[]) : void [[[./../.././qc/secujava/java.lang.Class.java.html#5326]]]
-privateGetDeclaredConstructors(boolean) : Constructor<T>[] [[[./../.././qc/secujava/java.lang.Class.java.html#5342]]]
-privateGetDeclaredMethods(boolean) : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#5376]]]
-privateGetPublicMethods() : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#5398]]]
-searchFields(Field[];String) : Field [[[./../.././qc/secujava/java.lang.Class.java.html#5442]]]
-getField0(String) : Field [[[./../.././qc/secujava/java.lang.Class.java.html#5454]]]
-searchMethods(Method[];String;Class<?>[]) : Method [[[./../.././qc/secujava/java.lang.Class.java.html#5487]]]
-getMethod0(String;Class<?>[]) : Method [[[./../.././qc/secujava/java.lang.Class.java.html#5510]]]
-getMethodsRecursive(String;Class<?>[];boolean) : PublicMethods.MethodList [[[./../.././qc/secujava/java.lang.Class.java.html#5521]]]
-getConstructor0(Class<?>[];int) : Constructor<T> [[[./../.././qc/secujava/java.lang.Class.java.html#5556]]]
-arrayContentsEq(Object[];Object[]) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5574]]]
-copyFields(Field[]) : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#5596]]]
-copyMethods(Method[]) : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#5605]]]
-getDeclaredFields0(boolean) : Field[] [[[./../.././qc/secujava/java.lang.Class.java.html#5623]]]
-getDeclaredMethods0(boolean) : Method[] [[[./../.././qc/secujava/java.lang.Class.java.html#5624]]]
-getDeclaredConstructors0(boolean) : Constructor<T>[] [[[./../.././qc/secujava/java.lang.Class.java.html#5625]]]
-getDeclaredClasses0() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#5626]]]
-getRecordComponents0() : RecordComponent[] [[[./../.././qc/secujava/java.lang.Class.java.html#5641]]]
-isRecord0() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5642]]]
-methodToString(String;Class<?>[]) : String [[[./../.././qc/secujava/java.lang.Class.java.html#5649]]]
+desiredAssertionStatus() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5748]]]
-desiredAssertionStatus0(Class<?>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5765]]]
+isEnum() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5802]]]
+isRecord() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#5841]]]
-getReflectionFactory() : ReflectionFactory [[[./../.././qc/secujava/java.lang.Class.java.html#5851]]]
+getEnumConstants() : T[] [[[./../.././qc/secujava/java.lang.Class.java.html#5883]]]
getEnumConstantsShared() : T[] [[[./../.././qc/secujava/java.lang.Class.java.html#5900]]]
enumConstantDirectory() : Map<String,T> [[[./../.././qc/secujava/java.lang.Class.java.html#5940]]]
+cast(Object) : T [[[./../.././qc/secujava/java.lang.Class.java.html#5982]]]
-cannotCastMsg(Object) : String [[[./../.././qc/secujava/java.lang.Class.java.html#5988]]]
+isAnnotationPresent(Class<?extendsAnnotation>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#6076]]]
+getAnnotations() : Annotation[] [[[./../.././qc/secujava/java.lang.Class.java.html#6119]]]
+getDeclaredAnnotations() : Annotation[] [[[./../.././qc/secujava/java.lang.Class.java.html#6183]]]
-annotationData() : AnnotationData [[[./../.././qc/secujava/java.lang.Class.java.html#6208]]]
-createAnnotationData(int) : AnnotationData [[[./../.././qc/secujava/java.lang.Class.java.html#6226]]]
casAnnotationType(AnnotationType;AnnotationType) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#6263]]]
getAnnotationType() : AnnotationType [[[./../.././qc/secujava/java.lang.Class.java.html#6267]]]
getDeclaredAnnotationMap() : Map<Class<?extendsAnnotation>,Annotation> [[[./../.././qc/secujava/java.lang.Class.java.html#6271]]]
+getAnnotatedSuperclass() : AnnotatedType [[[./../.././qc/secujava/java.lang.Class.java.html#6319]]]
+getAnnotatedInterfaces() : AnnotatedType[] [[[./../.././qc/secujava/java.lang.Class.java.html#6392]]]
-getNestHost0() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#6396]]]
+getNestHost() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#6466]]]
+isNestmateOf(Class<?>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#6508]]]
-getNestMembers0() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#6520]]]
+getNestMembers() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#6614]]]
+descriptorString() : String [[[./../.././qc/secujava/java.lang.Class.java.html#6745]]]
+componentType() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#6793]]]
+arrayType() : Class<?> [[[./../.././qc/secujava/java.lang.Class.java.html#6821]]]
+describeConstable() : Optional<ClassDesc> [[[./../.././qc/secujava/java.lang.Class.java.html#6845]]]
+isHidden() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#6867]]]
+getPermittedSubclasses() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#6941]]]
-isDirectSubType(Class<?>) : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#6966]]]
+isSealed() : boolean [[[./../.././qc/secujava/java.lang.Class.java.html#7008]]]
-getPermittedSubclasses0() : Class<?>[] [[[./../.././qc/secujava/java.lang.Class.java.html#7015]]]
-getClassFileVersion() : int [[[./../.././qc/secujava/java.lang.Class.java.html#7034]]]
-getClassFileVersion0() : int [[[./../.././qc/secujava/java.lang.Class.java.html#7039]]]
-getClassAccessFlagsRaw() : int [[[./../.././qc/secujava/java.lang.Class.java.html#7054]]]
-getClassAccessFlagsRaw0() : int [[[./../.././qc/secujava/java.lang.Class.java.html#7059]]]
} 
@enduml
