@startuml
!pragma layout smetana
"Reader" <|-- "java.io.BufferedReader"
class java.io.BufferedReader {
+BufferedReader(Reader;int) : BufferedReader [[[./../.././qc/secujava/java.io.BufferedReader.java.html#100]]]
+BufferedReader(Reader) : BufferedReader [[[./../.././qc/secujava/java.io.BufferedReader.java.html#115]]]
-ensureOpen() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#120]]]
-fill() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#128]]]
+read() : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#177]]]
-read1(char[];int;int) : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#202]]]
+read(char[];int;int) : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#276]]]
readLine(boolean) : String [[[./../.././qc/secujava/java.io.BufferedReader.java.html#312]]]
+readLine() : String [[[./../.././qc/secujava/java.io.BufferedReader.java.html#388]]]
+skip(long) : long [[[./../.././qc/secujava/java.io.BufferedReader.java.html#402]]]
+ready() : boolean [[[./../.././qc/secujava/java.io.BufferedReader.java.html#442]]]
+markSupported() : boolean [[[./../.././qc/secujava/java.io.BufferedReader.java.html#470]]]
+mark(int) : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#490]]]
+reset() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#508]]]
+close() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#520]]]
+lines() : Stream<String> [[[./../.././qc/secujava/java.io.BufferedReader.java.html#561]]]
} 
@enduml
