@startuml
!pragma layout smetana
"NumberComparable<Double>" <|-- "java.lang.Double"
class java.lang.Double {
+toString(double) : String [[[./../.././qc/secujava/java.lang.Double.java.html#348]]]
+toHexString(double) : String [[[./../.././qc/secujava/java.lang.Double.java.html#499]]]
+valueOf(String) : Double [[[./../.././qc/secujava/java.lang.Double.java.html#904]]]
+valueOf(double) : Double [[[./../.././qc/secujava/java.lang.Double.java.html#933]]]
+parseDouble(String) : double [[[./../.././qc/secujava/java.lang.Double.java.html#966]]]
+isNaN(double) : boolean [[[./../.././qc/secujava/java.lang.Double.java.html#985]]]
+isInfinite(double) : boolean [[[./../.././qc/secujava/java.lang.Double.java.html#1004]]]
+Double(double) : Double [[[./../.././qc/secujava/java.lang.Double.java.html#1030]]]
+Double(String) : Double [[[./../.././qc/secujava/java.lang.Double.java.html#1055]]]
+isNaN() : boolean [[[./../.././qc/secujava/java.lang.Double.java.html#1073]]]
+isInfinite() : boolean [[[./../.././qc/secujava/java.lang.Double.java.html#1092]]]
+toString() : String [[[./../.././qc/secujava/java.lang.Double.java.html#1113]]]
+byteValue() : byte [[[./../.././qc/secujava/java.lang.Double.java.html#1132]]]
+shortValue() : short [[[./../.././qc/secujava/java.lang.Double.java.html#1151]]]
+intValue() : int [[[./../.././qc/secujava/java.lang.Double.java.html#1168]]]
+longValue() : long [[[./../.././qc/secujava/java.lang.Double.java.html#1185]]]
+floatValue() : float [[[./../.././qc/secujava/java.lang.Double.java.html#1204]]]
+doubleValue() : double [[[./../.././qc/secujava/java.lang.Double.java.html#1219]]]
+hashCode() : int [[[./../.././qc/secujava/java.lang.Double.java.html#1264]]]
+equals(Object) : boolean [[[./../.././qc/secujava/java.lang.Double.java.html#1346]]]
+doubleToLongBits(double) : long [[[./../.././qc/secujava/java.lang.Double.java.html#1586]]]
+doubleToRawLongBits(double) : long [[[./../.././qc/secujava/java.lang.Double.java.html#1586]]]
+longBitsToDouble(long) : double [[[./../.././qc/secujava/java.lang.Double.java.html#1]]]
+compareTo(Double) : int [[[./../.././qc/secujava/java.lang.Double.java.html#1]]]
+compare(double;double) : int [[[./../.././qc/secujava/java.lang.Double.java.html#1]]]
} 
@enduml
