@startuml
!pragma layout smetana
"Reader" <|-- "java.io.InputStreamReader"
class java.io.InputStreamReader {
+InputStreamReader(InputStream) : InputStreamReader [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#71]]]
+InputStreamReader(InputStream;String) : InputStreamReader [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#94]]]
+InputStreamReader(InputStream;Charset) : InputStreamReader [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#112]]]
+InputStreamReader(InputStream;CharsetDecoder) : InputStreamReader [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#128]]]
+getEncoding() : String [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#155]]]
+read() : int [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#167]]]
+read(char[];int;int) : int [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#183]]]
+ready() : boolean [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#194]]]
+close() : void [[[./../.././qc/secujava/java.io.InputStreamReader.java.html#198]]]
} 
@enduml
