@startuml
!pragma layout smetana
"java.lang.Object" <|-- "java.lang.Object"
class java.lang.Object {
-registerNatives() : void [[[./../.././qc/secujava/java.lang.Object.java.html#70]]]
+getClass() : Class<?> [[[./../.././qc/secujava/java.lang.Object.java.html#114]]]
+hashCode() : int [[[./../.././qc/secujava/java.lang.Object.java.html#185]]]
+equals(Object) : boolean [[[./../.././qc/secujava/java.lang.Object.java.html#278]]]
clone() : Object [[[./../.././qc/secujava/java.lang.Object.java.html#401]]]
+toString() : String [[[./../.././qc/secujava/java.lang.Object.java.html#445]]]
+notify() : void [[[./../.././qc/secujava/java.lang.Object.java.html#512]]]
+notifyAll() : void [[[./../.././qc/secujava/java.lang.Object.java.html#557]]]
+wait(long) : void [[[./../.././qc/secujava/java.lang.Object.java.html#868]]]
+wait(long;int) : void [[[./../.././qc/secujava/java.lang.Object.java.html#1]]]
+wait() : void [[[./../.././qc/secujava/java.lang.Object.java.html#1]]]
finalize() : void [[[./../.././qc/secujava/java.lang.Object.java.html#1]]]
} 
@enduml
