@startuml
!pragma layout smetana
"NumberComparable<Byte>" <|-- "java.lang.Byte"
class java.lang.Byte {
+toString(byte) : String [[[./../.././qc/secujava/java.lang.Byte.java.html#126]]]
+valueOf(byte) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#166]]]
+parseByte(String;int) : byte [[[./../.././qc/secujava/java.lang.Byte.java.html#252]]]
+parseByte(String) : byte [[[./../.././qc/secujava/java.lang.Byte.java.html#296]]]
+valueOf(String;int) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#349]]]
+valueOf(String) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#397]]]
+decode(String) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#484]]]
+Byte(byte) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#516]]]
+Byte(String) : Byte [[[./../.././qc/secujava/java.lang.Byte.java.html#545]]]
+byteValue() : byte [[[./../.././qc/secujava/java.lang.Byte.java.html#556]]]
+shortValue() : short [[[./../.././qc/secujava/java.lang.Byte.java.html#567]]]
+intValue() : int [[[./../.././qc/secujava/java.lang.Byte.java.html#578]]]
+longValue() : long [[[./../.././qc/secujava/java.lang.Byte.java.html#589]]]
+floatValue() : float [[[./../.././qc/secujava/java.lang.Byte.java.html#600]]]
+doubleValue() : double [[[./../.././qc/secujava/java.lang.Byte.java.html#611]]]
+toString() : String [[[./../.././qc/secujava/java.lang.Byte.java.html#634]]]
+hashCode() : int [[[./../.././qc/secujava/java.lang.Byte.java.html#649]]]
+equals(Object) : boolean [[[./../.././qc/secujava/java.lang.Byte.java.html#672]]]
+compareTo(Byte) : int [[[./../.././qc/secujava/java.lang.Byte.java.html#704]]]
+compare(byte;byte) : int [[[./../.././qc/secujava/java.lang.Byte.java.html#735]]]
} 
@enduml
