@startuml
!pragma layout smetana
"ServletRequest" <|-- "javax.servlet.http.HttpServletRequest"
class javax.servlet.http.HttpServletRequest {
+getAuthType() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#26]]]
+getCookies() : Cookie[] [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#33]]]
+getDateHeader(String) : long [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#40]]]
+getHeader(String) : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#47]]]
+getHeaders(String) : Enumeration [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#54]]]
+getHeaderNames() : Enumeration [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#62]]]
+getIntHeader(String) : int [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#69]]]
+getMethod() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#76]]]
+getPathInfo() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#83]]]
+getPathTranslated() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#90]]]
+getContextPath() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#97]]]
+getQueryString() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#104]]]
+getRemoteUser() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#111]]]
+isUserInRole(String) : boolean [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#118]]]
+getUserPrincipal() : java.security.Principal [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#125]]]
+getRequestedSessionId() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#132]]]
+getRequestURI() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#198]]]
+getRequestURL() : StringBuffer [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#198]]]
+getServletPath() : String [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#198]]]
+getSession(boolean) : HttpSession [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
+getSession() : HttpSession [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
+isRequestedSessionIdValid() : boolean [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
+isRequestedSessionIdFromCookie() : boolean [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
+isRequestedSessionIdFromURL() : boolean [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
+isRequestedSessionIdFromUrl() : boolean [[[./../.././qc/secujava/javax.servlet.http.HttpServletRequest.java.html#1]]]
} 
@enduml
