@startuml
!pragma layout smetana
"OutputStreamObjectOutput" <|-- "java.io.ObjectOutputStream"
class java.io.ObjectOutputStream {
+ObjectOutputStream(OutputStream) : ObjectOutputStream [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#240]]]
ObjectOutputStream() : ObjectOutputStream [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#272]]]
+useProtocolVersion(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#304]]]
+writeObject(Object) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#342]]]
writeObjectOverride(Object) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#371]]]
+writeUnshared(Object) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#413]]]
+defaultWriteObject() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#433]]]
+putFields() : ObjectOutputStream.PutField [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#455]]]
+writeFields() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#477]]]
+reset() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#496]]]
annotateClass(Class<?>) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#522]]]
annotateProxyClass(Class<?>) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#546]]]
replaceObject(Object) : Object [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#587]]]
enableReplaceObject(boolean) : boolean [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#611]]]
writeStreamHeader() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#635]]]
writeClassDescriptor(ObjectStreamClass) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#665]]]
+write(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#678]]]
+write(byte[]) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#689]]]
+write(byte[];int;int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#701]]]
+flush() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#718]]]
drain() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#729]]]
+close() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#739]]]
+writeBoolean(boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#752]]]
+writeByte(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#763]]]
+writeShort(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#774]]]
+writeChar(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#785]]]
+writeInt(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#796]]]
+writeLong(long) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#807]]]
+writeFloat(float) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#818]]]
+writeDouble(double) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#829]]]
+writeBytes(String) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#840]]]
+writeChars(String) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#851]]]
+writeUTF(String) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#868]]]
getProtocolVersion() : int [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1015]]]
writeTypeString(String) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1023]]]
-verifySubclass() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1040]]]
-auditSubclass(Class<?>) : boolean [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1067]]]
-clear() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1097]]]
-writeObject0(Object;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1105]]]
-writeNull() : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1196]]]
-writeHandle(int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1203]]]
-writeClass(Class<?>;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1211]]]
-writeClassDesc(ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1220]]]
-isCustomSubclass() : boolean [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1235]]]
-writeProxyDesc(ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1244]]]
-writeNonProxyDesc(ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1272]]]
-writeString(String;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1301]]]
-writeArray(Object;ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1316]]]
-writeEnum(Enum<?>;ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1396]]]
-writeOrdinaryObject(Object;ObjectStreamClass;boolean) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1413]]]
-writeExternalData(Externalizable) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1445]]]
-writeSerialData(Object;ObjectStreamClass) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1477]]]
-defaultWriteFields(Object;ObjectStreamClass) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1519]]]
-writeFatalException(IOException) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1562]]]
-floatsToBytes(float[];int;byte[];int;int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1588]]]
-doublesToBytes(double[];int;byte[];int;int) : void [[[./../.././qc/secujava/java.io.ObjectOutputStream.java.html#1596]]]
} 
@enduml
