@startuml
!pragma layout smetana
"Reader" <|-- "java.io.PipedReader"
class java.io.PipedReader {
+PipedReader(PipedWriter) : PipedReader [[[./../.././qc/secujava/java.io.PipedReader.java.html#81]]]
+PipedReader(PipedWriter;int) : PipedReader [[[./../.././qc/secujava/java.io.PipedReader.java.html#97]]]
+PipedReader() : PipedReader [[[./../.././qc/secujava/java.io.PipedReader.java.html#110]]]
+PipedReader(int) : PipedReader [[[./../.././qc/secujava/java.io.PipedReader.java.html#126]]]
-initPipe(int) : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#130]]]
+connect(PipedWriter) : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#160]]]
receive(int) : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#168]]]
receive(char[];int;int) : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#204]]]
receivedLast() : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#214]]]
+read() : int [[[./../.././qc/secujava/java.io.PipedReader.java.html#233]]]
+read(char[];int;int) : int [[[./../.././qc/secujava/java.io.PipedReader.java.html#290]]]
+ready() : boolean [[[./../.././qc/secujava/java.io.PipedReader.java.html#336]]]
+close() : void [[[./../.././qc/secujava/java.io.PipedReader.java.html#358]]]
} 
@enduml
