@startuml
!pragma layout smetana
"java.lang.Object" <|-- "java.net.CacheRequest"
class java.net.CacheRequest {
+getBody() : OutputStream [[[./../.././qc/secujava/java.net.CacheRequest.java.html#55]]]
+abort() : void [[[./../.././qc/secujava/java.net.CacheRequest.java.html#62]]]
} 
@enduml
