@startuml
!pragma layout smetana
"Dictionary<K,V>Map<K,V>" <|-- "java.util.Hashtable"
class java.util.Hashtable {
+Hashtable(int;float) : Hashtable [[[./../.././qc/secujava/java.util.Hashtable.java.html#185]]]
+Hashtable(int) : Hashtable [[[./../.././qc/secujava/java.util.Hashtable.java.html#207]]]
+Hashtable() : Hashtable [[[./../.././qc/secujava/java.util.Hashtable.java.html#215]]]
+Hashtable(Map<?extendsK,?extendsV>) : Hashtable [[[./../.././qc/secujava/java.util.Hashtable.java.html#228]]]
Hashtable(Void) : Hashtable [[[./../.././qc/secujava/java.util.Hashtable.java.html#239]]]
+size() : int [[[./../.././qc/secujava/java.util.Hashtable.java.html#246]]]
+isEmpty() : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#256]]]
+keys() : Enumeration<K> [[[./../.././qc/secujava/java.util.Hashtable.java.html#272]]]
+elements() : Enumeration<V> [[[./../.././qc/secujava/java.util.Hashtable.java.html#288]]]
+contains(Object) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#308]]]
+containsValue(Object) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#336]]]
+containsKey(Object) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#350]]]
+get(Object) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#378]]]
rehash() : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#406]]]
-addEntry(int;K;V;int) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#436]]]
+put(K;V) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#472]]]
+remove(Object) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#505]]]
+putAll(Map<?extendsK,?extendsV>) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#537]]]
+clear() : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#545]]]
+clone() : Object [[[./../.././qc/secujava/java.util.Hashtable.java.html#560]]]
cloneHashtable() : Hashtable<?,?> [[[./../.././qc/secujava/java.util.Hashtable.java.html#575]]]
+toString() : String [[[./../.././qc/secujava/java.util.Hashtable.java.html#594]]]
+keySet() : Set<K> [[[./../.././qc/secujava/java.util.Hashtable.java.html#660]]]
+entrySet() : Set<Map.Entry<K,V>> [[[./../.././qc/secujava/java.util.Hashtable.java.html#700]]]
+values() : Collection<V> [[[./../.././qc/secujava/java.util.Hashtable.java.html#781]]]
+equals(Object) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#814]]]
+hashCode() : int [[[./../.././qc/secujava/java.util.Hashtable.java.html#852]]]
+getOrDefault(Object;V) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#882]]]
+forEach(BiConsumer<?superK,?superV>) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#889]]]
+replaceAll(BiFunction<?superK,?superV,?extendsV>) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#909]]]
+putIfAbsent(K;V) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#929]]]
+remove(Object;Object) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#953]]]
+replace(K;V;V) : boolean [[[./../.././qc/secujava/java.util.Hashtable.java.html#978]]]
+replace(K;V) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#1000]]]
+computeIfAbsent(K;Function<?superK,?extendsV>) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#1028]]]
+computeIfPresent(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#1064]]]
+compute(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#1106]]]
+merge(K;V;BiFunction<?superV,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.Hashtable.java.html#1157]]]
-writeObject(java.io.ObjectOutputStream) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1205]]]
writeHashtable(java.io.ObjectOutputStream) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1214]]]
defaultWriteHashtable(java.io.ObjectOutputStream;int;float) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1248]]]
-readObject(ObjectInputStream) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1259]]]
readHashtable(ObjectInputStream) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1268]]]
-reconstitutionPut(Entry<?,?>[];K;V) : void [[[./../.././qc/secujava/java.util.Hashtable.java.html#1346]]]
} 
@enduml
