@startuml
!pragma layout smetana
"InputStreamReader" <|-- "java.io.FileReader"
class java.io.FileReader {
+FileReader(String) : FileReader [[[./../.././qc/secujava/java.io.FileReader.java.html#10]]]
+FileReader(File) : FileReader [[[./../.././qc/secujava/java.io.FileReader.java.html#15]]]
+FileReader(FileDescriptor) : FileReader [[[./../.././qc/secujava/java.io.FileReader.java.html#20]]]
} 
@enduml
