@startuml
!pragma layout smetana
"Wrapper" <|-- "secujava.Connection"
class secujava.Connection {
createStatement() : Statement [[[./../.././qc/secujava/java.sql.Connection.java.html#211]]]
prepareStatement(String) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#276]]]
prepareCall(String) : CallableStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#337]]]
nativeSQL(String) : String [[[./../.././qc/secujava/java.sql.Connection.java.html#362]]]
setAutoCommit(boolean) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#433]]]
getAutoCommit() : boolean [[[./../.././qc/secujava/java.sql.Connection.java.html#454]]]
commit() : void [[[./../.././qc/secujava/java.sql.Connection.java.html#481]]]
rollback() : void [[[./../.././qc/secujava/java.sql.Connection.java.html#506]]]
close() : void [[[./../.././qc/secujava/java.sql.Connection.java.html#537]]]
isClosed() : boolean [[[./../.././qc/secujava/java.sql.Connection.java.html#572]]]
getMetaData() : DatabaseMetaData [[[./../.././qc/secujava/java.sql.Connection.java.html#602]]]
setReadOnly(boolean) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#627]]]
isReadOnly() : boolean [[[./../.././qc/secujava/java.sql.Connection.java.html#646]]]
setCatalog(String) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#689]]]
getCatalog() : String [[[./../.././qc/secujava/java.sql.Connection.java.html#706]]]
setTransactionIsolation(int) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#834]]]
getTransactionIsolation() : int [[[./../.././qc/secujava/java.sql.Connection.java.html#865]]]
getWarnings() : SQLWarning [[[./../.././qc/secujava/java.sql.Connection.java.html#908]]]
clearWarnings() : void [[[./../.././qc/secujava/java.sql.Connection.java.html#927]]]
createStatement(int;int) : Statement [[[./../.././qc/secujava/java.sql.Connection.java.html#986]]]
prepareStatement(String;int;int) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1052]]]
prepareCall(String;int;int) : CallableStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1114]]]
getTypeMap() : java.util.Map<String,Class<?>> [[[./../.././qc/secujava/java.sql.Connection.java.html#1166]]]
setTypeMap(java.util.Map<String,Class<?>>) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#1219]]]
setHoldability(int) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#1261]]]
getHoldability() : int [[[./../.././qc/secujava/java.sql.Connection.java.html#1290]]]
setSavepoint() : Savepoint [[[./../.././qc/secujava/java.sql.Connection.java.html#1327]]]
setSavepoint(String) : Savepoint [[[./../.././qc/secujava/java.sql.Connection.java.html#1366]]]
rollback(Savepoint) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#1405]]]
releaseSavepoint(Savepoint) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#1434]]]
createStatement(int;int;int) : Statement [[[./../.././qc/secujava/java.sql.Connection.java.html#1503]]]
prepareStatement(String;int;int;int) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1583]]]
prepareCall(String;int;int;int) : CallableStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1658]]]
prepareStatement(String;int) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1745]]]
prepareStatement(String;int[]) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1837]]]
prepareStatement(String;String[]) : PreparedStatement [[[./../.././qc/secujava/java.sql.Connection.java.html#1929]]]
createClob() : Clob [[[./../.././qc/secujava/java.sql.Connection.java.html#1959]]]
createBlob() : Blob [[[./../.././qc/secujava/java.sql.Connection.java.html#1988]]]
createNClob() : NClob [[[./../.././qc/secujava/java.sql.Connection.java.html#2017]]]
createSQLXML() : SQLXML [[[./../.././qc/secujava/java.sql.Connection.java.html#2044]]]
isValid(int) : boolean [[[./../.././qc/secujava/java.sql.Connection.java.html#2091]]]
setClientInfo(String;String) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#2198]]]
setClientInfo(Properties) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#2260]]]
getClientInfo(String) : String [[[./../.././qc/secujava/java.sql.Connection.java.html#2305]]]
getClientInfo() : Properties [[[./../.././qc/secujava/java.sql.Connection.java.html#2336]]]
createArrayOf(String;Object[]) : Array [[[./../.././qc/secujava/java.sql.Connection.java.html#2389]]]
createStruct(String;Object[]) : Struct [[[./../.././qc/secujava/java.sql.Connection.java.html#2418]]]
setSchema(String) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#2460]]]
getSchema() : String [[[./../.././qc/secujava/java.sql.Connection.java.html#2479]]]
abort(Executor) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#2552]]]
setNetworkTimeout(Executor;int) : void [[[./../.././qc/secujava/java.sql.Connection.java.html#2733]]]
getNetworkTimeout() : int [[[./../.././qc/secujava/java.sql.Connection.java.html#2765]]]
} 
@enduml
