@startuml
!pragma layout smetana
"Reader" <|-- "java.io.BufferedReader"
class java.io.BufferedReader {
+BufferedReader(Reader;int) : BufferedReader [[[./../.././qc/secujava/java.io.BufferedReader.java.html#37]]]
+BufferedReader(Reader) : BufferedReader [[[./../.././qc/secujava/java.io.BufferedReader.java.html#47]]]
-ensureOpen() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#52]]]
-fill() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#58]]]
+read() : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#100]]]
-read1(char[];int;int) : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#122]]]
+read(char[];int;int) : int [[[./../.././qc/secujava/java.io.BufferedReader.java.html#148]]]
readLine(boolean) : String [[[./../.././qc/secujava/java.io.BufferedReader.java.html#170]]]
+readLine() : String [[[./../.././qc/secujava/java.io.BufferedReader.java.html#234]]]
+skip(long) : long [[[./../.././qc/secujava/java.io.BufferedReader.java.html#239]]]
+ready() : boolean [[[./../.././qc/secujava/java.io.BufferedReader.java.html#273]]]
+markSupported() : boolean [[[./../.././qc/secujava/java.io.BufferedReader.java.html#294]]]
+mark(int) : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#299]]]
+reset() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#312]]]
+close() : void [[[./../.././qc/secujava/java.io.BufferedReader.java.html#324]]]
+lines() : Stream<String> [[[./../.././qc/secujava/java.io.BufferedReader.java.html#338]]]
} 
@enduml
