@startuml
!pragma layout smetana
"Writer" <|-- "java.io.BufferedWriter"
class java.io.BufferedWriter {
+BufferedWriter(Writer) : BufferedWriter [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#87]]]
+BufferedWriter(Writer;int) : BufferedWriter [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#100]]]
-ensureOpen() : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#114]]]
flushBuffer() : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#124]]]
+write(int) : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#139]]]
-min(int;int) : int [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#152]]]
+write(char[];int;int) : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#173]]]
+write(String;int;int) : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#219]]]
+newLine() : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#242]]]
+flush() : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#251]]]
+close() : void [[[./../.././qc/secujava/java.io.BufferedWriter.java.html#259]]]
} 
@enduml
