@startuml
!pragma layout smetana
"Map<K,V>" <|-- "java.util.concurrent.ConcurrentMap"
class java.util.concurrent.ConcurrentMap {
getOrDefault(Object;V) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#78]]]
forEach(BiConsumer<?superK,?superV>) : void [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#102]]]
putIfAbsent(K;V) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#150]]]
remove(Object;Object) : boolean [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#180]]]
replace(K;V;V) : boolean [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#211]]]
replace(K;V) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#244]]]
replaceAll(BiFunction<?superK,?superV,?extendsV>) : void [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#275]]]
computeIfAbsent(K;Function<?superK,?extendsV>) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#319]]]
computeIfPresent(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#362]]]
compute(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#416]]]
merge(K;V;BiFunction<?superV,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.concurrent.ConcurrentMap.java.html#495]]]
} 
@enduml
