@startuml
!pragma layout smetana
"AbstractMap<K,V>Map<K,V>" <|-- "java.util.HashMap"
class java.util.HashMap {
hash(Object) : int [[[./../.././qc/secujava/java.util.HashMap.java.html#336]]]
comparableClassFor(Object) : Class<?> [[[./../.././qc/secujava/java.util.HashMap.java.html#344]]]
compareComparables(Class<?>;Object;Object) : int [[[./../.././qc/secujava/java.util.HashMap.java.html#368]]]
tableSizeFor(int) : int [[[./../.././qc/secujava/java.util.HashMap.java.html#376]]]
+HashMap(int;float) : HashMap [[[./../.././qc/secujava/java.util.HashMap.java.html#445]]]
+HashMap(int) : HashMap [[[./../.././qc/secujava/java.util.HashMap.java.html#465]]]
+HashMap() : HashMap [[[./../.././qc/secujava/java.util.HashMap.java.html#473]]]
+HashMap(Map<?extendsK,?extendsV>) : HashMap [[[./../.././qc/secujava/java.util.HashMap.java.html#486]]]
putMapEntries(Map<?extendsK,?extendsV>;boolean) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#498]]]
+size() : int [[[./../.././qc/secujava/java.util.HashMap.java.html#523]]]
+isEmpty() : boolean [[[./../.././qc/secujava/java.util.HashMap.java.html#532]]]
+get(Object) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#553]]]
getNode(int;Object) : Node<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#565]]]
+containsKey(Object) : boolean [[[./../.././qc/secujava/java.util.HashMap.java.html#593]]]
+put(K;V) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
putVal(int;K;V;boolean;boolean) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
resize() : Node<K,V>[] [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
treeifyBin(Node<K,V>[];int) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+putAll(Map<?extendsK,?extendsV>) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+remove(Object) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
removeNode(int;Object;Object;boolean;boolean) : Node<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+clear() : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+containsValue(Object) : boolean [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+keySet() : Set<K> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+values() : Collection<V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+entrySet() : Set<Map.Entry<K,V>> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+getOrDefault(Object;V) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+putIfAbsent(K;V) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+remove(Object;Object) : boolean [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+replace(K;V;V) : boolean [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+replace(K;V) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+computeIfAbsent(K;Function<?superK,?extendsV>) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+computeIfPresent(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+compute(K;BiFunction<?superK,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+merge(K;V;BiFunction<?superV,?superV,?extendsV>) : V [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+forEach(BiConsumer<?superK,?superV>) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+replaceAll(BiFunction<?superK,?superV,?extendsV>) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
+clone() : Object [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
loadFactor() : float [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
capacity() : int [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
-writeObject(java.io.ObjectOutputStream) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
-readObject(java.io.ObjectInputStream) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
newNode(int;K;V;Node<K,V>) : Node<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
replacementNode(Node<K,V>;Node<K,V>) : Node<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
newTreeNode(int;K;V;Node<K,V>) : TreeNode<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
replacementTreeNode(Node<K,V>;Node<K,V>) : TreeNode<K,V> [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
reinitialize() : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
afterNodeAccess(Node<K,V>) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
afterNodeInsertion(boolean) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
afterNodeRemoval(Node<K,V>) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
internalWriteEntries(java.io.ObjectOutputStream) : void [[[./../.././qc/secujava/java.util.HashMap.java.html#599]]]
} 
@enduml
