@startuml
!pragma layout smetana
"java.io.Serializable" <|-- "java.lang.Number"
class java.lang.Number {
+intValue() : int [[[./../.././qc/secujava/java.lang.Number.java.html#106]]]
+longValue() : long [[[./../.././qc/secujava/java.lang.Number.java.html#121]]]
+floatValue() : float [[[./../.././qc/secujava/java.lang.Number.java.html#136]]]
+doubleValue() : double [[[./../.././qc/secujava/java.lang.Number.java.html#151]]]
+byteValue() : byte [[[./../.././qc/secujava/java.lang.Number.java.html#168]]]
+shortValue() : short [[[./../.././qc/secujava/java.lang.Number.java.html#187]]]
} 
@enduml
