@startuml
!pragma layout smetana
"Wrapper" <|-- "java.sql.Statement"
class java.sql.Statement {
executeQuery(String) : ResultSet [[[./../.././qc/secujava/java.sql.Statement.java.html#9]]]
executeUpdate(String) : int [[[./../.././qc/secujava/java.sql.Statement.java.html#12]]]
close() : void [[[./../.././qc/secujava/java.sql.Statement.java.html#15]]]
getMaxFieldSize() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#20]]]
setMaxFieldSize(int) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#23]]]
getMaxRows() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#26]]]
setMaxRows(int) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#29]]]
setEscapeProcessing(boolean) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#32]]]
getQueryTimeout() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#35]]]
setQueryTimeout(int) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#38]]]
cancel() : void [[[./../.././qc/secujava/java.sql.Statement.java.html#41]]]
getWarnings() : SQLWarning [[[./../.././qc/secujava/java.sql.Statement.java.html#44]]]
clearWarnings() : void [[[./../.././qc/secujava/java.sql.Statement.java.html#47]]]
setCursorName(String) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#50]]]
execute(String) : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#55]]]
getResultSet() : ResultSet [[[./../.././qc/secujava/java.sql.Statement.java.html#58]]]
getUpdateCount() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#61]]]
getMoreResults() : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#64]]]
setFetchDirection(int) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#71]]]
getFetchDirection() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#74]]]
setFetchSize(int) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#77]]]
getFetchSize() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#80]]]
getResultSetConcurrency() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#83]]]
getResultSetType() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#86]]]
addBatch(String) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#89]]]
clearBatch() : void [[[./../.././qc/secujava/java.sql.Statement.java.html#92]]]
executeBatch() : int[] [[[./../.././qc/secujava/java.sql.Statement.java.html#95]]]
getConnection() : Connection [[[./../.././qc/secujava/java.sql.Statement.java.html#98]]]
getMoreResults(int) : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#124]]]
getGeneratedKeys() : ResultSet [[[./../.././qc/secujava/java.sql.Statement.java.html#127]]]
executeUpdate(String;int) : int [[[./../.././qc/secujava/java.sql.Statement.java.html#130]]]
executeUpdate(String;int[]) : int [[[./../.././qc/secujava/java.sql.Statement.java.html#133]]]
executeUpdate(String;String[]) : int [[[./../.././qc/secujava/java.sql.Statement.java.html#136]]]
execute(String;int) : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#139]]]
execute(String;int[]) : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#142]]]
execute(String;String[]) : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#145]]]
getResultSetHoldability() : int [[[./../.././qc/secujava/java.sql.Statement.java.html#148]]]
isClosed() : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#151]]]
setPoolable(boolean) : void [[[./../.././qc/secujava/java.sql.Statement.java.html#154]]]
isPoolable() : boolean [[[./../.././qc/secujava/java.sql.Statement.java.html#158]]]
} 
@enduml
