@startuml
!pragma layout smetana
"NumberComparable<Float>" <|-- "java.lang.Float"
class java.lang.Float {
+toString(float) : String [[[./../.././qc/secujava/java.lang.Float.java.html#198]]]
+toHexString(float) : String [[[./../.././qc/secujava/java.lang.Float.java.html#276]]]
+valueOf(String) : Float [[[./../.././qc/secujava/java.lang.Float.java.html#416]]]
+valueOf(float) : Float [[[./../.././qc/secujava/java.lang.Float.java.html#433]]]
+parseFloat(String) : float [[[./../.././qc/secujava/java.lang.Float.java.html#451]]]
+isNaN(float) : boolean [[[./../.././qc/secujava/java.lang.Float.java.html#463]]]
+isInfinite(float) : boolean [[[./../.././qc/secujava/java.lang.Float.java.html#475]]]
+Float(float) : Float [[[./../.././qc/secujava/java.lang.Float.java.html#492]]]
+Float(double) : Float [[[./../.././qc/secujava/java.lang.Float.java.html#502]]]
+Float(String) : Float [[[./../.././qc/secujava/java.lang.Float.java.html#517]]]
+isNaN() : boolean [[[./../.././qc/secujava/java.lang.Float.java.html#529]]]
+isInfinite() : boolean [[[./../.././qc/secujava/java.lang.Float.java.html#541]]]
+toString() : String [[[./../.././qc/secujava/java.lang.Float.java.html#554]]]
+byteValue() : byte [[[./../.././qc/secujava/java.lang.Float.java.html#565]]]
+shortValue() : short [[[./../.././qc/secujava/java.lang.Float.java.html#577]]]
+intValue() : int [[[./../.././qc/secujava/java.lang.Float.java.html#588]]]
+longValue() : long [[[./../.././qc/secujava/java.lang.Float.java.html#599]]]
+floatValue() : float [[[./../.././qc/secujava/java.lang.Float.java.html#608]]]
+doubleValue() : double [[[./../.././qc/secujava/java.lang.Float.java.html#619]]]
+hashCode() : int [[[./../.././qc/secujava/java.lang.Float.java.html#632]]]
+equals(Object) : boolean [[[./../.././qc/secujava/java.lang.Float.java.html#676]]]
+floatToIntBits(float) : int [[[./../.././qc/secujava/java.lang.Float.java.html#712]]]
+floatToRawIntBits(float) : int [[[./../.././qc/secujava/java.lang.Float.java.html#758]]]
+intBitsToFloat(int) : float [[[./../.././qc/secujava/java.lang.Float.java.html#819]]]
+compareTo(Float) : int [[[./../.././qc/secujava/java.lang.Float.java.html#853]]]
+compare(float;float) : int [[[./../.././qc/secujava/java.lang.Float.java.html#875]]]
} 
@enduml
