@startuml
!pragma layout smetana
"OffsetBackingStore" <|-- "org.apache.kafka.connect.storage.KafkaOffsetBackingStore"
class org.apache.kafka.connect.storage.KafkaOffsetBackingStore {
+forTask(String;Producer<byte[],byte[]>;Consumer<byte[],byte[]>;TopicAdmin) : KafkaOffsetBackingStore [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#83]]]
+forConnector(String;Consumer<byte[],byte[]>;TopicAdmin) : KafkaOffsetBackingStore [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#114]]]
+KafkaOffsetBackingStore() : KafkaOffsetBackingStore [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#150]]]
+KafkaOffsetBackingStore(Supplier<TopicAdmin>) : KafkaOffsetBackingStore [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#162]]]
+configure(WorkerConfig) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#168]]]
-createKafkaBasedLog(String;Map<String,Object>;Map<String,Object>;Callback<ConsumerRecord<byte[],byte[]>>;NewTopic;Supplier<TopicAdmin>) : KafkaBasedLog<byte[],byte[]> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#217]]]
newTopicDescription(String;WorkerConfig) : NewTopic [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#225]]]
initialize(String;NewTopic) : java.util.function.Consumer<TopicAdmin> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#237]]]
+start() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#252]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#284]]]
+get(Collection<ByteBuffer>) : Future<Map<ByteBuffer,ByteBuffer>> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#297]]]
+set(Map<ByteBuffer,ByteBuffer>;Callback<Void>) : Future<Void> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaOffsetBackingStore.java.html#316]]]
} 
@enduml
