@startuml
!pragma layout smetana
OffsetBackingStore <|-- org.apache.kafka.connect.storage.MemoryOffsetBackingStore
class org.apache.kafka.connect.storage.MemoryOffsetBackingStore {
+  MemoryOffsetBackingStore()
+  configure(WorkerConfig)
+  start()
+  stop()
+  get(Collection<ByteBuffer>)
+  set(Map<ByteBuffer,ByteBuffer>;Callback<Void>)
+  save()
} 
@enduml
