@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.mirror.Checkpoint
class org.apache.kafka.connect.mirror.Checkpoint {
+ Checkpoint(String;TopicPartition;long;long;String) : Checkpoint [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#46]]]
+ consumerGroupId() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#55]]]
+ topicPartition() : TopicPartition [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#59]]]
+ upstreamOffset() : long [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#63]]]
+ downstreamOffset() : long [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#67]]]
+ metadata() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#71]]]
+ offsetAndMetadata() : OffsetAndMetadata [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#75]]]
+ toString() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#80]]]
serializeValue(short) : ByteBuffer [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#86]]]
serializeKey() : ByteBuffer [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#97]]]
+ deserializeRecord(ConsumerRecord<byte[],byte[]>) : Checkpoint [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#105]]]
- valueSchema(short) : Schema [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#122]]]
- valueStruct(Schema) : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#127]]]
- keyStruct() : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#135]]]
- headerStruct(short) : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#143]]]
connectPartition() : Map<String,?> [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#149]]]
unwrapGroup(Map<String,?>) : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#157]]]
recordKey() : byte[] [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#161]]]
recordValue() : byte[] [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Checkpoint.java.html#165]]]
} 
@enduml
