@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.mirror.Heartbeat
class org.apache.kafka.connect.mirror.Heartbeat {
+ Heartbeat(String;String;long) : Heartbeat [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#36]]]
+ sourceClusterAlias() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#42]]]
+ targetClusterAlias() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#46]]]
+ timestamp() : long [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#50]]]
+ toString() : String [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#55]]]
serializeValue(short) : ByteBuffer [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#60]]]
serializeKey() : ByteBuffer [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#71]]]
+ deserializeRecord(ConsumerRecord<byte[],byte[]>) : Heartbeat [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#79]]]
- headerStruct(short) : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#91]]]
- valueStruct(Schema) : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#97]]]
- keyStruct() : Struct [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#103]]]
connectPartition() : Map<String,?> [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#110]]]
recordKey() : byte[] [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#117]]]
recordValue() : byte[] [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#121]]]
- valueSchema(short) : Schema [[[././qc/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/Heartbeat.java.html#125]]]
} 
@enduml
