@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.trogdor.coordinator.Coordinator"
class org.apache.kafka.trogdor.coordinator.Coordinator {
+Coordinator(Platform;Scheduler;JsonRestServer;CoordinatorRestResource;long) : Coordinator [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#81]]]
+port() : int [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#90]]]
+status() : CoordinatorStatusResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#94]]]
+uptime() : UptimeResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#98]]]
+createTask(CreateTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#102]]]
+stopTask(StopTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#106]]]
+destroyTask(DestroyTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#110]]]
+tasks(TasksRequest) : TasksResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#114]]]
+task(TaskRequest) : TaskState [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#118]]]
+beginShutdown(boolean) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#122]]]
+waitForShutdown() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#127]]]
+main(String[]) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/Coordinator.java.html#132]]]
} 
@enduml
