@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.trogdor.coordinator.CoordinatorClient"
class org.apache.kafka.trogdor.coordinator.CoordinatorClient {
-CoordinatorClient(Logger;int;String) : CoordinatorClient [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#103]]]
+maxTries() : int [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#109]]]
-url(String) : String [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#113]]]
+status() : CoordinatorStatusResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#117]]]
+uptime() : UptimeResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#124]]]
+createTask(CreateTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#131]]]
+stopTask(StopTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#138]]]
+destroyTask(DestroyTaskRequest) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#145]]]
+tasks(TasksRequest) : TasksResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#154]]]
+task(TaskRequest) : TaskState [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#170]]]
+shutdown() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#177]]]
-addTargetArgument(ArgumentParser) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#184]]]
-addJsonArgument(ArgumentParser) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#194]]]
+main(String[]) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#202]]]
prettyPrintTasksResponse(TasksResponse;ZoneOffset) : String [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#446]]]
prettyPrintTaskInfo(TaskState;ZoneOffset) : String [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/CoordinatorClient.java.html#467]]]
} 
@enduml
