@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.trogdor.coordinator.NodeManager"
class org.apache.kafka.trogdor.coordinator.NodeManager {
NodeManager(Node;TaskManager) : NodeManager [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#156]]]
rescheduleNextHeartbeat(long) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#176]]]
+createWorker(long;String;TaskSpec) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#270]]]
+stopWorker(long) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#309]]]
+destroyWorker(long) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#347]]]
+beginShutdown(boolean) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#373]]]
+waitForShutdown() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/NodeManager.java.html#384]]]
} 
@enduml
