@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.trogdor.coordinator.TaskManager
class org.apache.kafka.trogdor.coordinator.TaskManager {
TaskManager(Platform;Scheduler;long) : TaskManager [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#81]]]
+createTask(String;TaskSpec) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#228]]]
+stopTask(String) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#332]]]
+destroyTask(String) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#398]]]
+updateWorkerState(String;long;WorkerState) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#438]]]
-handleWorkerCompletion(ManagedTask;String;WorkerDone) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#481]]]
+tasks(TasksRequest) : TasksResponse [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#508]]]
+task(TaskRequest) : TaskState [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#533]]]
+beginShutdown(boolean) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#557]]]
+waitForShutdown() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/coordinator/TaskManager.java.html#564]]]
} 
@enduml
