@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.rest.entities.ConfigInfos
class org.apache.kafka.connect.runtime.rest.entities.ConfigInfos {
+  ConfigInfos(String;int;List<String>;List<ConfigInfo>)
+  name()
+  groups()
+  errorCount()
+  values()
+  equals(Object)
+  hashCode()
+  toString()
} 
@enduml
