@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.rest.entities.ErrorMessage"
class org.apache.kafka.connect.runtime.rest.entities.ErrorMessage {
+ErrorMessage(int;String) : ErrorMessage [[[./../../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/entities/ErrorMessage.java.html#34]]]
+errorCode() : int [[[./../../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/entities/ErrorMessage.java.html#40]]]
+message() : String [[[./../../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/entities/ErrorMessage.java.html#45]]]
+equals(Object) : boolean [[[./../../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/entities/ErrorMessage.java.html#50]]]
+hashCode() : int [[[./../../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/entities/ErrorMessage.java.html#59]]]
} 
@enduml
