@startuml
!pragma layout smetana
"TaskWorker" <|-- "org.apache.kafka.trogdor.task.NoOpTaskWorker"
class org.apache.kafka.trogdor.task.NoOpTaskWorker {
+NoOpTaskWorker(String) : NoOpTaskWorker [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/task/NoOpTaskWorker.java.html#33]]]
+start(Platform;WorkerStatusTracker;KafkaFutureImpl<String>) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/task/NoOpTaskWorker.java.html#38]]]
+stop(Platform) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/task/NoOpTaskWorker.java.html#46]]]
} 
@enduml
