@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.trogdor.task.WorkerStatusTracker
class org.apache.kafka.trogdor.task.WorkerStatusTracker {
+  update(JsonNode)
} 
@enduml
