@startuml
!pragma layout smetana
"Authorizer" <|-- "org.apache.kafka.metadata.authorizer.ClusterMetadataAuthorizer"
class org.apache.kafka.metadata.authorizer.ClusterMetadataAuthorizer {
setAclMutator(AclMutator) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#49]]]
aclMutatorOrException() : AclMutator [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#57]]]
completeInitialLoad() : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#63]]]
completeInitialLoad(Exception) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#69]]]
loadSnapshot(Map<Uuid,StandardAcl>) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#76]]]
addAcl(Uuid;StandardAcl) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#81]]]
removeAcl(Uuid) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#86]]]
createAcls(AuthorizableRequestContext;List<AclBinding>) : List<?extendsCompletionStage<AclCreateResult>> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#99]]]
deleteAcls(AuthorizableRequestContext;List<AclBindingFilter>) : List<?extendsCompletionStage<AclDeleteResult>> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#139]]]
} 
@enduml
