@startuml
!pragma layout smetana
Authorizer <|-- org.apache.kafka.metadata.authorizer.ClusterMetadataAuthorizer
class org.apache.kafka.metadata.authorizer.ClusterMetadataAuthorizer {
setAclMutator(AclMutator) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#28]]]
aclMutatorOrException() : AclMutator [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#31]]]
completeInitialLoad() : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#34]]]
completeInitialLoad(Exception) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#37]]]
loadSnapshot(Map<Uuid,StandardAcl>) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#40]]]
addAcl(Uuid;StandardAcl) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#43]]]
removeAcl(Uuid) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#46]]]
createAcls(AuthorizableRequestContext;List<AclBinding>) : List<?extendsCompletionStage<AclCreateResult>> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#49]]]
deleteAcls(AuthorizableRequestContext;List<AclBindingFilter>) : List<?extendsCompletionStage<AclDeleteResult>> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/ClusterMetadataAuthorizer.java.html#79]]]
} 
@enduml
