@startuml
!pragma layout smetana
"Comparable<StandardAcl>" <|-- "org.apache.kafka.metadata.authorizer.StandardAcl"
class org.apache.kafka.metadata.authorizer.StandardAcl {
+fromRecord(AccessControlEntryRecord) : StandardAcl [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#37]]]
+fromAclBinding(AclBinding) : StandardAcl [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#48]]]
+StandardAcl(ResourceType;String;PatternType;String;String;AclOperation;AclPermissionType) : StandardAcl [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#67]]]
+resourceType() : ResourceType [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#84]]]
+resourceName() : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#88]]]
+patternType() : PatternType [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#92]]]
+principal() : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#96]]]
+kafkaPrincipal() : KafkaPrincipal [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#100]]]
+host() : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#111]]]
+operation() : AclOperation [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#115]]]
+permissionType() : AclPermissionType [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#119]]]
+toBinding() : AclBinding [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#123]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#132]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#146]]]
+compareTo(StandardAcl) : int [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#162]]]
+toString() : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAcl.java.html#181]]]
} 
@enduml
