@startuml
!pragma layout smetana
"Iterator<List<ApiMessageAndVersion>>" <|-- "org.apache.kafka.metadata.authorizer.StandardAclRecordIterator"
class org.apache.kafka.metadata.authorizer.StandardAclRecordIterator {
+StandardAclRecordIterator(Iterator<StandardAclWithId>) : StandardAclRecordIterator [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAclRecordIterator.java.html#35]]]
+StandardAclRecordIterator(Iterator<StandardAclWithId>;int) : StandardAclRecordIterator [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAclRecordIterator.java.html#39]]]
+hasNext() : boolean [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAclRecordIterator.java.html#45]]]
+next() : List<ApiMessageAndVersion> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAclRecordIterator.java.html#50]]]
} 
@enduml
