@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.metadata.authorizer.StandardAuthorizerData"
class org.apache.kafka.metadata.authorizer.StandardAuthorizerData {
-createLogger(int) : Logger [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#121]]]
-auditLogger() : Logger [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#125]]]
createEmpty() : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#129]]]
-StandardAuthorizerData(Logger;AclMutator;boolean;Set<String>;AuthorizationResult;ConcurrentSkipListSet<StandardAcl>;ConcurrentHashMap<Uuid,StandardAcl>) : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#138]]]
copyWithNewAclMutator(AclMutator) : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#155]]]
copyWithNewLoadingComplete(boolean) : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#166]]]
copyWithNewConfig(int;Set<String>;AuthorizationResult) : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#176]]]
copyWithNewAcls(Collection<Entry<Uuid,StandardAcl>>) : StandardAuthorizerData [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#189]]]
addAcl(Uuid;StandardAcl) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#205]]]
removeAcl(Uuid) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#223]]]
superUsers() : Set<String> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#240]]]
defaultResult() : AuthorizationResult [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#244]]]
aclCount() : int [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#248]]]
+authorize(AuthorizableRequestContext;Action) : AuthorizationResult [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#261]]]
-buildAuditMessage(KafkaPrincipal;AuthorizableRequestContext;Action;MatchingRule) : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#292]]]
-appendResourcePattern(ResourcePattern;StringBuilder) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#311]]]
-logAuditMessage(KafkaPrincipal;AuthorizableRequestContext;Action;MatchingRule) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#319]]]
-findAclRule(Set<KafkaPrincipal>;String;Action) : MatchingAclRule [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#350]]]
-checkSection(Action;StandardAcl;Set<KafkaPrincipal>;String;MatchingAclBuilder) : void [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#400]]]
findResult(Action;AuthorizableRequestContext;StandardAcl) : AuthorizationResult [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#452]]]
baseKafkaPrincipal(AuthorizableRequestContext) : KafkaPrincipal [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#463]]]
matchingPrincipals(AuthorizableRequestContext) : Set<KafkaPrincipal> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#470]]]
findResult(Action;Set<KafkaPrincipal>;String;StandardAcl) : AuthorizationResult [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#490]]]
acls(AclBindingFilter) : Iterable<AclBinding> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizerData.java.html#532]]]
} 
@enduml
