@startuml
!pragma layout smetana
ClusterMetadataAuthorizer <|-- org.apache.kafka.metadata.authorizer.StandardAuthorizer
class org.apache.kafka.metadata.authorizer.StandardAuthorizer {
+ setAclMutator(AclMutator) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#45]]]
+ aclMutatorOrException() : AclMutator [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#50]]]
+ completeInitialLoad() : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#59]]]
+ initialLoadFuture() : CompletableFuture<Void> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#66]]]
+ completeInitialLoad(Exception) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#71]]]
+ addAcl(Uuid;StandardAcl) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#77]]]
+ removeAcl(Uuid) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#82]]]
+ loadSnapshot(Map<Uuid,StandardAcl>) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#87]]]
+ start(AuthorizerServerInfo) : Map<Endpoint,?extendsCompletionStage<Void>> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#92]]]
+ authorize(AuthorizableRequestContext;List<Action>) : List<AuthorizationResult> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#107]]]
+ acls(AclBindingFilter) : Iterable<AclBinding> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#120]]]
+ aclCount() : int [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#125]]]
+ close() : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#130]]]
+ configure(Map<String,?>) : void [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#137]]]
superUsers() : Set<String> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#151]]]
defaultResult() : AuthorizationResult [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#155]]]
getConfiguredSuperUsers(Map<String,?>) : Set<String> [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#159]]]
getDefaultResult(Map<String,?>) : AuthorizationResult [[[././qc/metadata/src/main/java/org/apache/kafka/metadata/authorizer/StandardAuthorizer.java.html#174]]]
} 
@enduml
