@startuml
!pragma layout smetana
NumberConverter_Double_ <|-- org.apache.kafka.connect.converters.DoubleConverter
class org.apache.kafka.connect.converters.DoubleConverter {
+  DoubleConverter()
} 
@enduml
