@startuml
!pragma layout smetana
NumberConverter_Float_ <|-- org.apache.kafka.connect.converters.FloatConverter
class org.apache.kafka.connect.converters.FloatConverter {
+  FloatConverter()
} 
@enduml
