@startuml
!pragma layout smetana
NumberConverter_Long_ <|-- org.apache.kafka.connect.converters.LongConverter
class org.apache.kafka.connect.converters.LongConverter {
+  LongConverter()
} 
@enduml
