@startuml
!pragma layout smetana
NumberConverter_Short_ <|-- org.apache.kafka.connect.converters.ShortConverter
class org.apache.kafka.connect.converters.ShortConverter {
+  ShortConverter()
} 
@enduml
