@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.distributed.ConnectProtocol"
class org.apache.kafka.connect.runtime.distributed.ConnectProtocol {
+serializeMetadata(WorkerState) : ByteBuffer [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#126]]]
+metadataRequest(WorkerState) : JoinGroupRequestProtocolCollection [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#144]]]
+deserializeMetadata(ByteBuffer) : WorkerState [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#160]]]
+serializeAssignment(Assignment) : ByteBuffer [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#182]]]
+deserializeAssignment(ByteBuffer) : Assignment [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#213]]]
-checkVersionCompatibility(short) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#400]]]
} 
@enduml
