@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.distributed.ConnectProtocol
class org.apache.kafka.connect.runtime.distributed.ConnectProtocol {
+serializeMetadata(WorkerState) : ByteBuffer [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#66]]]
+metadataRequest(WorkerState) : JoinGroupRequestProtocolCollection [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#78]]]
+deserializeMetadata(ByteBuffer) : WorkerState [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#87]]]
+serializeAssignment(Assignment) : ByteBuffer [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#98]]]
+deserializeAssignment(ByteBuffer) : Assignment [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#122]]]
-checkVersionCompatibility(short) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java.html#263]]]
} 
@enduml
