@startuml
!pragma layout smetana
"AbstractHerderRunnable" <|-- "org.apache.kafka.connect.runtime.distributed.DistributedHerder"
class org.apache.kafka.connect.runtime.distributed.DistributedHerder {
+DistributedHerder(DistributedConfig;Time;Worker;String;StatusBackingStore;ConfigBackingStore;String;ConnectorClientConfigOverridePolicy;AutoCloseable...) : DistributedHerder [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#236]]]
DistributedHerder(DistributedConfig;Worker;String;String;StatusBackingStore;ConfigBackingStore;WorkerGroupMember;String;ConnectMetrics;Time;ConnectorClientConfigOverridePolicy;AutoCloseable...) : DistributedHerder [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#251]]]
+start() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#331]]]
+run() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#336]]]
+tick() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#363]]]
-checkForKeyRotation(long) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#521]]]
-updateConfigsWithEager(AtomicReference<Set<String>>;AtomicReference<Set<String>>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#555]]]
-updateConfigsWithIncrementalCooperative(AtomicReference<Set<String>>;AtomicReference<Set<String>>;AtomicReference<Set<ConnectorTaskId>>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#603]]]
-processConnectorConfigUpdates(Set<String>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#654]]]
-processTargetStateChanges(Set<String>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#683]]]
-processTaskConfigUpdatesWithIncrementalCooperative(Set<ConnectorTaskId>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#710]]]
-stopReconfiguredTasks(Set<String>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#722]]]
+halt() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#743]]]
stopServices() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#771]]]
+stop() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#780]]]
+connectors(Callback<Collection<String>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#806]]]
+connectorInfo(String;Callback<ConnectorInfo>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#820]]]
+tasksConfig(String;Callback<Map<ConnectorTaskId,Map<String,String>>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#841]]]
rawConfig(String) : Map<String,String> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#861]]]
+connectorConfig(String;Callback<Map<String,String>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#866]]]
+deleteConnectorConfig(String;Callback<Created<ConnectorInfo>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#872]]]
validateSinkConnectorConfig(SinkConnector;ConfigDef;Map<String,String>) : Map<String,ConfigValue> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#895]]]
validateSourceConnectorConfig(SourceConnector;ConfigDef;Map<String,String>) : Map<String,ConfigValue> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#902]]]
-validateSinkConnectorGroupId(Map<String,ConfigValue>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#910]]]
-validateSourceConnectorExactlyOnceSupport(Map<String,String>;Map<String,ConfigValue>;SourceConnector) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#919]]]
-validateSourceConnectorTransactionBoundary(Map<String,String>;Map<String,ConfigValue>;SourceConnector) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#966]]]
connectorUsesAdmin(org.apache.kafka.connect.health.ConnectorType;Map<String,String>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1005]]]
connectorUsesConsumer(org.apache.kafka.connect.health.ConnectorType;Map<String,String>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1011]]]
-connectorUsesSeparateOffsetsTopicClients(org.apache.kafka.connect.health.ConnectorType;Map<String,String>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1016]]]
+putConnectorConfig(String;Map<String,String>;boolean;Callback<Created<ConnectorInfo>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1025]]]
+requestTaskReconfiguration(String) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1077]]]
+taskConfigs(String;Callback<List<TaskInfo>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1095]]]
+putTaskConfigs(String;List<Map<String,String>>;Callback<Void>;InternalRequestSignature) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1120]]]
+fenceZombieSourceTasks(String;Callback<Void>;InternalRequestSignature) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1144]]]
fenceZombieSourceTasks(ConnectorTaskId;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1154]]]
fenceZombieSourceTasks(String;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1178]]]
+restartConnector(String;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1250]]]
+restartConnector(long;String;Callback<Void>) : HerderRequest [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1255]]]
+restartTask(ConnectorTaskId;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1285]]]
+generation() : int [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1322]]]
+restartConnectorAndTasks(RestartRequest;Callback<ConnectorStateInfo>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1327]]]
processRestartRequests() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1362]]]
doRestartConnectorAndTasks(RestartRequest) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1387]]]
-isLeader() : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1448]]]
-leaderUrl() : String [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1455]]]
-writeToConfigTopicAsLeader(Runnable) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1470]]]
-handleRebalanceCompleted() : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1486]]]
-readConfigToEnd(long) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1582]]]
-refreshConfigSnapshot(long) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1605]]]
-backoff(long) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1618]]]
-startAndStop(Collection<Callable<Void>>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1643]]]
-startWork() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1651]]]
-startTask(ConnectorTaskId) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1700]]]
-getTaskStartingCallable(ConnectorTaskId) : Callable<Void> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1754]]]
-getTaskStoppingCallable(ConnectorTaskId) : Callable<Void> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1767]]]
-startConnector(String;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1777]]]
-getConnectorStartingCallable(String) : Callable<Void> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1808]]]
-getConnectorStoppingCallable(String) : Callable<Void> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1824]]]
-reconfigureConnectorTasksWithRetry(long;String) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1835]]]
isPossibleExpiredKeyException(long;Throwable) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1862]]]
-reconfigureConnector(String;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1873]]]
-verifyTaskGenerationAndOwnership(ConnectorTaskId;int) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1946]]]
verifyTaskGenerationAndOwnership(ConnectorTaskId;int;Callback<Void>) : Void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1970]]]
-checkRebalanceNeeded(Callback<?>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#1986]]]
runOnTickThread(Callable<Void>;Callback<Void>) : DistributedHerderRequest [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2004]]]
addRequest(Callable<Void>;Callback<Void>) : DistributedHerderRequest [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2013]]]
addRequest(long;Callable<Void>;Callback<Void>) : DistributedHerderRequest [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2017]]]
-runRequest(Callable<Void>;Callback<Void>) : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2025]]]
-internalRequestValidationEnabled() : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2034]]]
-internalRequestValidationEnabled(short) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2038]]]
-peekWithoutException() : DistributedHerderRequest [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2042]]]
-forwardErrorCallback(Callback<?>) : Callback<Void> [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2208]]]
-updateDeletedConnectorStatus() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2215]]]
-updateDeletedTaskStatus() : void [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2226]]]
herderMetrics() : HerderMetrics [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2238]]]
-isSourceConnector(String) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2381]]]
-requestNotSignedProperly(InternalRequestSignature;Callback<?>) : boolean [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java.html#2393]]]
} 
@enduml
