@startuml
!pragma layout smetana
"ConnectException" <|-- "org.apache.kafka.connect.runtime.distributed.RequestTargetException"
class org.apache.kafka.connect.runtime.distributed.RequestTargetException {
+RequestTargetException(String;String) : RequestTargetException [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/RequestTargetException.java.html#28]]]
+RequestTargetException(String;Throwable;String) : RequestTargetException [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/RequestTargetException.java.html#33]]]
+RequestTargetException(Throwable;String) : RequestTargetException [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/RequestTargetException.java.html#38]]]
+forwardUrl() : String [[[./../../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/RequestTargetException.java.html#43]]]
} 
@enduml
