@startuml
!pragma layout smetana
"java.lang.Object" <|-- "kafka.tools.StreamsResetter"
class kafka.tools.StreamsResetter {
+run(String[]) : int [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#139]]]
+run(String[];Properties) : int [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#143]]]
-maybeDeleteActiveConsumers(String;Admin) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#187]]]
-parseArguments(String[]) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#209]]]
-maybeResetInputAndSeekToEndIntermediateTopicOffsets(Map<Object,Object>;boolean) : int [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#312]]]
+maybeSeekToEnd(String;Consumer<byte[],byte[]>;Set<TopicPartition>) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#423]]]
-maybeReset(String;Consumer<byte[],byte[]>;Set<TopicPartition>) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#437]]]
+resetOffsetsFromResetPlan(Consumer<byte[],byte[]>;Set<TopicPartition>;Map<TopicPartition,Long>) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#475]]]
-getTopicPartitionOffsetFromResetPlan(String) : Map<TopicPartition,Long> [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#489]]]
-resetByDuration(Consumer<byte[],byte[]>;Set<TopicPartition>;Duration) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#496]]]
+resetToDatetime(Consumer<byte[],byte[]>;Set<TopicPartition>;Long) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#503]]]
+shiftOffsetsBy(Consumer<byte[],byte[]>;Set<TopicPartition>;long) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#528]]]
+resetOffsetsTo(Consumer<byte[],byte[]>;Set<TopicPartition>;Long) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#550]]]
-parseResetPlan(String) : Map<TopicPartition,Long> [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#570]]]
-checkOffsetRange(Map<TopicPartition,Long>;Map<TopicPartition,Long>;Map<TopicPartition,Long>) : Map<TopicPartition,Long> [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#593]]]
-isInputTopic(String) : boolean [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#616]]]
-isIntermediateTopic(String) : boolean [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#620]]]
-maybeDeleteInternalTopics(Admin;boolean) : int [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#624]]]
+doDelete(List<String>;Admin) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#656]]]
-isInferredInternalTopic(String) : boolean [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#676]]]
+matchesInternalTopicFormat(String) : boolean [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#686]]]
+main(String[]) : void [[[./../../../../../../.././qc/core/src/main/scala/kafka/tools/StreamsResetter.java.html#694]]]
} 
@enduml
