@startuml
!pragma layout smetana
MeasurableStat <|-- org.apache.kafka.common.metrics.stats.CumulativeSum
class org.apache.kafka.common.metrics.stats.CumulativeSum {
+  CumulativeSum()
+  CumulativeSum(double)
+  record(MetricConfig;double;long)
+  measure(MetricConfig;long)
+  toString()
} 
@enduml
