@startuml
!pragma layout smetana
"SampledStatCompoundStat" <|-- "org.apache.kafka.common.metrics.stats.Frequencies"
class org.apache.kafka.common.metrics.stats.Frequencies {
+forBooleanValues(MetricName;MetricName) : Frequencies [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#55]]]
+Frequencies(int;double;double;Frequency...) : Frequencies [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#86]]]
+stats() : List<NamedMeasurable> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#110]]]
+frequency(MetricConfig;long;double) : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#132]]]
totalCount() : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#153]]]
+combine(List<Sample>;MetricConfig;long) : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#162]]]
newSample(long) : HistogramSample [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#167]]]
update(Sample;MetricConfig;double;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Frequencies.java.html#172]]]
} 
@enduml
