@startuml
!pragma layout smetana
"MeasurableStat" <|-- "org.apache.kafka.common.metrics.stats.Rate"
class org.apache.kafka.common.metrics.stats.Rate {
+Rate() : Rate [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#38]]]
+Rate(TimeUnit) : Rate [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#42]]]
+Rate(SampledStat) : Rate [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#46]]]
+Rate(TimeUnit;SampledStat) : Rate [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#50]]]
+unitName() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#55]]]
+record(MetricConfig;double;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#60]]]
+measure(MetricConfig;long) : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#65]]]
+windowSize(MetricConfig;long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#70]]]
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/stats/Rate.java.html#98]]]
} 
@enduml
