@startuml
!pragma layout smetana
"Reconfigurable" <|-- "org.apache.kafka.common.security.ssl.SslFactory"
class org.apache.kafka.common.security.ssl.SslFactory {
+SslFactory(Mode) : SslFactory [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#63]]]
+SslFactory(Mode;String;boolean) : SslFactory [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#76]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#86]]]
+reconfigurableConfigs() : Set<String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#110]]]
+validateReconfiguration(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#115]]]
+reconfigure(Map<String,?>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#120]]]
-instantiateSslEngineFactory(Map<String,Object>) : SslEngineFactory [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#130]]]
-createNewSslEngineFactory(Map<String,?>) : SslEngineFactory [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#145]]]
+createSslEngine(Socket) : SSLEngine [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#188]]]
+createSslEngine(String;int) : SSLEngine [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#196]]]
-peerHost(Socket) : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#241]]]
+sslEngineFactory() : SslEngineFactory [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#245]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java.html#284]]]
} 
@enduml
