@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.resource.Resource"
class org.apache.kafka.common.resource.Resource {
+Resource(ResourceType;String) : Resource [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#50]]]
+resourceType() : ResourceType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#60]]]
+name() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#67]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#72]]]
+isUnknown() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#79]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#84]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/resource/Resource.java.html#92]]]
} 
@enduml
