@startuml
!pragma layout smetana
WrappedStateStore_T,K,V_ <|-- org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator
class org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator {
+  AbstractReadWriteDecorator(T)
+  init(ProcessorContext;StateStore)
+  init(StateStoreContext;StateStore)
+  close()
+  getReadWriteStore(StateStore)
} 
@enduml
