@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.ActiveTaskCreator"
class org.apache.kafka.streams.processor.internals.ActiveTaskCreator {
ActiveTaskCreator(TopologyMetadata;StreamsConfig;StreamsMetricsImpl;StateDirectory;ChangelogReader;ThreadCache;Time;KafkaClientSupplier;String;UUID;Logger) : ActiveTaskCreator [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#61]]]
+reInitializeThreadProducer() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#107]]]
streamsProducerForTask(TaskId) : StreamsProducer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#111]]]
threadProducer() : StreamsProducer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#123]]]
removeRevokedUnknownTasks(Set<TaskId>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#130]]]
uncreatedTasksForTopologies(Set<String>) : Map<TaskId,Set<TopicPartition>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#134]]]
+createTasks(Consumer<byte[],byte[]>;Map<TaskId,Set<TopicPartition>>) : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#139]]]
createActiveTaskFromStandby(StandbyTask;Set<TopicPartition>;Consumer<byte[],byte[]>) : StreamTask [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#199]]]
-createActiveTask(TaskId;Set<TopicPartition>;Consumer<byte[],byte[]>;LogContext;ProcessorTopology;ProcessorStateManager;InternalProcessorContext) : StreamTask [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#220]]]
closeThreadProducerIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#273]]]
closeAndRemoveTaskProducerIfNeeded(TaskId) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#283]]]
producerMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#294]]]
producerClientIds() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#304]]]
-getLogContext(TaskId) : LogContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#315]]]
+totalProducerBlockedTime() : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java.html#321]]]
} 
@enduml
