@startuml
!pragma layout smetana
"StampedRecord" <|-- "org.apache.kafka.streams.processor.internals.CorruptedRecord"
class org.apache.kafka.streams.processor.internals.CorruptedRecord {
CorruptedRecord(ConsumerRecord<byte[],byte[]>) : CorruptedRecord [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/CorruptedRecord.java.html#29]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/CorruptedRecord.java.html#34]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/CorruptedRecord.java.html#41]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/CorruptedRecord.java.html#56]]]
} 
@enduml
