@startuml
!pragma layout smetana
StreamPartitioner<K,V> <|-- org.apache.kafka.streams.processor.internals.DefaultStreamPartitioner
class org.apache.kafka.streams.processor.internals.DefaultStreamPartitioner {
+  DefaultStreamPartitioner(Serializer<K>)
+  partition(String;K;V;int)
} 
@enduml
