@startuml
!pragma layout smetana
"KafkaClientSupplier" <|-- "org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier"
class org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier {
+getAdmin(Map<String,Object>) : Admin [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java.html#32]]]
+getProducer(Map<String,Object>) : Producer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java.html#38]]]
+getConsumer(Map<String,Object>) : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java.html#43]]]
+getRestoreConsumer(Map<String,Object>) : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java.html#48]]]
+getGlobalConsumer(Map<String,Object>) : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java.html#53]]]
} 
@enduml
