@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.InternalTopologyBuilder
class org.apache.kafka.streams.processor.internals.InternalTopologyBuilder {
+  InternalTopologyBuilder()
+  InternalTopologyBuilder(TopologyConfig)
+  setApplicationId(String)
+  setStreamsConfig(StreamsConfig)
+  setNamedTopology(NamedTopology)
+  topologyConfigs()
+  topologyName()
+  namedTopology()
+  rewriteTopology(StreamsConfig)
+  addSource(Topology.AutoOffsetReset;String;TimestampExtractor;Deserializer<?>;Deserializer<?>;String...)
+  addSource(Topology.AutoOffsetReset;String;TimestampExtractor;Deserializer<?>;Deserializer<?>;Pattern)
+  addStateStore(StoreBuilder<?>;String...)
+  addStateStore(StoreBuilder<?>;boolean;String...)
+  validateTopicNotAlreadyRegistered(String)
+  connectProcessorAndStateStores(String;String...)
+  getStoreForChangelogTopic(String)
+  connectSourceStoreAndTopic(String;String)
+  addInternalTopic(String;InternalTopicProperties)
+  copartitionSources(Collection<String>)
+  maybeUpdateCopartitionSourceGroups(String;String)
+  validateCopartition()
+  validateGlobalStoreArguments(String;String;String;ProcessorSupplier<?,?,Void,Void>;String;boolean)
+  connectProcessorAndStateStore(String;String)
+  findSourcesForProcessorPredecessors(String[])
+  nodeGroups()
+  makeNodeGroups()
+  putNodeGroupName(String;int;Map<Integer,Set<String>>;Map<String,Set<String>>)
+  buildTopology()
+  buildSubtopology(int)
+  buildGlobalStateTopology()
+  globalNodeGroups()
+  build(Set<String>)
+  buildSinkNode(Map<String,ProcessorNode<?,?,?,?>>;Map<String,SinkNode<?,?>>;Set<String>;SinkNodeFactory<?,?>;SinkNode<?,?>)
+  buildSourceNode(Map<String,SourceNode<?,?>>;Set<String>;SourceNodeFactory<?,?>;SourceNode<?,?>)
+  buildProcessorNode(Map<String,ProcessorNode<?,?,?,?>>;Map<String,StateStore>;ProcessorNodeFactory<?,?,?,?>;ProcessorNode<Object,Object,Object,Object>)
+  globalStateStores()
+  allStateStoreNames()
+  hasStore(String)
+  hasPersistentStores()
+  subtopologyToTopicsInfo()
+  nodeToSourceTopics()
+  buildRepartitionTopicConfig(String;Optional<Integer>)
+  setRegexMatchedTopicsToSourceNodes()
+  setRegexMatchedTopicToStateStore()
+  hasOffsetResetOverrides()
+  offsetResetStrategy(String)
+  stateStoreNameToFullSourceTopicNames()
+  sourceTopicsForStore(String)
+  copartitionGroups()
+  maybeDecorateInternalSourceTopics(Collection<String>)
+  decoratePseudoTopic(String)
+  decorateTopic(String)
+  initializeSubscription()
+  buildSourceTopicsPatternString()
+  usesPatternSubscription()
+  fullSourceTopicNames()
+  sourceTopicPatternString()
+  containsTopic(String)
+  hasNoLocalTopology()
+  hasGlobalStores()
+  isGlobalSource(String)
+  describe()
+  describeGlobalStore(TopologyDescription;Set<String>;int)
+  nodeGroupContainsGlobalSourceNode(Set<String>)
+  updateSize(AbstractNode;int)
+  describeSubtopology(TopologyDescription;Integer;Set<String>)
+  nodeNames(Set<TopologyDescription.Node>)
+  subscriptionUpdates()
+  hasSubscriptionUpdates()
+  addSubscribedTopicsFromAssignment(List<TopicPartition>;String)
+  addSubscribedTopicsFromMetadata(Set<String>;String)
+  updateSubscribedTopics(Set<String>;String)
+  allSourcePatternStrings()
+  hasNamedTopology()
+  stateStores()
} 
@enduml
