@startuml
!pragma layout smetana
"ProcessorContext" <|-- "org.apache.kafka.streams.processor.internals.InternalProcessorContext"
class org.apache.kafka.streams.processor.internals.InternalProcessorContext {
metrics() : StreamsMetricsImpl [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#48]]]
setSystemTimeMs(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#53]]]
recordContext() : ProcessorRecordContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#59]]]
setRecordContext(ProcessorRecordContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#64]]]
setCurrentNode(ProcessorNode<?,?,?,?>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#69]]]
currentNode() : ProcessorNode<?,?,?,?> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#74]]]
cache() : ThreadCache [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#79]]]
initialize() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#84]]]
uninitialize() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#89]]]
taskType() : TaskType [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
transitionToActive(StreamTask;RecordCollector;ThreadCache) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
transitionToStandby(ThreadCache) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
registerCacheFlushListener(String;DirtyEntryFlushListener) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
logChange(String;Bytes;byte[];long;Position) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
changelogFor(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
addProcessorMetadataKeyValue(String;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
processorMetadataForKey(String) : Long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
setProcessorMetadata(ProcessorMetadata) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
getProcessorMetadata() : ProcessorMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalProcessorContext.java.html#127]]]
} 
@enduml
