@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.InternalTopicManager"
class org.apache.kafka.streams.processor.internals.InternalTopicManager {
+InternalTopicManager(Time;Admin;StreamsConfig) : InternalTopicManager [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#80]]]
+validate(Map<String,InternalTopicConfig>) : ValidationResult [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#147]]]
-validatePartitionCount(ValidationResult;InternalTopicConfig;TopicDescription) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#258]]]
-validateCleanupPolicy(ValidationResult;InternalTopicConfig;Config) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#275]]]
-validateCleanupPolicyForUnwindowedChangelogs(ValidationResult;InternalTopicConfig;Config) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#289]]]
-validateCleanupPolicyForWindowedChangelogs(ValidationResult;InternalTopicConfig;Config) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#304]]]
-validateCleanupPolicyForRepartitionTopic(ValidationResult;InternalTopicConfig;Config) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#334]]]
-getBrokerSideConfigValue(Config;String;String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#367]]]
+makeReady(Map<String,InternalTopicConfig>) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#386]]]
getNumPartitions(Set<String>;Set<String>) : Map<String,Integer> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#513]]]
-validateTopics(Set<String>;Map<String,InternalTopicConfig>;Set<String>) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#559]]]
+setup(Map<String,InternalTopicConfig>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#600]]]
-processCreateTopicResults(CreateTopicsResult;Set<String>;Set<String>;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#633]]]
-cleanUpCreatedTopics(Set<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#691]]]
-maybeThrowTimeoutException(List<Set<String>>;long;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#762]]]
-maybeThrowTimeoutExceptionDuringSetup(Set<String>;Set<String>;Map<String,Throwable>;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#774]]]
-maybeSleep(List<Set<String>>;long;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopicManager.java.html#792]]]
} 
@enduml
