@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.ProcessorTopology"
class org.apache.kafka.streams.processor.internals.ProcessorTopology {
+ProcessorTopology(List<ProcessorNode<?,?,?,?>>;Map<String,SourceNode<?,?>>;Map<String,SinkNode<?,?>>;List<StateStore>;List<StateStore>;Map<String,String>;Set<String>) : ProcessorTopology [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#46]]]
+sourceTopics() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#74]]]
+source(String) : SourceNode<?,?> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#78]]]
+sources() : Set<SourceNode<?,?>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#82]]]
+sinkTopics() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#86]]]
+sink(String) : SinkNode<?,?> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#90]]]
+terminalNodes() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#94]]]
+processors() : List<ProcessorNode<?,?,?,?>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#98]]]
+stateStores() : List<StateStore> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#102]]]
+globalStateStores() : List<StateStore> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#106]]]
+storeToChangelogTopic() : Map<String,String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#110]]]
isRepartitionTopic(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#114]]]
hasStateWithChangelogs() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#118]]]
+hasPersistentLocalStore() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#127]]]
+hasPersistentGlobalStore() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#136]]]
+updateSourceTopics(Map<String,List<String>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#145]]]
-childrenToString(String;List<?extendsProcessorNode<?,?,?,?>>) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#171]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#197]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#206]]]
-topicsToString(String;List<String>) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#228]]]
+processorConnectedStateStores(String) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java.html#241]]]
} 
@enduml
