@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.ProcessorNode
class org.apache.kafka.streams.processor.internals.ProcessorNode {
+ProcessorNode(String) : ProcessorNode [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#37]]]
+ProcessorNode(String;Processor<KIn,VIn,KOut,VOut>;Set<String>) : ProcessorNode [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#41]]]
+ProcessorNode(String;FixedKeyProcessor<KIn,VIn,VOut>;Set<String>) : ProcessorNode [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#54]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#67]]]
+children() : List<ProcessorNode<KOut,VOut,?,?>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#71]]]
getChild(String) : ProcessorNode<KOut,VOut,?,?> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#75]]]
+addChild(ProcessorNode<KOut,VOut,?,?>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#79]]]
+init(InternalProcessorContext<KOut,VOut>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#84]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#108]]]
throwIfClosed() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#130]]]
+process(Record<KIn,VIn>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#137]]]
+punctuate(long;Punctuator) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#170]]]
+isTerminalNode() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#174]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#180]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java.html#185]]]
} 
@enduml
