@startuml
!pragma layout smetana
"StateManager" <|-- "org.apache.kafka.streams.processor.internals.ProcessorStateManager"
class org.apache.kafka.streams.processor.internals.ProcessorStateManager {
+storeChangelogTopic(String;String;String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#172]]]
+ProcessorStateManager(TaskId;TaskType;boolean;LogContext;StateDirectory;ChangelogRegister;Map<String,String>;Collection<TopicPartition>) : ProcessorStateManager [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#183]]]
registerStateStores(List<StateStore>;InternalProcessorContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#206]]]
registerGlobalStateStores(List<StateStore>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#218]]]
+getGlobalStore(String) : StateStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#226]]]
initializeStoreOffsetsFromCheckpoint(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#231]]]
-maybeRegisterStoreWithChangelogReader(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#295]]]
-getAllChangelogTopicPartitions() : List<TopicPartition> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#301]]]
+baseDir() : File [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#312]]]
+registerStore(StateStore;StateRestoreCallback;CommitCallback) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#317]]]
+getStore(String) : StateStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#359]]]
changelogPartitions() : Collection<TopicPartition> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#367]]]
markChangelogAsCorrupted(Collection<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#371]]]
+changelogOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#386]]]
taskId() : TaskId [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#401]]]
changelogAsSource(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#406]]]
+taskType() : TaskType [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#411]]]
storeMetadata(TopicPartition) : StateStoreMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#416]]]
restore(StateStoreMetadata;List<ConsumerRecord<byte[],byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#426]]]
+flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#459]]]
+flushCache() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#488]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#533]]]
recycle() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#572]]]
transitionTaskType(TaskType;LogContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#579]]]
+updateChangelogOffsets(Map<TopicPartition,Long>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#593]]]
+checkpoint() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#607]]]
-getStorePartition(String) : TopicPartition [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#645]]]
-isLoggingEnabled(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#652]]]
-findStore(TopicPartition) : StateStoreMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#658]]]
-checkpointableOffsetFromChangelogOffset(Long) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#672]]]
-changelogOffsetFromCheckpointedOffset(long) : Long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#677]]]
+registeredChangelogPartitionFor(String) : TopicPartition [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#681]]]
+changelogFor(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#698]]]
+deleteCheckPointFileIfEOSEnabled() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java.html#702]]]
} 
@enduml
