@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.ProcessorContextUtils
class org.apache.kafka.streams.processor.internals.ProcessorContextUtils {
- ProcessorContextUtils() : ProcessorContextUtils [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#14]]]
+ currentSystemTime(ProcessorContext) : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#17]]]
+ getMetricsImpl(ProcessorContext) : StreamsMetricsImpl [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#22]]]
+ getMetricsImpl(StateStoreContext) : StreamsMetricsImpl [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#27]]]
+ changelogFor(ProcessorContext;String;Boolean) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#31]]]
+ changelogFor(StateStoreContext;String;Boolean) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#42]]]
+ getPrefix(Map<String,Object>;String) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#53]]]
+ asInternalProcessorContext(ProcessorContext) : InternalProcessorContext [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#65]]]
+ asInternalProcessorContext(StateStoreContext) : InternalProcessorContext [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextUtils.java.html#75]]]
} 
@enduml
