@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.QuickUnion"
class org.apache.kafka.streams.processor.internals.QuickUnion {
+add(T) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/QuickUnion.java.html#26]]]
+exists(T) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/QuickUnion.java.html#30]]]
+root(T) : T [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/QuickUnion.java.html#37]]]
unite(T;T...) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/QuickUnion.java.html#57]]]
-unitePair(T;T) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/QuickUnion.java.html#63]]]
} 
@enduml
