@startuml
!pragma layout smetana
RecordCollector <|-- org.apache.kafka.streams.processor.internals.RecordCollectorImpl
class org.apache.kafka.streams.processor.internals.RecordCollectorImpl {
+  RecordCollectorImpl(LogContext;TaskId;StreamsProducer;ProductionExceptionHandler;StreamsMetricsImpl;ProcessorTopology)
+  initialize()
+  recordSendError(String;Exception;ProducerRecord<byte[],byte[]>)
+  isFatalException(Exception)
+  flush()
+  closeClean()
+  closeDirty()
+  removeAllProducedSensors()
+  offsets()
+  checkForException()
+  producer()
} 
@enduml
