@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.RecordCollector
class org.apache.kafka.streams.processor.internals.RecordCollector {
+  initialize()
+  flush()
+  closeClean()
+  closeDirty()
+  offsets()
} 
@enduml
