@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.RepartitionTopics"
class org.apache.kafka.streams.processor.internals.RepartitionTopics {
+RepartitionTopics(TopologyMetadata;InternalTopicManager;CopartitionedTopicsEnforcer;Cluster;String) : RepartitionTopics [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#57]]]
+setup() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#70]]]
+topologiesWithMissingInputTopics() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#106]]]
+missingSourceTopicExceptions() : Queue<StreamsException> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#113]]]
+topicPartitionsInfo() : Map<TopicPartition,PartitionInfo> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#127]]]
-computeRepartitionTopicConfig(Cluster) : Map<String,InternalTopicConfig> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#134]]]
-ensureCopartitioning(Collection<Set<String>>;Map<String,InternalTopicConfig>;Cluster) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#181]]]
-computeMissingExternalSourceTopics(TopicsInfo;Cluster) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#189]]]
-setRepartitionSourceTopicPartitionCount(Map<String,InternalTopicConfig>;Collection<TopicsInfo>;Cluster) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#200]]]
-computePartitionCount(Map<String,InternalTopicConfig>;Collection<TopicsInfo>;Cluster;String) : Integer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/RepartitionTopics.java.html#243]]]
} 
@enduml
