@startuml
!pragma layout smetana
"Stamped<ConsumerRecord<?,?>>" <|-- "org.apache.kafka.streams.processor.internals.StampedRecord"
class org.apache.kafka.streams.processor.internals.StampedRecord {
+StampedRecord(ConsumerRecord<?,?>;long) : StampedRecord [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#9]]]
+topic() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#13]]]
+partition() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#17]]]
+key() : Object [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#21]]]
+value() : Object [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#25]]]
+offset() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#29]]]
+headers() : Headers [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#33]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java.html#38]]]
} 
@enduml
