@startuml
!pragma layout smetana
"AbstractTaskTask" <|-- "org.apache.kafka.streams.processor.internals.StandbyTask"
class org.apache.kafka.streams.processor.internals.StandbyTask {
StandbyTask(TaskId;Set<TopicPartition>;ProcessorTopology;TaskConfig;StreamsMetricsImpl;ProcessorStateManager;StateDirectory;ThreadCache;InternalProcessorContext) : StandbyTask [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#56]]]
+isActive() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#84]]]
+initializeIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#92]]]
+completeRestoration(java.util.function.Consumer<Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#115]]]
+suspend() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#120]]]
+resume() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#149]]]
+prepareCommit() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#164]]]
+postCommit(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#186]]]
+closeClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#209]]]
+closeDirty() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#216]]]
+closeCleanAndRecycleState() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#223]]]
-close(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#237]]]
+commitNeeded() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#275]]]
+changelogOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#282]]]
+committedOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#287]]]
+highWaterMark() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#292]]]
+timeCurrentIdlingStarted() : Optional<Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#297]]]
+addRecords(TopicPartition;Iterable<ConsumerRecord<byte[],byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#302]]]
processorContext() : InternalProcessorContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#306]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#317]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#327]]]
} 
@enduml
