@startuml
!pragma layout smetana
AbstractTaskTask <|-- org.apache.kafka.streams.processor.internals.StandbyTask
class org.apache.kafka.streams.processor.internals.StandbyTask {
StandbyTask(TaskId;Set<TopicPartition>;ProcessorTopology;TaskConfig;StreamsMetricsImpl;ProcessorStateManager;StateDirectory;ThreadCache;InternalProcessorContext) : StandbyTask [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#31]]]
+isActive() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#59]]]
+initializeIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#65]]]
+completeRestoration(java.util.function.Consumer<Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#88]]]
+suspend() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#93]]]
+resume() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#122]]]
+prepareCommit() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#131]]]
+postCommit(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#153]]]
+closeClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#176]]]
+closeDirty() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#183]]]
+closeCleanAndRecycleState() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#190]]]
-close(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#204]]]
+commitNeeded() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#242]]]
+changelogOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#249]]]
+committedOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#254]]]
+highWaterMark() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#259]]]
+timeCurrentIdlingStarted() : Optional<Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#264]]]
+addRecords(TopicPartition;Iterable<ConsumerRecord<byte[],byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#269]]]
processorContext() : InternalProcessorContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#273]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#279]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java.html#284]]]
} 
@enduml
