@startuml
!pragma layout smetana
TopicNameExtractor<K,V> <|-- org.apache.kafka.streams.processor.internals.StaticTopicNameExtractor
class org.apache.kafka.streams.processor.internals.StaticTopicNameExtractor {
+  StaticTopicNameExtractor(String)
+  extract(K;V;RecordContext)
+  toString()
+  equals(Object)
+  hashCode()
} 
@enduml
