@startuml
!pragma layout smetana
TopicNameExtractor_K,V_ <|-- org.apache.kafka.streams.processor.internals.StaticTopicNameExtractor
class org.apache.kafka.streams.processor.internals.StaticTopicNameExtractor {
+ StaticTopicNameExtractor(String) : StaticTopicNameExtractor [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StaticTopicNameExtractor.java.html#14]]]
+ extract(K;V;RecordContext) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StaticTopicNameExtractor.java.html#18]]]
+ toString() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StaticTopicNameExtractor.java.html#23]]]
+ equals(Object) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StaticTopicNameExtractor.java.html#28]]]
+ hashCode() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StaticTopicNameExtractor.java.html#40]]]
} 
@enduml
