@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.StateManagerUtil"
class org.apache.kafka.streams.processor.internals.StateManagerUtil {
-StateManagerUtil() : StateManagerUtil [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#47]]]
converterForStore(StateStore) : RecordConverter [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#49]]]
checkpointNeeded(boolean;Map<TopicPartition,Long>;Map<TopicPartition,Long>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#53]]]
registerStateStores(Logger;String;ProcessorTopology;ProcessorStateManager;StateDirectory;InternalProcessorContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#79]]]
closeStateManager(Logger;String;boolean;boolean;ProcessorStateManager;StateDirectory;TaskType) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#110]]]
parseTaskDirectoryName(String;String) : TaskId [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#163]]]
toTaskDirString(TaskId) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StateManagerUtil.java.html#183]]]
} 
@enduml
