@startuml
!pragma layout smetana
ChangelogReader <|-- org.apache.kafka.streams.processor.internals.StoreChangelogReader
class org.apache.kafka.streams.processor.internals.StoreChangelogReader {
+  StoreChangelogReader(Time;StreamsConfig;LogContext;Admin;Consumer<byte[],byte[]>;StateRestoreListener)
+  recordEndOffset(Long)
+  hasRestoredToEnd(ChangelogMetadata)
+  enforceRestoreActive()
+  transitToUpdateStandby()
+  register(TopicPartition;ProcessorStateManager)
+  restoringChangelogByPartition(TopicPartition)
+  registeredChangelogs()
+  restoringChangelogs()
+  activeRestoringChangelogs()
+  standbyRestoringChangelogs()
+  allChangelogsCompleted()
+  completedChangelogs()
+  restore(Map<TaskId,Task>)
+  pauseResumePartitions(Map<TaskId,Task>;Set<TopicPartition>)
+  updatePartitionsByType(Map<TaskId,Task>;Set<TopicPartition>;TaskType)
+  shouldResume(Map<TaskId,Task>;TopicPartition;TaskType)
+  shouldPause(Map<TaskId,Task>;TopicPartition;TaskType)
+  maybeLogRestorationProgress()
+  getPositionString(TopicPartition;ChangelogMetadata)
+  maybeUpdateLimitOffsetsForStandbyChangelogs(Map<TaskId,Task>)
+  bufferChangelogRecords(ChangelogMetadata;List<ConsumerRecord<byte[],byte[]>>)
+  restoreChangelog(ChangelogMetadata)
+  getTasksFromPartitions(Map<TaskId,Task>;Set<TopicPartition>)
+  clearTaskTimeout(Set<Task>)
+  maybeInitTaskTimeoutOrThrow(Set<Task>;Exception)
+  committedOffsetForChangelogs(Map<TaskId,Task>;Set<TopicPartition>)
+  endOffsetForChangelogs(Map<TaskId,Task>;Set<TopicPartition>)
+  updateLimitOffsetsForStandbyChangelogs(Map<TopicPartition,Long>)
+  initializeChangelogs(Map<TaskId,Task>;Set<ChangelogMetadata>)
+  addChangelogsToRestoreConsumer(Set<TopicPartition>)
+  pauseChangelogsFromRestoreConsumer(Collection<TopicPartition>)
+  removeChangelogsFromRestoreConsumer(Collection<TopicPartition>)
+  resumeChangelogsFromRestoreConsumer(Collection<TopicPartition>)
+  prepareChangelogs(Set<ChangelogMetadata>)
+  unregister(Collection<TopicPartition>)
+  clear()
+  isEmpty()
+  toString()
+  changelogMetadata(TopicPartition)
+  state()
} 
@enduml
