@startuml
!pragma layout smetana
AbstractTaskProcessorNodePunctuator <|-- org.apache.kafka.streams.processor.internals.StreamTask
class org.apache.kafka.streams.processor.internals.StreamTask {
+ StreamTask(TaskId;Set<TopicPartition>;ProcessorTopology;Consumer<byte[],byte[]>;TaskConfig;StreamsMetricsImpl;StateDirectory;ThreadCache;Time;ProcessorStateManager;RecordCollector;InternalProcessorContext;LogContext) : StreamTask [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#94]]]
- createPartitionQueues() : Map<TopicPartition,RecordQueue> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#186]]]
+ isActive() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#195]]]
+ initializeIfNeeded() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#201]]]
+ addPartitionsForOffsetReset(Set<TopicPartition>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#218]]]
+ completeRestoration(java.util.function.Consumer<Set<TopicPartition>>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#225]]]
+ suspend() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#252]]]
- closeTopology() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#291]]]
+ resume() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#315]]]
+ prepareCommit() : Map<TopicPartition,OffsetAndMetadata> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#352]]]
- findOffset(TopicPartition) : Long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#385]]]
- committableOffsetsAndMetadata() : Map<TopicPartition,OffsetAndMetadata> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#404]]]
+ postCommit(boolean) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#443]]]
- clearCommitStatuses() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#477]]]
- extractPartitionTimes() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#484]]]
+ closeClean() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#493]]]
+ closeDirty() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#502]]]
+ updateInputPartitions(Set<TopicPartition>;Map<String,List<String>>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#510]]]
+ closeCleanAndRecycleState() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#517]]]
+ maybeCheckpoint(boolean) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#547]]]
- validateClean() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#557]]]
- removeAllSensors() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#567]]]
- close(boolean) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#575]]]
+ isProcessable(long) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#630]]]
+ process(long) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#658]]]
- doProcess(long) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#725]]]
+ recordProcessBatchTime(long) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#752]]]
+ recordProcessTimeRatioAndBufferSize(long;long) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#757]]]
- getStacktraceString(RuntimeException) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#763]]]
+ punctuate(ProcessorNode<?,?,?,?>;long;PunctuationType;Punctuator) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#778]]]
- updateProcessorContext(ProcessorNode<?,?,?,?>;long;ProcessorRecordContext) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#813]]]
- checkpointableOffsets() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#822]]]
- resetOffsetsIfNeededAndInitializeMetadata(java.util.function.Consumer<Set<TopicPartition>>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#833]]]
- initializeTaskTimeAndProcessorMetadata(Map<TopicPartition,OffsetAndMetadata>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#868]]]
+ purgeableOffsets() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#897]]]
- initializeTopology() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#910]]]
+ addRecords(TopicPartition;Iterable<ConsumerRecord<byte[],byte[]>>) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#925]]]
+ schedule(long;PunctuationType;Punctuator) : Cancellable [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#940]]]
- schedule(long;long;PunctuationType;Punctuator) : Cancellable [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#954]]]
+ maybePunctuateStreamTime() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#975]]]
+ maybePunctuateSystemTime() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#994]]]
maybeRecordE2ELatency(long;long;String) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1006]]]
requestCommit() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1016]]]
+ commitRequested() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1022]]]
+ processorContext() : InternalProcessorContext [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1027]]]
+ toString() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1033]]]
+ toString(String) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1038]]]
+ commitNeeded() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1064]]]
+ changelogOffsets() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1100]]]
+ committedOffsets() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1112]]]
+ highWaterMark() : Map<TopicPartition,Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1117]]]
- transitToSuspend() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1121]]]
+ timeCurrentIdlingStarted() : Optional<Long> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1128]]]
+ updateCommittedOffsets(TopicPartition;Long) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1132]]]
+ updateEndOffsets(TopicPartition;Long) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1136]]]
+ hasRecordsQueued() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1140]]]
recordCollector() : RecordCollector [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1144]]]
numBuffered() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1149]]]
streamTime() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1153]]]
} 
@enduml
