@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.StreamsMetadataState
class org.apache.kafka.streams.processor.internals.StreamsMetadataState {
+StreamsMetadataState(TopologyMetadata;HostInfo;LogContext) : StreamsMetadataState [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#42]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#52]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#56]]]
+getLocalMetadata() : StreamsMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#67]]]
+getAllMetadata() : Collection<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#72]]]
+getAllMetadataForStore(String) : Collection<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#77]]]
+getAllMetadataForStore(String;String) : Collection<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#108]]]
+getAllMetadataForTopology(String) : Collection<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#132]]]
onChange(Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>;Cluster) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#232]]]
-hasPartitionsForAnyTopics(List<String>;Set<TopicPartition>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#239]]]
-getStoresOnHost(Map<String,List<String>>;Set<TopicPartition>) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#248]]]
-rebuildMetadata(Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#260]]]
-rebuildMetadataForNamedTopologies(Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>) : List<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#279]]]
-rebuildMetadataForSingleTopology(Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>) : List<StreamsMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#350]]]
-getSourceTopicsInfo(String) : SourceTopicsInfo [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#460]]]
-getSourceTopicsInfo(String;String) : SourceTopicsInfo [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#464]]]
-isInitialized() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#473]]]
+getStoreForChangelogTopic(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java.html#477]]]
} 
@enduml
