@startuml
!pragma layout smetana
"AbstractTaskProcessorNodePunctuator" <|-- "org.apache.kafka.streams.processor.internals.StreamTask"
class org.apache.kafka.streams.processor.internals.StreamTask {
+StreamTask(TaskId;Set<TopicPartition>;ProcessorTopology;Consumer<byte[],byte[]>;TaskConfig;StreamsMetricsImpl;StateDirectory;ThreadCache;Time;ProcessorStateManager;RecordCollector;InternalProcessorContext;LogContext) : StreamTask [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#111]]]
-createPartitionQueues() : Map<TopicPartition,RecordQueue> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#203]]]
+isActive() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#212]]]
+initializeIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#222]]]
+addPartitionsForOffsetReset(Set<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#239]]]
+completeRestoration(java.util.function.Consumer<Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#248]]]
+suspend() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#275]]]
-closeTopology() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#314]]]
+resume() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#342]]]
+prepareCommit() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#383]]]
-findOffset(TopicPartition) : Long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#416]]]
-committableOffsetsAndMetadata() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#435]]]
+postCommit(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#474]]]
-clearCommitStatuses() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#508]]]
-extractPartitionTimes() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#515]]]
+closeClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#524]]]
+closeDirty() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#533]]]
+updateInputPartitions(Set<TopicPartition>;Map<String,List<String>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#541]]]
+closeCleanAndRecycleState() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#548]]]
+maybeCheckpoint(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#584]]]
-validateClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#594]]]
-removeAllSensors() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#604]]]
-close(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#614]]]
+isProcessable(long) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#672]]]
+process(long) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#705]]]
-doProcess(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#772]]]
+recordProcessBatchTime(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#799]]]
+recordProcessTimeRatioAndBufferSize(long;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#804]]]
-getStacktraceString(RuntimeException) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#810]]]
+punctuate(ProcessorNode<?,?,?,?>;long;PunctuationType;Punctuator) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#828]]]
-updateProcessorContext(ProcessorNode<?,?,?,?>;long;ProcessorRecordContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#863]]]
-checkpointableOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#875]]]
-resetOffsetsIfNeededAndInitializeMetadata(java.util.function.Consumer<Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#886]]]
-initializeTaskTimeAndProcessorMetadata(Map<TopicPartition,OffsetAndMetadata>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#921]]]
+purgeableOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#950]]]
-initializeTopology() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#963]]]
+addRecords(TopicPartition;Iterable<ConsumerRecord<byte[],byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#984]]]
+schedule(long;PunctuationType;Punctuator) : Cancellable [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1005]]]
-schedule(long;long;PunctuationType;Punctuator) : Cancellable [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1026]]]
+maybePunctuateStreamTime() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1053]]]
+maybePunctuateSystemTime() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1078]]]
maybeRecordE2ELatency(long;long;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1090]]]
requestCommit() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1102]]]
+commitRequested() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1110]]]
+processorContext() : InternalProcessorContext [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1115]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1126]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1136]]]
+commitNeeded() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1162]]]
+changelogOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1198]]]
+committedOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1210]]]
+highWaterMark() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1215]]]
-transitToSuspend() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1219]]]
+timeCurrentIdlingStarted() : Optional<Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1226]]]
+updateCommittedOffsets(TopicPartition;Long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1230]]]
+updateEndOffsets(TopicPartition;Long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1234]]]
+hasRecordsQueued() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1238]]]
recordCollector() : RecordCollector [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1242]]]
numBuffered() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1247]]]
streamTime() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java.html#1251]]]
} 
@enduml
