@startuml
!pragma layout smetana
"Thread" <|-- "org.apache.kafka.streams.processor.internals.StreamThread"
class org.apache.kafka.streams.processor.internals.StreamThread {
+setStateListener(StreamThread.StateListener) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#190]]]
+state() : State [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#197]]]
setPartitionAssignedTime(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#202]]]
setState(State) : State [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#212]]]
+isRunning() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#252]]]
+create(TopologyMetadata;StreamsConfig;KafkaClientSupplier;Admin;UUID;String;StreamsMetricsImpl;Time;StreamsMetadataState;long;StateDirectory;StateRestoreListener;int;Runnable;BiConsumer<Throwable,Boolean>) : StreamThread [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#323]]]
+StreamThread(Time;StreamsConfig;Admin;Consumer<byte[],byte[]>;Consumer<byte[],byte[]>;ChangelogReader;String;TaskManager;StreamsMetricsImpl;TopologyMetadata;String;LogContext;AtomicInteger;AtomicLong;Queue<StreamsException>;Runnable;BiConsumer<Throwable,Boolean>;java.util.function.Consumer<Long>) : StreamThread [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#440]]]
+run() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#542]]]
runLoop() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#568]]]
+setStreamsUncaughtExceptionHandler(BiConsumer<Throwable,Boolean>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#637]]]
+maybeSendShutdown() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#641]]]
+waitOnThreadState(StreamThread.State;long) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#649]]]
+shutdownToError() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#682]]]
+sendShutdownRequest(AssignorError) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#686]]]
-handleTaskMigrated(TaskMigratedException) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#690]]]
-subscribeConsumer() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#700]]]
+resizeCache(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#708]]]
runOnce() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#731]]]
-initializeAndRestorePhase() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#852]]]
-checkForTopologyUpdates() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#887]]]
-pollPhase() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#902]]]
-pollRequests(Duration) : ConsumerRecords<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#963]]]
-resetOffsets(Set<TopicPartition>;Exception) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#977]]]
-addToResetList(TopicPartition;Set<TopicPartition>;String;String;Set<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1042]]]
maybeCommit() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1058]]]
-advanceNowAndComputeLatency() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1099]]]
+shutdown() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1112]]]
-completeShutdown(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1121]]]
+threadMetadata() : ThreadMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1170]]]
updateThreadMetadata(String) : StreamThread [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1175]]]
-updateThreadMetadata(Map<TaskId,Task>;Map<TaskId,Task>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1190]]]
+activeTaskMap() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1226]]]
+activeTasks() : List<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1230]]]
+allTasks() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1234]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1245]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1255]]]
+getGroupInstanceID() : Optional<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1259]]]
+requestLeaveGroupDuringShutdown() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1263]]]
+producerMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1267]]]
+consumerMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1271]]]
+adminClientMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1275]]]
+getStateLock() : Object [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1279]]]
setNow(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1284]]]
taskManager() : TaskManager [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1288]]]
currentNumIterations() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1292]]]
rebalanceListener() : ConsumerRebalanceListener [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1296]]]
mainConsumer() : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1300]]]
restoreConsumer() : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1304]]]
adminClient() : Admin [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java.html#1308]]]
} 
@enduml
