@startuml
!pragma layout smetana
Thread <|-- org.apache.kafka.streams.processor.internals.StreamThread
class org.apache.kafka.streams.processor.internals.StreamThread {
+  setStateListener(StreamThread.StateListener)
+  state()
+  setPartitionAssignedTime(long)
+  setState(State)
+  isRunning()
+  create(TopologyMetadata;StreamsConfig;KafkaClientSupplier;Admin;UUID;String;StreamsMetricsImpl;Time;StreamsMetadataState;long;long;StateDirectory;StateRestoreListener;int;Runnable;BiConsumer<Throwable,Boolean>)
+  StreamThread(Time;StreamsConfig;Admin;Consumer<byte[],byte[]>;Consumer<byte[],byte[]>;ChangelogReader;String;TaskManager;StreamsMetricsImpl;TopologyMetadata;String;LogContext;AtomicInteger;AtomicLong;Queue<StreamsException>;Runnable;BiConsumer<Throwable,Boolean>;java.util.function.Consumer<Long>;long)
+  run()
+  runLoop()
+  setStreamsUncaughtExceptionHandler(BiConsumer<Throwable,Boolean>)
+  maybeSendShutdown()
+  waitOnThreadState(StreamThread.State;long)
+  shutdownToError()
+  sendShutdownRequest(AssignorError)
+  handleTaskMigrated(TaskMigratedException)
+  subscribeConsumer()
+  resizeCacheAndBufferMemory(long;long)
+  getCacheSize()
+  getMaxBufferSize()
+  runOnce()
+  initializeAndRestorePhase()
+  checkForTopologyUpdates()
+  pollPhase()
+  pollRequests(Duration)
+  resetOffsets(Set<TopicPartition>;Exception)
+  addToResetList(TopicPartition;Set<TopicPartition>;String;String;Set<String>)
+  maybeCommit()
+  advanceNowAndComputeLatency()
+  shutdown()
+  completeShutdown(boolean)
+  threadMetadata()
+  updateThreadMetadata(String)
+  updateThreadMetadata(Map<TaskId,Task>;Map<TaskId,Task>)
+  activeTaskMap()
+  activeTasks()
+  allTasks()
+  toString()
+  toString(String)
+  getGroupInstanceID()
+  requestLeaveGroupDuringShutdown()
+  producerMetrics()
+  consumerMetrics()
+  adminClientMetrics()
+  getStateLock()
+  setNow(long)
+  taskManager()
+  currentNumIterations()
+  rebalanceListener()
+  mainConsumer()
+  restoreConsumer()
+  adminClient()
} 
@enduml
