@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.StreamsProducer"
class org.apache.kafka.streams.processor.internals.StreamsProducer {
+StreamsProducer(StreamsConfig;String;KafkaClientSupplier;TaskId;UUID;LogContext;Time) : StreamsProducer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#81]]]
-formatException(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#141]]]
eosEnabled() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#145]]]
initTransaction() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#152]]]
+resetProducer() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#184]]]
-getMetricValue(Map<MetricName,?extendsMetric>;String) : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#199]]]
-totalBlockedTime(Producer<?,?>) : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#219]]]
+totalBlockedTime() : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#230]]]
-maybeBeginTransaction() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#234]]]
send(ProducerRecord<byte[],byte[]>;Callback) : Future<RecordMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#253]]]
-isRecoverable(KafkaException) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#276]]]
commitTransaction(Map<TopicPartition,OffsetAndMetadata>;ConsumerGroupMetadata) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#286]]]
abortTransaction() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#318]]]
partitionsFor(String) : List<PartitionInfo> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#356]]]
metrics() : Map<MetricName,?extendsMetric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#360]]]
flush() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#364]]]
close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#368]]]
kafkaProducer() : Producer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsProducer.java.html#373]]]
} 
@enduml
