@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.Task"
class org.apache.kafka.streams.processor.internals.Task {
initializeIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#108]]]
addPartitionsForOffsetReset(Set<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#110]]]
completeRestoration(java.util.function.Consumer<Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#117]]]
suspend() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#119]]]
resume() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#124]]]
closeDirty() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#129]]]
closeClean() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#134]]]
updateInputPartitions(Set<TopicPartition>;Map<String,List<String>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#142]]]
maybeCheckpoint(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#148]]]
markChangelogAsCorrupted(Collection<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#150]]]
revive() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#155]]]
closeCleanAndRecycleState() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#160]]]
addRecords(TopicPartition;Iterable<ConsumerRecord<byte[],byte[]>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#165]]]
process(long) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#167]]]
recordProcessBatchTime(long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#171]]]
recordProcessTimeRatioAndBufferSize(long;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#174]]]
maybePunctuateStreamTime() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#177]]]
maybePunctuateSystemTime() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#181]]]
prepareCommit() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#188]]]
postCommit(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#190]]]
purgeableOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#192]]]
maybeInitTaskTimeoutOrThrow(long;Exception) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#199]]]
clearTaskTimeout() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#202]]]
id() : TaskId [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#206]]]
isActive() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#208]]]
inputPartitions() : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#210]]]
changelogPartitions() : Collection<TopicPartition> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#215]]]
state() : State [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#217]]]
needsInitializationOrRestoration() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#219]]]
commitNeeded() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#223]]]
commitRequested() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#225]]]
getStore(String) : StateStore [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#232]]]
changelogOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#238]]]
committedOffsets() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#244]]]
highWaterMark() : Map<TopicPartition,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#249]]]
timeCurrentIdlingStarted() : Optional<Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java.html#254]]]
} 
@enduml
