@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.TaskManager"
class org.apache.kafka.streams.processor.internals.TaskManager {
TaskManager(Time;ChangelogReader;UUID;String;StreamsMetricsImpl;ActiveTaskCreator;StandbyTaskCreator;TopologyMetadata;Admin;StateDirectory) : TaskManager [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#96]]]
setMainConsumer(Consumer<byte[],byte[]>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#128]]]
+totalProducerBlockedTime() : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#133]]]
+processId() : UUID [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#137]]]
+topologyMetadata() : TopologyMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#141]]]
isRebalanceInProgress() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#145]]]
handleRebalanceStart(Set<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#149]]]
handleRebalanceComplete() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#157]]]
handleCorruption(Set<TaskId>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#170]]]
-closeDirtyAndRevive(Collection<Task>;boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#212]]]
+handleAssignment(Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#271]]]
-handleCloseAndRecycle(Set<Task>;Set<Task>;Set<Task>;Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>;LinkedHashMap<TaskId,RuntimeException>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#352]]]
tryToCompleteRestoration(long;java.util.function.Consumer<Set<TopicPartition>>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#448]]]
handleRevocation(Collection<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#518]]]
-prepareCommitAndAddOffsetsToMap(Set<Task>;Map<Task,Map<TopicPartition,OffsetAndMetadata>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#622]]]
handleLostAll() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#646]]]
+getTaskOffsetSums() : Map<TaskId,Long> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#670]]]
-tryToLockAllNonEmptyTaskDirectories() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#707]]]
-releaseLockedDirectoriesForTasks(Set<TaskId>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#733]]]
-releaseLockedUnassignedTaskDirectories() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#748]]]
-sumOfChangelogOffsets(TaskId;Map<TopicPartition,Long>) : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#759]]]
-closeTaskDirty(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#787]]]
-completeTaskCloseClean(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#805]]]
shutdown(boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#810]]]
closeAndCleanUpTasks(Collection<Task>;Collection<Task>;boolean) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#851]]]
-tryCloseCleanActiveTasks(Collection<Task>;boolean;AtomicReference<RuntimeException>) : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#879]]]
-tryCloseCleanStandbyTasks(Collection<Task>;boolean;AtomicReference<RuntimeException>) : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#977]]]
activeTaskIds() : Set<TaskId> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1003]]]
standbyTaskIds() : Set<TaskId> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1009]]]
tasks() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1015]]]
notPausedTasks() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1021]]]
activeTaskMap() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1026]]]
activeTaskIterable() : List<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1030]]]
-activeTaskStream() : Stream<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1034]]]
standbyTaskMap() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1038]]]
-standbyTaskIterable() : List<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1042]]]
-standbyTaskStream() : Stream<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1046]]]
commitAll() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1051]]]
addRecordsToTasks(ConsumerRecords<byte[],byte[]>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1060]]]
commit(Collection<Task>) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1081]]]
maybeCommitActiveTasksPerUserRequested() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1100]]]
-commitTasksAndMaybeUpdateCommittableOffsets(Collection<Task>;Map<Task,Map<TopicPartition,OffsetAndMetadata>>) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1113]]]
+updateTaskEndMetadata(TopicPartition;Long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1122]]]
handleTopologyUpdates() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1136]]]
maybeCloseTasksFromRemovedTopologies(Set<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1150]]]
process(int;Time) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1181]]]
recordTaskProcessRatio(long;long) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1185]]]
punctuate() : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1194]]]
maybePurgeCommittedRecords() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1198]]]
+toString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1229]]]
+toString(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1233]]]
producerMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1251]]]
producerClientIds() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1255]]]
lockedTaskDirectories() : Set<TaskId> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1259]]]
-maybeWrapAndSetFirstException(AtomicReference<RuntimeException>;RuntimeException;TaskId) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1263]]]
+executeAndMaybeSwallow(boolean;Runnable;java.util.function.Consumer<RuntimeException>;java.util.function.Consumer<RuntimeException>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1274]]]
+executeAndMaybeSwallow(boolean;Runnable;String;Logger) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1289]]]
needsInitializationOrRestoration() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1302]]]
addTask(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java.html#1307]]]
} 
@enduml
