@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.Tasks
class org.apache.kafka.streams.processor.internals.Tasks {
Tasks(LogContext;TopologyMetadata;ActiveTaskCreator;StandbyTaskCreator) : Tasks [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#52]]]
setMainConsumer(Consumer<byte[],byte[]>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#64]]]
handleNewAssignmentAndCreateTasks(Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>;Set<TaskId>;Set<TaskId>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#68]]]
maybeCreateTasksFromNewTopologies(Set<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#77]]]
totalProducerBlockedTime() : double [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#84]]]
createTasks(Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#88]]]
convertActiveToStandby(StreamTask;Set<TopicPartition>;Map<TaskId,RuntimeException>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#128]]]
convertStandbyToActive(StandbyTask;Set<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#147]]]
updateInputPartitionsAndResume(Task;Set<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#160]]]
cleanUpTaskProducerAndRemoveTask(TaskId;Map<TaskId,RuntimeException>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#177]]]
reInitializeThreadProducer() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#189]]]
closeThreadProducerIfNeeded() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#193]]]
closeAndRemoveTaskProducerIfNeeded(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#198]]]
removeTaskBeforeClosing(TaskId) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#202]]]
clear() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#213]]]
activeTasksForInputPartition(TopicPartition) : Task [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#221]]]
standbyTask(TaskId) : Task [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#226]]]
task(TaskId) : Task [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#233]]]
tasks(Collection<TaskId>) : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#240]]]
activeTasks() : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#249]]]
allTasks() : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#253]]]
notPausedActiveTasks() : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#257]]]
notPausedTasks() : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#264]]]
activeTaskIds() : Set<TaskId> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#271]]]
standbyTaskIds() : Set<TaskId> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#275]]]
activeTaskMap() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#280]]]
standbyTaskMap() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#285]]]
tasksPerId() : Map<TaskId,Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#289]]]
owned(TaskId) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#293]]]
streamsProducerForTask(TaskId) : StreamsProducer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#297]]]
threadProducer() : StreamsProducer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#301]]]
producerMetrics() : Map<MetricName,Metric> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#305]]]
producerClientIds() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#309]]]
mainConsumer() : Consumer<byte[],byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#313]]]
successfullyProcessed() : Collection<Task> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#317]]]
addToSuccessfullyProcessed(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#321]]]
removeTaskFromCuccessfullyProcessedBeforeClosing(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#325]]]
clearSuccessfullyProcessed() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#329]]]
addTask(Task) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/Tasks.java.html#334]]]
} 
@enduml
