@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.Tasks
class org.apache.kafka.streams.processor.internals.Tasks {
+  Tasks(LogContext;TopologyMetadata;ActiveTaskCreator;StandbyTaskCreator)
+  setMainConsumer(Consumer<byte[],byte[]>)
+  handleNewAssignmentAndCreateTasks(Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>;Set<TaskId>;Set<TaskId>)
+  maybeCreateTasksFromNewTopologies(Set<String>)
+  totalProducerBlockedTime()
+  createTasks(Map<TaskId,Set<TopicPartition>>;Map<TaskId,Set<TopicPartition>>)
+  convertActiveToStandby(StreamTask;Set<TopicPartition>;Map<TaskId,RuntimeException>)
+  convertStandbyToActive(StandbyTask;Set<TopicPartition>)
+  updateInputPartitionsAndResume(Task;Set<TopicPartition>)
+  cleanUpTaskProducerAndRemoveTask(TaskId;Map<TaskId,RuntimeException>)
+  reInitializeThreadProducer()
+  closeThreadProducerIfNeeded()
+  closeAndRemoveTaskProducerIfNeeded(Task)
+  removeTaskBeforeClosing(TaskId)
+  clear()
+  activeTasksForInputPartition(TopicPartition)
+  standbyTask(TaskId)
+  task(TaskId)
+  tasks(Collection<TaskId>)
+  activeTasks()
+  allTasks()
+  notPausedActiveTasks()
+  notPausedTasks()
+  activeTaskIds()
+  standbyTaskIds()
+  activeTaskMap()
+  standbyTaskMap()
+  tasksPerId()
+  owned(TaskId)
+  streamsProducerForTask(TaskId)
+  threadProducer()
+  producerMetrics()
+  producerClientIds()
+  mainConsumer()
+  successfullyProcessed()
+  addToSuccessfullyProcessed(Task)
+  removeTaskFromCuccessfullyProcessedBeforeClosing(Task)
+  clearSuccessfullyProcessed()
+  addTask(Task)
} 
@enduml
