@startuml
!pragma layout smetana
ThreadMetadata <|-- org.apache.kafka.streams.processor.internals.ThreadMetadataImpl
class org.apache.kafka.streams.processor.internals.ThreadMetadataImpl {
+ ThreadMetadataImpl(String;String;String;String;Set<String>;String;Set<TaskMetadata>;Set<TaskMetadata>) : ThreadMetadataImpl [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#33]]]
+ threadState() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#52]]]
+ threadName() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#56]]]
+ activeTasks() : Set<TaskMetadata> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#61]]]
+ standbyTasks() : Set<TaskMetadata> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#65]]]
+ consumerClientId() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#69]]]
+ restoreConsumerClientId() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#73]]]
+ producerClientIds() : Set<String> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#77]]]
+ adminClientId() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#81]]]
+ equals(Object) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#86]]]
+ hashCode() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#105]]]
+ toString() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/ThreadMetadataImpl.java.html#118]]]
} 
@enduml
