@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.TopicPartitionMetadata
class org.apache.kafka.streams.processor.internals.TopicPartitionMetadata {
+  TopicPartitionMetadata(long;ProcessorMetadata)
+  partitionTime()
+  processorMetadata()
+  encode()
+  decode(String)
+  hashCode()
+  equals(Object)
} 
@enduml
