@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.TopologyMetadata"
class org.apache.kafka.streams.processor.internals.TopologyMetadata {
+TopologyMetadata(InternalTopologyBuilder;StreamsConfig) : TopologyMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#102]]]
+TopologyMetadata(ConcurrentNavigableMap<String,InternalTopologyBuilder>;StreamsConfig) : TopologyMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#119]]]
+setLog(LogContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#135]]]
+processingMode() : ProcessingMode [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#139]]]
+topologyVersion() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#143]]]
-lock() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#147]]]
-unlock() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#151]]]
+sourceTopicsForTopology(String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#155]]]
+needsUpdate(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#159]]]
+registerThread(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#163]]]
+unregisterThread(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#167]]]
+taskExecutionMetadata() : TaskExecutionMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#172]]]
+executeTopologyUpdatesAndBumpThreadVersion(Consumer<Set<String>>;Consumer<Set<String>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#176]]]
+maybeNotifyTopologyVersionListeners() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#189]]]
-getMinimumThreadVersion() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#210]]]
+wakeupThreads() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#215]]]
+maybeWaitForNonEmptyTopology(Supplier<StreamThread.State>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#224]]]
+registerAndBuildNewTopology(KafkaFutureImpl<Void>;InternalTopologyBuilder) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#245]]]
+pauseTopology(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#267]]]
+isPaused(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#278]]]
+resumeTopology(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#290]]]
+unregisterTopology(KafkaFutureImpl<Void>;String) : KafkaFuture<Void> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#297]]]
+getTaskConfigFor(TaskId) : TaskConfig [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#317]]]
+buildAndRewriteTopology() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#322]]]
-buildAndVerifyTopology(InternalTopologyBuilder) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#326]]]
+getNumStreamThreads(StreamsConfig) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#365]]]
+hasNamedTopologies() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#396]]]
+namedTopologiesView() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#400]]]
+hasGlobalTopology() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#407]]]
+hasNoLocalTopology() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#414]]]
+hasPersistentStores() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#418]]]
+hasStore(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#427]]]
+hasOffsetResetOverrides() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#431]]]
+offsetResetStrategy(String) : OffsetResetStrategy [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#436]]]
+fullSourceTopicNamesForTopology(String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#452]]]
+allFullSourceTopicNames() : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#457]]]
sourceTopicPattern() : Pattern [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#463]]]
+usesPatternSubscription() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#481]]]
+isEmpty() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#486]]]
+topologyDescriptionString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#490]]]
+buildSubtopology(TaskId) : ProcessorTopology [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#506]]]
+globalTaskTopology() : ProcessorTopology [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#511]]]
+globalStateStores() : Map<String,StateStore> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#518]]]
+stateStoreNameToSourceTopicsForTopology(String) : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#522]]]
+stateStoreNameToSourceTopics() : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#526]]]
+getStoreForChangelogTopic(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#532]]]
+sourceTopicsForStore(String;String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#548]]]
+getTopologyNameOrElseUnnamed(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#552]]]
+subtopologyTopicsInfoMapExcluding(Set<String>) : Map<Subtopology,TopicsInfo> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#562]]]
+topologyToSubtopologyTopicsInfoMap() : Map<String,Map<Subtopology,TopicsInfo>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#575]]]
+nodeToSourceTopics(TaskId) : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#581]]]
addSubscribedTopicsFromMetadata(Set<String>;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#585]]]
addSubscribedTopicsFromAssignment(List<TopicPartition>;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#589]]]
+copartitionGroups() : Collection<Set<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#593]]]
-lookupBuilderForTask(TaskId) : InternalTopologyBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#604]]]
+getAllNamedTopologies() : Collection<NamedTopology> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#615]]]
+lookupBuilderForNamedTopology(String) : InternalTopologyBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#628]]]
-evaluateConditionIsTrueForAnyBuilders(Function<InternalTopologyBuilder,Boolean>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#636]]]
-applyToEachBuilder(Consumer<InternalTopologyBuilder>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#645]]]
} 
@enduml
