@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.TopologyMetadata
class org.apache.kafka.streams.processor.internals.TopologyMetadata {
+TopologyMetadata(InternalTopologyBuilder;StreamsConfig) : TopologyMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#87]]]
+TopologyMetadata(ConcurrentNavigableMap<String,InternalTopologyBuilder>;StreamsConfig) : TopologyMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#104]]]
+setLog(LogContext) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#120]]]
+processingMode() : ProcessingMode [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#124]]]
+topologyVersion() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#128]]]
-lock() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#132]]]
-unlock() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#136]]]
+sourceTopicsForTopology(String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#140]]]
+needsUpdate(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#144]]]
+registerThread(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#148]]]
+unregisterThread(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#152]]]
+taskExecutionMetadata() : TaskExecutionMetadata [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#157]]]
+executeTopologyUpdatesAndBumpThreadVersion(Consumer<Set<String>>;Consumer<Set<String>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#161]]]
+maybeNotifyTopologyVersionListeners() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#174]]]
-getMinimumThreadVersion() : long [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#195]]]
+wakeupThreads() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#200]]]
+maybeWaitForNonEmptyTopology(Supplier<StreamThread.State>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#209]]]
+registerAndBuildNewTopology(KafkaFutureImpl<Void>;InternalTopologyBuilder) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#228]]]
+pauseTopology(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#247]]]
+isPaused(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#252]]]
+resumeTopology(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#261]]]
+unregisterTopology(KafkaFutureImpl<Void>;String) : KafkaFuture<Void> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#266]]]
+getTaskConfigFor(TaskId) : TaskConfig [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#286]]]
+buildAndRewriteTopology() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#291]]]
-buildAndVerifyTopology(InternalTopologyBuilder) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#295]]]
+getNumStreamThreads(StreamsConfig) : int [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#334]]]
+hasNamedTopologies() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#363]]]
+namedTopologiesView() : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#367]]]
+hasGlobalTopology() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#372]]]
+hasNoLocalTopology() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#377]]]
+hasPersistentStores() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#381]]]
+hasStore(String) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#390]]]
+hasOffsetResetOverrides() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#394]]]
+offsetResetStrategy(String) : OffsetResetStrategy [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#399]]]
+fullSourceTopicNamesForTopology(String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#415]]]
+allFullSourceTopicNames() : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#420]]]
sourceTopicPattern() : Pattern [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#426]]]
+usesPatternSubscription() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#444]]]
+isEmpty() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#449]]]
+topologyDescriptionString() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#453]]]
+buildSubtopology(TaskId) : ProcessorTopology [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#465]]]
+globalTaskTopology() : ProcessorTopology [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#470]]]
+globalStateStores() : Map<String,StateStore> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#477]]]
+stateStoreNameToSourceTopicsForTopology(String) : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#481]]]
+stateStoreNameToSourceTopics() : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#485]]]
+getStoreForChangelogTopic(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#491]]]
+sourceTopicsForStore(String;String) : Collection<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#503]]]
+getTopologyNameOrElseUnnamed(String) : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#507]]]
+subtopologyTopicsInfoMapExcluding(Set<String>) : Map<Subtopology,TopicsInfo> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#512]]]
+topologyToSubtopologyTopicsInfoMap() : Map<String,Map<Subtopology,TopicsInfo>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#523]]]
+nodeToSourceTopics(TaskId) : Map<String,List<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#529]]]
addSubscribedTopicsFromMetadata(Set<String>;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#533]]]
addSubscribedTopicsFromAssignment(List<TopicPartition>;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#537]]]
+copartitionGroups() : Collection<Set<String>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#541]]]
-lookupBuilderForTask(TaskId) : InternalTopologyBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#548]]]
+getAllNamedTopologies() : Collection<NamedTopology> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#559]]]
+lookupBuilderForNamedTopology(String) : InternalTopologyBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#568]]]
-evaluateConditionIsTrueForAnyBuilders(Function<InternalTopologyBuilder,Boolean>) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#576]]]
-applyToEachBuilder(Consumer<InternalTopologyBuilder>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java.html#585]]]
} 
@enduml
