@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.metadata.placement.ReplicaPlacer
class org.apache.kafka.metadata.placement.ReplicaPlacer {
place(PlacementSpec;ClusterDescriber) : List<List<Integer>> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/ReplicaPlacer.java.html#15]]]
} 
@enduml
