@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.metadata.placement.UsableBroker"
class org.apache.kafka.metadata.placement.UsableBroker {
+UsableBroker(int;Optional<String>;boolean) : UsableBroker [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#37]]]
+id() : int [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#43]]]
+rack() : Optional<String> [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#47]]]
+fenced() : boolean [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#51]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#56]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#63]]]
+toString() : String [[[./../../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/placement/UsableBroker.java.html#70]]]
} 
@enduml
