@startuml
!pragma layout smetana
TaskWorker <|-- org.apache.kafka.trogdor.fault.NetworkPartitionFaultWorker
class org.apache.kafka.trogdor.fault.NetworkPartitionFaultWorker {
+  NetworkPartitionFaultWorker(String;List<Set<String>>)
+  start(Platform;WorkerStatusTracker;KafkaFutureImpl<String>)
+  stop(Platform)
+  runIptablesCommands(Platform;String)
} 
@enduml
