@startuml
!pragma layout smetana
"TaskSpec" <|-- "org.apache.kafka.trogdor.fault.NetworkPartitionFaultSpec"
class org.apache.kafka.trogdor.fault.NetworkPartitionFaultSpec {
+NetworkPartitionFaultSpec(long;long;List<List<String>>) : NetworkPartitionFaultSpec [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/fault/NetworkPartitionFaultSpec.java.html#38]]]
+partitions() : List<List<String>> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/fault/NetworkPartitionFaultSpec.java.html#46]]]
+newController(String) : TaskController [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/fault/NetworkPartitionFaultSpec.java.html#51]]]
+newTaskWorker(String) : TaskWorker [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/fault/NetworkPartitionFaultSpec.java.html#56]]]
-partitionSets() : List<Set<String>> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/fault/NetworkPartitionFaultSpec.java.html#60]]]
} 
@enduml
