@startuml
!pragma layout smetana
Query_V_ <|-- org.apache.kafka.streams.query.KeyQuery
class org.apache.kafka.streams.query.KeyQuery {
+  KeyQuery(K;boolean)
+  skipCache()
+  getKey()
+  isSkipCache()
} 
@enduml
