@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.query.Position"
class org.apache.kafka.streams.query.Position {
-Position(ConcurrentHashMap<String,ConcurrentHashMap<Integer,Long>>) : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#48]]]
+emptyPosition() : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#55]]]
+fromMap(Map<String,?extendsMap<Integer,Long>>) : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#65]]]
+withComponent(String;int;long) : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#78]]]
+copy() : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#91]]]
+merge(Position) : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#101]]]
+getTopics() : Set<String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#125]]]
+getPartitionPositions(String) : Map<Integer,Long> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#132]]]
-deepCopy(Map<String,?extendsMap<Integer,Long>>) : ConcurrentHashMap<String,ConcurrentHashMap<Integer,Long>> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#137]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#152]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#159]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#171]]]
+isEmpty() : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/Position.java.html#176]]]
} 
@enduml
