@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.query.PositionBound
class org.apache.kafka.streams.query.PositionBound {
- PositionBound(Position) : PositionBound [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#15]]]
+ unbounded() : PositionBound [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#20]]]
+ at(Position) : PositionBound [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#25]]]
+ isUnbounded() : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#30]]]
+ position() : Position [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#35]]]
+ toString() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#40]]]
+ equals(Object) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#45]]]
+ hashCode() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/PositionBound.java.html#57]]]
} 
@enduml
