@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.query.QueryResult"
class org.apache.kafka.streams.query.QueryResult {
addExecutionInfo(String) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#98]]]
setPosition(Position) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#104]]]
isSuccess() : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#110]]]
isFailure() : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#117]]]
getExecutionInfo() : List<String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#123]]]
getPosition() : Position [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#131]]]
getFailureReason() : FailureReason [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#138]]]
getFailureMessage() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#145]]]
getResult() : R [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/query/QueryResult.java.html#155]]]
} 
@enduml
