@startuml
!pragma layout smetana
Query_KeyValueIterator_Windowed_K_,V__ <|-- org.apache.kafka.streams.query.WindowRangeQuery
class org.apache.kafka.streams.query.WindowRangeQuery {
+  WindowRangeQuery(Optional<K>;Optional<Instant>;Optional<Instant>)
+  getKey()
+  getTimeFrom()
+  getTimeTo()
+  toString()
} 
@enduml
