@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.server.authorizer.AclCreateResult
class org.apache.kafka.server.authorizer.AclCreateResult {
+  AclCreateResult()
+  AclCreateResult(ApiException)
+  exception()
} 
@enduml
