@startuml
!pragma layout smetana
"Configurable" <|-- "org.apache.kafka.server.authorizer.Authorizer"
class org.apache.kafka.server.authorizer.Authorizer {
start(AuthorizerServerInfo) : Map<Endpoint,?extendsCompletionStage<Void>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#93]]]
authorize(AuthorizableRequestContext;List<Action>) : List<AuthorizationResult> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#109]]]
createAcls(AuthorizableRequestContext;List<AclBinding>) : List<?extendsCompletionStage<AclCreateResult>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#126]]]
deleteAcls(AuthorizableRequestContext;List<AclBindingFilter>) : List<?extendsCompletionStage<AclDeleteResult>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#147]]]
acls(AclBindingFilter) : Iterable<AclBinding> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#158]]]
aclCount() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#164]]]
authorizeByResourceType(AuthorizableRequestContext;AclOperation;ResourceType) : AuthorizationResult [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/authorizer/Authorizer.java.html#188]]]
} 
@enduml
