@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.internals.AdminMetadataManager"
class org.apache.kafka.clients.admin.internals.AdminMetadataManager {
+AdminMetadataManager(LogContext;long;long) : AdminMetadataManager [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#133]]]
+updater() : AdminMetadataUpdater [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#140]]]
+isReady() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#144]]]
+controller() : Node [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#163]]]
+nodeById(int) : Node [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#167]]]
+requestUpdate() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#171]]]
+clearController() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#178]]]
+metadataFetchDelayMs(long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#193]]]
-delayBeforeNextExpireMs(long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#209]]]
-delayBeforeNextAttemptMs(long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#214]]]
+transitionToUpdatePending(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#222]]]
+updateFailed(Throwable) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#227]]]
+update(Cluster;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminMetadataManager.java.html#243]]]
} 
@enduml
