@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.admin.internals.AdminApiDriver
class org.apache.kafka.clients.admin.internals.AdminApiDriver {
+ AdminApiDriver(AdminApiHandler<K,V>;AdminApiFuture<K,V>;long;long;LogContext) : AdminApiDriver [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#39]]]
- map(K;Integer) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#55]]]
- unmap(K) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#61]]]
- clear(Collection<K>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#74]]]
keyToBrokerId(K) : OptionalInt [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#81]]]
- completeExceptionally(Map<K,Throwable>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#89]]]
- completeLookupExceptionally(Map<K,Throwable>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#96]]]
- retryLookup(Collection<K>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#103]]]
- complete(Map<K,V>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#108]]]
- completeLookup(Map<K,Integer>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#115]]]
+ poll() : List<RequestSpec<K>> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#123]]]
+ onResponse(long;RequestSpec<K>;AbstractResponse;Node) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#131]]]
+ onFailure(long;RequestSpec<K>;Throwable) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#161]]]
- clearInflightRequest(long;RequestSpec<K>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#199]]]
- collectLookupRequests(List<RequestSpec<K>>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#255]]]
- collectFulfillmentRequests(List<RequestSpec<K>>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#263]]]
} 
@enduml
