@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.admin.internals.AdminApiDriver"
class org.apache.kafka.clients.admin.internals.AdminApiDriver {
+AdminApiDriver(AdminApiHandler<K,V>;AdminApiFuture<K,V>;long;long;LogContext) : AdminApiDriver [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#431]]]
-map(K;Integer) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-unmap(K) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-clear(Collection<K>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
keyToBrokerId(K) : OptionalInt [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-completeExceptionally(Map<K,Throwable>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-completeLookupExceptionally(Map<K,Throwable>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-retryLookup(Collection<K>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-complete(Map<K,V>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-completeLookup(Map<K,Integer>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
+poll() : List<RequestSpec<K>> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
+onResponse(long;RequestSpec<K>;AbstractResponse;Node) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
+onFailure(long;RequestSpec<K>;Throwable) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-clearInflightRequest(long;RequestSpec<K>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-collectLookupRequests(List<RequestSpec<K>>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
-collectFulfillmentRequests(List<RequestSpec<K>>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AdminApiDriver.java.html#1]]]
} 
@enduml
