@startuml
!pragma layout smetana
AdminApiLookupStrategy_AllBrokersStrategy.BrokerKey_ <|-- org.apache.kafka.clients.admin.internals.AllBrokersStrategy
class org.apache.kafka.clients.admin.internals.AllBrokersStrategy {
+  AllBrokersStrategy(LogContext)
+  lookupScope(BrokerKey)
+  buildRequest(Set<BrokerKey>)
+  handleResponse(Set<BrokerKey>;AbstractResponse)
+  validateLookupKeys(Set<BrokerKey>)
} 
@enduml
