@startuml
!pragma layout smetana
AdminApiHandler.Batched_CoordinatorKey,Map_TopicPartition,Errors__ <|-- org.apache.kafka.clients.admin.internals.AlterConsumerGroupOffsetsHandler
class org.apache.kafka.clients.admin.internals.AlterConsumerGroupOffsetsHandler {
+ AlterConsumerGroupOffsetsHandler(String;Map<TopicPartition,OffsetAndMetadata>;LogContext) : AlterConsumerGroupOffsetsHandler [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#36]]]
+ apiName() : String [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#48]]]
+ lookupStrategy() : AdminApiLookupStrategy<CoordinatorKey> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#53]]]
+ newFuture(String) : AdminApiFuture.SimpleAdminApiFuture<CoordinatorKey,Map<TopicPartition,Errors>> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#57]]]
- validateKeys(Set<CoordinatorKey>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#63]]]
+ buildBatchedRequest(int;Set<CoordinatorKey>) : OffsetCommitRequest.Builder [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#71]]]
+ handleResponse(Node;Set<CoordinatorKey>;AbstractResponse) : ApiResult<CoordinatorKey,Map<TopicPartition,Errors>> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#99]]]
- handleError(CoordinatorKey;TopicPartition;Errors;Map<TopicPartition,Errors>;Set<CoordinatorKey>;Set<CoordinatorKey>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/AlterConsumerGroupOffsetsHandler.java.html#138]]]
} 
@enduml
