@startuml
!pragma layout smetana
AdminApiHandler.Batched_CoordinatorKey,Map_TopicPartition,Errors__ <|-- org.apache.kafka.clients.admin.internals.DeleteConsumerGroupOffsetsHandler
class org.apache.kafka.clients.admin.internals.DeleteConsumerGroupOffsetsHandler {
+  DeleteConsumerGroupOffsetsHandler(String;Set<TopicPartition>;LogContext)
+  apiName()
+  lookupStrategy()
+  newFuture(String)
+  validateKeys(Set<CoordinatorKey>)
+  buildBatchedRequest(int;Set<CoordinatorKey>)
+  handleResponse(Node;Set<CoordinatorKey>;AbstractResponse)
+  handleGroupError(CoordinatorKey;Errors;Map<CoordinatorKey,Throwable>;Set<CoordinatorKey>)
} 
@enduml
