@startuml
!pragma layout smetana
AdminApiHandler.Batched_CoordinatorKey,TransactionDescription_ <|-- org.apache.kafka.clients.admin.internals.DescribeTransactionsHandler
class org.apache.kafka.clients.admin.internals.DescribeTransactionsHandler {
+ DescribeTransactionsHandler(LogContext) : DescribeTransactionsHandler [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#35]]]
+ newFuture(Collection<String>) : AdminApiFuture.SimpleAdminApiFuture<CoordinatorKey,TransactionDescription> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#42]]]
- buildKeySet(Collection<String>) : Set<CoordinatorKey> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#48]]]
+ apiName() : String [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#55]]]
+ lookupStrategy() : AdminApiLookupStrategy<CoordinatorKey> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#60]]]
+ buildBatchedRequest(int;Set<CoordinatorKey>) : DescribeTransactionsRequest.Builder [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#65]]]
+ handleResponse(Node;Set<CoordinatorKey>;AbstractResponse) : ApiResult<CoordinatorKey,TransactionDescription> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#82]]]
- collectTopicPartitions(DescribeTransactionsResponseData.TransactionState) : Set<TopicPartition> [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#125]]]
- handleError(CoordinatorKey;Errors;Map<CoordinatorKey,Throwable>;List<CoordinatorKey>) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeTransactionsHandler.java.html#138]]]
} 
@enduml
