@startuml
!pragma layout smetana
"AdminApiHandler.Batched<CoordinatorKey,Map<MemberIdentity,Errors>>" <|-- "org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler"
class org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler {
+RemoveMembersFromConsumerGroupHandler(String;List<MemberIdentity>;LogContext) : RemoveMembersFromConsumerGroupHandler [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#30]]]
+apiName() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#42]]]
+lookupStrategy() : AdminApiLookupStrategy<CoordinatorKey> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#47]]]
+newFuture(String) : AdminApiFuture.SimpleAdminApiFuture<CoordinatorKey,Map<MemberIdentity,Errors>> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#51]]]
-validateKeys(Set<CoordinatorKey>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#57]]]
+buildBatchedRequest(int;Set<CoordinatorKey>) : LeaveGroupRequest.Builder [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#67]]]
+handleResponse(Node;Set<CoordinatorKey>;AbstractResponse) : ApiResult<CoordinatorKey,Map<MemberIdentity,Errors>> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#73]]]
-handleGroupError(CoordinatorKey;Errors;Map<CoordinatorKey,Throwable>;Set<CoordinatorKey>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/admin/internals/RemoveMembersFromConsumerGroupHandler.java.html#102]]]
} 
@enduml
