@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.streams.KafkaStreams
class org.apache.kafka.streams.KafkaStreams {
+  waitOnState(State;long)
+  setState(State)
+  state()
+  isRunningOrRebalancing()
+  hasStartedOrFinishedShuttingDown()
+  validateIsRunningOrRebalancing()
+  setStateListener(KafkaStreams.StateListener)
+  setUncaughtExceptionHandler(Thread.UncaughtExceptionHandler)
+  setUncaughtExceptionHandler(StreamsUncaughtExceptionHandler)
+  defaultStreamsUncaughtExceptionHandler(Throwable;boolean)
+  replaceStreamThread(Throwable)
+  wrappedExceptionIsIn(Throwable;Set<Class<?extendsThrowable>>)
+  getActionForThrowable(Throwable;StreamsUncaughtExceptionHandler)
+  handleStreamsUncaughtException(Throwable;StreamsUncaughtExceptionHandler;boolean)
+  setGlobalStateRestoreListener(StateRestoreListener)
+  metrics()
+  KafkaStreams(Topology;Properties)
+  KafkaStreams(Topology;Properties;KafkaClientSupplier)
+  KafkaStreams(Topology;Properties;Time)
+  KafkaStreams(Topology;Properties;KafkaClientSupplier;Time)
+  KafkaStreams(Topology;StreamsConfig)
+  KafkaStreams(Topology;StreamsConfig;KafkaClientSupplier)
+  KafkaStreams(Topology;StreamsConfig;Time)
+  KafkaStreams(Topology;StreamsConfig;KafkaClientSupplier;Time)
+  KafkaStreams(TopologyMetadata;StreamsConfig;KafkaClientSupplier)
+  KafkaStreams(TopologyMetadata;StreamsConfig;KafkaClientSupplier;Time)
+  createAndAddStreamThread(long;long;int)
+  getMetrics(StreamsConfig;Time;String)
+  addStreamThread()
+  removeStreamThread()
+  removeStreamThread(Duration)
+  removeStreamThread(long)
+  getNumLiveStreamThreads()
+  getNextThreadIndex()
+  getThreadCacheAndBufferMemoryString()
+  resizeThreadCacheAndBufferMemory(int)
+  setupStateDirCleaner()
+  maybeCreateRocksDBMetricsRecordingService(String;StreamsConfig)
+  parseHostInfo(String)
+  start()
+  close()
+  shutdownHelper(boolean)
+  close(long)
+  closeToError()
+  close(Duration)
+  close(CloseOptions)
+  cleanUp()
+  allMetadata()
+  metadataForAllStreamsClients()
+  allMetadataForStore(String)
+  streamsMetadataForStore(String)
+  pause()
+  isPaused()
+  resume()
+  processStreamThread(Consumer<StreamThread>)
+  localThreadsMetadata()
+  metadataForLocalThreads()
+  allLocalStorePartitionLags()
+  allLocalStorePartitionLags(List<Task>)
} 
@enduml
