@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.LagInfo"
class org.apache.kafka.streams.LagInfo {
LagInfo(long;long) : LagInfo [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#33]]]
+currentOffsetPosition() : long [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#45]]]
+endOffsetPosition() : long [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#54]]]
+offsetLag() : long [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#63]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#68]]]
+hashCode() : int [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#79]]]
+toString() : String [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/LagInfo.java.html#84]]]
} 
@enduml
