@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.StreamsMetadata"
class org.apache.kafka.streams.StreamsMetadata {
hostInfo() : HostInfo [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#35]]]
stateStoreNames() : Set<String> [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#42]]]
topicPartitions() : Set<TopicPartition> [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#49]]]
standbyTopicPartitions() : Set<TopicPartition> [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#56]]]
standbyStateStoreNames() : Set<String> [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#63]]]
host() : String [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#72]]]
port() : int [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#81]]]
equals(Object) : boolean [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#90]]]
hashCode() : int [[[./../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/StreamsMetadata.java.html#102]]]
} 
@enduml
