@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.TopologyDescription
class org.apache.kafka.streams.TopologyDescription {
+  subtopologies()
+  globalStores()
} 
@enduml
