@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.Topology
class org.apache.kafka.streams.Topology {
+  Topology()
+  Topology(TopologyConfig)
+  Topology(InternalTopologyBuilder)
+  addSource(String;String...)
+  addSource(String;Pattern)
+  addSource(AutoOffsetReset;String;String...)
+  addSource(AutoOffsetReset;String;Pattern)
+  addSource(TimestampExtractor;String;String...)
+  addSource(TimestampExtractor;String;Pattern)
+  addSource(AutoOffsetReset;TimestampExtractor;String;String...)
+  addSource(AutoOffsetReset;TimestampExtractor;String;Pattern)
+  addSource(String;Deserializer<?>;Deserializer<?>;String...)
+  addSource(String;Deserializer<?>;Deserializer<?>;Pattern)
+  addSource(AutoOffsetReset;String;Deserializer<?>;Deserializer<?>;String...)
+  addSource(AutoOffsetReset;String;Deserializer<?>;Deserializer<?>;Pattern)
+  addSource(AutoOffsetReset;String;TimestampExtractor;Deserializer<?>;Deserializer<?>;String...)
+  addSource(AutoOffsetReset;String;TimestampExtractor;Deserializer<?>;Deserializer<?>;Pattern)
+  addSink(String;String;String...)
+  addProcessor(String;org.apache.kafka.streams.processor.ProcessorSupplier;String...)
+  addStateStore(StoreBuilder<?>;String...)
+  connectProcessorAndStateStores(String;String...)
+  describe()
} 
@enduml
