@startuml
!pragma layout smetana
"GraphNode" <|-- "org.apache.kafka.streams.kstream.internals.graph.BaseJoinProcessorNode"
class org.apache.kafka.streams.kstream.internals.graph.BaseJoinProcessorNode {
BaseJoinProcessorNode(String;ValueJoinerWithKey<?superK,?superV1,?superV2,?extendsVR>;ProcessorParameters<K,V1,?,?>;ProcessorParameters<K,V2,?,?>;ProcessorParameters<K,VR,?,?>;String;String) : BaseJoinProcessorNode [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#36]]]
thisProcessorParameters() : ProcessorParameters<K,V1,?,?> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#54]]]
otherProcessorParameters() : ProcessorParameters<K,V2,?,?> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#58]]]
mergeProcessorParameters() : ProcessorParameters<K,VR,?,?> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#62]]]
thisJoinSideNodeName() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#66]]]
otherJoinSideNodeName() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#70]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/BaseJoinProcessorNode.java.html#75]]]
} 
@enduml
