@startuml
!pragma layout smetana
"StateStoreNode<S>" <|-- "org.apache.kafka.streams.kstream.internals.graph.GlobalStoreNode"
class org.apache.kafka.streams.kstream.internals.graph.GlobalStoreNode {
+GlobalStoreNode(StoreBuilder<S>;String;String;ConsumedInternal<KIn,VIn>;String;ProcessorSupplier<KIn,VIn,Void,Void>) : GlobalStoreNode [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/GlobalStoreNode.java.html#19]]]
+writeToTopology(InternalTopologyBuilder) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/GlobalStoreNode.java.html#35]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/GlobalStoreNode.java.html#49]]]
} 
@enduml
