@startuml
!pragma layout smetana
BaseRepartitionNode_K,V_ <|-- org.apache.kafka.streams.kstream.internals.graph.OptimizableRepartitionNode
class org.apache.kafka.streams.kstream.internals.graph.OptimizableRepartitionNode {
+  OptimizableRepartitionNode(String;String;ProcessorParameters<K,V,?,?>;Serde<K>;Serde<V>;String;String;StreamPartitioner<K,V>)
+  keySerde()
+  valueSerde()
+  repartitionTopic()
+  toString()
+  writeToTopology(InternalTopologyBuilder)
} 
@enduml
