@startuml
!pragma layout smetana
"SourceGraphNode<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.graph.StreamSourceNode"
class org.apache.kafka.streams.kstream.internals.graph.StreamSourceNode {
+StreamSourceNode(String;Collection<String>;ConsumedInternal<K,V>) : StreamSourceNode [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java.html#34]]]
+StreamSourceNode(String;Pattern;ConsumedInternal<K,V>) : StreamSourceNode [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java.html#40]]]
+merge(StreamSourceNode<?,?>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java.html#47]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java.html#63]]]
+writeToTopology(InternalTopologyBuilder) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java.html#72]]]
} 
@enduml
