@startuml
!pragma layout smetana
"BaseRepartitionNode<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.graph.UnoptimizableRepartitionNode"
class org.apache.kafka.streams.kstream.internals.graph.UnoptimizableRepartitionNode {
-UnoptimizableRepartitionNode(String;String;ProcessorParameters<K,V,?,?>;Serde<K>;Serde<V>;String;String;StreamPartitioner<K,V>;InternalTopicProperties) : UnoptimizableRepartitionNode [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/UnoptimizableRepartitionNode.java.html#30]]]
+writeToTopology(InternalTopologyBuilder) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/UnoptimizableRepartitionNode.java.html#53]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/UnoptimizableRepartitionNode.java.html#78]]]
} 
@enduml
