@startuml
!pragma layout smetana
Closeable <|-- org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient
class org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient {
+  ConsumerNetworkClient(LogContext;KafkaClient;Metadata;Time;long;int;int)
+  defaultRequestTimeoutMs()
+  send(Node;AbstractRequest.Builder<?>)
+  send(Node;AbstractRequest.Builder<?>;int)
+  leastLoadedNode()
+  hasReadyNodes(long)
+  awaitMetadataUpdate(Timer)
+  ensureFreshMetadata(Timer)
+  wakeup()
+  poll(RequestFuture<?>)
+  poll(RequestFuture<?>;Timer)
+  poll(Timer)
+  poll(Timer;PollCondition)
+  poll(Timer;PollCondition;boolean)
+  pollNoWakeup()
+  transmitSends()
+  awaitPendingRequests(Node;Timer)
+  pendingRequestCount(Node)
+  hasPendingRequests(Node)
+  pendingRequestCount()
+  hasPendingRequests()
+  firePendingCompletedRequests()
+  checkDisconnects(long)
+  handlePendingDisconnects()
+  disconnectAsync(Node)
+  failExpiredRequests(long)
+  failUnsentRequests(Node;RuntimeException)
+  trySend(long)
+  maybeTriggerWakeup()
+  maybeThrowInterruptException()
+  disableWakeups()
+  close()
+  isUnavailable(Node)
+  maybeThrowAuthFailure(Node)
+  tryConnect(Node)
} 
@enduml
