@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.consumer.internals.FetcherMetricsRegistry"
class org.apache.kafka.clients.consumer.internals.FetcherMetricsRegistry {
+FetcherMetricsRegistry() : FetcherMetricsRegistry [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/FetcherMetricsRegistry.java.html#59]]]
+FetcherMetricsRegistry(String) : FetcherMetricsRegistry [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/FetcherMetricsRegistry.java.html#63]]]
+FetcherMetricsRegistry(Set<String>;String) : FetcherMetricsRegistry [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/FetcherMetricsRegistry.java.html#67]]]
+getAllTemplates() : List<MetricNameTemplate> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/FetcherMetricsRegistry.java.html#148]]]
} 
@enduml
