@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.clients.consumer.internals.KafkaConsumerMetrics"
class org.apache.kafka.clients.consumer.internals.KafkaConsumerMetrics {
+KafkaConsumerMetrics(Metrics;String) : KafkaConsumerMetrics [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#40]]]
+recordPollStart(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#91]]]
+recordPollEnd(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#98]]]
+recordCommitSync(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#104]]]
+recordCommitted(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#108]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/KafkaConsumerMetrics.java.html#113]]]
} 
@enduml
