@startuml
!pragma layout smetana
AsyncClient_Map_TopicPartition,SubscriptionState.FetchPosition_,OffsetsForLeaderEpochRequest,OffsetsForLeaderEpochResponse,OffsetsForLeaderEpochClient.OffsetForEpochResult_ <|-- org.apache.kafka.clients.consumer.internals.OffsetsForLeaderEpochClient
class org.apache.kafka.clients.consumer.internals.OffsetsForLeaderEpochClient {
+  OffsetsForLeaderEpochClient(ConsumerNetworkClient;LogContext)
+  prepareRequest(Node;Map<TopicPartition,SubscriptionState.FetchPosition>)
+  handleResponse(Node;Map<TopicPartition,SubscriptionState.FetchPosition>;OffsetsForLeaderEpochResponse)
} 
@enduml
