@startuml
!pragma layout smetana
"AsyncClient<Map<TopicPartition,SubscriptionState.FetchPosition>,OffsetsForLeaderEpochRequest,OffsetsForLeaderEpochResponse,OffsetsForLeaderEpochClient.OffsetForEpochResult>" <|-- "org.apache.kafka.clients.consumer.internals.OffsetsForLeaderEpochClient"
class org.apache.kafka.clients.consumer.internals.OffsetsForLeaderEpochClient {
OffsetsForLeaderEpochClient(ConsumerNetworkClient;LogContext) : OffsetsForLeaderEpochClient [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/OffsetsForLeaderEpochClient.java.html#48]]]
prepareRequest(Node;Map<TopicPartition,SubscriptionState.FetchPosition>) : AbstractRequest.Builder<OffsetsForLeaderEpochRequest> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/OffsetsForLeaderEpochClient.java.html#53]]]
handleResponse(Node;Map<TopicPartition,SubscriptionState.FetchPosition>;OffsetsForLeaderEpochResponse) : OffsetForEpochResult [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/OffsetsForLeaderEpochClient.java.html#75]]]
} 
@enduml
