@startuml
!pragma layout smetana
"ConsumerNetworkClient.PollCondition" <|-- "org.apache.kafka.clients.consumer.internals.RequestFuture"
class org.apache.kafka.clients.consumer.internals.RequestFuture {
+isDone() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#22]]]
+awaitDone(long;TimeUnit) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#26]]]
+value() : T [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#32]]]
+succeeded() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#39]]]
+failed() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#44]]]
+isRetriable() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#49]]]
+exception() : RuntimeException [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#54]]]
+complete(T) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#61]]]
+raise(RuntimeException) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#75]]]
+raise(Errors) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#90]]]
-fireSuccess() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#94]]]
-fireFailure() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#104]]]
+addListener(RequestFutureListener<T>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#115]]]
+chain(RequestFuture<T>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#140]]]
+voidSuccess() : RequestFuture<Void> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#160]]]
+shouldBlock() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestFuture.java.html#175]]]
} 
@enduml
