@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.consumer.internals.SubscriptionState"
class org.apache.kafka.clients.consumer.internals.SubscriptionState {
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#108]]]
+prettyString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#118]]]
+SubscriptionState(LogContext;OffsetResetStrategy) : SubscriptionState [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#133]]]
assignmentId() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#149]]]
-setSubscriptionType(SubscriptionType) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#159]]]
+subscribe(Set<String>;ConsumerRebalanceListener) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#166]]]
+subscribe(Pattern;ConsumerRebalanceListener) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#172]]]
+subscribeFromPattern(Set<String>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#178]]]
-changeSubscription(Set<String>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#186]]]
groupSubscribe(Collection<String>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#201]]]
resetGroupSubscription() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#211]]]
+assignFromUser(Set<TopicPartition>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#220]]]
+checkAssignmentMatchedSubscription(Collection<TopicPartition>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#247]]]
+assignFromSubscribed(Collection<TopicPartition>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#273]]]
-registerRebalanceListener(ConsumerRebalanceListener) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#289]]]
hasPatternSubscription() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#299]]]
+hasNoSubscriptionOrUserAssignment() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#303]]]
+unsubscribe() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#307]]]
matchesSubscribedPattern(String) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#321]]]
+subscription() : Set<String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#328]]]
+pausedPartitions() : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#334]]]
metadataTopics() : Set<String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#349]]]
needsMetadata(String) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#363]]]
-assignedState(TopicPartition) : TopicPartitionState [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#367]]]
-assignedStateOrNull(TopicPartition) : TopicPartitionState [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#374]]]
+seekValidated(TopicPartition;FetchPosition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#378]]]
+seek(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#382]]]
+seekUnvalidated(TopicPartition;FetchPosition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#386]]]
maybeSeekUnvalidated(TopicPartition;FetchPosition;OffsetResetStrategy) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#390]]]
+assignedPartitions() : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#407]]]
+assignedPartitionsList() : List<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#414]]]
numAssignedPartitions() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#422]]]
+fetchablePartitions(Predicate<TopicPartition>) : List<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#427]]]
+hasAutoAssignedPartitions() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#439]]]
+position(TopicPartition;FetchPosition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#443]]]
+maybeValidatePositionForCurrentLeader(ApiVersions;TopicPartition;Metadata.LeaderAndEpoch) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#456]]]
+maybeCompleteValidation(TopicPartition;FetchPosition;EpochEndOffset) : Optional<LogTruncation> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#477]]]
+awaitingValidation(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#525]]]
+completeValidation(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#529]]]
+validPosition(TopicPartition) : FetchPosition [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#533]]]
+position(TopicPartition) : FetchPosition [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#537]]]
+partitionLag(TopicPartition;IsolationLevel) : Long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#541]]]
+partitionEndOffset(TopicPartition;IsolationLevel) : Long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#552]]]
+requestPartitionEndOffset(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#561]]]
+partitionEndOffsetRequested(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#566]]]
partitionLead(TopicPartition) : Long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#571]]]
updateHighWatermark(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#576]]]
updateLogStartOffset(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#580]]]
updateLastStableOffset(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#584]]]
+updatePreferredReadReplica(TopicPartition;int;LongSupplier) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#596]]]
+preferredReadReplica(TopicPartition;long) : Optional<Integer> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#607]]]
+clearPreferredReadReplica(TopicPartition) : Optional<Integer> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#622]]]
+allConsumed() : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#626]]]
+requestOffsetReset(TopicPartition;OffsetResetStrategy) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#636]]]
+requestOffsetReset(Collection<TopicPartition>;OffsetResetStrategy) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#640]]]
+requestOffsetReset(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#647]]]
setNextAllowedRetry(Set<TopicPartition>;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#651]]]
hasDefaultOffsetResetPolicy() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#657]]]
+isOffsetResetNeeded(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#661]]]
+resetStrategy(TopicPartition) : OffsetResetStrategy [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#665]]]
+hasAllFetchPositions() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#669]]]
+initializingPartitions() : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#680]]]
-collectPartitions(Predicate<TopicPartitionState>) : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#684]]]
+resetInitializingPositions() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#695]]]
+partitionsNeedingReset(long) : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#710]]]
+partitionsNeedingValidation(long) : Set<TopicPartition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#714]]]
+isAssigned(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#718]]]
+isPaused(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#722]]]
isFetchable(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#727]]]
+hasValidPosition(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#732]]]
+pause(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#737]]]
+resume(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#741]]]
requestFailed(Set<TopicPartition>;long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#745]]]
movePartitionToEnd(TopicPartition) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#755]]]
+rebalanceListener() : ConsumerRebalanceListener [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/internals/SubscriptionState.java.html#759]]]
} 
@enduml
