@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.consumer.internals.SubscriptionState
class org.apache.kafka.clients.consumer.internals.SubscriptionState {
+  toString()
+  prettyString()
+  SubscriptionState(LogContext;OffsetResetStrategy)
+  assignmentId()
+  setSubscriptionType(SubscriptionType)
+  subscribe(Set<String>;ConsumerRebalanceListener)
+  subscribe(Pattern;ConsumerRebalanceListener)
+  subscribeFromPattern(Set<String>)
+  changeSubscription(Set<String>)
+  groupSubscribe(Collection<String>)
+  resetGroupSubscription()
+  assignFromUser(Set<TopicPartition>)
+  checkAssignmentMatchedSubscription(Collection<TopicPartition>)
+  assignFromSubscribed(Collection<TopicPartition>)
+  registerRebalanceListener(ConsumerRebalanceListener)
+  hasPatternSubscription()
+  hasNoSubscriptionOrUserAssignment()
+  unsubscribe()
+  matchesSubscribedPattern(String)
+  subscription()
+  pausedPartitions()
+  metadataTopics()
+  needsMetadata(String)
+  assignedState(TopicPartition)
+  assignedStateOrNull(TopicPartition)
+  seekValidated(TopicPartition;FetchPosition)
+  seek(TopicPartition;long)
+  seekUnvalidated(TopicPartition;FetchPosition)
+  maybeSeekUnvalidated(TopicPartition;FetchPosition;OffsetResetStrategy)
+  assignedPartitions()
+  assignedPartitionsList()
+  numAssignedPartitions()
+  fetchablePartitions(Predicate<TopicPartition>)
+  hasAutoAssignedPartitions()
+  position(TopicPartition;FetchPosition)
+  maybeValidatePositionForCurrentLeader(ApiVersions;TopicPartition;Metadata.LeaderAndEpoch)
+  maybeCompleteValidation(TopicPartition;FetchPosition;EpochEndOffset)
+  awaitingValidation(TopicPartition)
+  completeValidation(TopicPartition)
+  validPosition(TopicPartition)
+  position(TopicPartition)
+  partitionLag(TopicPartition;IsolationLevel)
+  partitionEndOffset(TopicPartition;IsolationLevel)
+  requestPartitionEndOffset(TopicPartition)
+  partitionEndOffsetRequested(TopicPartition)
+  partitionLead(TopicPartition)
+  updateHighWatermark(TopicPartition;long)
+  updateLogStartOffset(TopicPartition;long)
+  updateLastStableOffset(TopicPartition;long)
+  updatePreferredReadReplica(TopicPartition;int;LongSupplier)
+  preferredReadReplica(TopicPartition;long)
+  clearPreferredReadReplica(TopicPartition)
+  allConsumed()
+  requestOffsetReset(TopicPartition;OffsetResetStrategy)
+  requestOffsetReset(Collection<TopicPartition>;OffsetResetStrategy)
+  requestOffsetReset(TopicPartition)
+  setNextAllowedRetry(Set<TopicPartition>;long)
+  hasDefaultOffsetResetPolicy()
+  isOffsetResetNeeded(TopicPartition)
+  resetStrategy(TopicPartition)
+  hasAllFetchPositions()
+  initializingPartitions()
+  collectPartitions(Predicate<TopicPartitionState>)
+  resetInitializingPositions()
+  partitionsNeedingReset(long)
+  partitionsNeedingValidation(long)
+  isAssigned(TopicPartition)
+  isPaused(TopicPartition)
+  isFetchable(TopicPartition)
+  hasValidPosition(TopicPartition)
+  pause(TopicPartition)
+  resume(TopicPartition)
+  requestFailed(Set<TopicPartition>;long)
+  movePartitionToEnd(TopicPartition)
+  rebalanceListener()
} 
@enduml
