@startuml
!pragma layout smetana
"EpochState" <|-- "org.apache.kafka.raft.CandidateState"
class org.apache.kafka.raft.CandidateState {
CandidateState(Time;int;int;Set<Integer>;Optional<LogOffsetMetadata>;int;int;LogContext) : CandidateState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#51]]]
+localId() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#77]]]
+majoritySize() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#81]]]
-numGranted() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#85]]]
-numUnrecorded() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#89]]]
+isBackingOff() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#96]]]
+retries() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#100]]]
+isVoteGranted() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#109]]]
+isVoteRejected() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#119]]]
+recordGrantedVote(int) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#131]]]
+recordRejectedVote(int) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#150]]]
+startBackingOff(long;long) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#165]]]
+unrecordedVoters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#176]]]
+grantingVoters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#185]]]
+rejectingVoters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#194]]]
-votersInState(State) : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#198]]]
+hasElectionTimeoutExpired(long) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#205]]]
+isBackoffComplete(long) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#210]]]
+remainingBackoffMs(long) : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#215]]]
+remainingElectionTimeMs(long) : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#223]]]
+election() : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#229]]]
+epoch() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#234]]]
+highWatermark() : Optional<LogOffsetMetadata> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#239]]]
+canGrantVote(int;boolean) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#244]]]
+toString() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#253]]]
+name() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#263]]]
+close() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/CandidateState.java.html#268]]]
} 
@enduml
