@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.raft.ElectionState"
class org.apache.kafka.raft.ElectionState {
ElectionState(int;OptionalInt;OptionalInt;Set<Integer>) : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#31]]]
+withVotedCandidate(int;int;Set<Integer>) : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#41]]]
+withElectedLeader(int;int;Set<Integer>) : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#49]]]
+withUnknownLeader(int;Set<Integer>) : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#57]]]
+isLeader(int) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#61]]]
+isVotedCandidate(int) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#67]]]
+leaderId() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#73]]]
+votedId() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#79]]]
+voters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#85]]]
+hasLeader() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#89]]]
+hasVoted() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#93]]]
+toString() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#99]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#107]]]
+hashCode() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ElectionState.java.html#119]]]
} 
@enduml
