@startuml
!pragma layout smetana
"QuorumStateStore" <|-- "org.apache.kafka.raft.FileBasedStateStore"
class org.apache.kafka.raft.FileBasedStateStore {
+FileBasedStateStore(File) : FileBasedStateStore [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#67]]]
-readStateFromFile(File) : QuorumStateData [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#71]]]
+readElectionState() : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#105]]]
+writeElectionState(ElectionState) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#122]]]
-voters(Set<Integer>) : List<Voter> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#131]]]
-writeElectionStateToFile(File;QuorumStateData) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#136]]]
+clear() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#167]]]
+toString() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#173]]]
-deleteFileIfExists(File) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java.html#177]]]
} 
@enduml
