@startuml
!pragma layout smetana
EpochState <|-- org.apache.kafka.raft.LeaderState
class org.apache.kafka.raft.LeaderState {
LeaderState(int;int;long;Set<Integer>;Set<Integer>;BatchAccumulator<T>;LogContext) : LeaderState [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#41]]]
+ accumulator() : BatchAccumulator<T> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#64]]]
- convertToVoters(Set<Integer>) : List<Voter> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#68]]]
+ appendLeaderChangeMessage(long) : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#74]]]
+ isResignRequested() : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#88]]]
+ requestResign() : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#92]]]
+ highWatermark() : Optional<LogOffsetMetadata> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#97]]]
+ election() : ElectionState [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#102]]]
+ epoch() : int [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#107]]]
+ grantingVoters() : Set<Integer> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#111]]]
+ localId() : int [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#115]]]
+ nonAcknowledgingVoters() : Set<Integer> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#119]]]
- updateHighWatermark() : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#128]]]
+ updateLocalState(long;LogOffsetMetadata) : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#186]]]
+ updateReplicaState(int;long;LogOffsetMetadata) : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#191]]]
+ nonLeaderVotersByDescendingFetchOffset() : List<Integer> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#205]]]
- followersByDescendingFetchOffset() : List<ReplicaState> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#212]]]
- updateEndOffset(ReplicaState;LogOffsetMetadata) : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#218]]]
+ addAcknowledgementFrom(int) : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#237]]]
- ensureValidVoter(int) : ReplicaState [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#242]]]
+ epochStartOffset() : long [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#249]]]
- getReplicaState(int) : ReplicaState [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#253]]]
getVoterEndOffsets() : Map<Integer,Long> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#262]]]
getObserverStates(long) : Map<Integer,Long> [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#266]]]
- clearInactiveObservers(long) : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#280]]]
- isVoter(int) : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#287]]]
+ canGrantVote(int;boolean) : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#335]]]
+ toString() : String [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#342]]]
+ name() : String [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#354]]]
+ close() : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/LeaderState.java.html#359]]]
} 
@enduml
