@startuml
!pragma layout smetana
"Comparable<OffsetAndEpoch>" <|-- "org.apache.kafka.raft.OffsetAndEpoch"
class org.apache.kafka.raft.OffsetAndEpoch {
+OffsetAndEpoch(long;int) : OffsetAndEpoch [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/OffsetAndEpoch.java.html#23]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/OffsetAndEpoch.java.html#29]]]
+hashCode() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/OffsetAndEpoch.java.html#40]]]
+toString() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/OffsetAndEpoch.java.html#47]]]
+compareTo(OffsetAndEpoch) : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/OffsetAndEpoch.java.html#55]]]
} 
@enduml
