@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.raft.QuorumState
class org.apache.kafka.raft.QuorumState {
+  QuorumState(OptionalInt;Set<Integer>;int;int;QuorumStateStore;Time;LogContext;Random)
+  initialize(OffsetAndEpoch)
+  remoteVoters()
+  localIdOrSentinel()
+  localIdOrThrow()
+  localId()
+  epoch()
+  leaderIdOrSentinel()
+  highWatermark()
+  leaderId()
+  hasLeader()
+  hasRemoteLeader()
+  isVoter()
+  isVoter(int)
+  isObserver()
+  transitionToResigned(List<Integer>)
+  transitionToUnattached(int)
+  transitionToVoted(int;int)
+  transitionToFollower(int;int)
+  transitionToCandidate()
+  transitionTo(EpochState)
+  randomElectionTimeoutMs()
+  canGrantVote(int;boolean)
+  followerStateOrThrow()
+  votedStateOrThrow()
+  unattachedStateOrThrow()
+  resignedStateOrThrow()
+  candidateStateOrThrow()
+  leaderAndEpoch()
+  isFollower()
+  isVoted()
+  isUnattached()
+  isLeader()
+  isResigned()
+  isCandidate()
} 
@enduml
