@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.raft.QuorumState"
class org.apache.kafka.raft.QuorumState {
+QuorumState(OptionalInt;Set<Integer>;int;int;QuorumStateStore;Time;LogContext;Random) : QuorumState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#90]]]
+initialize(OffsetAndEpoch) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#109]]]
+remoteVoters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#215]]]
+localIdOrSentinel() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#219]]]
+localIdOrThrow() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#223]]]
+localId() : OptionalInt [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#227]]]
+epoch() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#231]]]
+leaderIdOrSentinel() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#235]]]
+highWatermark() : Optional<LogOffsetMetadata> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#239]]]
+leaderId() : OptionalInt [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#243]]]
+hasLeader() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#252]]]
+hasRemoteLeader() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#256]]]
+isVoter() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#260]]]
+isVoter(int) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#264]]]
+isObserver() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#268]]]
+transitionToResigned(List<Integer>) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#272]]]
+transitionToUnattached(int) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#296]]]
+transitionToVoted(int;int) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#332]]]
+transitionToFollower(int;int) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#373]]]
+transitionToCandidate() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#406]]]
-transitionTo(EpochState) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#467]]]
-randomElectionTimeoutMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#482]]]
+canGrantVote(int;boolean) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#488]]]
+followerStateOrThrow() : FollowerState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#492]]]
+votedStateOrThrow() : VotedState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#498]]]
+unattachedStateOrThrow() : UnattachedState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#504]]]
+resignedStateOrThrow() : ResignedState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#527]]]
+candidateStateOrThrow() : CandidateState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#533]]]
+leaderAndEpoch() : LeaderAndEpoch [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#539]]]
+isFollower() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#544]]]
+isVoted() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#548]]]
+isUnattached() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#552]]]
+isLeader() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#556]]]
+isResigned() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#560]]]
+isCandidate() : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/QuorumState.java.html#564]]]
} 
@enduml
