@startuml
!pragma layout smetana
"RaftMessage" <|-- "org.apache.kafka.raft.RaftRequest"
class org.apache.kafka.raft.RaftRequest {
+RaftRequest(int;ApiMessage;long) : RaftRequest [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java.html#28]]]
+correlationId() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java.html#35]]]
+data() : ApiMessage [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java.html#40]]]
+createdTimeMs() : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java.html#44]]]
} 
@enduml
