@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.raft.RaftConfig"
class org.apache.kafka.raft.RaftConfig {
+RaftConfig(AbstractConfig) : RaftConfig [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+RaftConfig(Map<Integer,AddressSpec>;int;int;int;int;int;int) : RaftConfig [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+requestTimeoutMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+retryBackoffMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+electionTimeoutMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+electionBackoffMaxMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+fetchTimeoutMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+appendLingerMs() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+quorumVoterIds() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+quorumVoterConnections() : Map<Integer,AddressSpec> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
-parseVoterId(String) : Integer [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+parseVoterConnections(List<String>) : Map<Integer,AddressSpec> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+quorumVoterStringsToNodes(List<String>) : List<Node> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
+voterConnectionsToNodes(Map<Integer,RaftConfig.AddressSpec>) : List<Node> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java.html#1]]]
} 
@enduml
