@startuml
!pragma layout smetana
"EpochState" <|-- "org.apache.kafka.raft.ResignedState"
class org.apache.kafka.raft.ResignedState {
+ResignedState(Time;int;int;Set<Integer>;long;List<Integer>;LogContext) : ResignedState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+election() : ElectionState [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+epoch() : int [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+unackedVoters() : Set<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+acknowledgeResignation(int) : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+hasElectionTimeoutExpired(long) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#135]]]
+remainingElectionTimeMs(long) : long [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
+preferredSuccessors() : List<Integer> [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
+canGrantVote(int;boolean) : boolean [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
+name() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
+toString() : String [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
+close() : void [[[./../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/ResignedState.java.html#1]]]
} 
@enduml
