@startuml
!pragma layout smetana
"Reconfigurable" <|-- "org.apache.kafka.server.metrics.KafkaYammerMetrics"
class org.apache.kafka.server.metrics.KafkaYammerMetrics {
+defaultRegistry() : MetricsRegistry [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#51]]]
-KafkaYammerMetrics() : KafkaYammerMetrics [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#59]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#65]]]
+reconfigurableConfigs() : Set<String> [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#70]]]
+validateReconfiguration(Map<String,?>) : void [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#75]]]
+reconfigure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#80]]]
+getMetricName(String;String;String) : MetricName [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#85]]]
+getMetricName(String;String;String;LinkedHashMap<String,String>) : MetricName [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#98]]]
-toMBeanName(LinkedHashMap<String,String>) : Optional<String> [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#121]]]
-toScope(Map<String,String>) : Optional<String> [[[./../../../../../../../../../.././qc/server-common/src/main/java/org/apache/kafka/server/metrics/KafkaYammerMetrics.java.html#156]]]
} 
@enduml
