@startuml
!pragma layout smetana
"AbstractLogin" <|-- "org.apache.kafka.common.security.authenticator.DefaultLogin"
class org.apache.kafka.common.security.authenticator.DefaultLogin {
+serviceName() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/authenticator/DefaultLogin.java.html#7]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/authenticator/DefaultLogin.java.html#12]]]
} 
@enduml
