@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.tools.TransactionsCommand"
class org.apache.kafka.tools.TransactionsCommand {
TransactionsCommand(Time) : TransactionsCommand [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#75]]]
name() : String [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#82]]]
addSubparser(Subparsers) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#87]]]
execute(Admin;Namespace;PrintStream) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#92]]]
-appendColumnValue(StringBuilder;String;int) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#906]]]
-printRow(List<Integer>;String[];PrintStream) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#917]]]
-prettyPrintTable(String[];List<String[]>;PrintStream) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#932]]]
-printErrorAndExit(String;Throwable) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#951]]]
-printErrorAndExit(String) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#960]]]
-buildAdminClient(Namespace) : Admin [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#965]]]
buildBaseParser() : ArgumentParser [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#986]]]
execute(String[];Function<Namespace,Admin>;PrintStream;Time) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#1015]]]
+main(String[]) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionsCommand.java.html#1062]]]
} 
@enduml
