@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.tools.TransactionalMessageCopier"
class org.apache.kafka.tools.TransactionalMessageCopier {
-argParser() : ArgumentParser [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#70]]]
-createProducer(Namespace) : KafkaProducer<String,String> [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#179]]]
-createConsumer(Namespace) : KafkaConsumer<String,String> [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#197]]]
-producerRecordFromConsumerRecord(String;ConsumerRecord<String,String>) : ProducerRecord<String,String> [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#221]]]
-consumerPositions(KafkaConsumer<String,String>) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#225]]]
-resetToLastCommittedPositions(KafkaConsumer<String,String>) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#233]]]
-messagesRemaining(KafkaConsumer<String,String>;TopicPartition) : long [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#244]]]
-toJsonString(Map<String,Object>) : String [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#253]]]
-statusAsJson(String;long;long;long;String) : String [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#264]]]
-abortTransactionAndResetPosition(KafkaProducer<String,String>;KafkaConsumer<String,String>) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#281]]]
+main(String[]) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#289]]]
+runEventLoop(Namespace) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java.html#302]]]
} 
@enduml
