@startuml
!pragma layout smetana
"Closeable" <|-- "org.apache.kafka.tools.VerifiableConsumer"
class org.apache.kafka.tools.VerifiableConsumer {
+VerifiableConsumer(KafkaConsumer<String,String>;PrintStream;String;int;boolean;boolean;boolean) : VerifiableConsumer [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#102]]]
-addKafkaSerializerModule() : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#119]]]
-hasMessageLimit() : boolean [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#133]]]
-isFinished() : boolean [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#137]]]
-onRecordsReceived(ConsumerRecords<String,String>) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#141]]]
+onComplete(Map<TopicPartition,OffsetAndMetadata>;Exception) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#177]]]
+onPartitionsAssigned(Collection<TopicPartition>) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#194]]]
+onPartitionsRevoked(Collection<TopicPartition>) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#199]]]
-printJson(Object) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#203]]]
+commitSync(Map<TopicPartition,OffsetAndMetadata>) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#211]]]
+run() : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#226]]]
+close() : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#255]]]
-argParser() : ArgumentParser [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#502]]]
+createFromArgs(ArgumentParser;String[]) : VerifiableConsumer [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#605]]]
+main(String[]) : void [[[./../../../../../../../../.././qc/tools/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java.html#662]]]
} 
@enduml
