@startuml
!pragma layout smetana
"DocumentedType" <|-- "org.apache.kafka.common.protocol.types.TaggedFields"
class org.apache.kafka.common.protocol.types.TaggedFields {
+of(Object...) : TaggedFields [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#44]]]
+TaggedFields(Map<Integer,Field>) : TaggedFields [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#58]]]
+isNullable() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#63]]]
+write(ByteBuffer;Object) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#69]]]
+read(ByteBuffer) : NavigableMap<Integer,Object> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#89]]]
+sizeOf(Object) : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#117]]]
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#137]]]
+validate(Object) : Map<Integer,Object> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#151]]]
+typeName() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#173]]]
+documentation() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#178]]]
+numFields() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/TaggedFields.java.html#185]]]
} 
@enduml
