@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.protocol.types.Type"
class org.apache.kafka.common.protocol.types.Type {
+write(ByteBuffer;Object) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#38]]]
+read(ByteBuffer) : Object [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#45]]]
+validate(Object) : Object [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#52]]]
+sizeOf(Object) : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#57]]]
+isNullable() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#63]]]
+arrayElementType() : Optional<Type> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#70]]]
+isArray() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#77]]]
-toHtml() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#1100]]]
+main(String[]) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/protocol/types/Type.java.html#1127]]]
} 
@enduml
