@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.security.JaasContext"
class org.apache.kafka.common.security.JaasContext {
+loadServerContext(ListenerName;String;Map<String,?>) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#27]]]
+loadClientContext(Map<String,?>) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#40]]]
load(JaasContext.Type;String;String;Password) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#45]]]
-defaultContext(JaasContext.Type;String;String) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#59]]]
+JaasContext(String;Type;Configuration;Password) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#106]]]
+name() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#117]]]
+type() : Type [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#121]]]
+configuration() : Configuration [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#125]]]
+configurationEntries() : List<AppConfigurationEntry> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#129]]]
+dynamicJaasConfig() : Password [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#133]]]
+configEntryOption(List<AppConfigurationEntry>;String;String) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#138]]]
} 
@enduml
