@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.security.JaasContext"
class org.apache.kafka.common.security.JaasContext {
+loadServerContext(ListenerName;String;Map<String,?>) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#60]]]
+loadClientContext(Map<String,?>) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#80]]]
load(JaasContext.Type;String;String;Password) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#85]]]
-defaultContext(JaasContext.Type;String;String) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#99]]]
+JaasContext(String;Type;Configuration;Password) : JaasContext [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#149]]]
+name() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#160]]]
+type() : Type [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#164]]]
+configuration() : Configuration [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#168]]]
+configurationEntries() : List<AppConfigurationEntry> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#172]]]
+dynamicJaasConfig() : Password [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#176]]]
+configEntryOption(List<AppConfigurationEntry>;String;String) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/JaasContext.java.html#184]]]
} 
@enduml
