@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.scram.internals.ScramCredentialUtils
class org.apache.kafka.common.security.scram.internals.ScramCredentialUtils {
- ScramCredentialUtils() : ScramCredentialUtils [[[././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramCredentialUtils.java.html#18]]]
+ credentialToString(ScramCredential) : String [[[././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramCredentialUtils.java.html#20]]]
+ credentialFromString(String) : ScramCredential [[[././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramCredentialUtils.java.html#32]]]
- toProps(String) : Properties [[[././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramCredentialUtils.java.html#45]]]
+ createCache(CredentialCache;Collection<String>) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramCredentialUtils.java.html#57]]]
} 
@enduml
