@startuml
!pragma layout smetana
"SaslServer" <|-- "org.apache.kafka.common.security.scram.internals.ScramSaslServer"
class org.apache.kafka.common.security.scram.internals.ScramSaslServer {
+ScramSaslServer(ScramMechanism;Map<String,?>;CallbackHandler) : ScramSaslServer [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#81]]]
+evaluateResponse(byte[]) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#98]]]
+getAuthorizationID() : String [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#174]]]
+getMechanismName() : String [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#181]]]
+getNegotiatedProperty(String) : Object [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#186]]]
+isComplete() : boolean [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#198]]]
+unwrap(byte[];int;int) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#203]]]
+wrap(byte[];int;int) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#210]]]
+dispose() : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#217]]]
-setState(State) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#220]]]
-verifyClientProof(ClientFinalMessage) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#225]]]
-clearCredentials() : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslServer.java.html#237]]]
} 
@enduml
