@startuml
!pragma layout smetana
"SaslExtensions" <|-- "org.apache.kafka.common.security.scram.internals.ScramExtensions"
class org.apache.kafka.common.security.scram.internals.ScramExtensions {
+ScramExtensions() : ScramExtensions [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramExtensions.java.html#28]]]
+ScramExtensions(String) : ScramExtensions [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramExtensions.java.html#32]]]
+ScramExtensions(Map<String,String>) : ScramExtensions [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramExtensions.java.html#36]]]
+tokenAuthenticated() : boolean [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramExtensions.java.html#40]]]
} 
@enduml
