@startuml
!pragma layout smetana
"SaslClient" <|-- "org.apache.kafka.common.security.scram.internals.ScramSaslClient"
class org.apache.kafka.common.security.scram.internals.ScramSaslClient {
+ScramSaslClient(ScramMechanism;CallbackHandler) : ScramSaslClient [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#75]]]
+getMechanismName() : String [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#83]]]
+hasInitialResponse() : boolean [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#88]]]
+evaluateChallenge(byte[]) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#93]]]
+isComplete() : boolean [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#156]]]
+unwrap(byte[];int;int) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#161]]]
+wrap(byte[];int;int) : byte[] [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#168]]]
+getNegotiatedProperty(String) : Object [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#175]]]
+dispose() : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#182]]]
-setState(State) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#185]]]
-handleServerFirstMessage(char[]) : ClientFinalMessage [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#190]]]
-handleServerFinalMessage(byte[]) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/internals/ScramSaslClient.java.html#204]]]
} 
@enduml
