@startuml
!pragma layout smetana
TaskWorker <|-- org.apache.kafka.trogdor.workload.ConnectionStressWorker
class org.apache.kafka.trogdor.workload.ConnectionStressWorker {
+  ConnectionStressWorker(String;ConnectionStressSpec)
+  start(Platform;WorkerStatusTracker;KafkaFutureImpl<String>)
+  stop(Platform)
} 
@enduml
