@startuml
!pragma layout smetana
TaskSpec <|-- org.apache.kafka.trogdor.workload.ConsumeBenchSpec
class org.apache.kafka.trogdor.workload.ConsumeBenchSpec {
+  ConsumeBenchSpec(long;long;String;String;int;long;String;Map<String,String>;Map<String,String>;Map<String,String>;Integer;Optional<RecordProcessor>;List<String>)
+  consumerNode()
+  consumerGroup()
+  bootstrapServers()
+  targetMessagesPerSec()
+  maxMessages()
+  threadsPerWorker()
+  recordProcessor()
+  consumerConf()
+  commonClientConf()
+  adminClientConf()
+  activeTopics()
+  newController(String)
+  newTaskWorker(String)
+  materializeTopics()
+  expandTopicName(String)
} 
@enduml
