@startuml
!pragma layout smetana
"FlushGenerator" <|-- "org.apache.kafka.trogdor.workload.GaussianFlushGenerator"
class org.apache.kafka.trogdor.workload.GaussianFlushGenerator {
+GaussianFlushGenerator(int;double) : GaussianFlushGenerator [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianFlushGenerator.java.html#63]]]
+messagesPerFlushAverage() : int [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianFlushGenerator.java.html#71]]]
+messagesPerFlushDeviation() : double [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianFlushGenerator.java.html#76]]]
-calculateFlushSize() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianFlushGenerator.java.html#80]]]
} 
@enduml
