@startuml
!pragma layout smetana
"ThroughputGenerator" <|-- "org.apache.kafka.trogdor.workload.GaussianThroughputGenerator"
class org.apache.kafka.trogdor.workload.GaussianThroughputGenerator {
+GaussianThroughputGenerator(int;double;int;long) : GaussianThroughputGenerator [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#26]]]
+messagesPerWindowAverage() : int [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#44]]]
+messagesPerWindowDeviation() : double [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#49]]]
+windowsUntilRateChange() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#54]]]
+windowSizeMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#59]]]
-calculateNextWindow(boolean) : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#63]]]
+throttle() : void [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/GaussianThroughputGenerator.java.html#89]]]
} 
@enduml
