@startuml
!pragma layout smetana
"Message" <|-- "org.apache.kafka.trogdor.workload.PartitionsSpec"
class org.apache.kafka.trogdor.workload.PartitionsSpec {
+PartitionsSpec(int;short;Map<Integer,List<Integer>>;Map<String,String>) : PartitionsSpec [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#45]]]
+numPartitions() : int [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#73]]]
+partitionNumbers() : List<Integer> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#77]]]
+replicationFactor() : short [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#91]]]
+partitionAssignments() : Map<Integer,List<Integer>> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#96]]]
+configs() : Map<String,String> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#101]]]
+newTopic(String) : NewTopic [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/workload/PartitionsSpec.java.html#105]]]
} 
@enduml
