@startuml
!pragma layout smetana
Message <|-- org.apache.kafka.trogdor.workload.PartitionsSpec
class org.apache.kafka.trogdor.workload.PartitionsSpec {
+  PartitionsSpec(int;short;Map<Integer,List<Integer>>;Map<String,String>)
+  numPartitions()
+  partitionNumbers()
+  replicationFactor()
+  partitionAssignments()
+  configs()
+  newTopic(String)
} 
@enduml
