@startuml
!pragma layout smetana
Iterator_byte[]_ <|-- org.apache.kafka.trogdor.workload.PayloadIterator
class org.apache.kafka.trogdor.workload.PayloadIterator {
+  PayloadIterator(PayloadGenerator)
+  hasNext()
+  next()
+  remove()
+  seek(long)
+  position()
} 
@enduml
