@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.config.types.Password
class org.apache.kafka.common.config.types.Password {
+  Password(String)
+  hashCode()
+  equals(Object)
+  toString()
+  value()
} 
@enduml
