@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.trogdor.rest.Message
class org.apache.kafka.trogdor.rest.Message {
+  equals(Object)
+  hashCode()
+  toString()
} 
@enduml
