@startuml
!pragma layout smetana
"TaskState" <|-- "org.apache.kafka.trogdor.rest.TaskStopping"
class org.apache.kafka.trogdor.rest.TaskStopping {
+TaskStopping(TaskSpec;long;JsonNode) : TaskStopping [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TaskStopping.java.html#35]]]
+startedMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TaskStopping.java.html#43]]]
+stateType() : TaskStateType [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TaskStopping.java.html#48]]]
} 
@enduml
