@startuml
!pragma layout smetana
TaskState <|-- org.apache.kafka.trogdor.rest.TaskDone
class org.apache.kafka.trogdor.rest.TaskDone {
+  TaskDone(TaskSpec;long;long;String;boolean;JsonNode)
+  startedMs()
+  doneMs()
+  error()
+  cancelled()
+  stateType()
} 
@enduml
