@startuml
!pragma layout smetana
TaskState <|-- org.apache.kafka.trogdor.rest.TaskRunning
class org.apache.kafka.trogdor.rest.TaskRunning {
+  TaskRunning(TaskSpec;long;JsonNode)
+  startedMs()
+  stateType()
} 
@enduml
