@startuml
!pragma layout smetana
"Message" <|-- "org.apache.kafka.trogdor.rest.TasksRequest"
class org.apache.kafka.trogdor.rest.TasksRequest {
+TasksRequest(Collection<String>;long;long;long;long;Optional<TaskStateType>) : TasksRequest [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#66]]]
+taskIds() : Collection<String> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#82]]]
+firstStartMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#87]]]
+lastStartMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#92]]]
+firstEndMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#97]]]
+lastEndMs() : long [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#102]]]
+state() : Optional<TaskStateType> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#107]]]
+matches(String;long;long;TaskStateType) : boolean [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/rest/TasksRequest.java.html#119]]]
} 
@enduml
