@startuml
!pragma layout smetana
AbstractConnectorClientConfigOverridePolicy <|-- org.apache.kafka.connect.connector.policy.NoneConnectorClientConfigOverridePolicy
class org.apache.kafka.connect.connector.policy.NoneConnectorClientConfigOverridePolicy {
+  policyName()
+  isAllowed(ConfigValue)
+  configure(Map<String,?>)
} 
@enduml
