@startuml
!pragma layout smetana
"Processor<K,V>" <|-- "org.apache.kafka.streams.processor.AbstractProcessor"
class org.apache.kafka.streams.processor.AbstractProcessor {
AbstractProcessor() : AbstractProcessor [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/AbstractProcessor.java.html#33]]]
+init(ProcessorContext) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/AbstractProcessor.java.html#36]]]
+close() : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/AbstractProcessor.java.html#47]]]
context() : ProcessorContext [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/AbstractProcessor.java.html#56]]]
} 
@enduml
