@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.Cancellable"
class org.apache.kafka.streams.processor.Cancellable {
cancel() : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/Cancellable.java.html#10]]]
} 
@enduml
