@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.ConnectedStoreProvider
class org.apache.kafka.streams.processor.ConnectedStoreProvider {
+  stores()
} 
@enduml
