@startuml
!pragma layout smetana
TimestampExtractor <|-- org.apache.kafka.streams.processor.ExtractRecordMetadataTimestamp
class org.apache.kafka.streams.processor.ExtractRecordMetadataTimestamp {
+  extract(ConsumerRecord<Object,Object>;long)
+  onInvalidTimestamp(ConsumerRecord<Object,Object>;long;long)
} 
@enduml
