@startuml
!pragma layout smetana
"TimestampExtractor" <|-- "org.apache.kafka.streams.processor.ExtractRecordMetadataTimestamp"
class org.apache.kafka.streams.processor.ExtractRecordMetadataTimestamp {
+extract(ConsumerRecord<Object,Object>;long) : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ExtractRecordMetadataTimestamp.java.html#11]]]
+onInvalidTimestamp(ConsumerRecord<Object,Object>;long;long) : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ExtractRecordMetadataTimestamp.java.html#22]]]
} 
@enduml
