@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.ProcessorContext
class org.apache.kafka.streams.processor.ProcessorContext {
applicationId() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#21]]]
taskId() : TaskId [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#24]]]
keySerde() : Serde<?> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#27]]]
valueSerde() : Serde<?> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#30]]]
stateDir() : File [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#33]]]
metrics() : StreamsMetrics [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#36]]]
register(StateStore;StateRestoreCallback) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#39]]]
schedule(Duration;PunctuationType;Punctuator) : Cancellable [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#46]]]
commit() : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#57]]]
topic() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#60]]]
partition() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#63]]]
offset() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#66]]]
headers() : Headers [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#69]]]
timestamp() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#72]]]
appConfigs() : Map<String,Object> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#75]]]
appConfigsWithPrefix(String) : Map<String,Object> [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#78]]]
currentSystemTimeMs() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#81]]]
currentStreamTimeMs() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#84]]]
} 
@enduml
