@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.ProcessorContext"
class org.apache.kafka.streams.processor.ProcessorContext {
applicationId() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#42]]]
taskId() : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#49]]]
keySerde() : Serde<?> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#56]]]
valueSerde() : Serde<?> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#63]]]
stateDir() : File [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#70]]]
metrics() : StreamsMetrics [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#77]]]
register(StateStore;StateRestoreCallback) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#88]]]
schedule(Duration;PunctuationType;Punctuator) : Cancellable [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#134]]]
commit() : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#166]]]
topic() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#182]]]
partition() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#198]]]
offset() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#214]]]
headers() : Headers [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#230]]]
timestamp() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#249]]]
appConfigs() : Map<String,Object> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#264]]]
appConfigsWithPrefix(String) : Map<String,Object> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#276]]]
currentSystemTimeMs() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#286]]]
currentStreamTimeMs() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java.html#302]]]
} 
@enduml
