@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.RecordContext
class org.apache.kafka.streams.processor.RecordContext {
+  topic()
+  partition()
+  offset()
+  timestamp()
+  headers()
} 
@enduml
