@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.StateRestoreListener
class org.apache.kafka.streams.processor.StateRestoreListener {
+  onRestoreStart(TopicPartition;String;long;long)
+  onBatchRestored(TopicPartition;String;long;long)
+  onRestoreEnd(TopicPartition;String;long)
} 
@enduml
