@startuml
!pragma layout smetana
Comparable_TaskId_ <|-- org.apache.kafka.streams.processor.TaskId
class org.apache.kafka.streams.processor.TaskId {
+TaskId(int;int) : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#35]]]
+TaskId(int;int;String) : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#39]]]
+subtopology() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#51]]]
+partition() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#55]]]
+topologyName() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#60]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#65]]]
+parse(String) : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#70]]]
+writeTo(DataOutputStream;int) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#98]]]
+readFrom(DataInputStream;int) : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#104]]]
+writeTo(ByteBuffer;int) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#110]]]
+readFrom(ByteBuffer;int) : TaskId [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#116]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#121]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#142]]]
+compareTo(TaskId) : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TaskId.java.html#147]]]
} 
@enduml
