@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.ThreadMetadata
class org.apache.kafka.streams.processor.ThreadMetadata {
+ThreadMetadata(String;String;String;String;Set<String>;String;Set<org.apache.kafka.streams.processor.TaskMetadata>;Set<org.apache.kafka.streams.processor.TaskMetadata>) : ThreadMetadata [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#32]]]
+threadState() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#50]]]
+threadName() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#54]]]
+activeTasks() : Set<org.apache.kafka.streams.processor.TaskMetadata> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#58]]]
+standbyTasks() : Set<org.apache.kafka.streams.processor.TaskMetadata> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#62]]]
+consumerClientId() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#66]]]
+restoreConsumerClientId() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#70]]]
+producerClientIds() : Set<String> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#74]]]
+adminClientId() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#78]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#83]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#102]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/ThreadMetadata.java.html#115]]]
} 
@enduml
