@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.TimestampExtractor"
class org.apache.kafka.streams.processor.TimestampExtractor {
extract(ConsumerRecord<Object,Object>;long) : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/TimestampExtractor.java.html#11]]]
} 
@enduml
