@startuml
!pragma layout smetana
Predicate_R_ <|-- org.apache.kafka.connect.transforms.predicates.RecordIsTombstone
class org.apache.kafka.connect.transforms.predicates.RecordIsTombstone {
+  config()
+  test(R)
+  close()
+  configure(Map<String,?>)
+  toString()
} 
@enduml
