@startuml
!pragma layout smetana
"Predicate<R>" <|-- "org.apache.kafka.connect.transforms.predicates.RecordIsTombstone"
class org.apache.kafka.connect.transforms.predicates.RecordIsTombstone {
+config() : ConfigDef [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/RecordIsTombstone.java.html#34]]]
+test(R) : boolean [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/RecordIsTombstone.java.html#39]]]
+close() : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/RecordIsTombstone.java.html#44]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/RecordIsTombstone.java.html#49]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/RecordIsTombstone.java.html#54]]]
} 
@enduml
