@startuml
!pragma layout smetana
Predicate_R_ <|-- org.apache.kafka.connect.transforms.predicates.TopicNameMatches
class org.apache.kafka.connect.transforms.predicates.TopicNameMatches {
+config() : ConfigDef [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#29]]]
+test(R) : boolean [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#34]]]
+close() : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#39]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#44]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#57]]]
} 
@enduml
