@startuml
!pragma layout smetana
"Predicate<R>" <|-- "org.apache.kafka.connect.transforms.predicates.TopicNameMatches"
class org.apache.kafka.connect.transforms.predicates.TopicNameMatches {
+config() : ConfigDef [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#47]]]
+test(R) : boolean [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#52]]]
+close() : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#57]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#62]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates/TopicNameMatches.java.html#75]]]
} 
@enduml
