@startuml
!pragma layout smetana
"Commands.Handler" <|-- "org.apache.kafka.shell.ErroneousCommandHandler"
class org.apache.kafka.shell.ErroneousCommandHandler {
+ErroneousCommandHandler(String) : ErroneousCommandHandler [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/ErroneousCommandHandler.java.html#30]]]
+run(Optional<InteractiveShell>;PrintWriter;MetadataNodeManager) : void [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/ErroneousCommandHandler.java.html#35]]]
+hashCode() : int [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/ErroneousCommandHandler.java.html#42]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/ErroneousCommandHandler.java.html#47]]]
+toString() : String [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/ErroneousCommandHandler.java.html#55]]]
} 
@enduml
