@startuml
!pragma layout smetana
Commands.Handler <|-- org.apache.kafka.shell.ExitCommandHandler
class org.apache.kafka.shell.ExitCommandHandler {
+ run(Optional<InteractiveShell>;PrintWriter;MetadataNodeManager) : void [[[././qc/shell/src/main/java/org/apache/kafka/shell/ExitCommandHandler.java.html#55]]]
+ hashCode() : int [[[././qc/shell/src/main/java/org/apache/kafka/shell/ExitCommandHandler.java.html#62]]]
+ equals(Object) : boolean [[[././qc/shell/src/main/java/org/apache/kafka/shell/ExitCommandHandler.java.html#67]]]
} 
@enduml
