@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.shell.GlobComponent
class org.apache.kafka.shell.GlobComponent {
-isRegularExpressionSpecialCharacter(char) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#15]]]
-isGlobSpecialCharacter(char) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#35]]]
toRegularExpression(String) : String [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#50]]]
+GlobComponent(String) : GlobComponent [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#125]]]
+component() : String [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#139]]]
+literal() : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#143]]]
+matches(String) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#147]]]
} 
@enduml
