@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.shell.GlobComponent"
class org.apache.kafka.shell.GlobComponent {
-isRegularExpressionSpecialCharacter(char) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#34]]]
-isGlobSpecialCharacter(char) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#56]]]
toRegularExpression(String) : String [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#75]]]
+GlobComponent(String) : GlobComponent [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#150]]]
+component() : String [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#164]]]
+literal() : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#168]]]
+matches(String) : boolean [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/GlobComponent.java.html#172]]]
} 
@enduml
