@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.shell.MetadataShell"
class org.apache.kafka.shell.MetadataShell {
+MetadataShell(KafkaRaftManager<ApiMessageAndVersion>;SnapshotFileReader;MetadataNodeManager) : MetadataShell [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/MetadataShell.java.html#86]]]
+run(List<String>) : void [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/MetadataShell.java.html#94]]]
+close() : void [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/MetadataShell.java.html#125]]]
+main(String[]) : void [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/MetadataShell.java.html#135]]]
waitUntilCaughtUp() : void [[[./../../../../../../../../.././qc/shell/src/main/java/org/apache/kafka/shell/MetadataShell.java.html#178]]]
} 
@enduml
