@startuml
!pragma layout smetana
"Topology" <|-- "org.apache.kafka.trogdor.basic.BasicTopology"
class org.apache.kafka.trogdor.basic.BasicTopology {
+BasicTopology(NavigableMap<String,Node>) : BasicTopology [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicTopology.java.html#16]]]
+BasicTopology(JsonNode) : BasicTopology [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicTopology.java.html#20]]]
+node(String) : Node [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicTopology.java.html#35]]]
+nodes() : NavigableMap<String,Node> [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicTopology.java.html#40]]]
} 
@enduml
