@startuml
!pragma layout smetana
"Platform" <|-- "org.apache.kafka.trogdor.basic.BasicPlatform"
class org.apache.kafka.trogdor.basic.BasicPlatform {
+BasicPlatform(String;BasicTopology;Scheduler;CommandRunner) : BasicPlatform [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#61]]]
+BasicPlatform(String;Scheduler;JsonNode) : BasicPlatform [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#74]]]
+name() : String [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#92]]]
+curNode() : Node [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#97]]]
+topology() : Topology [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#102]]]
+scheduler() : Scheduler [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#107]]]
+runCommand(String[]) : String [[[./../../../../../../../../../.././qc/trogdor/src/main/java/org/apache/kafka/trogdor/basic/BasicPlatform.java.html#112]]]
} 
@enduml
