@startuml
!pragma layout smetana
"Closeable" <|-- "org.apache.kafka.raft.internals.BatchAccumulator"
class org.apache.kafka.raft.internals.BatchAccumulator {
+BatchAccumulator(int;long;int;int;MemoryPool;Time;CompressionType;RecordSerde<T>) : BatchAccumulator [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#68]]]
+append(int;List<T>) : long [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#111]]]
+appendAtomic(int;List<T>) : long [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#131]]]
-append(int;List<T>;boolean) : long [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#135]]]
-maybeResetLinger() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#176]]]
-maybeAllocateBatch(Collection<T>;ObjectSerializationCache) : BatchBuilder<T> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#182]]]
-completeCurrentBatch() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#209]]]
-appendControlMessage(Function<ByteBuffer,MemoryRecords>) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#230]]]
+appendLeaderChangeMessage(LeaderChangeMessage;long) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#267]]]
+appendSnapshotHeaderMessage(SnapshotHeaderRecord;long) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#289]]]
+appendSnapshotFooterMessage(SnapshotFooterRecord;long) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#311]]]
+forceDrain() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#326]]]
-maybeCompleteDrain() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#336]]]
-startNewBatch() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#348]]]
+needsDrain(long) : boolean [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#370]]]
+timeUntilDrain(long) : long [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#381]]]
+epoch() : int [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#394]]]
+drain() : List<CompletedBatch<T>> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#414]]]
-drainCompleted() : List<CompletedBatch<T>> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#438]]]
+isEmpty() : boolean [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#450]]]
+numCompletedBatches() : int [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#461]]]
+close() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java.html#466]]]
} 
@enduml
