@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.raft.internals.FuturePurgatory"
class org.apache.kafka.raft.internals.FuturePurgatory {
await(T;long) : CompletableFuture<Long> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java.html#56]]]
maybeComplete(T;long) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java.html#66]]]
completeAll(long) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java.html#74]]]
completeAllExceptionally(Throwable) : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java.html#83]]]
numWaiting() : int [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java.html#90]]]
} 
@enduml
