@startuml
!pragma layout smetana
BatchReader_T_ <|-- org.apache.kafka.raft.internals.MemoryBatchReader
class org.apache.kafka.raft.internals.MemoryBatchReader {
+  MemoryBatchReader(long;long;Iterator<Batch<T>>;CloseListener<BatchReader<T>>)
+  hasNext()
+  next()
+  baseOffset()
+  lastOffset()
+  close()
} 
@enduml
