@startuml
!pragma layout smetana
"Iterator<Batch<T>>" <|-- "org.apache.kafka.raft.internals.RecordsIterator"
class org.apache.kafka.raft.internals.RecordsIterator {
+RecordsIterator(Records;RecordSerde<T>;BufferSupplier;int) : RecordsIterator [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#53]]]
+hasNext() : boolean [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#66]]]
+next() : Batch<T> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#77]]]
+close() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#89]]]
-ensureOpen() : void [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#95]]]
-readFileRecords(FileRecords;ByteBuffer) : MemoryRecords [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#101]]]
-createMemoryRecords(FileRecords) : MemoryRecords [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#113]]]
-nextBatches() : Iterator<MutableRecordBatch> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#140]]]
-nextBatch() : Optional<Batch<T>> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#159]]]
-readBatch(DefaultRecordBatch) : Batch<T> [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#182]]]
-readRecord(Readable) : T [[[./../../../../../../../../../.././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#218]]]
} 
@enduml
