@startuml
!pragma layout smetana
Iterator_Batch_T__ <|-- org.apache.kafka.raft.internals.RecordsIterator
class org.apache.kafka.raft.internals.RecordsIterator {
+ RecordsIterator(Records;RecordSerde<T>;BufferSupplier;int) : RecordsIterator [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#38]]]
+ hasNext() : boolean [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#51]]]
+ next() : Batch<T> [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#62]]]
+ close() : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#74]]]
- ensureOpen() : void [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#80]]]
- readFileRecords(FileRecords;ByteBuffer) : MemoryRecords [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#86]]]
- createMemoryRecords(FileRecords) : MemoryRecords [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#98]]]
- nextBatches() : Iterator<MutableRecordBatch> [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#125]]]
- nextBatch() : Optional<Batch<T>> [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#144]]]
- readBatch(DefaultRecordBatch) : Batch<T> [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#167]]]
- readRecord(Readable) : T [[[././qc/raft/src/main/java/org/apache/kafka/raft/internals/RecordsIterator.java.html#203]]]
} 
@enduml
