@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.kerberos.KerberosName
class org.apache.kafka.common.security.kerberos.KerberosName {
+  KerberosName(String;String;String)
+  parse(String)
+  toString()
+  serviceName()
+  hostName()
+  realm()
} 
@enduml
