@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.state.internals.metrics.NamedCacheMetrics
class org.apache.kafka.streams.state.internals.metrics.NamedCacheMetrics {
- NamedCacheMetrics() : NamedCacheMetrics [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/NamedCacheMetrics.java.html#11]]]
+ hitRatioSensor(StreamsMetricsImpl;String;String;String) : Sensor [[[././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/NamedCacheMetrics.java.html#19]]]
} 
@enduml
