@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.state.internals.metrics.RocksDBMetrics"
class org.apache.kafka.streams.state.internals.metrics.RocksDBMetrics {
-RocksDBMetrics() : RocksDBMetrics [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#24]]]
+bytesWrittenToDatabaseSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#188]]]
+bytesReadFromDatabaseSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#206]]]
+memtableBytesFlushedSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#224]]]
+memtableHitRatioSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#242]]]
+memtableAvgFlushTimeSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#259]]]
+memtableMinFlushTimeSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#276]]]
+memtableMaxFlushTimeSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#293]]]
+writeStallDurationSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#310]]]
+blockCacheDataHitRatioSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#328]]]
+blockCacheIndexHitRatioSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#345]]]
+blockCacheFilterHitRatioSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#362]]]
+bytesReadDuringCompactionSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#379]]]
+bytesWrittenDuringCompactionSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#396]]]
+compactionTimeAvgSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#413]]]
+compactionTimeMinSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#430]]]
+compactionTimeMaxSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#447]]]
+numberOfOpenFilesSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#464]]]
+numberOfFileErrorsSensor(StreamsMetricsImpl;RocksDBMetricContext) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#482]]]
+addNumEntriesActiveMemTableMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#499]]]
+addNumEntriesImmMemTablesMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#511]]]
+addNumDeletesImmMemTablesMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#523]]]
+addNumDeletesActiveMemTableMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#535]]]
+addNumImmutableMemTableMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#547]]]
+addCurSizeActiveMemTable(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#559]]]
+addCurSizeAllMemTables(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#571]]]
+addSizeAllMemTables(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#583]]]
+addMemTableFlushPending(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#595]]]
+addNumRunningFlushesMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#607]]]
+addCompactionPendingMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#619]]]
+addNumRunningCompactionsMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#631]]]
+addEstimatePendingCompactionBytesMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#643]]]
+addTotalSstFilesSizeMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#655]]]
+addLiveSstFilesSizeMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#667]]]
+addNumLiveVersionMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#679]]]
+addBlockCacheCapacityMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#691]]]
+addBlockCacheUsageMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#703]]]
+addBlockCachePinnedUsageMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#715]]]
+addEstimateNumKeysMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#727]]]
+addEstimateTableReadersMemMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#739]]]
+addBackgroundErrorsMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#751]]]
-addMutableMetric(StreamsMetricsImpl;RocksDBMetricContext;Gauge<BigInteger>;String;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#763]]]
-createSensor(StreamsMetricsImpl;RocksDBMetricContext;String) : Sensor [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java.html#779]]]
} 
@enduml
