@startuml
!pragma layout smetana
"Runnable" <|-- "org.apache.kafka.streams.state.internals.metrics.RocksDBMetricsRecordingTrigger"
class org.apache.kafka.streams.state.internals.metrics.RocksDBMetricsRecordingTrigger {
+RocksDBMetricsRecordingTrigger(Time) : RocksDBMetricsRecordingTrigger [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetricsRecordingTrigger.java.html#29]]]
+addMetricsRecorder(RocksDBMetricsRecorder) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetricsRecordingTrigger.java.html#33]]]
+removeMetricsRecorder(RocksDBMetricsRecorder) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetricsRecordingTrigger.java.html#43]]]
-metricsRecorderName(RocksDBMetricsRecorder) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetricsRecordingTrigger.java.html#53]]]
+run() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetricsRecordingTrigger.java.html#58]]]
} 
@enduml
