@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredential
class org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredential {
+  principalName()
+  startTimeMs()
+  expireTimeMs()
+  absoluteLastRefreshTimeMs()
} 
@enduml
