@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshConfig
class org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshConfig {
+  ExpiringCredentialRefreshConfig(Map<String,?>;boolean)
+  loginRefreshWindowFactor()
+  loginRefreshWindowJitter()
+  loginRefreshMinPeriodSeconds()
+  loginRefreshBufferSeconds()
+  loginRefreshReloginAllowedBeforeLogout()
} 
@enduml
