@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin
class org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin {
+  ExpiringCredentialRefreshingLogin(String;Configuration;ExpiringCredentialRefreshConfig;AuthenticateCallbackHandler;Class<?>)
+  ExpiringCredentialRefreshingLogin(String;Configuration;ExpiringCredentialRefreshConfig;AuthenticateCallbackHandler;Class<?>;LoginContextFactory;Time)
+  subject()
+  contextName()
+  configuration()
+  callbackHandler()
+  serviceName()
+  login()
+  close()
+  expiringCredential()
+  refreshMs(long)
+  reLogin()
+  principalLogText()
+  currentMs()
+  isLogoutRequiredBeforeLoggingBackIn()
} 
@enduml
