@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshConfig
class org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshConfig {
+ExpiringCredentialRefreshConfig(Map<String,?>;boolean) : ExpiringCredentialRefreshConfig [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#18]]]
+loginRefreshWindowFactor() : double [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#28]]]
+loginRefreshWindowJitter() : double [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#33]]]
+loginRefreshMinPeriodSeconds() : short [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#38]]]
+loginRefreshBufferSeconds() : short [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#43]]]
+loginRefreshReloginAllowedBeforeLogout() : boolean [[[./../../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/expiring/ExpiringCredentialRefreshConfig.java.html#48]]]
} 
@enduml
