@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.internals.ApiUtils
class org.apache.kafka.streams.internals.ApiUtils {
+  ApiUtils()
+  validateMillisecondDuration(Duration;String)
+  validateMillisecondInstant(Instant;String)
+  prepareMillisCheckFailMsgPrefix(Object;String)
+  checkSupplier(Supplier<?>)
} 
@enduml
