@startuml
!pragma layout smetana
OutputStream <|-- org.apache.kafka.common.compress.KafkaLZ4BlockOutputStream
class org.apache.kafka.common.compress.KafkaLZ4BlockOutputStream {
+KafkaLZ4BlockOutputStream(OutputStream;int;boolean;boolean) : KafkaLZ4BlockOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#41]]]
+KafkaLZ4BlockOutputStream(OutputStream;int;boolean) : KafkaLZ4BlockOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#57]]]
+KafkaLZ4BlockOutputStream(OutputStream;int) : KafkaLZ4BlockOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#62]]]
+KafkaLZ4BlockOutputStream(OutputStream) : KafkaLZ4BlockOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#67]]]
+KafkaLZ4BlockOutputStream(OutputStream;boolean) : KafkaLZ4BlockOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#71]]]
+useBrokenFlagDescriptorChecksum() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#76]]]
-writeHeader() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#81]]]
-writeBlock() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#104]]]
-writeEndMark() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#133]]]
+write(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#139]]]
+write(byte[];int;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#148]]]
+flush() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#170]]]
-ensureNotFinished() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#180]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/compress/KafkaLZ4BlockOutputStream.java.html#187]]]
} 
@enduml
