@startuml
!pragma layout smetana
"java.lang.Object" <|-- "kafka.server.builders.KafkaApisBuilder"
class kafka.server.builders.KafkaApisBuilder {
+setRequestChannel(RequestChannel) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#65]]]
+setMetadataSupport(MetadataSupport) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#70]]]
+setReplicaManager(ReplicaManager) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#75]]]
+setGroupCoordinator(GroupCoordinator) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#80]]]
+setTxnCoordinator(TransactionCoordinator) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#85]]]
+setAutoTopicCreationManager(AutoTopicCreationManager) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#90]]]
+setBrokerId(int) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#95]]]
+setConfig(KafkaConfig) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#100]]]
+setConfigRepository(ConfigRepository) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#105]]]
+setMetadataCache(MetadataCache) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#110]]]
+setMetrics(Metrics) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#115]]]
+setAuthorizer(Optional<Authorizer>) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#120]]]
+setQuotas(QuotaManagers) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#125]]]
+setFetchManager(FetchManager) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#130]]]
+setBrokerTopicStats(BrokerTopicStats) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#135]]]
+setClusterId(String) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#140]]]
+setTime(Time) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#145]]]
+setTokenManager(DelegationTokenManager) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#150]]]
+setApiVersionManager(ApiVersionManager) : KafkaApisBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#155]]]
+build() : KafkaApis [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/KafkaApisBuilder.java.html#160]]]
} 
@enduml
