@startuml
!pragma layout smetana
"java.lang.Object" <|-- "kafka.server.builders.ReplicaManagerBuilder"
class kafka.server.builders.ReplicaManagerBuilder {
+setConfig(KafkaConfig) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#63]]]
+setMetrics(Metrics) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#68]]]
+setTime(Time) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#73]]]
+setScheduler(Scheduler) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#78]]]
+setLogManager(LogManager) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#83]]]
+setQuotaManagers(QuotaManagers) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#88]]]
+setMetadataCache(MetadataCache) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#93]]]
+setLogDirFailureChannel(LogDirFailureChannel) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#98]]]
+setAlterPartitionManager(AlterPartitionManager) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#103]]]
+setBrokerTopicStats(BrokerTopicStats) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#108]]]
+setIsShuttingDown(AtomicBoolean) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#113]]]
+setZkClient(KafkaZkClient) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#118]]]
+setDelayedProducePurgatory(DelayedOperationPurgatory<DelayedProduce>) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#123]]]
+setDelayedFetchPurgatory(DelayedOperationPurgatory<DelayedFetch>) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#128]]]
+setDelayedDeleteRecordsPurgatory(DelayedOperationPurgatory<DelayedDeleteRecords>) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#133]]]
+setDelayedElectLeaderPurgatoryParam(DelayedOperationPurgatory<DelayedElectLeader>) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#138]]]
+setThreadNamePrefix(String) : ReplicaManagerBuilder [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#143]]]
+build() : ReplicaManager [[[./../../../../../../../.././qc/core/src/main/java/kafka/server/builders/ReplicaManagerBuilder.java.html#148]]]
} 
@enduml
