@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.controller.ClientQuotaControlManager
class org.apache.kafka.controller.ClientQuotaControlManager {
ClientQuotaControlManager(SnapshotRegistry) : ClientQuotaControlManager [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#41]]]
alterClientQuotas(Collection<ClientQuotaAlteration>) : ControllerResult<Map<ClientQuotaEntity,ApiError>> [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#47]]]
+ replay(ClientQuotaRecord) : void [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#76]]]
- alterClientQuotaEntity(ClientQuotaEntity;Map<String,Double>;List<ApiMessageAndVersion>;Map<ClientQuotaEntity,ApiError>) : void [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#95]]]
- configKeysForEntityType(Map<String,String>;Map<String,ConfigDef.ConfigKey>) : ApiError [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#162]]]
- validateQuotaKeyValue(Map<String,ConfigDef.ConfigKey>;String;Double) : ApiError [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#195]]]
- isValidIpEntity(String) : boolean [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#225]]]
- validateEntity(ClientQuotaEntity;Map<String,String>) : ApiError [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#238]]]
iterator(long) : ClientQuotaControlIterator [[[././qc/metadata/src/main/java/org/apache/kafka/controller/ClientQuotaControlManager.java.html#305]]]
} 
@enduml
