@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.controller.ConfigurationControlManager
class org.apache.kafka.controller.ConfigurationControlManager {
-ConfigurationControlManager(LogContext;SnapshotRegistry;KafkaConfigSchema;Consumer<ConfigResource>;Optional<AlterConfigPolicy>;ConfigurationValidator;Map<String,Object>;int) : ConfigurationControlManager [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#117]]]
snapshotRegistry() : SnapshotRegistry [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#136]]]
incrementalAlterConfigs(Map<ConfigResource,Map<String,Entry<OpType,String>>>;boolean) : ControllerResult<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#141]]]
-incrementalAlterConfigResource(ConfigResource;Map<String,Entry<OpType,String>>;boolean;List<ApiMessageAndVersion>;Map<ConfigResource,ApiError>) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#157]]]
-validateAlterConfig(ConfigResource;List<ApiMessageAndVersion>;boolean) : ApiError [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#221]]]
legacyAlterConfigs(Map<ConfigResource,Map<String,String>>;boolean) : ControllerResult<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#252]]]
-legacyAlterConfigResource(ConfigResource;Map<String,String>;boolean;List<ApiMessageAndVersion>;Map<ConfigResource,ApiError>) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#269]]]
-getParts(String;String;ConfigResource) : List<String> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#309]]]
+replay(ConfigRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#327]]]
getConfigs(ConfigResource) : Map<String,String> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#347]]]
+describeConfigs(long;Map<ConfigResource,Collection<String>>) : Map<ConfigResource,ResultOrError<Map<String,String>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#356]]]
deleteTopicConfigs(String) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#393]]]
uncleanLeaderElectionEnabledForTopic(String) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#397]]]
computeEffectiveTopicConfigs(Map<String,String>) : Map<String,ConfigEntry> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#401]]]
clusterConfig() : Map<String,String> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#406]]]
currentControllerConfig() : Map<String,String> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#411]]]
iterator(long) : ConfigurationControlIterator [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/ConfigurationControlManager.java.html#447]]]
} 
@enduml
