@startuml
!pragma layout smetana
AclMutator <|-- org.apache.kafka.controller.Controller
class org.apache.kafka.controller.Controller {
alterPartition(ControllerRequestContext;AlterPartitionRequestData) : CompletableFuture<AlterPartitionResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#43]]]
createTopics(ControllerRequestContext;CreateTopicsRequestData;Set<String>) : CompletableFuture<CreateTopicsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#49]]]
unregisterBroker(ControllerRequestContext;int) : CompletableFuture<Void> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#56]]]
findTopicIds(ControllerRequestContext;Collection<String>) : CompletableFuture<Map<String,ResultOrError<Uuid>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#62]]]
findAllTopicIds(ControllerRequestContext) : CompletableFuture<Map<String,Uuid>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#68]]]
findTopicNames(ControllerRequestContext;Collection<Uuid>) : CompletableFuture<Map<Uuid,ResultOrError<String>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#73]]]
deleteTopics(ControllerRequestContext;Collection<Uuid>) : CompletableFuture<Map<Uuid,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#79]]]
describeConfigs(ControllerRequestContext;Map<ConfigResource,Collection<String>>) : CompletableFuture<Map<ConfigResource,ResultOrError<Map<String,String>>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#85]]]
electLeaders(ControllerRequestContext;ElectLeadersRequestData) : CompletableFuture<ElectLeadersResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#91]]]
finalizedFeatures(ControllerRequestContext) : CompletableFuture<FinalizedControllerFeatures> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#97]]]
incrementalAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,Map.Entry<AlterConfigOp.OpType,String>>>;boolean) : CompletableFuture<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#102]]]
alterPartitionReassignments(ControllerRequestContext;AlterPartitionReassignmentsRequestData) : CompletableFuture<AlterPartitionReassignmentsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#109]]]
listPartitionReassignments(ControllerRequestContext;ListPartitionReassignmentsRequestData) : CompletableFuture<ListPartitionReassignmentsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#115]]]
legacyAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,String>>;boolean) : CompletableFuture<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#121]]]
processBrokerHeartbeat(ControllerRequestContext;BrokerHeartbeatRequestData) : CompletableFuture<BrokerHeartbeatReply> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#128]]]
registerBroker(ControllerRequestContext;BrokerRegistrationRequestData) : CompletableFuture<BrokerRegistrationReply> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#134]]]
waitForReadyBrokers(int) : CompletableFuture<Void> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#140]]]
alterClientQuotas(ControllerRequestContext;Collection<ClientQuotaAlteration>;boolean) : CompletableFuture<Map<ClientQuotaEntity,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#143]]]
allocateProducerIds(ControllerRequestContext;AllocateProducerIdsRequestData) : CompletableFuture<AllocateProducerIdsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#150]]]
updateFeatures(ControllerRequestContext;UpdateFeaturesRequestData) : CompletableFuture<UpdateFeaturesResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#156]]]
beginWritingSnapshot() : CompletableFuture<Long> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#162]]]
createPartitions(ControllerRequestContext;List<CreatePartitionsTopic>;boolean) : CompletableFuture<List<CreatePartitionsTopicResult>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#165]]]
beginShutdown() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#172]]]
curClaimEpoch() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#175]]]
isActive() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#178]]]
close() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/Controller.java.html#183]]]
} 
@enduml
