@startuml
!pragma layout smetana
ControllerResult_T_ <|-- org.apache.kafka.controller.ControllerResultAndOffset
class org.apache.kafka.controller.ControllerResultAndOffset {
+  ControllerResultAndOffset(long;ControllerResult<T>)
+  offset()
+  equals(Object)
+  hashCode()
+  toString()
} 
@enduml
