@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.controller.PartitionChangeBuilder"
class org.apache.kafka.controller.PartitionChangeBuilder {
+changeRecordIsNoOp(PartitionChangeRecord) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#45]]]
+PartitionChangeBuilder(PartitionRegistration;Uuid;int;Function<Integer,Boolean>;boolean) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#85]]]
+setTargetIsr(List<Integer>) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#102]]]
+setTargetReplicas(List<Integer>) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#107]]]
+setElection(Election) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#112]]]
+setTargetRemoving(List<Integer>) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#117]]]
+setTargetAdding(List<Integer>) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#122]]]
+setTargetLeaderRecoveryState(LeaderRecoveryState) : PartitionChangeBuilder [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#127]]]
electLeader() : ElectionResult [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#149]]]
-electPreferredLeader() : ElectionResult [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#160]]]
-electAnyLeader() : ElectionResult [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#185]]]
-isValidNewLeader(int) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#211]]]
-tryElection(PartitionChangeRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#215]]]
triggerLeaderEpochBumpIfNeeded(PartitionChangeRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#259]]]
-completeReassignmentIfNeeded() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#268]]]
+build() : Optional<ApiMessageAndVersion> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#299]]]
+toString() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/PartitionChangeBuilder.java.html#336]]]
} 
@enduml
