@startuml
!pragma layout smetana
"Controller" <|-- "org.apache.kafka.controller.QuorumController"
class org.apache.kafka.controller.QuorumController {
-newNotControllerException() : NotControllerException [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#382]]]
+exceptionToApparentController(NotControllerException) : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#392]]]
-handleEventEnd(String;long) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#401]]]
-handleEventException(String;OptionalLong;Throwable) : Throwable [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#409]]]
-appendControlEvent(String;Runnable) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#473]]]
replicationControl() : ReplicationControlManager [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#626]]]
clusterControl() : ClusterControlManager [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#631]]]
-maybeCompleteAuthorizerInitialLoad() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1029]]]
-isActiveController() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1048]]]
-updateWriteOffset(long) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1052]]]
-updateLastCommittedState(long;int;long) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1068]]]
-renounce() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1080]]]
-rescheduleMaybeFenceStaleBrokers() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1128]]]
-cancelMaybeFenceReplicas() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1143]]]
-maybeScheduleNextBalancePartitionLeaders() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1149]]]
-cancelMaybeBalancePartitionLeaders() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1196]]]
-maybeScheduleNextWriteNoOpRecord() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1203]]]
-cancelNextWriteNoOpRecord() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1231]]]
-handleFeatureControlChange() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1236]]]
-replay(ApiMessage;Optional<OffsetAndEpoch>;long) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1249]]]
-maybeGenerateSnapshot(long) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1316]]]
-resetState() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1339]]]
-QuorumController(LogContext;int;String;KafkaEventQueue;Time;KafkaConfigSchema;RaftClient<ApiMessageAndVersion>;QuorumFeatures;short;int;ReplicaPlacer;long;OptionalLong;OptionalLong;long;ControllerMetrics;Optional<CreateTopicPolicy>;Optional<AlterConfigPolicy>;ConfigurationValidator;Optional<ClusterMetadataAuthorizer>;Map<String,Object>;BootstrapMetadata) : QuorumController [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1533]]]
+alterPartition(ControllerRequestContext;AlterPartitionRequestData) : CompletableFuture<AlterPartitionResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1625]]]
+createTopics(ControllerRequestContext;CreateTopicsRequestData;Set<String>) : CompletableFuture<CreateTopicsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1637]]]
+unregisterBroker(ControllerRequestContext;int) : CompletableFuture<Void> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1649]]]
+findTopicIds(ControllerRequestContext;Collection<String>) : CompletableFuture<Map<String,ResultOrError<Uuid>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1658]]]
+findAllTopicIds(ControllerRequestContext) : CompletableFuture<Map<String,Uuid>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1669]]]
+findTopicNames(ControllerRequestContext;Collection<Uuid>) : CompletableFuture<Map<Uuid,ResultOrError<String>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1677]]]
+deleteTopics(ControllerRequestContext;Collection<Uuid>) : CompletableFuture<Map<Uuid,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1688]]]
+describeConfigs(ControllerRequestContext;Map<ConfigResource,Collection<String>>) : CompletableFuture<Map<ConfigResource,ResultOrError<Map<String,String>>>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1699]]]
+electLeaders(ControllerRequestContext;ElectLeadersRequestData) : CompletableFuture<ElectLeadersResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1708]]]
+finalizedFeatures(ControllerRequestContext) : CompletableFuture<FinalizedControllerFeatures> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1722]]]
+incrementalAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,Entry<OpType,String>>>;boolean) : CompletableFuture<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1730]]]
+alterPartitionReassignments(ControllerRequestContext;AlterPartitionReassignmentsRequestData) : CompletableFuture<AlterPartitionReassignmentsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1750]]]
+listPartitionReassignments(ControllerRequestContext;ListPartitionReassignmentsRequestData) : CompletableFuture<ListPartitionReassignmentsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1762]]]
+legacyAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,String>>;boolean) : CompletableFuture<Map<ConfigResource,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1775]]]
+processBrokerHeartbeat(ControllerRequestContext;BrokerHeartbeatRequestData) : CompletableFuture<BrokerHeartbeatReply> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1794]]]
+registerBroker(ControllerRequestContext;BrokerRegistrationRequestData) : CompletableFuture<BrokerRegistrationReply> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1823]]]
+alterClientQuotas(ControllerRequestContext;Collection<ClientQuotaAlteration>;boolean) : CompletableFuture<Map<ClientQuotaEntity,ApiError>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1837]]]
+allocateProducerIds(ControllerRequestContext;AllocateProducerIdsRequestData) : CompletableFuture<AllocateProducerIdsResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1857]]]
+updateFeatures(ControllerRequestContext;UpdateFeaturesRequestData) : CompletableFuture<UpdateFeaturesResponseData> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1869]]]
+createPartitions(ControllerRequestContext;List<CreatePartitionsTopic>;boolean) : CompletableFuture<List<CreatePartitionsTopicResult>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1896]]]
+beginWritingSnapshot() : CompletableFuture<Long> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1918]]]
+createAcls(ControllerRequestContext;List<AclBinding>) : CompletableFuture<List<AclCreateResult>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1934]]]
+deleteAcls(ControllerRequestContext;List<AclBindingFilter>) : CompletableFuture<List<AclDeleteResult>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1943]]]
+waitForReadyBrokers(int) : CompletableFuture<Void> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1952]]]
+beginShutdown() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1961]]]
+nodeId() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1965]]]
+clusterId() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1969]]]
+curClaimEpoch() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1974]]]
metadataVersion() : MetadataVersion [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1979]]]
+close() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1984]]]
pause() : CountDownLatch [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#1990]]]
time() : Time [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java.html#2003]]]
} 
@enduml
