@startuml
!pragma layout smetana
Controller <|-- org.apache.kafka.controller.QuorumController
class org.apache.kafka.controller.QuorumController {
+  newNotControllerException()
+  exceptionToApparentController(NotControllerException)
+  handleEventEnd(String;long)
+  handleEventException(String;OptionalLong;Throwable)
+  appendControlEvent(String;Runnable)
+  replicationControl()
+  clusterControl()
+  maybeCompleteAuthorizerInitialLoad()
+  isActiveController()
+  updateWriteOffset(long)
+  updateLastCommittedState(long;int;long)
+  renounce()
+  rescheduleMaybeFenceStaleBrokers()
+  cancelMaybeFenceReplicas()
+  maybeScheduleNextBalancePartitionLeaders()
+  cancelMaybeBalancePartitionLeaders()
+  maybeScheduleNextWriteNoOpRecord()
+  cancelNextWriteNoOpRecord()
+  handleFeatureControlChange()
+  replay(ApiMessage;Optional<OffsetAndEpoch>;long)
+  maybeGenerateSnapshot(long)
+  resetState()
+  QuorumController(LogContext;int;String;KafkaEventQueue;Time;KafkaConfigSchema;RaftClient<ApiMessageAndVersion>;QuorumFeatures;short;int;ReplicaPlacer;long;OptionalLong;OptionalLong;long;ControllerMetrics;Optional<CreateTopicPolicy>;Optional<AlterConfigPolicy>;ConfigurationValidator;Optional<ClusterMetadataAuthorizer>;Map<String,Object>;BootstrapMetadata)
+  alterPartition(ControllerRequestContext;AlterPartitionRequestData)
+  createTopics(ControllerRequestContext;CreateTopicsRequestData;Set<String>)
+  unregisterBroker(ControllerRequestContext;int)
+  findTopicIds(ControllerRequestContext;Collection<String>)
+  findAllTopicIds(ControllerRequestContext)
+  findTopicNames(ControllerRequestContext;Collection<Uuid>)
+  deleteTopics(ControllerRequestContext;Collection<Uuid>)
+  describeConfigs(ControllerRequestContext;Map<ConfigResource,Collection<String>>)
+  electLeaders(ControllerRequestContext;ElectLeadersRequestData)
+  finalizedFeatures(ControllerRequestContext)
+  incrementalAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,Entry<OpType,String>>>;boolean)
+  alterPartitionReassignments(ControllerRequestContext;AlterPartitionReassignmentsRequestData)
+  listPartitionReassignments(ControllerRequestContext;ListPartitionReassignmentsRequestData)
+  legacyAlterConfigs(ControllerRequestContext;Map<ConfigResource,Map<String,String>>;boolean)
+  processBrokerHeartbeat(ControllerRequestContext;BrokerHeartbeatRequestData)
+  registerBroker(ControllerRequestContext;BrokerRegistrationRequestData)
+  alterClientQuotas(ControllerRequestContext;Collection<ClientQuotaAlteration>;boolean)
+  allocateProducerIds(ControllerRequestContext;AllocateProducerIdsRequestData)
+  updateFeatures(ControllerRequestContext;UpdateFeaturesRequestData)
+  createPartitions(ControllerRequestContext;List<CreatePartitionsTopic>;boolean)
+  beginWritingSnapshot()
+  createAcls(ControllerRequestContext;List<AclBinding>)
+  deleteAcls(ControllerRequestContext;List<AclBindingFilter>)
+  waitForReadyBrokers(int)
+  beginShutdown()
+  nodeId()
+  clusterId()
+  curClaimEpoch()
+  metadataVersion()
+  close()
+  pause()
+  time()
} 
@enduml
