@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.controller.ReplicationControlManager
class org.apache.kafka.controller.ReplicationControlManager {
+  translateCreationConfigs(CreateableTopicConfigCollection)
+  ReplicationControlManager(SnapshotRegistry;LogContext;short;int;int;ConfigurationControlManager;ClusterControlManager;ControllerMetrics;Optional<CreateTopicPolicy>;FeatureControlManager)
+  replay(TopicRecord)
+  replay(PartitionRecord)
+  updateReassigningTopicsIfNeeded(Uuid;int;boolean;boolean)
+  replay(PartitionChangeRecord)
+  replay(RemoveTopicRecord)
+  createTopics(CreateTopicsRequestData;Set<String>)
+  createTopic(CreatableTopic;List<ApiMessageAndVersion>;Map<String,CreatableTopicResult>;boolean)
+  maybeCheckCreateTopicPolicy(Supplier<CreateTopicPolicy.RequestMetadata>)
+  validateNewTopicNames(Map<String,ApiError>;CreatableTopicCollection;Map<String,?extendsSet<String>>)
+  computeConfigChanges(Map<String,ApiError>;CreatableTopicCollection)
+  findTopicIds(long;Collection<String>)
+  findAllTopicIds(long)
+  findTopicNames(long;Collection<Uuid>)
+  deleteTopics(Collection<Uuid>)
+  deleteTopic(Uuid;List<ApiMessageAndVersion>)
+  getPartition(Uuid;int)
+  getTopic(Uuid)
+  getTopicId(String)
+  brokersToIsrs()
+  imbalancedPartitions()
+  alterPartition(ControllerRequestContext;AlterPartitionRequestData)
+  validateAlterPartitionData(int;TopicControlInfo;int;PartitionRegistration;short;AlterPartitionRequestData.PartitionData)
+  ineligibleReplicasForIsr(int[])
+  handleBrokerFenced(int;List<ApiMessageAndVersion>)
+  handleBrokerUnregistered(int;long;List<ApiMessageAndVersion>)
+  handleBrokerUnfenced(int;long;List<ApiMessageAndVersion>)
+  handleBrokerInControlledShutdown(int;long;List<ApiMessageAndVersion>)
+  electLeaders(ElectLeadersRequestData)
+  electionType(byte)
+  electLeader(String;int;ElectionType;List<ApiMessageAndVersion>)
+  processBrokerHeartbeat(BrokerHeartbeatRequestData;long)
+  unregisterBroker(int)
+  maybeFenceOneStaleBroker()
+  arePartitionLeadersImbalanced()
+  maybeBalancePartitionLeaders()
+  createPartitions(List<CreatePartitionsTopic>)
+  createPartitions(CreatePartitionsTopic;List<ApiMessageAndVersion>)
+  validateManualPartitionAssignment(List<Integer>;OptionalInt)
+  generateLeaderAndIsrUpdates(String;int;int;List<ApiMessageAndVersion>;Iterator<TopicIdPartition>)
+  alterPartitionReassignments(AlterPartitionReassignmentsRequestData)
+  alterPartitionReassignment(String;ReassignablePartition;List<ApiMessageAndVersion>)
+  cancelPartitionReassignment(String;TopicIdPartition;PartitionRegistration)
+  changePartitionReassignment(TopicIdPartition;PartitionRegistration;ReassignablePartition)
+  listPartitionReassignments(List<ListPartitionReassignmentsTopics>)
+  listReassigningTopic(ListPartitionReassignmentsResponseData;Uuid;List<Integer>)
+  getOngoingPartitionReassignment(TopicControlInfo;int)
+  iterator(long)
} 
@enduml
