@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.oauthbearer.OAuthBearerToken
class org.apache.kafka.common.security.oauthbearer.OAuthBearerToken {
+  value()
+  scope()
+  lifetimeMs()
+  principalName()
+  startTimeMs()
} 
@enduml
