@startuml
!pragma layout smetana
"Callback" <|-- "org.apache.kafka.common.security.oauthbearer.OAuthBearerExtensionsValidatorCallback"
class org.apache.kafka.common.security.oauthbearer.OAuthBearerExtensionsValidatorCallback {
+OAuthBearerExtensionsValidatorCallback(OAuthBearerToken;SaslExtensions) : OAuthBearerExtensionsValidatorCallback [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#52]]]
+token() : OAuthBearerToken [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#60]]]
+inputExtensions() : SaslExtensions [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#67]]]
+validatedExtensions() : Map<String,String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#74]]]
+invalidExtensions() : Map<String,String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#81]]]
+ignoredExtensions() : Map<String,String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#88]]]
+valid(String) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#96]]]
+error(String;String) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/OAuthBearerExtensionsValidatorCallback.java.html#109]]]
} 
@enduml
