@startuml
!pragma layout smetana
AbstractHerder <|-- org.apache.kafka.connect.runtime.standalone.StandaloneHerder
class org.apache.kafka.connect.runtime.standalone.StandaloneHerder {
+ StandaloneHerder(Worker;String;ConnectorClientConfigOverridePolicy) : StandaloneHerder [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#56]]]
StandaloneHerder(Worker;String;String;StatusBackingStore;MemoryConfigBackingStore;ConnectorClientConfigOverridePolicy) : StandaloneHerder [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#67]]]
+ start() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#80]]]
+ stop() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#88]]]
+ generation() : int [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#111]]]
+ connectors(Callback<Collection<String>>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#116]]]
+ connectorInfo(String;Callback<ConnectorInfo>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#121]]]
- createConnectorInfo(String) : ConnectorInfo [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#130]]]
rawConfig(String) : Map<String,String> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#139]]]
+ deleteConnectorConfig(String;Callback<Created<ConnectorInfo>>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#144]]]
+ putConnectorConfig(String;Map<String,String>;boolean;Callback<Created<ConnectorInfo>>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#164]]]
- putConnectorConfig(String;Map<String,String>;boolean;Callback<Created<ConnectorInfo>>;ConfigInfos) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#184]]]
+ requestTaskReconfiguration(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#225]]]
+ taskConfigs(String;Callback<List<TaskInfo>>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#234]]]
+ putTaskConfigs(String;List<Map<String,String>>;Callback<Void>;InternalRequestSignature) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#247]]]
+ fenceZombieSourceTasks(String;Callback<Void>;InternalRequestSignature) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#252]]]
+ restartTask(ConnectorTaskId;Callback<Void>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#257]]]
+ restartConnector(String;Callback<Void>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#274]]]
+ restartConnector(long;String;Callback<Void>) : HerderRequest [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#284]]]
+ restartConnectorAndTasks(RestartRequest;Callback<ConnectorStateInfo>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#292]]]
- startConnector(String;Callback<TargetState>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#340]]]
- recomputeTaskConfigs(String) : List<Map<String,String>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#346]]]
- createConnectorTasks(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#356]]]
- createConnectorTasks(String;Collection<ConnectorTaskId>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#361]]]
- startTask(ConnectorTaskId;Map<String,String>) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#368]]]
- removeConnectorTasks(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#393]]]
- updateConnectorTasks(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#402]]]
+ tasksConfig(String;Callback<Map<ConnectorTaskId,Map<String,String>>>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/standalone/StandaloneHerder.java.html#510]]]
} 
@enduml
