@startuml
!pragma layout smetana
Connector <|-- org.apache.kafka.connect.tools.MockConnector
class org.apache.kafka.connect.tools.MockConnector {
+version() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#34]]]
+start(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#39]]]
+taskClass() : Class<?extendsTask> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#60]]]
+taskConfigs(int) : List<Map<String,String>> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#65]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#71]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/MockConnector.java.html#85]]]
} 
@enduml
