@startuml
!pragma layout smetana
SinkTask <|-- org.apache.kafka.connect.tools.MockSinkTask
class org.apache.kafka.connect.tools.MockSinkTask {
+  version()
+  start(Map<String,String>)
+  put(Collection<SinkRecord>)
+  flush(Map<TopicPartition,OffsetAndMetadata>)
+  stop()
+  setTimeout()
} 
@enduml
