@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.tools.TransformationDoc"
class org.apache.kafka.connect.tools.TransformationDoc {
-printTransformationHtml(PrintStream;DocInfo) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/TransformationDoc.java.html#74]]]
-printHtml(PrintStream) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/TransformationDoc.java.html#90]]]
+main(String...) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/tools/TransformationDoc.java.html#96]]]
} 
@enduml
