@startuml
!pragma layout smetana
SourceTask <|-- org.apache.kafka.connect.tools.VerifiableSourceTask
class org.apache.kafka.connect.tools.VerifiableSourceTask {
+  version()
+  start(Map<String,String>)
+  poll()
+  commitRecord(SourceRecord;RecordMetadata)
+  stop()
} 
@enduml
