@startuml
!pragma layout smetana
SinkConnector <|-- org.apache.kafka.connect.tools.VerifiableSinkConnector
class org.apache.kafka.connect.tools.VerifiableSinkConnector {
+  version()
+  start(Map<String,String>)
+  taskClass()
+  taskConfigs(int)
+  stop()
+  config()
} 
@enduml
