@startuml
!pragma layout smetana
AbstractQueryResult_R_QueryResult_R_ <|-- org.apache.kafka.streams.query.internals.FailedQueryResult
class org.apache.kafka.streams.query.internals.FailedQueryResult {
+  FailedQueryResult(FailureReason;String)
+  isSuccess()
+  isFailure()
+  getFailureReason()
+  getFailureMessage()
+  getResult()
+  toString()
} 
@enduml
