@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.query.internals.InternalQueryResultUtil
class org.apache.kafka.streams.query.internals.InternalQueryResultUtil {
+ InternalQueryResultUtil() : InternalQueryResultUtil [[[././qc/streams/src/main/java/org/apache/kafka/streams/query/internals/InternalQueryResultUtil.java.html#11]]]
} 
@enduml
