@startuml
!pragma layout smetana
Suppressed_K_ <|-- org.apache.kafka.streams.kstream.internals.suppress.NamedSuppressed
class org.apache.kafka.streams.kstream.internals.suppress.NamedSuppressed {
+  name()
} 
@enduml
