@startuml
!pragma layout smetana
Suppressed<K> <|-- org.apache.kafka.streams.kstream.internals.suppress.NamedSuppressed
class org.apache.kafka.streams.kstream.internals.suppress.NamedSuppressed {
+  name()
} 
@enduml
