@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.replica.ClientMetadata
class org.apache.kafka.common.replica.ClientMetadata {
+  rackId()
+  clientId()
+  clientAddress()
+  principal()
+  listenerName()
} 
@enduml
