@startuml
!pragma layout smetana
"Configurable" <|-- "org.apache.kafka.common.replica.ReplicaSelector"
class org.apache.kafka.common.replica.ReplicaSelector {
select(TopicPartition;ClientMetadata;PartitionView) : Optional<ReplicaView> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/replica/ReplicaSelector.java.html#37]]]
close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/replica/ReplicaSelector.java.html#41]]]
configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/replica/ReplicaSelector.java.html#46]]]
} 
@enduml
