@startuml
!pragma layout smetana
"SnapshottableHashTable<TimelineHashSet.TimelineHashSetEntry<T>>Set<T>" <|-- "org.apache.kafka.timeline.TimelineHashSet"
class org.apache.kafka.timeline.TimelineHashSet {
+TimelineHashSet(SnapshotRegistry;int) : TimelineHashSet [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#52]]]
+size() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#57]]]
+size(long) : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#61]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#66]]]
+isEmpty(long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#70]]]
+contains(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#75]]]
+contains(Object;long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#79]]]
+iterator() : Iterator<T> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#107]]]
+iterator(long) : Iterator<T> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#111]]]
+toArray() : Object[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#116]]]
+add(T) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#146]]]
+remove(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#152]]]
+containsAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#157]]]
+addAll(Collection<?extendsT>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#165]]]
+retainAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#176]]]
+removeAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#190]]]
+clear() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#204]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#209]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#219]]]
} 
@enduml
