@startuml
!pragma layout smetana
"SnapshottableHashTable<TimelineHashSet.TimelineHashSetEntry<T>>Set<T>" <|-- "org.apache.kafka.timeline.TimelineHashSet"
class org.apache.kafka.timeline.TimelineHashSet {
+TimelineHashSet(SnapshotRegistry;int) : TimelineHashSet [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#75]]]
+size() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#80]]]
+size(long) : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#84]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#89]]]
+isEmpty(long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#93]]]
+contains(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#98]]]
+contains(Object;long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#102]]]
+iterator() : Iterator<T> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#130]]]
+iterator(long) : Iterator<T> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#134]]]
+toArray() : Object[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#139]]]
+add(T) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#169]]]
+remove(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#175]]]
+containsAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#180]]]
+addAll(Collection<?extendsT>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#188]]]
+retainAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#199]]]
+removeAll(Collection<?>) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#213]]]
+clear() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#227]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#232]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashSet.java.html#242]]]
} 
@enduml
