@startuml
!pragma layout smetana
"SnapshottableHashTable<TimelineHashMap.TimelineHashMapEntry<K,V>>Map<K,V>" <|-- "org.apache.kafka.timeline.TimelineHashMap"
class org.apache.kafka.timeline.TimelineHashMap {
+TimelineHashMap(SnapshotRegistry;int) : TimelineHashMap [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#97]]]
+size() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#102]]]
+size(long) : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#106]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#111]]]
+isEmpty(long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#115]]]
+containsKey(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#120]]]
+containsKey(Object;long) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#124]]]
+containsValue(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#129]]]
+get(Object) : V [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#141]]]
+get(Object;long) : V [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#145]]]
+put(K;V) : V [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#155]]]
+remove(Object) : V [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#167]]]
+putAll(Map<?extendsK,?extendsV>) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#174]]]
+clear() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#181]]]
+keySet() : Set<K> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#244]]]
+keySet(long) : Set<K> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#248]]]
+values() : Collection<V> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#304]]]
+values(long) : Collection<V> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#308]]]
+entrySet() : Set<Entry<K,V>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#370]]]
+entrySet(long) : Set<Entry<K,V>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#374]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#379]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/timeline/TimelineHashMap.java.html#389]]]
} 
@enduml
