@startuml
!pragma layout smetana
Deserializer_Bytes_ <|-- org.apache.kafka.common.serialization.BytesDeserializer
class org.apache.kafka.common.serialization.BytesDeserializer {
+  deserialize(String;byte[])
} 
@enduml
