@startuml
!pragma layout smetana
Closeable <|-- org.apache.kafka.common.serialization.Deserializer
class org.apache.kafka.common.serialization.Deserializer {
configure(Map<String,?>;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java.html#13]]]
deserialize(String;byte[]) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java.html#18]]]
deserialize(String;Headers;byte[]) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java.html#21]]]
close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java.html#27]]]
} 
@enduml
