@startuml
!pragma layout smetana
Deserializer_Float_ <|-- org.apache.kafka.common.serialization.FloatDeserializer
class org.apache.kafka.common.serialization.FloatDeserializer {
+  deserialize(String;byte[])
} 
@enduml
