@startuml
!pragma layout smetana
"Serializer<List<Inner>>" <|-- "org.apache.kafka.common.serialization.ListSerializer"
class org.apache.kafka.common.serialization.ListSerializer {
+ListSerializer() : ListSerializer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#52]]]
+ListSerializer(Serializer<Inner>) : ListSerializer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#54]]]
+getInnerSerializer() : Serializer<Inner> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#62]]]
+configure(Map<String,?>;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#68]]]
-serializeNullIndexList(DataOutputStream;List<Inner>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#93]]]
+serialize(String;List<Inner>) : byte[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#108]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/ListSerializer.java.html#143]]]
} 
@enduml
