@startuml
!pragma layout smetana
Deserializer_List_Inner__ <|-- org.apache.kafka.common.serialization.ListDeserializer
class org.apache.kafka.common.serialization.ListDeserializer {
+  ListDeserializer()
+  innerDeserializer()
+  configure(Map<String,?>;boolean)
+  configureListClass(Map<String,?>;boolean)
+  configureInnerSerde(Map<String,?>;boolean)
+  createListInstance(int)
+  parseSerializationStrategyFlag(int)
+  deserializeNullIndexList(DataInputStream)
+  deserialize(String;byte[])
+  close()
} 
@enduml
