@startuml
!pragma layout smetana
Deserializer_Short_ <|-- org.apache.kafka.common.serialization.ShortDeserializer
class org.apache.kafka.common.serialization.ShortDeserializer {
+  deserialize(String;byte[])
} 
@enduml
