@startuml
!pragma layout smetana
Serializer<Short> <|-- org.apache.kafka.common.serialization.ShortSerializer
class org.apache.kafka.common.serialization.ShortSerializer {
+  serialize(String;Short)
} 
@enduml
