@startuml
!pragma layout smetana
"Deserializer<String>" <|-- "org.apache.kafka.common.serialization.StringDeserializer"
class org.apache.kafka.common.serialization.StringDeserializer {
+configure(Map<String,?>;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/StringDeserializer.java.html#33]]]
+deserialize(String;byte[]) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/serialization/StringDeserializer.java.html#43]]]
} 
@enduml
