@startuml
!pragma layout smetana
Serializer_Void_ <|-- org.apache.kafka.common.serialization.VoidSerializer
class org.apache.kafka.common.serialization.VoidSerializer {
+  serialize(String;Void)
} 
@enduml
