@startuml
!pragma layout smetana
LogInputStream_MutableRecordBatch_ <|-- org.apache.kafka.common.record.ByteBufferLogInputStream
class org.apache.kafka.common.record.ByteBufferLogInputStream {
+  ByteBufferLogInputStream(ByteBuffer;int)
+  nextBatch()
+  nextBatchSize()
} 
@enduml
