@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.record.CompressionRatioEstimator"
class org.apache.kafka.common.record.CompressionRatioEstimator {
+updateEstimation(String;CompressionType;float) : float [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#42]]]
+estimation(String;CompressionType) : float [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#58]]]
+resetEstimation(String) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#66]]]
+removeEstimation(String) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#78]]]
+setEstimation(String;CompressionType;float) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#85]]]
-getAndCreateEstimationIfAbsent(String) : float[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#92]]]
-initialCompressionRatio() : float[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/CompressionRatioEstimator.java.html#104]]]
} 
@enduml
