@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.record.ControlRecordUtils"
class org.apache.kafka.common.record.ControlRecordUtils {
+deserializeLeaderChangeMessage(Record) : LeaderChangeMessage [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#35]]]
+deserializeLeaderChangeMessage(ByteBuffer) : LeaderChangeMessage [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#44]]]
+deserializedSnapshotHeaderRecord(Record) : SnapshotHeaderRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#49]]]
+deserializedSnapshotHeaderRecord(ByteBuffer) : SnapshotHeaderRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#58]]]
+deserializedSnapshotFooterRecord(Record) : SnapshotFooterRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#63]]]
+deserializedSnapshotFooterRecord(ByteBuffer) : SnapshotFooterRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/ControlRecordUtils.java.html#72]]]
} 
@enduml
