@startuml
!pragma layout smetana
"AbstractRecordBatchMutableRecordBatch" <|-- "org.apache.kafka.common.record.DefaultRecordBatch"
class org.apache.kafka.common.record.DefaultRecordBatch {
DefaultRecordBatch(ByteBuffer) : DefaultRecordBatch [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#141]]]
+magic() : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#146]]]
+ensureValid() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#151]]]
+baseTimestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#166]]]
+maxTimestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#171]]]
+timestampType() : TimestampType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#176]]]
+baseOffset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#181]]]
+lastOffset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#186]]]
+producerId() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#191]]]
+producerEpoch() : short [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#196]]]
+baseSequence() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#201]]]
-lastOffsetDelta() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#205]]]
+lastSequence() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#210]]]
+compressionType() : CompressionType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#218]]]
+sizeInBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#223]]]
-count() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#227]]]
+countOrNull() : Integer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#232]]]
+writeTo(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#237]]]
+writeTo(ByteBufferOutputStream) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#242]]]
+isTransactional() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#247]]]
-hasDeleteHorizonMs() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#251]]]
+deleteHorizonMs() : OptionalLong [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#256]]]
+isControlBatch() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#264]]]
+partitionLeaderEpoch() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#269]]]
+recordInputStream(BufferSupplier) : DataInputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#273]]]
-compressedIterator(BufferSupplier;boolean) : CloseableIterator<Record> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#279]]]
-uncompressedIterator() : CloseableIterator<Record> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#302]]]
+iterator() : Iterator<Record> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#324]]]
+skipKeyValueIterator(BufferSupplier) : CloseableIterator<Record> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#343]]]
+streamingIterator(BufferSupplier) : CloseableIterator<Record> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#362]]]
+setLastOffset(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#370]]]
+setMaxTimestamp(TimestampType;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#375]]]
+setPartitionLeaderEpoch(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#389]]]
+checksum() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#394]]]
+isValid() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#398]]]
-computeChecksum() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#402]]]
-attributes() : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#406]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#412]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#423]]]
-computeAttributes(CompressionType;TimestampType;boolean;boolean;boolean) : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#427]]]
+writeEmptyHeader(ByteBuffer;byte;long;short;int;long;long;int;TimestampType;long;boolean;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#445]]]
+writeHeader(ByteBuffer;long;int;int;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;boolean;int;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#463]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#506]]]
+sizeInBytes(long;Iterable<Record>) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#513]]]
+sizeInBytes(Iterable<SimpleRecord>) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#532]]]
estimateBatchSizeUpperBound(ByteBuffer;ByteBuffer;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#556]]]
+incrementSequence(int;int) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#560]]]
+decrementSequence(int;int) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java.html#566]]]
} 
@enduml
