@startuml
!pragma layout smetana
RecordsSend_T_ <|-- org.apache.kafka.common.record.DefaultRecordsSend
class org.apache.kafka.common.record.DefaultRecordsSend {
+  DefaultRecordsSend(T)
+  DefaultRecordsSend(T;int)
+  writeTo(TransferableChannel;long;int)
} 
@enduml
