@startuml
!pragma layout smetana
AbstractRecordBatchMutableRecordBatch <|-- org.apache.kafka.common.record.DefaultRecordBatch
class org.apache.kafka.common.record.DefaultRecordBatch {
+  DefaultRecordBatch(ByteBuffer)
+  magic()
+  ensureValid()
+  baseTimestamp()
+  maxTimestamp()
+  timestampType()
+  baseOffset()
+  lastOffset()
+  producerId()
+  producerEpoch()
+  baseSequence()
+  lastOffsetDelta()
+  lastSequence()
+  compressionType()
+  sizeInBytes()
+  count()
+  countOrNull()
+  writeTo(ByteBuffer)
+  writeTo(ByteBufferOutputStream)
+  isTransactional()
+  hasDeleteHorizonMs()
+  deleteHorizonMs()
+  isControlBatch()
+  partitionLeaderEpoch()
+  recordInputStream(BufferSupplier)
+  compressedIterator(BufferSupplier;boolean)
+  uncompressedIterator()
+  iterator()
+  skipKeyValueIterator(BufferSupplier)
+  streamingIterator(BufferSupplier)
+  setLastOffset(long)
+  setMaxTimestamp(TimestampType;long)
+  setPartitionLeaderEpoch(int)
+  checksum()
+  isValid()
+  computeChecksum()
+  attributes()
+  equals(Object)
+  hashCode()
+  computeAttributes(CompressionType;TimestampType;boolean;boolean;boolean)
+  writeEmptyHeader(ByteBuffer;byte;long;short;int;long;long;int;TimestampType;long;boolean;boolean)
+  writeHeader(ByteBuffer;long;int;int;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;boolean;int;int)
+  toString()
+  sizeInBytes(long;Iterable<Record>)
+  sizeInBytes(Iterable<SimpleRecord>)
+  estimateBatchSizeUpperBound(ByteBuffer;ByteBuffer;Header[])
+  incrementSequence(int;int)
+  decrementSequence(int;int)
} 
@enduml
