@startuml
!pragma layout smetana
"Record" <|-- "org.apache.kafka.common.record.DefaultRecord"
class org.apache.kafka.common.record.DefaultRecord {
DefaultRecord(int;byte;long;long;int;ByteBuffer;ByteBuffer;Header[]) : DefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#81]]]
+offset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#100]]]
+sequence() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#105]]]
+sizeInBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#110]]]
+timestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#115]]]
+attributes() : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#119]]]
+ensureValid() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#124]]]
+keySize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#127]]]
+valueSize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#132]]]
+hasKey() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#137]]]
+key() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#142]]]
+hasValue() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#147]]]
+value() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#152]]]
+headers() : Header[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#157]]]
+writeTo(DataOutputStream;int;long;ByteBuffer;ByteBuffer;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#164]]]
+hasMagic(byte) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#222]]]
+isCompressed() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#227]]]
+hasTimestampType(TimestampType) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#232]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#237]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#246]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#264]]]
+readFrom(DataInput;long;long;int;Long) : DefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#276]]]
+readFrom(ByteBuffer;long;long;int;Long) : DefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#289]]]
-readFrom(ByteBuffer;int;int;long;long;int;Long) : DefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#305]]]
+readPartiallyFrom(DataInput;byte[];long;long;int;Long) : PartialDefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#363]]]
-readPartiallyFrom(DataInput;byte[];int;int;long;long;int;Long) : PartialDefaultRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#376]]]
-readByte(ByteBuffer;DataInput;IntRef) : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#434]]]
-readVarLong(ByteBuffer;DataInput;IntRef) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#442]]]
-readVarInt(ByteBuffer;DataInput;IntRef) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#450]]]
-skipLengthDelimitedField(ByteBuffer;DataInput;IntRef) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#458]]]
-readMore(ByteBuffer;DataInput;IntRef) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#493]]]
-readHeaders(ByteBuffer;int) : Header[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#518]]]
+sizeInBytes(int;long;ByteBuffer;ByteBuffer;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#543]]]
+sizeInBytes(int;long;int;int;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#552]]]
-sizeOfBodyInBytes(int;long;ByteBuffer;ByteBuffer;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#561]]]
+sizeOfBodyInBytes(int;long;int;int;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#571]]]
-sizeOf(int;int;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#583]]]
recordSizeUpperBound(ByteBuffer;ByteBuffer;Header[]) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java.html#617]]]
} 
@enduml
