@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.record.EndTransactionMarker"
class org.apache.kafka.common.record.EndTransactionMarker {
+EndTransactionMarker(ControlRecordType;int) : EndTransactionMarker [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#50]]]
+coordinatorEpoch() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#56]]]
+controlType() : ControlRecordType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#60]]]
-buildRecordValue() : Struct [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#64]]]
+serializeValue() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#71]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#80]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#89]]]
-ensureTransactionMarkerControlType(ControlRecordType) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#95]]]
+deserialize(Record) : EndTransactionMarker [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#100]]]
deserializeValue(ControlRecordType;ByteBuffer) : EndTransactionMarker [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/EndTransactionMarker.java.html#105]]]
} 
@enduml
