@startuml
!pragma layout smetana
BaseRecords <|-- org.apache.kafka.common.record.LazyDownConversionRecords
class org.apache.kafka.common.record.LazyDownConversionRecords {
+ LazyDownConversionRecords(TopicPartition;Records;byte;long;Time) : LazyDownConversionRecords [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#23]]]
+ sizeInBytes() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#48]]]
+ toSend() : LazyDownConversionRecordsSend [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#53]]]
+ topicPartition() : TopicPartition [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#57]]]
+ equals(Object) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#62]]]
+ hashCode() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#74]]]
+ toString() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#83]]]
+ iterator(long) : java.util.Iterator<ConvertedRecords<?>> [[[././qc/clients/src/main/java/org/apache/kafka/common/record/LazyDownConversionRecords.java.html#91]]]
} 
@enduml
