@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.common.record.MemoryRecordsBuilder
class org.apache.kafka.common.record.MemoryRecordsBuilder {
+  MemoryRecordsBuilder(ByteBufferOutputStream;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int;long)
+  MemoryRecordsBuilder(ByteBufferOutputStream;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int)
+  MemoryRecordsBuilder(ByteBuffer;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int)
+  buffer()
+  initialCapacity()
+  compressionRatio()
+  compressionType()
+  isControlBatch()
+  isTransactional()
+  hasDeleteHorizonMs()
+  build()
+  info()
+  numRecords()
+  uncompressedBytesWritten()
+  setProducerState(long;short;int;boolean)
+  overrideLastOffset(long)
+  closeForRecordAppends()
+  abort()
+  reopenAndRewriteProducerState(long;short;int;boolean)
+  close()
+  validateProducerState()
+  writeDefaultBatchHeader()
+  writeLegacyCompressedWrapperHeader()
+  appendWithOffset(long;boolean;long;ByteBuffer;ByteBuffer;Header[])
+  appendWithOffset(long;long;byte[];byte[];Header[])
+  appendWithOffset(long;long;ByteBuffer;ByteBuffer;Header[])
+  appendWithOffset(long;long;byte[];byte[])
+  appendWithOffset(long;long;ByteBuffer;ByteBuffer)
+  appendWithOffset(long;SimpleRecord)
+  appendControlRecordWithOffset(long;SimpleRecord)
+  append(long;ByteBuffer;ByteBuffer)
+  append(long;ByteBuffer;ByteBuffer;Header[])
+  append(long;byte[];byte[])
+  append(long;byte[];byte[];Header[])
+  append(SimpleRecord)
+  appendControlRecord(long;ControlRecordType;ByteBuffer)
+  appendEndTxnMarker(long;EndTransactionMarker)
+  appendLeaderChangeMessage(long;LeaderChangeMessage)
+  appendSnapshotHeaderMessage(long;SnapshotHeaderRecord)
+  appendSnapshotFooterMessage(long;SnapshotFooterRecord)
+  appendUncheckedWithOffset(long;LegacyRecord)
+  appendUncheckedWithOffset(long;SimpleRecord)
+  append(Record)
+  appendWithOffset(long;Record)
+  appendWithOffset(long;LegacyRecord)
+  append(LegacyRecord)
+  appendDefaultRecord(long;long;ByteBuffer;ByteBuffer;Header[])
+  appendLegacyRecord(long;long;ByteBuffer;ByteBuffer;byte)
+  toInnerOffset(long)
+  recordWritten(long;long;int)
+  ensureOpenForRecordAppend()
+  ensureOpenForRecordBatchWrite()
+  estimatedBytesWritten()
+  setEstimatedCompressionRatio(float)
+  hasRoomFor(long;byte[];byte[];Header[])
+  hasRoomFor(long;ByteBuffer;ByteBuffer;Header[])
+  isClosed()
+  isFull()
+  estimatedSizeInBytes()
+  magic()
+  nextSequentialOffset()
+  producerId()
+  producerEpoch()
+  baseSequence()
} 
@enduml
