@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.common.record.MemoryRecordsBuilder"
class org.apache.kafka.common.record.MemoryRecordsBuilder {
+MemoryRecordsBuilder(ByteBufferOutputStream;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int;long) : MemoryRecordsBuilder [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#93]]]
+MemoryRecordsBuilder(ByteBufferOutputStream;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int) : MemoryRecordsBuilder [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#149]]]
+MemoryRecordsBuilder(ByteBuffer;byte;CompressionType;TimestampType;long;long;long;short;int;boolean;boolean;int;int) : MemoryRecordsBuilder [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#187]]]
+buffer() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#205]]]
+initialCapacity() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#209]]]
+compressionRatio() : double [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#213]]]
+compressionType() : CompressionType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#217]]]
+isControlBatch() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#221]]]
+isTransactional() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#225]]]
+hasDeleteHorizonMs() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#229]]]
+build() : MemoryRecords [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#237]]]
+info() : RecordsInfo [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#256]]]
+numRecords() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#278]]]
+uncompressedBytesWritten() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#285]]]
+setProducerState(long;short;int;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#289]]]
+overrideLastOffset(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#303]]]
+closeForRecordAppends() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#313]]]
+abort() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#325]]]
+reopenAndRewriteProducerState(long;short;int;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#331]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#342]]]
-validateProducerState() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#369]]]
-writeDefaultBatchHeader() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#389]]]
-writeLegacyCompressedWrapperHeader() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#416]]]
-appendWithOffset(long;boolean;long;ByteBuffer;ByteBuffer;Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#436]]]
+appendWithOffset(long;long;byte[];byte[];Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#473]]]
+appendWithOffset(long;long;ByteBuffer;ByteBuffer;Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#485]]]
+appendWithOffset(long;long;byte[];byte[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#496]]]
+appendWithOffset(long;long;ByteBuffer;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#507]]]
+appendWithOffset(long;SimpleRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#516]]]
+appendControlRecordWithOffset(long;SimpleRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#527]]]
+append(long;ByteBuffer;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#543]]]
+append(long;ByteBuffer;ByteBuffer;Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#554]]]
+append(long;byte[];byte[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#564]]]
+append(long;byte[];byte[];Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#575]]]
+append(SimpleRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#583]]]
-appendControlRecord(long;ControlRecordType;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#593]]]
+appendEndTxnMarker(long;EndTransactionMarker) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#601]]]
+appendLeaderChangeMessage(long;LeaderChangeMessage) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#610]]]
+appendSnapshotHeaderMessage(long;SnapshotHeaderRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#618]]]
+appendSnapshotFooterMessage(long;SnapshotFooterRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#623]]]
+appendUncheckedWithOffset(long;LegacyRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#633]]]
+appendUncheckedWithOffset(long;SimpleRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#654]]]
+append(Record) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#681]]]
+appendWithOffset(long;Record) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#690]]]
+appendWithOffset(long;LegacyRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#700]]]
+append(LegacyRecord) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#709]]]
-appendDefaultRecord(long;long;ByteBuffer;ByteBuffer;Header[]) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#713]]]
-appendLegacyRecord(long;long;ByteBuffer;ByteBuffer;byte) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#722]]]
-toInnerOffset(long) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#737]]]
-recordWritten(long;long;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#744]]]
-ensureOpenForRecordAppend() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#761]]]
-ensureOpenForRecordBatchWrite() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#766]]]
-estimatedBytesWritten() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#777]]]
+setEstimatedCompressionRatio(float) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#789]]]
+hasRoomFor(long;byte[];byte[];Header[]) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#797]]]
+hasRoomFor(long;ByteBuffer;ByteBuffer;Header[]) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#809]]]
+isClosed() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#830]]]
+isFull() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#834]]]
+estimatedSizeInBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#844]]]
+magic() : byte [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#848]]]
-nextSequentialOffset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#852]]]
+producerId() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#870]]]
+producerEpoch() : short [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#874]]]
+baseSequence() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java.html#878]]]
} 
@enduml
