@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.record.Record"
class org.apache.kafka.common.record.Record {
offset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#35]]]
sequence() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#41]]]
sizeInBytes() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#47]]]
timestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#53]]]
ensureValid() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#58]]]
keySize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#64]]]
hasKey() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#70]]]
key() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#76]]]
valueSize() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#82]]]
hasValue() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#88]]]
value() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#94]]]
hasMagic(byte) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#104]]]
isCompressed() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#111]]]
hasTimestampType(TimestampType) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#121]]]
headers() : Header[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#128]]]
} 
@enduml
