@startuml
!pragma layout smetana
"Send" <|-- "org.apache.kafka.common.record.RecordsSend"
class org.apache.kafka.common.record.RecordsSend {
RecordsSend(T;int) : RecordsSend [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#34]]]
+completed() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#41]]]
+writeTo(TransferableChannel) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#46]]]
+size() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#64]]]
records() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#68]]]
writeTo(TransferableChannel;long;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/RecordsSend.java.html#83]]]
} 
@enduml
