@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.record.Record
class org.apache.kafka.common.record.Record {
offset() : long [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#14]]]
sequence() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#17]]]
sizeInBytes() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#20]]]
timestamp() : long [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#23]]]
ensureValid() : void [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#26]]]
keySize() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#29]]]
hasKey() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#32]]]
key() : ByteBuffer [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#35]]]
valueSize() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#38]]]
hasValue() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#41]]]
value() : ByteBuffer [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#44]]]
hasMagic(byte) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#47]]]
isCompressed() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#50]]]
hasTimestampType(TimestampType) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#53]]]
headers() : Header[] [[[././qc/clients/src/main/java/org/apache/kafka/common/record/Record.java.html#56]]]
} 
@enduml
