@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.record.SimpleRecord
class org.apache.kafka.common.record.SimpleRecord {
+SimpleRecord(long;ByteBuffer;ByteBuffer;Header[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#18]]]
+SimpleRecord(long;byte[];byte[];Header[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#26]]]
+SimpleRecord(long;ByteBuffer;ByteBuffer) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#30]]]
+SimpleRecord(long;byte[];byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#34]]]
+SimpleRecord(long;byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#38]]]
+SimpleRecord(byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#42]]]
+SimpleRecord(ByteBuffer) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#46]]]
+SimpleRecord(byte[];byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#50]]]
+SimpleRecord(Record) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#54]]]
+key() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#58]]]
+value() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#62]]]
+timestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#66]]]
+headers() : Header[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#70]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#75]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#89]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#98]]]
} 
@enduml
