@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.record.SimpleRecord"
class org.apache.kafka.common.record.SimpleRecord {
+SimpleRecord(long;ByteBuffer;ByteBuffer;Header[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#36]]]
+SimpleRecord(long;byte[];byte[];Header[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#44]]]
+SimpleRecord(long;ByteBuffer;ByteBuffer) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#48]]]
+SimpleRecord(long;byte[];byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#52]]]
+SimpleRecord(long;byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#56]]]
+SimpleRecord(byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#60]]]
+SimpleRecord(ByteBuffer) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#64]]]
+SimpleRecord(byte[];byte[]) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#68]]]
+SimpleRecord(Record) : SimpleRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#72]]]
+key() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#76]]]
+value() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#80]]]
+timestamp() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#84]]]
+headers() : Header[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#88]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#93]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#107]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/record/SimpleRecord.java.html#116]]]
} 
@enduml
