@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.producer.ProducerRecord"
class org.apache.kafka.clients.producer.ProducerRecord {
+ProducerRecord(String;Integer;Long;K;V;Iterable<Header>) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#69]]]
+ProducerRecord(String;Integer;Long;K;V) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#96]]]
+ProducerRecord(String;Integer;K;V;Iterable<Header>) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#109]]]
+ProducerRecord(String;Integer;K;V) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#121]]]
+ProducerRecord(String;K;V) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#132]]]
+ProducerRecord(String;V) : ProducerRecord [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#142]]]
+topic() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#149]]]
+headers() : Headers [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#156]]]
+key() : K [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#163]]]
+value() : V [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#170]]]
+timestamp() : Long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#177]]]
+partition() : Integer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#184]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#189]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#199]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/ProducerRecord.java.html#216]]]
} 
@enduml
