@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource
class org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource {
+  ConnectorPluginsResource(Herder)
+  validateConfigs(String;Map<String,String>)
+  listConnectorPlugins(boolean)
+  getConnectorConfigDef(String)
+  normalizedPluginName(String)
} 
@enduml
