@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.rest.resources.RootResource
class org.apache.kafka.connect.runtime.rest.resources.RootResource {
+  RootResource(Herder)
+  serverInfo()
} 
@enduml
