@startuml
!pragma layout smetana
"SourceTask" <|-- "org.apache.kafka.connect.file.FileStreamSourceTask"
class org.apache.kafka.connect.file.FileStreamSourceTask {
+FileStreamSourceTask() : FileStreamSourceTask [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#41]]]
FileStreamSourceTask(int) : FileStreamSourceTask [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#46]]]
+version() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#51]]]
+start(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#56]]]
+poll() : List<SourceRecord> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#71]]]
-extractLine() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#172]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#203]]]
-offsetKey(String) : Map<String,String> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#218]]]
-offsetValue(Long) : Map<String,Long> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#222]]]
-logFilename() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#226]]]
bufferSize() : int [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#231]]]
} 
@enduml
