@startuml
!pragma layout smetana
"SinkConnector" <|-- "org.apache.kafka.connect.file.FileStreamSinkConnector"
class org.apache.kafka.connect.file.FileStreamSinkConnector {
+version() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#45]]]
+start(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#50]]]
+taskClass() : Class<?extendsTask> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#56]]]
+taskConfigs(int) : List<Map<String,String>> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#61]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#73]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSinkConnector.java.html#78]]]
} 
@enduml
