@startuml
!pragma layout smetana
"SourceTask" <|-- "org.apache.kafka.connect.file.FileStreamSourceTask"
class org.apache.kafka.connect.file.FileStreamSourceTask {
+FileStreamSourceTask() : FileStreamSourceTask [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#58]]]
FileStreamSourceTask(int) : FileStreamSourceTask [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#63]]]
+version() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#68]]]
+start(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#73]]]
+poll() : List<SourceRecord> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#88]]]
-extractLine() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#189]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#220]]]
-offsetKey(String) : Map<String,String> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#235]]]
-offsetValue(Long) : Map<String,Long> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#239]]]
-logFilename() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#243]]]
bufferSize() : int [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceTask.java.html#248]]]
} 
@enduml
