@startuml
!pragma layout smetana
"SourceConnector" <|-- "org.apache.kafka.connect.file.FileStreamSourceConnector"
class org.apache.kafka.connect.file.FileStreamSourceConnector {
+version() : String [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#55]]]
+start(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#60]]]
+taskClass() : Class<?extendsTask> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#72]]]
+taskConfigs(int) : List<Map<String,String>> [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#77]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#90]]]
+config() : ConfigDef [[[./../../../../../../../../../../.././qc/connect/file/src/main/java/org/apache/kafka/connect/file/FileStreamSourceConnector.java.html#95]]]
} 
@enduml
