@startuml
!pragma layout smetana
Configurable <|-- org.apache.kafka.connect.mirror.GroupFilter
class org.apache.kafka.connect.mirror.GroupFilter {
+  shouldReplicateGroup(String)
+  close()
+  configure(Map<String,?>)
} 
@enduml
