@startuml
!pragma layout smetana
SourceTask <|-- org.apache.kafka.connect.mirror.MirrorCheckpointTask
class org.apache.kafka.connect.mirror.MirrorCheckpointTask {
+ MirrorCheckpointTask() : MirrorCheckpointTask [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#55]]]
MirrorCheckpointTask(String;String;ReplicationPolicy;OffsetSyncStore;Map<String,Map<TopicPartition,OffsetAndMetadata>>;Map<String,List<Checkpoint>>) : MirrorCheckpointTask [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#58]]]
+ start(Map<String,String>) : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#71]]]
+ commit() : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#96]]]
+ stop() : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#101]]]
+ version() : String [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#114]]]
+ poll() : List<SourceRecord> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#119]]]
- sourceRecordsForGroup(String) : List<SourceRecord> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#142]]]
- checkpointsForGroup(String) : List<Checkpoint> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#156]]]
- listConsumerGroupOffsets(String) : Map<TopicPartition,OffsetAndMetadata> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#165]]]
checkpoint(String;TopicPartition;OffsetAndMetadata) : Optional<Checkpoint> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#174]]]
checkpointRecord(Checkpoint;long) : SourceRecord [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#186]]]
renameTopicPartition(TopicPartition) : TopicPartition [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#195]]]
shouldCheckpointTopic(String) : boolean [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#207]]]
+ commitRecord(SourceRecord;RecordMetadata) : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#212]]]
- refreshIdleConsumerGroupOffset() : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#218]]]
syncGroupOffset() : Map<String,Map<TopicPartition,OffsetAndMetadata>> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#240]]]
syncGroupOffset(String;Map<TopicPartition,OffsetAndMetadata>) : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#292]]]
getConvertedUpstreamOffset() : Map<String,Map<TopicPartition,OffsetAndMetadata>> [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorCheckpointTask.java.html#300]]]
} 
@enduml
