@startuml
!pragma layout smetana
SourceConnector <|-- org.apache.kafka.connect.mirror.MirrorSourceConnector
class org.apache.kafka.connect.mirror.MirrorSourceConnector {
+  MirrorSourceConnector()
+  MirrorSourceConnector(List<TopicPartition>;MirrorConnectorConfig)
+  MirrorSourceConnector(SourceAndTarget;ReplicationPolicy;TopicFilter;ConfigPropertyFilter)
+  start(Map<String,String>)
+  stop()
+  taskClass()
+  taskConfigs(int)
+  config()
+  version()
+  findSourceTopicPartitions()
+  findTargetTopicPartitions()
+  refreshTopicPartitions()
+  loadTopicPartitions()
+  refreshKnownTargetTopics()
+  topicsBeingReplicated()
+  toTopics(Collection<TopicPartition>)
+  syncTopicAcls()
+  syncTopicConfigs()
+  createOffsetSyncsTopic()
+  computeAndCreateTopicPartitions()
+  createNewTopics(Set<String>;Map<String,Long>)
+  createNewTopics(Map<String,NewTopic>)
+  createNewPartitions(Map<String,NewPartitions>)
+  listTopics(AdminClient)
+  listTopicAclBindings()
+  describeTopics(AdminClient;Collection<String>)
+  configToMap(Config)
+  updateTopicConfigs(Map<String,Config>)
+  updateTopicAcls(List<AclBinding>)
+  expandTopicDescription(TopicDescription)
+  describeTopicConfigs(Set<String>)
+  targetConfig(Config)
+  downgradeAllowAllACL(AccessControlEntry)
+  targetAclBinding(AclBinding)
+  shouldReplicateTopic(String)
+  shouldReplicateAcl(AclBinding)
+  shouldReplicateTopicConfigurationProperty(String)
+  isCycle(String)
+  formatRemoteTopic(String)
} 
@enduml
