@startuml
!pragma layout smetana
"AutoCloseable" <|-- "org.apache.kafka.connect.mirror.MirrorMetrics"
class org.apache.kafka.connect.mirror.MirrorMetrics {
MirrorMetrics(MirrorTaskConfig) : MirrorMetrics [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#104]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#123]]]
countRecord(TopicPartition) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#127]]]
recordAge(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#131]]]
replicationLatency(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#135]]]
recordBytes(TopicPartition;long) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#139]]]
checkpointLatency(TopicPartition;String;long) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#143]]]
group(TopicPartition;String) : GroupMetrics [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#147]]]
addReporter(MetricsReporter) : void [[[./../../../../../../../../../../.././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorMetrics.java.html#152]]]
} 
@enduml
