@startuml
!pragma layout smetana
"NamedOperation<Branched<K,V>>" <|-- "org.apache.kafka.streams.kstream.Branched"
class org.apache.kafka.streams.kstream.Branched {
Branched(String;Function<?superKStream<K,V>,?extendsKStream<K,V>>;Consumer<?superKStream<K,V>>) : Branched [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Branched.java.html#36]]]
Branched(Branched<K,V>) : Branched [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Branched.java.html#133]]]
+withName(String) : Branched<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Branched.java.html#145]]]
} 
@enduml
