@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.kstream.EmitStrategy
class org.apache.kafka.streams.kstream.EmitStrategy {
type() : StrategyType [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/EmitStrategy.java.html#54]]]
onWindowClose() : EmitStrategy [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/EmitStrategy.java.html#57]]]
onWindowUpdate() : EmitStrategy [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/EmitStrategy.java.html#62]]]
} 
@enduml
