@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.kstream.EmitStrategy
class org.apache.kafka.streams.kstream.EmitStrategy {
+  type()
+  onWindowClose()
+  onWindowUpdate()
} 
@enduml
