@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.kstream.KGroupedTable
class org.apache.kafka.streams.kstream.KGroupedTable {
+  count(Materialized<K,Long,KeyValueStore<Bytes,byte[]>>)
+  count(Named;Materialized<K,Long,KeyValueStore<Bytes,byte[]>>)
+  count()
+  count(Named)
+  reduce(Reducer<V>;Reducer<V>;Materialized<K,V,KeyValueStore<Bytes,byte[]>>)
+  reduce(Reducer<V>;Reducer<V>;Named;Materialized<K,V,KeyValueStore<Bytes,byte[]>>)
+  reduce(Reducer<V>;Reducer<V>)
} 
@enduml
