@startuml
!pragma layout smetana
"NamedOperation<Repartitioned<K,V>>" <|-- "org.apache.kafka.streams.kstream.Repartitioned"
class org.apache.kafka.streams.kstream.Repartitioned {
-Repartitioned(String;Serde<K>;Serde<V>;Integer;StreamPartitioner<K,V>) : Repartitioned [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#18]]]
Repartitioned(Repartitioned<K,V>) : Repartitioned [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#30]]]
+withName(String) : Repartitioned<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#63]]]
+withNumberOfPartitions(int) : Repartitioned<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#68]]]
+withKeySerde(Serde<K>) : Repartitioned<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#73]]]
+withValueSerde(Serde<V>) : Repartitioned<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#78]]]
+withStreamPartitioner(StreamPartitioner<K,V>) : Repartitioned<K,V> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/Repartitioned.java.html#83]]]
} 
@enduml
