@startuml
!pragma layout smetana
WindowedSerializer_T_ <|-- org.apache.kafka.streams.kstream.SessionWindowedSerializer
class org.apache.kafka.streams.kstream.SessionWindowedSerializer {
+  SessionWindowedSerializer()
+  SessionWindowedSerializer(Serializer<T>)
+  configure(Map<String,?>;boolean)
+  serialize(String;Windowed<T>)
+  close()
+  serializeBaseKey(String;Windowed<T>)
+  innerSerializer()
} 
@enduml
