@startuml
!pragma layout smetana
Deserializer_Windowed_T__ <|-- org.apache.kafka.streams.kstream.SessionWindowedDeserializer
class org.apache.kafka.streams.kstream.SessionWindowedDeserializer {
+  SessionWindowedDeserializer()
+  SessionWindowedDeserializer(Deserializer<T>)
+  configure(Map<String,?>;boolean)
+  deserialize(String;byte[])
+  close()
+  innerDeserializer()
} 
@enduml
