@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.kstream.SessionWindows"
class org.apache.kafka.streams.kstream.SessionWindows {
-SessionWindows(long;long;boolean) : SessionWindows [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#82]]]
+ofInactivityGapWithNoGrace(Duration) : SessionWindows [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#110]]]
+ofInactivityGapAndGrace(Duration;Duration) : SessionWindows [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#132]]]
+with(Duration) : SessionWindows [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#151]]]
+grace(Duration) : SessionWindows [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#173]]]
+gracePeriodMs() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#185]]]
+inactivityGap() : long [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#194]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#199]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#212]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindows.java.html#217]]]
} 
@enduml
