@startuml
!pragma layout smetana
"NamedOperation<StreamJoined<K,V1,V2>>" <|-- "org.apache.kafka.streams.kstream.StreamJoined"
class org.apache.kafka.streams.kstream.StreamJoined {
StreamJoined(StreamJoined<K,V1,V2>) : StreamJoined [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#45]]]
-StreamJoined(Serde<K>;Serde<V1>;Serde<V2>;WindowBytesStoreSupplier;WindowBytesStoreSupplier;String;String;boolean;Map<String,String>) : StreamJoined [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#57]]]
+withName(String) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#170]]]
+withStoreName(String) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#194]]]
+withKeySerde(Serde<K>) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#213]]]
+withValueSerde(Serde<V1>) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#232]]]
+withOtherValueSerde(Serde<V2>) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#251]]]
+withThisStoreSupplier(WindowBytesStoreSupplier) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#273]]]
+withOtherStoreSupplier(WindowBytesStoreSupplier) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#295]]]
+withLoggingEnabled(Map<String,String>) : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#316]]]
+withLoggingDisabled() : StreamJoined<K,V1,V2> [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#335]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/StreamJoined.java.html#350]]]
} 
@enduml
