@startuml
!pragma layout smetana
NamedOperation_Suppressed_K__ <|-- org.apache.kafka.streams.kstream.Suppressed
class org.apache.kafka.streams.kstream.Suppressed {
+  untilWindowCloses(StrictBufferConfig)
+  withName(String)
} 
@enduml
