@startuml
!pragma layout smetana
WindowedSerializer<T> <|-- org.apache.kafka.streams.kstream.TimeWindowedSerializer
class org.apache.kafka.streams.kstream.TimeWindowedSerializer {
+  TimeWindowedSerializer()
+  TimeWindowedSerializer(Serializer<T>)
+  configure(Map<String,?>;boolean)
+  serialize(String;Windowed<T>)
+  close()
+  serializeBaseKey(String;Windowed<T>)
+  innerSerializer()
} 
@enduml
