@startuml
!pragma layout smetana
Windows_TimeWindow_ <|-- org.apache.kafka.streams.kstream.TimeWindows
class org.apache.kafka.streams.kstream.TimeWindows {
- TimeWindows(long;long;long;boolean) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#32]]]
+ ofSizeWithNoGrace(Duration) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#53]]]
+ ofSizeAndGrace(Duration;Duration) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#58]]]
+ of(Duration) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#70]]]
+ advanceBy(Duration) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#78]]]
+ windowsFor(long) : Map<Long,TimeWindow> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#85]]]
+ size() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#97]]]
+ grace(Duration) : TimeWindows [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#103]]]
+ gracePeriodMs() : long [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#116]]]
+ equals(Object) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#121]]]
+ hashCode() : int [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#135]]]
+ toString() : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/TimeWindows.java.html#140]]]
} 
@enduml
