@startuml
!pragma layout smetana
Deserializer_Windowed_T__ <|-- org.apache.kafka.streams.kstream.TimeWindowedDeserializer
class org.apache.kafka.streams.kstream.TimeWindowedDeserializer {
+  TimeWindowedDeserializer()
+  TimeWindowedDeserializer(Deserializer<T>)
+  TimeWindowedDeserializer(Deserializer<T>;Long)
+  getWindowSize()
+  configure(Map<String,?>;boolean)
+  deserialize(String;byte[])
+  close()
+  setIsChangelogTopic(boolean)
+  innerDeserializer()
} 
@enduml
