@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.kstream.ValueTransformer
class org.apache.kafka.streams.kstream.ValueTransformer {
+  init(ProcessorContext)
+  transform(V)
+  close()
} 
@enduml
