@startuml
!pragma layout smetana
ConnectedStoreProvider <|-- org.apache.kafka.streams.kstream.ValueTransformerWithKeySupplier
class org.apache.kafka.streams.kstream.ValueTransformerWithKeySupplier {
+  get()
} 
@enduml
