@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.metadata.BrokerRegistrationReply
class org.apache.kafka.metadata.BrokerRegistrationReply {
+  BrokerRegistrationReply(long)
+  epoch()
+  hashCode()
+  equals(Object)
+  toString()
} 
@enduml
