@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.metadata.ConfigSynonym"
class org.apache.kafka.metadata.ConfigSynonym {
-valueToInt(String;int;String) : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/ConfigSynonym.java.html#44]]]
+ConfigSynonym(String;Function<String,String>) : ConfigSynonym [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/ConfigSynonym.java.html#61]]]
+ConfigSynonym(String) : ConfigSynonym [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/ConfigSynonym.java.html#66]]]
+name() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/ConfigSynonym.java.html#70]]]
+converter() : Function<String,String> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/ConfigSynonym.java.html#74]]]
} 
@enduml
