@startuml
!pragma layout smetana
"AbstractApiMessageSerde" <|-- "org.apache.kafka.metadata.MetadataRecordSerde"
class org.apache.kafka.metadata.MetadataRecordSerde {
+apiMessageFor(short) : ApiMessage [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/MetadataRecordSerde.java.html#12]]]
} 
@enduml
