@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.metadata.Replicas"
class org.apache.kafka.metadata.Replicas {
+toList(int[]) : List<Integer> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#39]]]
+toArray(List<Integer>) : int[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#54]]]
+clone(int[]) : int[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#69]]]
+validate(int[]) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#82]]]
+validateIsr(int[];int[]) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#104]]]
+contains(int[];int) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#135]]]
+contains(List<Integer>;int[]) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#150]]]
+copyWithout(int[];int) : int[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#175]]]
+copyWithout(int[];int[]) : int[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#201]]]
+copyWith(int[];int) : int[] [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#227]]]
+toSet(int[]) : Set<Integer> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/metadata/Replicas.java.html#241]]]
} 
@enduml
