@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.Connect"
class org.apache.kafka.connect.runtime.Connect {
+Connect(Herder;RestServer) : Connect [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#41]]]
+start() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#48]]]
+stop() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#62]]]
+awaitStop() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#78]]]
+isRunning() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#86]]]
+rest() : RestServer [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Connect.java.html#91]]]
} 
@enduml
