@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.HerderRequest
class org.apache.kafka.connect.runtime.HerderRequest {
cancel() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/HerderRequest.java.html#5]]]
} 
@enduml
