@startuml
!pragma layout smetana
"CloseableConnectorContext" <|-- "org.apache.kafka.connect.runtime.HerderConnectorContext"
class org.apache.kafka.connect.runtime.HerderConnectorContext {
+HerderConnectorContext(AbstractHerder;String) : HerderConnectorContext [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/HerderConnectorContext.java.html#34]]]
+requestTaskReconfiguration() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/HerderConnectorContext.java.html#41]]]
+raiseError(Exception) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/HerderConnectorContext.java.html#54]]]
+close() : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/HerderConnectorContext.java.html#66]]]
} 
@enduml
