@startuml
!pragma layout smetana
"SinkRecord" <|-- "org.apache.kafka.connect.runtime.InternalSinkRecord"
class org.apache.kafka.connect.runtime.InternalSinkRecord {
+InternalSinkRecord(ConsumerRecord<byte[],byte[]>;SinkRecord) : InternalSinkRecord [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#35]]]
InternalSinkRecord(ConsumerRecord<byte[],byte[]>;String;int;Schema;Object;Schema;Object;long;Long;TimestampType;Iterable<Header>) : InternalSinkRecord [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#42]]]
+newRecord(String;Integer;Schema;Object;Schema;Object;Long;Iterable<Header>) : SinkRecord [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#51]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#59]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#64]]]
+toString() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#69]]]
+originalRecord() : ConsumerRecord<byte[],byte[]> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/InternalSinkRecord.java.html#78]]]
} 
@enduml
