@startuml
!pragma layout smetana
"Comparable<RestartRequest>" <|-- "org.apache.kafka.connect.runtime.RestartRequest"
class org.apache.kafka.connect.runtime.RestartRequest {
+RestartRequest(String;boolean;boolean) : RestartRequest [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#17]]]
+connectorName() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#24]]]
+onlyFailed() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#29]]]
+includeTasks() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#34]]]
+shouldRestartConnector(ConnectorStatus) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#39]]]
+forceRestartConnectorOnly() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#44]]]
+shouldRestartTask(TaskStatus) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#49]]]
+compareTo(RestartRequest) : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#54]]]
-impactRank() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#59]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#72]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#84]]]
+toString() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartRequest.java.html#89]]]
} 
@enduml
