@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.RestartPlan"
class org.apache.kafka.connect.runtime.RestartPlan {
+RestartPlan(RestartRequest;ConnectorStateInfo) : RestartPlan [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#44]]]
+connectorName() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#62]]]
+restartRequest() : RestartRequest [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#71]]]
+restartConnectorStateInfo() : ConnectorStateInfo [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#82]]]
+taskIdsToRestart() : Collection<ConnectorTaskId> [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#92]]]
+shouldRestartConnector() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#102]]]
+shouldRestartTasks() : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#112]]]
+restartTaskCount() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#122]]]
+totalTaskCount() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#131]]]
-isRestarting(ConnectorStateInfo.AbstractState) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#135]]]
-isRestarting(String) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#139]]]
+toString() : String [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/RestartPlan.java.html#144]]]
} 
@enduml
