@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.SessionKey"
class org.apache.kafka.connect.runtime.SessionKey {
+SessionKey(SecretKey;long) : SessionKey [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SessionKey.java.html#35]]]
+key() : SecretKey [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SessionKey.java.html#45]]]
+creationTimestamp() : long [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SessionKey.java.html#54]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SessionKey.java.html#59]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SessionKey.java.html#70]]]
} 
@enduml
