@startuml
!pragma layout smetana
ConnectorConfig <|-- org.apache.kafka.connect.runtime.SinkConnectorConfig
class org.apache.kafka.connect.runtime.SinkConnectorConfig {
+ configDef() : ConfigDef [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#63]]]
+ SinkConnectorConfig(Plugins;Map<String,String>) : SinkConnectorConfig [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#67]]]
+ validate(Map<String,String>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#72]]]
+ hasTopicsConfig(Map<String,String>) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#107]]]
+ hasTopicsRegexConfig(Map<String,String>) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#112]]]
+ hasDlqTopicConfig(Map<String,String>) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#117]]]
+ parseTopicsList(Map<String,String>) : List<String> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#123]]]
+ dlqTopicName() : String [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#135]]]
+ dlqTopicReplicationFactor() : short [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#139]]]
+ isDlqContextHeadersEnabled() : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#143]]]
+ enableErrantRecordReporter() : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#147]]]
+ main(String[]) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SinkConnectorConfig.java.html#152]]]
} 
@enduml
