@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter"
class org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter {
SourceTaskOffsetCommitter(WorkerConfig;ScheduledExecutorService;ConcurrentMap<ConnectorTaskId,ScheduledFuture<?>>) : SourceTaskOffsetCommitter [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#55]]]
+SourceTaskOffsetCommitter(WorkerConfig) : SourceTaskOffsetCommitter [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#63]]]
+close(long) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#69]]]
+schedule(ConnectorTaskId;WorkerSourceTask) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#80]]]
+remove(ConnectorTaskId) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#90]]]
-commit(WorkerSourceTask) : void [[[./../../../../../../../../../../.././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/SourceTaskOffsetCommitter.java.html#107]]]
} 
@enduml
