@startuml
!pragma layout smetana
AutoCloseable <|-- org.apache.kafka.connect.runtime.TransformationChain
class org.apache.kafka.connect.runtime.TransformationChain {
+  TransformationChain(List<Transformation<R>>;RetryWithToleranceOperator)
+  apply(R)
+  close()
+  equals(Object)
+  hashCode()
+  toString()
} 
@enduml
