@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.connect.runtime.Worker
class org.apache.kafka.connect.runtime.Worker {
+ Worker(String;Time;Plugins;WorkerConfig;OffsetBackingStore;ConnectorClientConfigOverridePolicy) : Worker [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#114]]]
Worker(String;Time;Plugins;WorkerConfig;OffsetBackingStore;ExecutorService;ConnectorClientConfigOverridePolicy) : Worker [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#124]]]
- initConfigTransformer() : WorkerConfigTransformer [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#154]]]
+ configTransformer() : WorkerConfigTransformer [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#168]]]
herder() : Herder [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#172]]]
+ start() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#177]]]
+ stop() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#192]]]
+ startConnector(String;Map<String,String>;CloseableConnectorContext;ConnectorStatus.Listener;TargetState;Callback<TargetState>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#237]]]
+ isSinkConnector(String) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#316]]]
+ connectorTaskConfigs(String;ConnectorConfig) : List<Map<String,String>> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#331]]]
- stopConnector(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#369]]]
- stopConnectors(Collection<String>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#389]]]
- awaitStopConnector(String;long) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#396]]]
- awaitStopConnectors(Collection<String>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#417]]]
+ stopAndAwaitConnectors() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#427]]]
+ stopAndAwaitConnectors(Collection<String>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#432]]]
+ stopAndAwaitConnector(String) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#438]]]
+ connectorNames() : Set<String> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#444]]]
+ isRunning(String) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#449]]]
+ startSinkTask(ConnectorTaskId;ClusterConfigState;Map<String,String>;Map<String,String>;TaskStatus.Listener;TargetState) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#455]]]
+ startSourceTask(ConnectorTaskId;ClusterConfigState;Map<String,String>;Map<String,String>;TaskStatus.Listener;TargetState) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#468]]]
+ startExactlyOnceSourceTask(ConnectorTaskId;ClusterConfigState;Map<String,String>;Map<String,String>;TaskStatus.Listener;TargetState;Runnable;Runnable) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#481]]]
- startTask(ConnectorTaskId;Map<String,String>;Map<String,String>;TaskStatus.Listener;TaskBuilder) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#496]]]
+ fenceZombies(String;int;Map<String,String>) : KafkaFuture<Void> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#586]]]
fenceZombies(String;int;Map<String,String>;Function<Map<String,Object>,Admin>) : KafkaFuture<Void> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#591]]]
exactlyOnceSourceTaskProducerConfigs(ConnectorTaskId;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#632]]]
baseProducerConfigs(String;String;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#653]]]
exactlyOnceSourceOffsetsConsumerConfigs(String;String;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#692]]]
regularSourceOffsetsConsumerConfigs(String;String;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#710]]]
baseConsumerConfigs(String;String;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String;ConnectorType) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#727]]]
adminConfigs(String;String;WorkerConfig;ConnectorConfig;Class<?extendsConnector>;ConnectorClientConfigOverridePolicy;String;ConnectorType) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#760]]]
- connectorClientConfigOverrides(String;ConnectorConfig;Class<?extendsConnector>;String;ConnectorType;ConnectorClientConfigRequest.ClientType;ConnectorClientConfigOverridePolicy) : Map<String,Object> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#799]]]
- taskTransactionalId(ConnectorTaskId) : String [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#824]]]
+ taskTransactionalId(String;String;int) : String [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#829]]]
errorHandlingMetrics(ConnectorTaskId) : ErrorHandlingMetrics [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#833]]]
- sinkTaskReporters(ConnectorTaskId;SinkConnectorConfig;ErrorHandlingMetrics;Class<?extendsConnector>) : List<ErrorReporter> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#837]]]
- sourceTaskReporters(ConnectorTaskId;ConnectorConfig;ErrorHandlingMetrics) : List<ErrorReporter> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#858]]]
- createWorkerErrantRecordReporter(SinkConnectorConfig;RetryWithToleranceOperator;Converter;Converter;HeaderConverter) : WorkerErrantRecordReporter [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#867]]]
- stopTask(ConnectorTaskId) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#881]]]
- stopTasks(Collection<ConnectorTaskId>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#903]]]
- awaitStopTask(ConnectorTaskId;long) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#911]]]
- awaitStopTasks(Collection<ConnectorTaskId>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#934]]]
+ stopAndAwaitTasks() : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#944]]]
+ stopAndAwaitTasks(Collection<ConnectorTaskId>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#949]]]
+ stopAndAwaitTask(ConnectorTaskId) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#955]]]
+ taskIds() : Set<ConnectorTaskId> [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#961]]]
+ getInternalKeyConverter() : Converter [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#965]]]
+ getInternalValueConverter() : Converter [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#969]]]
+ getPlugins() : Plugins [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#973]]]
+ workerId() : String [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#977]]]
+ isTopicCreationEnabled() : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#982]]]
+ metrics() : ConnectMetrics [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#987]]]
+ setTargetState(String;TargetState;Callback<TargetState>) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#991]]]
- executeStateTransition(Runnable;ClassLoader) : void [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1011]]]
connectorStatusMetricsGroup() : ConnectorStatusMetricsGroup [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1021]]]
workerMetricsGroup() : WorkerMetricsGroup [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1025]]]
offsetStoreForRegularSourceConnector(SourceConnectorConfig;String;Connector) : ConnectorOffsetBackingStore [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1288]]]
offsetStoreForExactlyOnceSourceConnector(SourceConnectorConfig;String;Connector) : ConnectorOffsetBackingStore [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1352]]]
offsetStoreForRegularSourceTask(ConnectorTaskId;SourceConnectorConfig;Class<?extendsConnector>;Producer<byte[],byte[]>;Map<String,Object>;TopicAdmin) : ConnectorOffsetBackingStore [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1402]]]
offsetStoreForExactlyOnceSourceTask(ConnectorTaskId;SourceConnectorConfig;Class<?extendsConnector>;Producer<byte[],byte[]>;Map<String,Object>;TopicAdmin) : ConnectorOffsetBackingStore [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1458]]]
- sameOffsetTopicAsWorker(String;Map<String,Object>) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1505]]]
- regularSourceTaskUsesConnectorSpecificOffsetsStore(SourceConnectorConfig) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1528]]]
- sourceConnectorTopicCreationEnabled(SourceConnectorConfig) : boolean [[[././qc/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java.html#1535]]]
} 
@enduml
