@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.memory.MemoryPool"
class org.apache.kafka.common.memory.MemoryPool {
tryAllocate(int) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java.html#65]]]
release(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java.html#71]]]
size() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java.html#77]]]
availableMemory() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java.html#84]]]
isOutOfMemory() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java.html#94]]]
} 
@enduml
