@startuml
!pragma layout smetana
"MemoryPool" <|-- "org.apache.kafka.common.memory.SimpleMemoryPool"
class org.apache.kafka.common.memory.SimpleMemoryPool {
+SimpleMemoryPool(long;int;boolean;Sensor) : SimpleMemoryPool [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#42]]]
+tryAllocate(int) : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#54]]]
+release(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#88]]]
+size() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#98]]]
+availableMemory() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#103]]]
+isOutOfMemory() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#108]]]
bufferToBeReturned(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#113]]]
bufferToBeReleased(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#118]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#123]]]
maybeRecordEndOfDrySpell() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/memory/SimpleMemoryPool.java.html#128]]]
} 
@enduml
