@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.acl.AccessControlEntry"
class org.apache.kafka.common.acl.AccessControlEntry {
+AccessControlEntry(String;String;AclOperation;AclPermissionType) : AccessControlEntry [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#41]]]
+principal() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#56]]]
+host() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#65]]]
+operation() : AclOperation [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#72]]]
+permissionType() : AclPermissionType [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#79]]]
+toFilter() : AccessControlEntryFilter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#86]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#91]]]
+isUnknown() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#98]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#103]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntry.java.html#111]]]
} 
@enduml
