@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.acl.AccessControlEntryFilter
class org.apache.kafka.common.acl.AccessControlEntryFilter {
+ AccessControlEntryFilter(String;String;AclOperation;AclPermissionType) : AccessControlEntryFilter [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#19]]]
AccessControlEntryFilter(AccessControlEntryData) : AccessControlEntryFilter [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#26]]]
+ principal() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#31]]]
+ host() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#36]]]
+ operation() : AclOperation [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#41]]]
+ permissionType() : AclPermissionType [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#46]]]
+ toString() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#51]]]
+ isUnknown() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#56]]]
+ matches(AccessControlEntry) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#61]]]
+ matchesAtMostOne() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#72]]]
+ findIndefiniteField() : String [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#77]]]
+ equals(Object) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#82]]]
+ hashCode() : int [[[././qc/clients/src/main/java/org/apache/kafka/common/acl/AccessControlEntryFilter.java.html#90]]]
} 
@enduml
