@startuml
!pragma layout smetana
"Iterator<T>" <|-- "org.apache.kafka.common.utils.AbstractIterator"
class org.apache.kafka.common.utils.AbstractIterator {
+hasNext() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#18]]]
+next() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#32]]]
+remove() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#42]]]
+peek() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#46]]]
allDone() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#52]]]
makeNext() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#57]]]
-maybeComputeNext() : Boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/AbstractIterator.java.html#59]]]
} 
@enduml
