@startuml
!pragma layout smetana
"OutputStream" <|-- "org.apache.kafka.common.utils.ByteBufferOutputStream"
class org.apache.kafka.common.utils.ByteBufferOutputStream {
+ByteBufferOutputStream(ByteBuffer) : ByteBufferOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#60]]]
+ByteBufferOutputStream(int) : ByteBufferOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#66]]]
+ByteBufferOutputStream(int;boolean) : ByteBufferOutputStream [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#70]]]
+write(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#74]]]
+write(byte[];int;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#79]]]
+write(ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#84]]]
+buffer() : ByteBuffer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#89]]]
+position() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#93]]]
+remaining() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#97]]]
+limit() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#101]]]
+position(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#105]]]
+initialCapacity() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#114]]]
+ensureRemaining(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#125]]]
-expandBuffer(int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferOutputStream.java.html#130]]]
} 
@enduml
