@startuml
!pragma layout smetana
Comparable_Bytes_ <|-- org.apache.kafka.common.utils.Bytes
class org.apache.kafka.common.utils.Bytes {
+  wrap(byte[])
+  Bytes(byte[])
+  get()
+  hashCode()
+  equals(Object)
+  compareTo(Bytes)
+  toString()
+  toString(byte[];int;int)
+  increment(Bytes)
} 
@enduml
