@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.ByteUtils"
class org.apache.kafka.common.utils.ByteUtils {
-ByteUtils() : ByteUtils [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#33]]]
+readUnsignedInt(ByteBuffer) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#41]]]
+readUnsignedInt(ByteBuffer;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#52]]]
+readUnsignedIntLE(InputStream) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#62]]]
+readUnsignedIntLE(byte[];int) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#77]]]
+writeUnsignedInt(ByteBuffer;int;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#91]]]
+writeUnsignedInt(ByteBuffer;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#101]]]
+writeUnsignedIntLE(OutputStream;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#111]]]
+writeUnsignedIntLE(byte[];int;int) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#126]]]
+readUnsignedVarint(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#142]]]
+readUnsignedVarint(DataInput) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#166]]]
+readVarint(ByteBuffer) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#189]]]
+readVarint(DataInput) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#204]]]
+readVarlong(DataInput) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#219]]]
+readVarlong(ByteBuffer) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#242]]]
+readDouble(DataInput) : double [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#262]]]
+readDouble(ByteBuffer) : double [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#272]]]
+writeUnsignedVarint(int;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#284]]]
+writeUnsignedVarint(int;DataOutput) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#301]]]
+writeVarint(int;DataOutput) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#318]]]
+writeVarint(int;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#330]]]
+writeVarlong(long;DataOutput) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#342]]]
+writeVarlong(long;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#359]]]
+writeDouble(double;DataOutput) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#375]]]
+writeDouble(double;ByteBuffer) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#385]]]
+sizeOfUnsignedVarint(int) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#396]]]
+sizeOfVarint(int) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#419]]]
+sizeOfVarlong(long) : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#429]]]
-illegalVarintException(int) : IllegalArgumentException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#441]]]
-illegalVarlongException(long) : IllegalArgumentException [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java.html#446]]]
} 
@enduml
