@startuml
!pragma layout smetana
"Iterator<T>" <|-- "org.apache.kafka.common.utils.CloseableIterator"
class org.apache.kafka.common.utils.CloseableIterator {
close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/CloseableIterator.java.html#9]]]
} 
@enduml
