@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.utils.CollectionUtils
class org.apache.kafka.common.utils.CollectionUtils {
- CollectionUtils() : CollectionUtils [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/CollectionUtils.java.html#17]]]
+ groupPartitionsByTopic(Collection<TopicPartition>) : Map<String,List<Integer>> [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/CollectionUtils.java.html#39]]]
} 
@enduml
