@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.Crc32C"
class org.apache.kafka.common.utils.Crc32C {
-Crc32C() : Crc32C [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Crc32C.java.html#23]]]
+compute(byte[];int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Crc32C.java.html#26]]]
+compute(ByteBuffer;int;int) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Crc32C.java.html#33]]]
+create() : Checksum [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Crc32C.java.html#39]]]
} 
@enduml
