@startuml
!pragma layout smetana
AbstractIterator<I> <|-- org.apache.kafka.common.utils.FlattenedIterator
class org.apache.kafka.common.utils.FlattenedIterator {
+  FlattenedIterator(Iterator<O>;Function<O,Iterator<I>>)
+  makeNext()
} 
@enduml
