@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.utils.LogContext
class org.apache.kafka.common.utils.LogContext {
+  LogContext(String)
+  LogContext()
+  logger(Class<?>)
+  logPrefix()
} 
@enduml
