@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.utils.LoggingSignalHandler
class org.apache.kafka.common.utils.LoggingSignalHandler {
+LoggingSignalHandler() : LoggingSignalHandler [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/LoggingSignalHandler.java.html#30]]]
+register() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/LoggingSignalHandler.java.html#40]]]
-createSignalHandler(Map<String,Object>) : Object [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/LoggingSignalHandler.java.html#49]]]
-register(String;Map<String,Object>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/LoggingSignalHandler.java.html#74]]]
} 
@enduml
