@startuml
!pragma layout smetana
Iterator_T_ <|-- org.apache.kafka.common.utils.MappedIterator
class org.apache.kafka.common.utils.MappedIterator {
+  MappedIterator(Iterator<?extendsF>;Function<F,T>)
+  hasNext()
+  next()
} 
@enduml
