@startuml
!pragma layout smetana
Checksum <|-- org.apache.kafka.common.utils.PureJavaCrc32C
class org.apache.kafka.common.utils.PureJavaCrc32C {
+ PureJavaCrc32C() : PureJavaCrc32C [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/PureJavaCrc32C.java.html#15]]]
+ getValue() : long [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/PureJavaCrc32C.java.html#20]]]
+ reset() : void [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/PureJavaCrc32C.java.html#26]]]
+ update(byte[];int;int) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/PureJavaCrc32C.java.html#32]]]
+ update(int) : void [[[././qc/clients/src/main/java/org/apache/kafka/common/utils/PureJavaCrc32C.java.html#80]]]
} 
@enduml
