@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.Sanitizer"
class org.apache.kafka.common.utils.Sanitizer {
+sanitize(String) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Sanitizer.java.html#54]]]
+desanitize(String) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Sanitizer.java.html#79]]]
+jmxSanitize(String) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Sanitizer.java.html#97]]]
} 
@enduml
