@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.Shell"
class org.apache.kafka.common.utils.Shell {
execString() : String[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#20]]]
parseExecResult(BufferedReader) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#23]]]
+Shell(long) : Shell [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#34]]]
+exitCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#39]]]
+process() : Process [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#44]]]
run() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#48]]]
-runCommand() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#54]]]
+execCommand(String...) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#201]]]
+execCommand(String[];long) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#206]]]
} 
@enduml
