@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.Shell"
class org.apache.kafka.common.utils.Shell {
execString() : String[] [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#40]]]
parseExecResult(BufferedReader) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#43]]]
+Shell(long) : Shell [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#56]]]
+exitCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#63]]]
+process() : Process [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#70]]]
run() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#74]]]
-runCommand() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#80]]]
+execCommand(String...) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#254]]]
+execCommand(String[];long) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Shell.java.html#266]]]
} 
@enduml
