@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.utils.ThreadUtils
class org.apache.kafka.common.utils.ThreadUtils {
+  createThreadFactory(String;boolean)
} 
@enduml
