@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.utils.Time
class org.apache.kafka.common.utils.Time {
milliseconds() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#14]]]
hiResClockMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#17]]]
nanoseconds() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#22]]]
sleep(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#25]]]
waitObject(Object;Supplier<Boolean>;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#28]]]
timer(long) : Timer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#31]]]
timer(Duration) : Timer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Time.java.html#36]]]
} 
@enduml
