@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.utils.Timer"
class org.apache.kafka.common.utils.Timer {
Timer(Time;long) : Timer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#57]]]
+isExpired() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#70]]]
+notExpired() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#78]]]
+updateAndReset(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#89]]]
+reset(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#101]]]
+resetDeadline(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#119]]]
+update() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#133]]]
+update(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#146]]]
+remainingMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#157]]]
+currentTimeMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#171]]]
+elapsedMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#181]]]
+timeoutMs() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#191]]]
+sleep(long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/utils/Timer.java.html#201]]]
} 
@enduml
