@startuml
!pragma layout smetana
AppenderSkeleton <|-- org.apache.kafka.log4jappender.KafkaLog4jAppender
class org.apache.kafka.log4jappender.KafkaLog4jAppender {
+  getProducer()
+  getBrokerList()
+  setBrokerList(String)
+  getRequiredNumAcks()
+  setRequiredNumAcks(int)
+  getLingerMs()
+  setLingerMs(int)
+  getBatchSize()
+  setBatchSize(int)
+  getRetries()
+  setRetries(int)
+  getDeliveryTimeoutMs()
+  setDeliveryTimeoutMs(int)
+  getCompressionType()
+  setCompressionType(String)
+  getTopic()
+  setTopic(String)
+  getIgnoreExceptions()
+  setIgnoreExceptions(boolean)
+  getSyncSend()
+  setSyncSend(boolean)
+  getSslTruststorePassword()
+  getSslTruststoreLocation()
+  getSecurityProtocol()
+  setSecurityProtocol(String)
+  setSslTruststoreLocation(String)
+  setSslTruststorePassword(String)
+  setSslKeystorePassword(String)
+  setSslKeystoreType(String)
+  setSslKeystoreLocation(String)
+  setSaslKerberosServiceName(String)
+  setClientJaasConfPath(String)
+  setKerb5ConfPath(String)
+  getSslKeystoreLocation()
+  getSslKeystoreType()
+  getSslKeystorePassword()
+  getSaslKerberosServiceName()
+  getClientJaasConfPath()
+  setSaslMechanism(String)
+  getSaslMechanism()
+  setClientJaasConf(String)
+  getClientJaasConf()
+  getKerb5ConfPath()
+  getMaxBlockMs()
+  setMaxBlockMs(int)
+  getSslEngineFactoryClass()
+  setSslEngineFactoryClass(String)
+  activateOptions()
+  getKafkaProducer(Properties)
+  append(LoggingEvent)
+  subAppend(LoggingEvent)
+  close()
+  requiresLayout()
} 
@enduml
