@startuml
!pragma layout smetana
MessageFormatter <|-- org.apache.kafka.connect.mirror.formatters.CheckpointFormatter
class org.apache.kafka.connect.mirror.formatters.CheckpointFormatter {
+ writeTo(ConsumerRecord<byte[],byte[]>;PrintStream) : void [[[././qc/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/formatters/CheckpointFormatter.java.html#13]]]
} 
@enduml
