@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.kstream.internals.foreignkeyjoin.CombinedKeySchema"
class org.apache.kafka.streams.kstream.internals.foreignkeyjoin.CombinedKeySchema {
+CombinedKeySchema(Supplier<String>;Serde<KO>;Supplier<String>;Serde<K>) : CombinedKeySchema [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java.html#41]]]
+init(ProcessorContext<?,?>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java.html#54]]]
toBytes(KO;K) : Bytes [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java.html#63]]]
+fromBytes(Bytes) : CombinedKey<KO,K> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java.html#82]]]
prefixBytes(KO) : Bytes [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java.html#97]]]
} 
@enduml
