@startuml
!pragma layout smetana
ProcessorSupplier<K,SubscriptionResponseWrapper<VO>,K,VR> <|-- org.apache.kafka.streams.kstream.internals.foreignkeyjoin.SubscriptionResolverJoinProcessorSupplier
class org.apache.kafka.streams.kstream.internals.foreignkeyjoin.SubscriptionResolverJoinProcessorSupplier {
+  SubscriptionResolverJoinProcessorSupplier(KTableValueGetterSupplier<K,V>;Serializer<V>;Supplier<String>;ValueJoiner<V,VO,VR>;boolean)
+  get()
} 
@enduml
