@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.kstream.internals.foreignkeyjoin.SubscriptionWrapper"
class org.apache.kafka.streams.kstream.internals.foreignkeyjoin.SubscriptionWrapper {
+SubscriptionWrapper(long[];Instruction;K;Integer) : SubscriptionWrapper [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#71]]]
+SubscriptionWrapper(long[];Instruction;K;byte;Integer) : SubscriptionWrapper [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#75]]]
+getInstruction() : Instruction [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#89]]]
+getHash() : long[] [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#93]]]
+getPrimaryKey() : K [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#97]]]
+getVersion() : byte [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#101]]]
+getPrimaryPartition() : Integer [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#105]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java.html#110]]]
} 
@enduml
