@startuml
!pragma layout smetana
"KafkaFuture<T>" <|-- "org.apache.kafka.common.internals.KafkaFutureImpl"
class org.apache.kafka.common.internals.KafkaFutureImpl {
+KafkaFutureImpl() : KafkaFutureImpl [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#21]]]
-KafkaFutureImpl(boolean;KafkaCompletableFuture<T>) : KafkaFutureImpl [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#25]]]
+toCompletionStage() : CompletionStage<T> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#31]]]
+whenComplete(BiConsumer<?superT,?superThrowable>) : KafkaFuture<T> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#81]]]
+complete(T) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#98]]]
+completeExceptionally(Throwable) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#103]]]
+cancel(boolean) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#113]]]
-maybeThrowCancellationException(Throwable) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#118]]]
+get() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#126]]]
+get(long;TimeUnit) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#137]]]
+getNow(T) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#149]]]
+isCancelled() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#163]]]
+isCompletedExceptionally() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#185]]]
+isDone() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#191]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#196]]]
} 
@enduml
