@startuml
!pragma layout smetana
"KafkaFuture<T>" <|-- "org.apache.kafka.common.internals.KafkaFutureImpl"
class org.apache.kafka.common.internals.KafkaFutureImpl {
+KafkaFutureImpl() : KafkaFutureImpl [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#38]]]
-KafkaFutureImpl(boolean;KafkaCompletableFuture<T>) : KafkaFutureImpl [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#42]]]
+toCompletionStage() : CompletionStage<T> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#48]]]
+whenComplete(BiConsumer<?superT,?superThrowable>) : KafkaFuture<T> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#104]]]
+complete(T) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#121]]]
+completeExceptionally(Throwable) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#126]]]
+cancel(boolean) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#140]]]
-maybeThrowCancellationException(Throwable) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#153]]]
+get() : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#163]]]
+get(long;TimeUnit) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#177]]]
+getNow(T) : T [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#192]]]
+isCancelled() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#208]]]
+isCompletedExceptionally() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#232]]]
+isDone() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#240]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/internals/KafkaFutureImpl.java.html#245]]]
} 
@enduml
