@startuml
!pragma layout smetana
"ProcessorContext<KForward,VForward>" <|-- "org.apache.kafka.streams.processor.api.MockProcessorContext"
class org.apache.kafka.streams.processor.api.MockProcessorContext {
+MockProcessorContext() : MockProcessorContext [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#173]]]
+MockProcessorContext(Properties) : MockProcessorContext [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#185]]]
+MockProcessorContext(Properties;TaskId;File) : MockProcessorContext [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#190]]]
+applicationId() : String [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#212]]]
+taskId() : TaskId [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#217]]]
+appConfigs() : Map<String,Object> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#222]]]
+appConfigsWithPrefix(String) : Map<String,Object> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#230]]]
+currentSystemTimeMs() : long [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#235]]]
+currentStreamTimeMs() : long [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#243]]]
+keySerde() : Serde<?> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#251]]]
+valueSerde() : Serde<?> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#256]]]
+stateDir() : File [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#261]]]
+metrics() : StreamsMetrics [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#272]]]
+setRecordMetadata(String;int;long) : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#279]]]
+setCurrentSystemTimeMs(long) : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#285]]]
+setCurrentStreamTimeMs(long) : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#289]]]
+recordMetadata() : Optional<RecordMetadata> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#294]]]
+schedule(Duration;PunctuationType;Punctuator) : Cancellable [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#311]]]
+scheduledPunctuators() : List<CapturedPunctuator> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#322]]]
+forwarded() : List<CapturedForward<?extendsKForward,?extendsVForward>> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#337]]]
+forwarded(String) : List<CapturedForward<?extendsKForward,?extendsVForward>> [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#342]]]
+resetForwards() : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#353]]]
+commit() : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#358]]]
+committed() : boolean [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#363]]]
+resetCommit() : void [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#368]]]
+recordCollector() : RecordCollector [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#373]]]
+getStateStoreContext() : StateStoreContext [[[./../../../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/processor/api/MockProcessorContext.java.html#385]]]
} 
@enduml
