@startuml
!pragma layout smetana
"ConnectRestExtension" <|-- "org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension"
class org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension {
initializeConfiguration(Supplier<Configuration>) : Supplier<Configuration> [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#71]]]
+BasicAuthSecurityRestExtension() : BasicAuthSecurityRestExtension [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#86]]]
BasicAuthSecurityRestExtension(Supplier<Configuration>) : BasicAuthSecurityRestExtension [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#91]]]
+register(ConnectRestExtensionContext) : void [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#96]]]
+close() : void [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#103]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#108]]]
+version() : String [[[./../../../../../../../../../../../../../.././qc/connect/basic-auth-extension/src/main/java/org/apache/kafka/connect/rest/basic/auth/extension/BasicAuthSecurityRestExtension.java.html#114]]]
} 
@enduml
