@startuml
!pragma layout smetana
"Configurable" <|-- "org.apache.kafka.server.quota.ClientQuotaCallback"
class org.apache.kafka.server.quota.ClientQuotaCallback {
quotaMetricTags(ClientQuotaType;KafkaPrincipal;String) : Map<String,String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#40]]]
quotaLimit(ClientQuotaType;Map<String,String>) : Double [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#74]]]
updateQuota(ClientQuotaType;ClientQuotaEntity;double) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#74]]]
removeQuota(ClientQuotaType;ClientQuotaEntity) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#74]]]
quotaResetRequired(ClientQuotaType) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#74]]]
updateClusterMetadata(Cluster) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#1]]]
close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/server/quota/ClientQuotaCallback.java.html#1]]]
} 
@enduml
