@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.TestInputTopic"
class org.apache.kafka.streams.TestInputTopic {
TestInputTopic(TopologyTestDriver;String;Serializer<K>;Serializer<V>;Instant;Duration) : TestInputTopic [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#25]]]
+advanceTime(Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#49]]]
-getTimestampAndAdvance() : Instant [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#56]]]
+pipeInput(TestRecord<K,V>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#63]]]
+pipeInput(V) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#70]]]
+pipeInput(K;V) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#75]]]
+pipeInput(V;Instant) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#81]]]
+pipeInput(K;V;long) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#87]]]
+pipeInput(K;V;Instant) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#94]]]
+pipeRecordList(List<?extendsTestRecord<K,V>>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#101]]]
+pipeKeyValueList(List<KeyValue<K,V>>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#108]]]
+pipeValueList(List<V>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#115]]]
+pipeKeyValueList(List<KeyValue<K,V>>;Instant;Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#122]]]
+pipeValueList(List<V>;Instant;Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#133]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#144]]]
} 
@enduml
