@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.TestInputTopic"
class org.apache.kafka.streams.TestInputTopic {
TestInputTopic(TopologyTestDriver;String;Serializer<K>;Serializer<V>;Instant;Duration) : TestInputTopic [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#59]]]
+advanceTime(Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#93]]]
-getTimestampAndAdvance() : Instant [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#100]]]
+pipeInput(TestRecord<K,V>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#112]]]
+pipeInput(V) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#124]]]
+pipeInput(K;V) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#135]]]
+pipeInput(V;Instant) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#147]]]
+pipeInput(K;V;long) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#160]]]
+pipeInput(K;V;Instant) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#174]]]
+pipeRecordList(List<?extendsTestRecord<K,V>>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#186]]]
+pipeKeyValueList(List<KeyValue<K,V>>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#199]]]
+pipeValueList(List<V>) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#212]]]
+pipeKeyValueList(List<KeyValue<K,V>>;Instant;Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#226]]]
+pipeValueList(List<V>;Instant;Duration) : void [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#245]]]
+toString() : String [[[./../../../../../../../../../.././qc/streams/test-utils/src/main/java/org/apache/kafka/streams/TestInputTopic.java.html#256]]]
} 
@enduml
