@startuml
!pragma layout smetana
ScramCredentialCallback <|-- org.apache.kafka.common.security.token.delegation.internals.DelegationTokenCredentialCallback
class org.apache.kafka.common.security.token.delegation.internals.DelegationTokenCredentialCallback {
+  tokenOwner(String)
+  tokenOwner()
+  tokenExpiryTimestamp(Long)
+  tokenExpiryTimestamp()
} 
@enduml
