@startuml
!pragma layout smetana
"Consumer<K,V>" <|-- "org.apache.kafka.clients.consumer.KafkaConsumer"
class org.apache.kafka.clients.consumer.KafkaConsumer {
+KafkaConsumer(Map<String,Object>) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#613]]]
+KafkaConsumer(Properties) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#626]]]
+KafkaConsumer(Properties;Deserializer<K>;Deserializer<V>) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#644]]]
+KafkaConsumer(Map<String,Object>;Deserializer<K>;Deserializer<V>) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#663]]]
KafkaConsumer(ConsumerConfig;Deserializer<K>;Deserializer<V>) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#671]]]
KafkaConsumer(LogContext;String;ConsumerCoordinator;Deserializer<K>;Deserializer<V>;Fetcher<K,V>;ConsumerInterceptors<K,V>;Time;ConsumerNetworkClient;Metrics;SubscriptionState;ConsumerMetadata;long;long;int;List<ConsumerPartitionAssignor>;String) : KafkaConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#835]]]
-buildMetrics(ConsumerConfig;Time;String) : Metrics [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#873]]]
+assignment() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#897]]]
+subscription() : Set<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#911]]]
+subscribe(Collection<String>;ConsumerRebalanceListener) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#956]]]
+subscribe(Collection<String>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1004]]]
+subscribe(Pattern;ConsumerRebalanceListener) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1028]]]
+subscribe(Pattern) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1063]]]
+unsubscribe() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1073]]]
+assign(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1108]]]
+poll(long) : ConsumerRecords<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1172]]]
+poll(Duration) : ConsumerRecords<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1219]]]
-poll(Timer;boolean) : ConsumerRecords<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1226]]]
updateAssignmentMetadataIfNeeded(Timer;boolean) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1275]]]
-pollForFetches(Timer) : Fetch<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1286]]]
+commitSync() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1361]]]
+commitSync(Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1404]]]
+commitSync(Map<TopicPartition,OffsetAndMetadata>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1452]]]
+commitSync(Map<TopicPartition,OffsetAndMetadata>;Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1500]]]
+commitAsync() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1522]]]
+commitAsync(OffsetCommitCallback) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1545]]]
+commitAsync(Map<TopicPartition,OffsetAndMetadata>;OffsetCommitCallback) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1572]]]
+seek(TopicPartition;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1593]]]
+seek(TopicPartition;OffsetAndMetadata) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1620]]]
+seekToBeginning(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1655]]]
+seekToEnd(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1680]]]
+position(TopicPartition) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1720]]]
+position(TopicPartition;Duration) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1750]]]
+committed(TopicPartition) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1799]]]
+committed(TopicPartition;Duration) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1828]]]
+committed(Set<TopicPartition>) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1860]]]
+committed(Set<TopicPartition>;Duration) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1888]]]
+metrics() : Map<MetricName,?extendsMetric> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1913]]]
+partitionsFor(String) : List<PartitionInfo> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1935]]]
+partitionsFor(String;Duration) : List<PartitionInfo> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1959]]]
+listTopics() : Map<String,List<PartitionInfo>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#1991]]]
+listTopics(Duration) : Map<String,List<PartitionInfo>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2011]]]
+pause(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2031]]]
+resume(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2051]]]
+paused() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2069]]]
+offsetsForTimes(Map<TopicPartition,Long>) : Map<TopicPartition,OffsetAndTimestamp> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2100]]]
+offsetsForTimes(Map<TopicPartition,Long>;Duration) : Map<TopicPartition,OffsetAndTimestamp> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2127]]]
+beginningOffsets(Collection<TopicPartition>) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2158]]]
+beginningOffsets(Collection<TopicPartition>;Duration) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2179]]]
+endOffsets(Collection<TopicPartition>) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2208]]]
+endOffsets(Collection<TopicPartition>;Duration) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2234]]]
+currentLag(TopicPartition) : OptionalLong [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2257]]]
+groupMetadata() : ConsumerGroupMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2291]]]
+enforceRebalance(String) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2324]]]
+enforceRebalance() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2340]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2355]]]
+close(Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2375]]]
+wakeup() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2397]]]
-configureClusterResourceListeners(Deserializer<K>;Deserializer<V>;List<?>...) : ClusterResourceListeners [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2401]]]
-close(long;boolean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2411]]]
-updateFetchPositions(Timer) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2448]]]
-acquireAndEnsureOpen() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2478]]]
-acquire() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2492]]]
-release() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2502]]]
-throwIfNoAssignorsConfigured() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2507]]]
-maybeThrowInvalidGroupIdException() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2513]]]
-updateLastSeenEpochIfNewer(TopicPartition;OffsetAndMetadata) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2519]]]
getClientId() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2525]]]
updateAssignmentMetadataIfNeeded(Timer) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java.html#2529]]]
} 
@enduml
