@startuml
!pragma layout smetana
"Consumer<K,V>" <|-- "org.apache.kafka.clients.consumer.MockConsumer"
class org.apache.kafka.clients.consumer.MockConsumer {
+MockConsumer(OffsetResetStrategy) : MockConsumer [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#75]]]
+assignment() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#91]]]
+rebalance(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#96]]]
+subscription() : Set<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#103]]]
+subscribe(Collection<String>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#108]]]
+subscribe(Pattern;ConsumerRebalanceListener) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#113]]]
+subscribe(Pattern) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#136]]]
+subscribe(Collection<String>;ConsumerRebalanceListener) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#141]]]
+assign(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#148]]]
+unsubscribe() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#155]]]
+poll(long) : ConsumerRecords<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#163]]]
+poll(Duration) : ConsumerRecords<K,V> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#168]]]
+addRecord(ConsumerRecord<K,V>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#227]]]
+setException(KafkaException) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#241]]]
+setPollException(KafkaException) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#245]]]
+setOffsetsException(KafkaException) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#249]]]
+commitAsync(Map<TopicPartition,OffsetAndMetadata>;OffsetCommitCallback) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#254]]]
+commitSync(Map<TopicPartition,OffsetAndMetadata>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#264]]]
+commitAsync() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#269]]]
+commitAsync(OffsetCommitCallback) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#274]]]
+commitSync() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#280]]]
+commitSync(Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#285]]]
+commitSync(Map<TopicPartition,OffsetAndMetadata>;Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#290]]]
+seek(TopicPartition;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#295]]]
+seek(TopicPartition;OffsetAndMetadata) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#301]]]
+committed(TopicPartition) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#308]]]
+committed(TopicPartition;Duration) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#314]]]
+committed(Set<TopicPartition>) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#319]]]
+committed(Set<TopicPartition>;Duration) : Map<TopicPartition,OffsetAndMetadata> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#329]]]
+position(TopicPartition) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#334]]]
+position(TopicPartition;Duration) : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#347]]]
+seekToBeginning(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#352]]]
+updateBeginningOffsets(Map<TopicPartition,Long>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#357]]]
+seekToEnd(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#362]]]
+updateEndOffsets(Map<TopicPartition,Long>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#367]]]
+metrics() : Map<MetricName,?extendsMetric> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#372]]]
+partitionsFor(String) : List<PartitionInfo> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#378]]]
+listTopics() : Map<String,List<PartitionInfo>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#384]]]
+updatePartitions(String;List<PartitionInfo>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#389]]]
+pause(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#395]]]
+resume(Collection<TopicPartition>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#403]]]
+offsetsForTimes(Map<TopicPartition,Long>) : Map<TopicPartition,OffsetAndTimestamp> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#411]]]
+beginningOffsets(Collection<TopicPartition>) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#416]]]
+endOffsets(Collection<TopicPartition>) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#433]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#450]]]
+close(Duration) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#455]]]
+closed() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#459]]]
+wakeup() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#464]]]
+schedulePollTask(Runnable) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#473]]]
+scheduleNopPollTask() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#479]]]
+paused() : Set<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#483]]]
-ensureNotClosed() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#487]]]
-updateFetchPosition(TopicPartition) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#492]]]
-resetOffsetPosition(TopicPartition) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#503]]]
+partitionsFor(String;Duration) : List<PartitionInfo> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#521]]]
+listTopics(Duration) : Map<String,List<PartitionInfo>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#526]]]
+offsetsForTimes(Map<TopicPartition,Long>;Duration) : Map<TopicPartition,OffsetAndTimestamp> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#531]]]
+beginningOffsets(Collection<TopicPartition>;Duration) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#537]]]
+endOffsets(Collection<TopicPartition>;Duration) : Map<TopicPartition,Long> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#542]]]
+currentLag(TopicPartition) : OptionalLong [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#547]]]
+groupMetadata() : ConsumerGroupMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#557]]]
+enforceRebalance() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#562]]]
+enforceRebalance(String) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#567]]]
+shouldRebalance() : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#571]]]
+resetShouldRebalance() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#575]]]
+lastPollTimeout() : Duration [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/MockConsumer.java.html#579]]]
} 
@enduml
