@startuml
!pragma layout smetana
Consumer<K,V> <|-- org.apache.kafka.clients.consumer.MockConsumer
class org.apache.kafka.clients.consumer.MockConsumer {
+  MockConsumer(OffsetResetStrategy)
+  assignment()
+  rebalance(Collection<TopicPartition>)
+  subscription()
+  subscribe(Collection<String>)
+  subscribe(Pattern;ConsumerRebalanceListener)
+  subscribe(Pattern)
+  subscribe(Collection<String>;ConsumerRebalanceListener)
+  assign(Collection<TopicPartition>)
+  unsubscribe()
+  poll(long)
+  poll(Duration)
+  addRecord(ConsumerRecord<K,V>)
+  setException(KafkaException)
+  setPollException(KafkaException)
+  setOffsetsException(KafkaException)
+  commitAsync(Map<TopicPartition,OffsetAndMetadata>;OffsetCommitCallback)
+  commitSync(Map<TopicPartition,OffsetAndMetadata>)
+  commitAsync()
+  commitAsync(OffsetCommitCallback)
+  commitSync()
+  commitSync(Duration)
+  commitSync(Map<TopicPartition,OffsetAndMetadata>;Duration)
+  seek(TopicPartition;long)
+  seek(TopicPartition;OffsetAndMetadata)
+  committed(TopicPartition)
+  committed(TopicPartition;Duration)
+  committed(Set<TopicPartition>)
+  committed(Set<TopicPartition>;Duration)
+  position(TopicPartition)
+  position(TopicPartition;Duration)
+  seekToBeginning(Collection<TopicPartition>)
+  updateBeginningOffsets(Map<TopicPartition,Long>)
+  seekToEnd(Collection<TopicPartition>)
+  updateEndOffsets(Map<TopicPartition,Long>)
+  metrics()
+  partitionsFor(String)
+  listTopics()
+  updatePartitions(String;List<PartitionInfo>)
+  pause(Collection<TopicPartition>)
+  resume(Collection<TopicPartition>)
+  offsetsForTimes(Map<TopicPartition,Long>)
+  beginningOffsets(Collection<TopicPartition>)
+  endOffsets(Collection<TopicPartition>)
+  close()
+  close(Duration)
+  closed()
+  wakeup()
+  schedulePollTask(Runnable)
+  scheduleNopPollTask()
+  paused()
+  ensureNotClosed()
+  updateFetchPosition(TopicPartition)
+  resetOffsetPosition(TopicPartition)
+  partitionsFor(String;Duration)
+  listTopics(Duration)
+  offsetsForTimes(Map<TopicPartition,Long>;Duration)
+  beginningOffsets(Collection<TopicPartition>;Duration)
+  endOffsets(Collection<TopicPartition>;Duration)
+  currentLag(TopicPartition)
+  groupMetadata()
+  enforceRebalance()
+  enforceRebalance(String)
+  shouldRebalance()
+  resetShouldRebalance()
+  lastPollTimeout()
} 
@enduml
