@startuml
!pragma layout smetana
"Serializable" <|-- "org.apache.kafka.clients.consumer.OffsetAndMetadata"
class org.apache.kafka.clients.consumer.OffsetAndMetadata {
+OffsetAndMetadata(long;Optional<Integer>;String) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#48]]]
+OffsetAndMetadata(long;String) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#68]]]
+OffsetAndMetadata(long) : OffsetAndMetadata [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#77]]]
+offset() : long [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#81]]]
+metadata() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#85]]]
+leaderEpoch() : Optional<Integer> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#96]]]
+equals(Object) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#103]]]
+hashCode() : int [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#113]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetAndMetadata.java.html#118]]]
} 
@enduml
