@startuml
!pragma layout smetana
"AbstractPartitionAssignor" <|-- "org.apache.kafka.clients.consumer.RoundRobinAssignor"
class org.apache.kafka.clients.consumer.RoundRobinAssignor {
+assign(Map<String,Integer>;Map<String,Subscription>) : Map<String,List<TopicPartition>> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java.html#104]]]
-allPartitionsSorted(Map<String,Integer>;Map<String,Subscription>) : List<TopicPartition> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java.html#125]]]
+name() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java.html#141]]]
} 
@enduml
