@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.kstream.internals.AbstractStream"
class org.apache.kafka.streams.kstream.internals.AbstractStream {
+AbstractStream(AbstractStream<K,V>) : AbstractStream [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#60]]]
AbstractStream(String;Serde<K>;Serde<V>;Set<String>;GraphNode;InternalStreamsBuilder) : AbstractStream [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#69]]]
internalTopologyBuilder() : InternalTopologyBuilder [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#89]]]
ensureCopartitionWith(Collection<?extendsAbstractStream<K,?>>) : Set<String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#93]]]
+keySerde() : Serde<K> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#155]]]
+valueSerde() : Serde<V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/AbstractStream.java.html#159]]]
} 
@enduml
