@startuml
!pragma layout smetana
"Branched<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.BranchedInternal"
class org.apache.kafka.streams.kstream.internals.BranchedInternal {
BranchedInternal(Branched<K,V>) : BranchedInternal [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/BranchedInternal.java.html#26]]]
BranchedInternal() : BranchedInternal [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/BranchedInternal.java.html#30]]]
name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/BranchedInternal.java.html#38]]]
+chainFunction() : Function<?superKStream<K,V>,?extendsKStream<K,V>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/BranchedInternal.java.html#42]]]
+chainConsumer() : Consumer<?superKStream<K,V>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/BranchedInternal.java.html#46]]]
} 
@enduml
