@startuml
!pragma layout smetana
"Serializer<Change<T>>" <|-- "org.apache.kafka.streams.kstream.internals.ChangedSerializer"
class org.apache.kafka.streams.kstream.internals.ChangedSerializer {
+ChangedSerializer(Serializer<T>) : ChangedSerializer [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#32]]]
+inner() : Serializer<T> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#36]]]
+setIfUnset(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#42]]]
+serialize(String;Headers;Change<T>) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#53]]]
+serialize(String;Change<T>) : byte[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#80]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/ChangedSerializer.java.html#85]]]
} 
@enduml
