@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.kstream.internals.FullChangeSerde"
class org.apache.kafka.streams.kstream.internals.FullChangeSerde {
-FullChangeSerde(Serde<T>) : FullChangeSerde [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java.html#39]]]
+innerSerde() : Serde<T> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java.html#43]]]
+serializeParts(String;Change<T>) : Change<byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java.html#47]]]
+deserializeParts(String;Change<byte[]>) : Change<T> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java.html#58]]]
+decomposeLegacyFormattedArrayIntoChangeArrays(byte[]) : Change<byte[]> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java.html#76]]]
} 
@enduml
