@startuml
!pragma layout smetana
"Joined<K,V,VO>" <|-- "org.apache.kafka.streams.kstream.internals.JoinedInternal"
class org.apache.kafka.streams.kstream.internals.JoinedInternal {
JoinedInternal(Joined<K,V,VO>) : JoinedInternal [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/JoinedInternal.java.html#24]]]
+keySerde() : Serde<K> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/JoinedInternal.java.html#28]]]
+valueSerde() : Serde<V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/JoinedInternal.java.html#32]]]
+otherValueSerde() : Serde<VO> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/JoinedInternal.java.html#36]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/JoinedInternal.java.html#40]]]
} 
@enduml
