@startuml
!pragma layout smetana
"ProcessorSupplier<K,V1,K,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamKTableJoin"
class org.apache.kafka.streams.kstream.internals.KStreamKTableJoin {
KStreamKTableJoin(KTableValueGetterSupplier<K,V2>;ValueJoinerWithKey<?superK,?superV1,?superV2,VOut>;boolean) : KStreamKTableJoin [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoin.java.html#31]]]
+get() : Processor<K,V1,K,VOut> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoin.java.html#40]]]
} 
@enduml
