@startuml
!pragma layout smetana
FixedKeyProcessorSupplier_KIn,VIn,VOut_ <|-- org.apache.kafka.streams.kstream.internals.KStreamFlatMapValues
class org.apache.kafka.streams.kstream.internals.KStreamFlatMapValues {
+  KStreamFlatMapValues(ValueMapperWithKey<?superKIn,?superVIn,?extendsIterable<?extendsVOut>>)
+  get()
} 
@enduml
