@startuml
!pragma layout smetana
KStreamAggProcessorSupplier_KIn,VIn,KIn,VAgg_ <|-- org.apache.kafka.streams.kstream.internals.KStreamAggregate
class org.apache.kafka.streams.kstream.internals.KStreamAggregate {
+  KStreamAggregate(String;Initializer<VAgg>;Aggregator<?superKIn,?superVIn,VAgg>)
+  get()
+  enableSendingOldValues()
+  view()
} 
@enduml
