@startuml
!pragma layout smetana
"AbstractStream<K,V>KStream<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamImpl"
class org.apache.kafka.streams.kstream.internals.KStreamImpl {
KStreamImpl(String;Serde<K>;Serde<V>;Set<String>;boolean;GraphNode;InternalStreamsBuilder) : KStreamImpl [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#143]]]
+filter(Predicate<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#155]]]
+filter(Predicate<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#160]]]
+filterNot(Predicate<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#184]]]
+filterNot(Predicate<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#189]]]
+print(Printed<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#389]]]
+foreach(ForeachAction<?superK,?superV>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#403]]]
+foreach(ForeachAction<?superK,?superV>;Named) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#408]]]
+peek(ForeachAction<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#423]]]
+peek(ForeachAction<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#428]]]
+branch(Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#454]]]
+branch(Named;Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#461]]]
-doBranch(NamedInternal;Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#468]]]
+split() : BranchedKStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#507]]]
+split(Named) : BranchedKStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#512]]]
+merge(KStream<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#518]]]
+merge(KStream<K,V>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#523]]]
-merge(InternalStreamsBuilder;KStream<K,V>;NamedInternal) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#531]]]
+through(String) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#562]]]
+through(String;Produced<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#568]]]
+repartition() : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#594]]]
+repartition(Repartitioned<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#599]]]
-doRepartition(Repartitioned<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#603]]]
+to(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#647]]]
+to(String;Produced<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#652]]]
+to(TopicNameExtractor<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#668]]]
+to(TopicNameExtractor<K,V>;Produced<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#673]]]
-to(TopicNameExtractor<K,V>;ProducedInternal<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#688]]]
+toTable() : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#701]]]
+toTable(Named) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#706]]]
+toTable(Materialized<K,V,KeyValueStore<Bytes,byte[]>>) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#711]]]
+toTable(Named;Materialized<K,V,KeyValueStore<Bytes,byte[]>>) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#716]]]
+groupByKey() : KGroupedStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#808]]]
+groupByKey(Grouped<K,V>) : KGroupedStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#813]]]
-repartitionForJoin(String;Serde<K>;Serde<V>) : KStreamImpl<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#977]]]
+process(org.apache.kafka.streams.processor.ProcessorSupplier<?superK,?superV>;String...) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#1485]]]
+process(org.apache.kafka.streams.processor.ProcessorSupplier<?superK,?superV>;Named;String...) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#1492]]]
} 
@enduml
