@startuml
!pragma layout smetana
FixedKeyProcessorSupplier<K,V,V> <|-- org.apache.kafka.streams.kstream.internals.KStreamFilter
class org.apache.kafka.streams.kstream.internals.KStreamFilter {
+  KStreamFilter(Predicate<K,V>;boolean)
+  get()
} 
@enduml
