@startuml
!pragma layout smetana
"ContextualProcessor<K1,V1,K1,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamKTableJoinProcessor"
class org.apache.kafka.streams.kstream.internals.KStreamKTableJoinProcessor {
KStreamKTableJoinProcessor(KTableValueGetter<K2,V2>;KeyValueMapper<?superK1,?superV1,?extendsK2>;ValueJoinerWithKey<?superK1,?superV1,?superV2,?extendsVOut>;boolean) : KStreamKTableJoinProcessor [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoinProcessor.java.html#42]]]
+init(ProcessorContext<K1,VOut>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoinProcessor.java.html#53]]]
+process(Record<K1,V1>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoinProcessor.java.html#61]]]
+close() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKTableJoinProcessor.java.html#94]]]
} 
@enduml
