@startuml
!pragma layout smetana
KStreamAggProcessorSupplier<KIn,VIn,Windowed<KIn>,VAgg> <|-- org.apache.kafka.streams.kstream.internals.KStreamSessionWindowAggregate
class org.apache.kafka.streams.kstream.internals.KStreamSessionWindowAggregate {
+  KStreamSessionWindowAggregate(SessionWindows;String;Initializer<VAgg>;Aggregator<?superKIn,?superVIn,VAgg>;Merger<?superKIn,VAgg>)
+  get()
+  windows()
+  enableSendingOldValues()
+  mergeSessionWindow(SessionWindow;SessionWindow)
+  view()
} 
@enduml
