@startuml
!pragma layout smetana
FixedKeyProcessorSupplier_K,V,V_ <|-- org.apache.kafka.streams.kstream.internals.KStreamPeek
class org.apache.kafka.streams.kstream.internals.KStreamPeek {
+  KStreamPeek(ForeachAction<K,V>)
+  get()
} 
@enduml
