@startuml
!pragma layout smetana
"AbstractStream<K,V>KStream<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamImpl"
class org.apache.kafka.streams.kstream.internals.KStreamImpl {
KStreamImpl(String;Serde<K>;Serde<V>;Set<String>;boolean;GraphNode;InternalStreamsBuilder) : KStreamImpl [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#128]]]
+filter(Predicate<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#140]]]
+filter(Predicate<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#145]]]
+filterNot(Predicate<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#169]]]
+filterNot(Predicate<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#174]]]
+print(Printed<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#374]]]
+foreach(ForeachAction<?superK,?superV>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#388]]]
+foreach(ForeachAction<?superK,?superV>;Named) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#393]]]
+peek(ForeachAction<?superK,?superV>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#408]]]
+peek(ForeachAction<?superK,?superV>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#413]]]
+branch(Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#439]]]
+branch(Named;Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#446]]]
-doBranch(NamedInternal;Predicate<?superK,?superV>...) : KStream<K,V>[] [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#453]]]
+split() : BranchedKStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#492]]]
+split(Named) : BranchedKStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#497]]]
+merge(KStream<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#503]]]
+merge(KStream<K,V>;Named) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#508]]]
-merge(InternalStreamsBuilder;KStream<K,V>;NamedInternal) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#516]]]
+through(String) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#547]]]
+through(String;Produced<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#553]]]
+repartition() : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#579]]]
+repartition(Repartitioned<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#584]]]
-doRepartition(Repartitioned<K,V>) : KStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#588]]]
+to(String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#632]]]
+to(String;Produced<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#637]]]
+to(TopicNameExtractor<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#653]]]
+to(TopicNameExtractor<K,V>;Produced<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#658]]]
-to(TopicNameExtractor<K,V>;ProducedInternal<K,V>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#673]]]
+toTable() : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#686]]]
+toTable(Named) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#691]]]
+toTable(Materialized<K,V,KeyValueStore<Bytes,byte[]>>) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#696]]]
+toTable(Named;Materialized<K,V,KeyValueStore<Bytes,byte[]>>) : KTable<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#701]]]
+groupByKey() : KGroupedStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#793]]]
+groupByKey(Grouped<K,V>) : KGroupedStream<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#798]]]
-repartitionForJoin(String;Serde<K>;Serde<V>) : KStreamImpl<K,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#959]]]
+process(org.apache.kafka.streams.processor.ProcessorSupplier<?superK,?superV>;String...) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#1467]]]
+process(org.apache.kafka.streams.processor.ProcessorSupplier<?superK,?superV>;Named;String...) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java.html#1474]]]
} 
@enduml
