@startuml
!pragma layout smetana
ProcessorSupplier_KIn,VIn,KIn,VOut_ <|-- org.apache.kafka.streams.kstream.internals.KStreamTransformValues
class org.apache.kafka.streams.kstream.internals.KStreamTransformValues {
+  KStreamTransformValues(ValueTransformerWithKeySupplier<KIn,VIn,VOut>)
+  get()
+  stores()
} 
@enduml
