@startuml
!pragma layout smetana
ProcessorSupplier_KIn,VIn,KIn,VOut_ <|-- org.apache.kafka.streams.kstream.internals.KStreamFlatTransformValues
class org.apache.kafka.streams.kstream.internals.KStreamFlatTransformValues {
+  KStreamFlatTransformValues(ValueTransformerWithKeySupplier<KIn,VIn,Iterable<VOut>>)
+  get()
+  stores()
} 
@enduml
