@startuml
!pragma layout smetana
KStreamAggProcessorSupplier_KIn,VIn,Windowed_KIn_,VAgg_ <|-- org.apache.kafka.streams.kstream.internals.KStreamSessionWindowAggregate
class org.apache.kafka.streams.kstream.internals.KStreamSessionWindowAggregate {
+  KStreamSessionWindowAggregate(SessionWindows;String;EmitStrategy;Initializer<VAgg>;Aggregator<?superKIn,?superVIn,VAgg>;Merger<?superKIn,VAgg>)
+  get()
+  windows()
+  enableSendingOldValues()
+  mergeSessionWindow(SessionWindow;SessionWindow)
+  view()
} 
@enduml
