@startuml
!pragma layout smetana
ProcessorSupplier<K,V,K,V> <|-- org.apache.kafka.streams.kstream.internals.KStreamJoinWindow
class org.apache.kafka.streams.kstream.internals.KStreamJoinWindow {
+  KStreamJoinWindow(String)
+  get()
} 
@enduml
