@startuml
!pragma layout smetana
"ProcessorSupplier<KIn,VIn,KOut,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamMap"
class org.apache.kafka.streams.kstream.internals.KStreamMap {
+KStreamMap(KeyValueMapper<?superKIn,?superVIn,?extendsKeyValue<?extendsKOut,?extendsVOut>>) : KStreamMap [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamMap.java.html#17]]]
+get() : Processor<KIn,VIn,KOut,VOut> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamMap.java.html#22]]]
} 
@enduml
