@startuml
!pragma layout smetana
"ProcessorSupplier<KIn,VIn,KIn,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.KStreamTransformValues"
class org.apache.kafka.streams.kstream.internals.KStreamTransformValues {
KStreamTransformValues(ValueTransformerWithKeySupplier<KIn,VIn,VOut>) : KStreamTransformValues [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamTransformValues.java.html#36]]]
+get() : Processor<KIn,VIn,KIn,VOut> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamTransformValues.java.html#41]]]
+stores() : Set<StoreBuilder<?>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamTransformValues.java.html#46]]]
} 
@enduml
