@startuml
!pragma layout smetana
"KTableProcessorSupplier<KIn,VIn,KIn,VIn>" <|-- "org.apache.kafka.streams.kstream.internals.KTablePassThrough"
class org.apache.kafka.streams.kstream.internals.KTablePassThrough {
KTablePassThrough(Collection<KStreamAggProcessorSupplier>;String) : KTablePassThrough [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTablePassThrough.java.html#32]]]
+get() : Processor<KIn,Change<VIn>,KIn,Change<VIn>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTablePassThrough.java.html#38]]]
+enableSendingOldValues(boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTablePassThrough.java.html#43]]]
+view() : KTableValueGetterSupplier<KIn,VIn> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTablePassThrough.java.html#52]]]
} 
@enduml
