@startuml
!pragma layout smetana
"KTableProcessorSupplier<KIn,VIn,KIn,VIn>" <|-- "org.apache.kafka.streams.kstream.internals.KTableFilter"
class org.apache.kafka.streams.kstream.internals.KTableFilter {
KTableFilter(KTableImpl<KIn,?,VIn>;Predicate<?superKIn,?superVIn>;boolean;String) : KTableFilter [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#35]]]
+get() : Processor<KIn,Change<VIn>,KIn,Change<VIn>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#48]]]
+enableSendingOldValues(boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#53]]]
-computeValue(KIn;VIn) : VIn [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#65]]]
-computeValue(KIn;ValueAndTimestamp<VIn>) : ValueAndTimestamp<VIn> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#75]]]
+view() : KTableValueGetterSupplier<KIn,VIn> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#139]]]
} 
@enduml
