@startuml
!pragma layout smetana
KTableProcessorSupplier_K,V,K,V_ <|-- org.apache.kafka.streams.kstream.internals.KTableReduce
class org.apache.kafka.streams.kstream.internals.KTableReduce {
KTableReduce(String;Reducer<V>;Reducer<V>) : KTableReduce [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableReduce.java.html#22]]]
+ enableSendingOldValues(boolean) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableReduce.java.html#29]]]
+ get() : Processor<K,Change<V>,K,Change<V>> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableReduce.java.html#36]]]
+ view() : KTableValueGetterSupplier<K,V> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableReduce.java.html#100]]]
} 
@enduml
