@startuml
!pragma layout smetana
"KTableRepartitionMapSupplier<K,V,KeyValue<K1,V1>,K1,V1>" <|-- "org.apache.kafka.streams.kstream.internals.KTableRepartitionMap"
class org.apache.kafka.streams.kstream.internals.KTableRepartitionMap {
KTableRepartitionMap(KTableImpl<K,?,V>;KeyValueMapper<?superK,?superV,KeyValue<K1,V1>>) : KTableRepartitionMap [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableRepartitionMap.java.html#41]]]
+get() : Processor<K,Change<V>,K1,Change<V1>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableRepartitionMap.java.html#47]]]
+view() : KTableValueGetterSupplier<K,KeyValue<K1,V1>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableRepartitionMap.java.html#52]]]
+enableSendingOldValues(boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableRepartitionMap.java.html#72]]]
} 
@enduml
