@startuml
!pragma layout smetana
KTableProcessorSupplier_KIn,VIn,KIn,VIn_ <|-- org.apache.kafka.streams.kstream.internals.KTableFilter
class org.apache.kafka.streams.kstream.internals.KTableFilter {
KTableFilter(KTableImpl<KIn,?,VIn>;Predicate<?superKIn,?superVIn>;boolean;String) : KTableFilter [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#20]]]
+ get() : Processor<KIn,Change<VIn>,KIn,Change<VIn>> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#33]]]
+ enableSendingOldValues(boolean) : boolean [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#38]]]
- computeValue(KIn;VIn) : VIn [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#50]]]
- computeValue(KIn;ValueAndTimestamp<VIn>) : ValueAndTimestamp<VIn> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#60]]]
+ view() : KTableValueGetterSupplier<KIn,VIn> [[[././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableFilter.java.html#124]]]
} 
@enduml
