@startuml
!pragma layout smetana
KTableValueGetterSupplier_K,V_ <|-- org.apache.kafka.streams.kstream.internals.KTableMaterializedValueGetterSupplier
class org.apache.kafka.streams.kstream.internals.KTableMaterializedValueGetterSupplier {
+  KTableMaterializedValueGetterSupplier(String)
+  get()
+  storeNames()
} 
@enduml
