@startuml
!pragma layout smetana
KTableProcessorSupplier<K,V,K,V> <|-- org.apache.kafka.streams.kstream.internals.KTableReduce
class org.apache.kafka.streams.kstream.internals.KTableReduce {
+  KTableReduce(String;Reducer<V>;Reducer<V>)
+  enableSendingOldValues(boolean)
+  get()
+  view()
} 
@enduml
