@startuml
!pragma layout smetana
"ProcessorSupplier<KIn,VIn,KIn,Change<VIn>>" <|-- "org.apache.kafka.streams.kstream.internals.KTableSource"
class org.apache.kafka.streams.kstream.internals.KTableSource {
+KTableSource(String;String) : KTableSource [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#27]]]
+queryableName() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#35]]]
+get() : Processor<KIn,VIn,KIn,Change<VIn>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#40]]]
+enableSendingOldValues() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#46]]]
+materialize() : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#53]]]
+materialized() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java.html#57]]]
} 
@enduml
