@startuml
!pragma layout smetana
KTableProcessorSupplier_K,V,K,V_ <|-- org.apache.kafka.streams.kstream.internals.KTableReduce
class org.apache.kafka.streams.kstream.internals.KTableReduce {
+  KTableReduce(String;Reducer<V>;Reducer<V>)
+  enableSendingOldValues(boolean)
+  get()
+  view()
} 
@enduml
