@startuml
!pragma layout smetana
KTableProcessorSupplier_KIn,VIn,KIn,VIn_ <|-- org.apache.kafka.streams.kstream.internals.KTablePassThrough
class org.apache.kafka.streams.kstream.internals.KTablePassThrough {
+  KTablePassThrough(Collection<KStreamAggProcessorSupplier>;String)
+  get()
+  enableSendingOldValues(boolean)
+  view()
} 
@enduml
