@startuml
!pragma layout smetana
"KTableProcessorSupplier<KIn,VIn,KIn,VAgg>" <|-- "org.apache.kafka.streams.kstream.internals.KTableAggregate"
class org.apache.kafka.streams.kstream.internals.KTableAggregate {
KTableAggregate(String;Initializer<VAgg>;Aggregator<?superKIn,?superVIn,VAgg>;Aggregator<?superKIn,?superVIn,VAgg>) : KTableAggregate [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableAggregate.java.html#40]]]
+enableSendingOldValues(boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableAggregate.java.html#51]]]
+get() : Processor<KIn,Change<VIn>,KIn,Change<VAgg>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableAggregate.java.html#58]]]
+view() : KTableValueGetterSupplier<KIn,VAgg> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableAggregate.java.html#128]]]
} 
@enduml
