@startuml
!pragma layout smetana
ProcessorSupplier<KIn,Change<VIn>,KOut,Change<VOut>> <|-- org.apache.kafka.streams.kstream.internals.KTableRepartitionMapSupplier
class org.apache.kafka.streams.kstream.internals.KTableRepartitionMapSupplier {
+  view()
+  enableSendingOldValues(boolean)
} 
@enduml
