@startuml
!pragma layout smetana
"KTableProcessorSupplier<K,V,K,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.KTableTransformValues"
class org.apache.kafka.streams.kstream.internals.KTableTransformValues {
KTableTransformValues(KTableImpl<K,?,V>;ValueTransformerWithKeySupplier<?superK,?superV,?extendsVOut>;String) : KTableTransformValues [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableTransformValues.java.html#43]]]
+get() : Processor<K,Change<V>,K,Change<VOut>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableTransformValues.java.html#52]]]
+view() : KTableValueGetterSupplier<K,VOut> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableTransformValues.java.html#57]]]
+enableSendingOldValues(boolean) : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableTransformValues.java.html#79]]]
} 
@enduml
