@startuml
!pragma layout smetana
Printed<K,V> <|-- org.apache.kafka.streams.kstream.internals.PrintedInternal
class org.apache.kafka.streams.kstream.internals.PrintedInternal {
+  PrintedInternal(Printed<K,V>)
+  build(String)
+  name()
} 
@enduml
