@startuml
!pragma layout smetana
"AbstractStream<K,V>SessionWindowedCogroupedKStream<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.SessionWindowedCogroupedKStreamImpl"
class org.apache.kafka.streams.kstream.internals.SessionWindowedCogroupedKStreamImpl {
SessionWindowedCogroupedKStreamImpl(SessionWindows;InternalStreamsBuilder;Set<String>;String;CogroupedStreamAggregateBuilder<K,V>;GraphNode;Map<KGroupedStreamImpl<K,?>,Aggregator<?superK,?superObject,V>>) : SessionWindowedCogroupedKStreamImpl [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#49]]]
+aggregate(Initializer<V>;Merger<?superK,V>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#64]]]
+aggregate(Initializer<V>;Merger<?superK,V>;Materialized<K,V,SessionStore<Bytes,byte[]>>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#70]]]
+aggregate(Initializer<V>;Merger<?superK,V>;Named) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#77]]]
+aggregate(Initializer<V>;Merger<?superK,V>;Named;Materialized<K,V,SessionStore<Bytes,byte[]>>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#83]]]
-materialize(MaterializedInternal<K,V,SessionStore<Bytes,byte[]>>) : StoreBuilder<SessionStore<K,V>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionWindowedCogroupedKStreamImpl.java.html#109]]]
} 
@enduml
