@startuml
!pragma layout smetana
AbstractStream<K,V>SessionWindowedCogroupedKStream<K,V> <|-- org.apache.kafka.streams.kstream.internals.SessionWindowedCogroupedKStreamImpl
class org.apache.kafka.streams.kstream.internals.SessionWindowedCogroupedKStreamImpl {
+  SessionWindowedCogroupedKStreamImpl(SessionWindows;InternalStreamsBuilder;Set<String>;String;CogroupedStreamAggregateBuilder<K,V>;GraphNode;Map<KGroupedStreamImpl<K,?>,Aggregator<?superK,?superObject,V>>)
+  aggregate(Initializer<V>;Merger<?superK,V>)
+  aggregate(Initializer<V>;Merger<?superK,V>;Materialized<K,V,SessionStore<Bytes,byte[]>>)
+  aggregate(Initializer<V>;Merger<?superK,V>;Named)
+  aggregate(Initializer<V>;Merger<?superK,V>;Named;Materialized<K,V,SessionStore<Bytes,byte[]>>)
+  materialize(MaterializedInternal<K,V,SessionStore<Bytes,byte[]>>)
} 
@enduml
