@startuml
!pragma layout smetana
"CacheFlushListener<Windowed<KOut>,VOut>" <|-- "org.apache.kafka.streams.kstream.internals.SessionCacheFlushListener"
class org.apache.kafka.streams.kstream.internals.SessionCacheFlushListener {
SessionCacheFlushListener(ProcessorContext<Windowed<KOut>,Change<VOut>>) : SessionCacheFlushListener [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionCacheFlushListener.java.html#32]]]
+apply(Record<Windowed<KOut>,Change<VOut>>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SessionCacheFlushListener.java.html#38]]]
} 
@enduml
