@startuml
!pragma layout smetana
"AbstractStream<K,V>TimeWindowedCogroupedKStream<K,V>" <|-- "org.apache.kafka.streams.kstream.internals.SlidingWindowedCogroupedKStreamImpl"
class org.apache.kafka.streams.kstream.internals.SlidingWindowedCogroupedKStreamImpl {
SlidingWindowedCogroupedKStreamImpl(SlidingWindows;InternalStreamsBuilder;Set<String>;String;CogroupedStreamAggregateBuilder<K,V>;GraphNode;Map<KGroupedStreamImpl<K,?>,Aggregator<?superK,?superObject,V>>) : SlidingWindowedCogroupedKStreamImpl [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#46]]]
+aggregate(Initializer<V>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#61]]]
+aggregate(Initializer<V>;Materialized<K,V,WindowStore<Bytes,byte[]>>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#66]]]
+aggregate(Initializer<V>;Named) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#72]]]
+aggregate(Initializer<V>;Named;Materialized<K,V,WindowStore<Bytes,byte[]>>) : KTable<Windowed<K>,V> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#78]]]
-materialize(MaterializedInternal<K,V,WindowStore<Bytes,byte[]>>) : StoreBuilder<TimestampedWindowStore<K,V>> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/SlidingWindowedCogroupedKStreamImpl.java.html#101]]]
} 
@enduml
