@startuml
!pragma layout smetana
"StreamJoined<K,V1,V2>" <|-- "org.apache.kafka.streams.kstream.internals.StreamJoinedInternal"
class org.apache.kafka.streams.kstream.internals.StreamJoinedInternal {
+StreamJoinedInternal(StreamJoined<K,V1,V2>) : StreamJoinedInternal [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#14]]]
+keySerde() : Serde<K> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#18]]]
+valueSerde() : Serde<V1> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#22]]]
+otherValueSerde() : Serde<V2> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#26]]]
+name() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#30]]]
+storeName() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#34]]]
+thisStoreSupplier() : WindowBytesStoreSupplier [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#38]]]
+otherStoreSupplier() : WindowBytesStoreSupplier [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#42]]]
+loggingEnabled() : boolean [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#46]]]
logConfig() : Map<String,String> [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/StreamJoinedInternal.java.html#50]]]
} 
@enduml
