@startuml
!pragma layout smetana
TableJoined_K,KO_ <|-- org.apache.kafka.streams.kstream.internals.TableJoinedInternal
class org.apache.kafka.streams.kstream.internals.TableJoinedInternal {
+  TableJoinedInternal(TableJoined<K,KO>)
+  partitioner()
+  otherPartitioner()
+  name()
} 
@enduml
