@startuml
!pragma layout smetana
CacheFlushListener_KOut,ValueAndTimestamp_VOut__ <|-- org.apache.kafka.streams.kstream.internals.TimestampedCacheFlushListener
class org.apache.kafka.streams.kstream.internals.TimestampedCacheFlushListener {
+  TimestampedCacheFlushListener(ProcessorContext<KOut,Change<VOut>>)
+  apply(Record<KOut,Change<ValueAndTimestamp<VOut>>>)
} 
@enduml
