@startuml
!pragma layout smetana
"Deserializer<Outer>" <|-- "org.apache.kafka.streams.kstream.internals.WrappingNullableDeserializer"
class org.apache.kafka.streams.kstream.internals.WrappingNullableDeserializer {
setIfUnset(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/WrappingNullableDeserializer.java.html#8]]]
} 
@enduml
