@startuml
!pragma layout smetana
Serializer_Outer_ <|-- org.apache.kafka.streams.kstream.internals.WrappingNullableSerializer
class org.apache.kafka.streams.kstream.internals.WrappingNullableSerializer {
+  setIfUnset(SerdeGetter)
} 
@enduml
