@startuml
!pragma layout smetana
Serializer_Outer_ <|-- org.apache.kafka.streams.kstream.internals.WrappingNullableSerializer
class org.apache.kafka.streams.kstream.internals.WrappingNullableSerializer {
setIfUnset(SerdeGetter) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/kstream/internals/WrappingNullableSerializer.java.html#8]]]
} 
@enduml
