@startuml
!pragma layout smetana
"MetricsReporter" <|-- "org.apache.kafka.common.metrics.JmxReporter"
class org.apache.kafka.common.metrics.JmxReporter {
+JmxReporter() : JmxReporter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#76]]]
+JmxReporter(String) : JmxReporter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#87]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#92]]]
+reconfigurableConfigs() : Set<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#97]]]
+validateReconfiguration(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#102]]]
+reconfigure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#107]]]
+init(List<KafkaMetric>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#122]]]
+containsMbean(String) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#135]]]
+metricChange(KafkaMetric) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#140]]]
+metricRemoval(KafkaMetric) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#150]]]
-removeAttribute(KafkaMetric;String) : KafkaMbean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#165]]]
-addAttribute(KafkaMetric) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#173]]]
getMBeanName(String;MetricName) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#191]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#207]]]
-unregister(KafkaMbean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#214]]]
-reregister(KafkaMbean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#224]]]
+compilePredicate(Map<String,?>) : Predicate<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#310]]]
+contextChange(MetricsContext) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#338]]]
} 
@enduml
