@startuml
!pragma layout smetana
"MetricsReporter" <|-- "org.apache.kafka.common.metrics.JmxReporter"
class org.apache.kafka.common.metrics.JmxReporter {
+JmxReporter() : JmxReporter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#59]]]
+JmxReporter(String) : JmxReporter [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#65]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#70]]]
+reconfigurableConfigs() : Set<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#75]]]
+validateReconfiguration(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#80]]]
+reconfigure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#85]]]
+init(List<KafkaMetric>) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#100]]]
+containsMbean(String) : boolean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#113]]]
+metricChange(KafkaMetric) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#118]]]
+metricRemoval(KafkaMetric) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#128]]]
-removeAttribute(KafkaMetric;String) : KafkaMbean [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#143]]]
-addAttribute(KafkaMetric) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#151]]]
getMBeanName(String;MetricName) : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#166]]]
+close() : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#182]]]
-unregister(KafkaMbean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#189]]]
-reregister(KafkaMbean) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#199]]]
+compilePredicate(Map<String,?>) : Predicate<String> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#285]]]
+contextChange(MetricsContext) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java.html#313]]]
} 
@enduml
