@startuml
!pragma layout smetana
Closeable <|-- org.apache.kafka.common.metrics.Metrics
class org.apache.kafka.common.metrics.Metrics {
+  Metrics()
+  Metrics(Time)
+  Metrics(MetricConfig;Time)
+  Metrics(MetricConfig)
+  Metrics(MetricConfig;List<MetricsReporter>;Time)
+  Metrics(MetricConfig;List<MetricsReporter>;Time;MetricsContext)
+  Metrics(MetricConfig;List<MetricsReporter>;Time;boolean)
+  Metrics(MetricConfig;List<MetricsReporter>;Time;boolean;MetricsContext)
+  metricName(String;String;String;Map<String,String>)
+  metricName(String;String;String)
+  metricName(String;String)
+  metricName(String;String;String;String...)
+  metricName(String;String;Map<String,String>)
+  toHtmlTable(String;Iterable<MetricNameTemplate>)
+  config()
+  getSensor(String)
+  sensor(String)
+  sensor(String;Sensor.RecordingLevel)
+  sensor(String;Sensor...)
+  sensor(String;Sensor.RecordingLevel;Sensor...)
+  sensor(String;MetricConfig;Sensor...)
+  sensor(String;MetricConfig;Sensor.RecordingLevel;Sensor...)
+  sensor(String;MetricConfig;long;Sensor.RecordingLevel;Sensor...)
+  sensor(String;MetricConfig;long;Sensor...)
+  removeSensor(String)
+  addMetric(MetricName;Measurable)
+  addMetric(MetricName;MetricConfig;Measurable)
+  addMetric(MetricName;MetricConfig;MetricValueProvider<?>)
+  addMetric(MetricName;MetricValueProvider<?>)
+  addMetricIfAbsent(MetricName;MetricConfig;MetricValueProvider<?>)
+  removeMetric(MetricName)
+  addReporter(MetricsReporter)
+  removeReporter(MetricsReporter)
+  registerMetric(KafkaMetric)
+  metrics()
+  reporters()
+  metric(MetricName)
+  childrenSensors()
+  metricInstance(MetricNameTemplate;String...)
+  metricInstance(MetricNameTemplate;Map<String,String>)
+  close()
} 
@enduml
