@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.metrics.Stat"
class org.apache.kafka.common.metrics.Stat {
record(MetricConfig;double;long) : void [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/metrics/Stat.java.html#8]]]
} 
@enduml
