@startuml
!pragma layout smetana
ProcessorContext <|-- org.apache.kafka.streams.processor.MockProcessorContext
class org.apache.kafka.streams.processor.MockProcessorContext {
+  MockProcessorContext()
+  MockProcessorContext(Properties)
+  MockProcessorContext(Properties;TaskId;File)
+  applicationId()
+  taskId()
+  appConfigs()
+  appConfigsWithPrefix(String)
+  currentSystemTimeMs()
+  currentStreamTimeMs()
+  keySerde()
+  valueSerde()
+  stateDir()
+  metrics()
+  setRecordMetadata(String;int;long;Headers;long)
+  setTopic(String)
+  setPartition(int)
+  setOffset(long)
+  setHeaders(Headers)
+  setTimestamp(long)
+  setRecordTimestamp(long)
+  setCurrentSystemTimeMs(long)
+  setCurrentStreamTimeMs(long)
+  topic()
+  partition()
+  offset()
+  headers()
+  timestamp()
+  register(StateStore;StateRestoreCallback)
+  schedule(Duration;PunctuationType;Punctuator)
+  scheduledPunctuators()
+  forwarded()
+  forwarded(String)
+  resetForwards()
+  commit()
+  committed()
+  resetCommit()
+  recordCollector()
} 
@enduml
