@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.quota.ClientQuotaAlteration
class org.apache.kafka.common.quota.ClientQuotaAlteration {
+ClientQuotaAlteration(ClientQuotaEntity;Collection<Op>) : ClientQuotaAlteration [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/quota/ClientQuotaAlteration.java.html#54]]]
+entity() : ClientQuotaEntity [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/quota/ClientQuotaAlteration.java.html#60]]]
+ops() : Collection<Op> [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/quota/ClientQuotaAlteration.java.html#65]]]
+toString() : String [[[./../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/quota/ClientQuotaAlteration.java.html#70]]]
} 
@enduml
