@startuml
!pragma layout smetana
"Deserializer<JsonNode>" <|-- "org.apache.kafka.connect.json.JsonDeserializer"
class org.apache.kafka.connect.json.JsonDeserializer {
+JsonDeserializer() : JsonDeserializer [[[./../../../../../../../../../../.././qc/connect/json/src/main/java/org/apache/kafka/connect/json/JsonDeserializer.java.html#38]]]
JsonDeserializer(Set<DeserializationFeature>;JsonNodeFactory) : JsonDeserializer [[[./../../../../../../../../../../.././qc/connect/json/src/main/java/org/apache/kafka/connect/json/JsonDeserializer.java.html#49]]]
+deserialize(String;byte[]) : JsonNode [[[./../../../../../../../../../../.././qc/connect/json/src/main/java/org/apache/kafka/connect/json/JsonDeserializer.java.html#58]]]
} 
@enduml
