@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.assignment.AssignmentInfo"
class org.apache.kafka.streams.processor.internals.assignment.AssignmentInfo {
+AssignmentInfo(int;int) : AssignmentInfo [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#62]]]
+AssignmentInfo(int;List<TaskId>;Map<TaskId,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>;int) : AssignmentInfo [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#73]]]
+AssignmentInfo(int;int;List<TaskId>;Map<TaskId,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>;Map<HostInfo,Set<TopicPartition>>;int) : AssignmentInfo [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#82]]]
+setNextRebalanceTime(long) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#103]]]
+version() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#107]]]
+errCode() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#111]]]
+commonlySupportedVersion() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#115]]]
+activeTasks() : List<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#119]]]
+standbyTasks() : Map<TaskId,Set<TopicPartition>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#123]]]
+partitionsByHost() : Map<HostInfo,Set<TopicPartition>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#127]]]
+standbyPartitionByHost() : Map<HostInfo,Set<TopicPartition>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#131]]]
+nextRebalanceMs() : long [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#135]]]
+encode() : ByteBuffer [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#143]]]
-encodeActiveAndStandbyTaskAssignment(DataOutputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#210]]]
-encodePartitionsByHost(DataOutputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#228]]]
-encodeHostPartitionMapUsingDictionary(DataOutputStream;Map<String,Integer>;Map<HostInfo,Set<TopicPartition>>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#237]]]
-encodeTopicDictionaryAndGet(DataOutputStream;Set<TopicPartition>) : Map<String,Integer> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#254]]]
-encodePartitionsByHostAsDictionary(DataOutputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#275]]]
-encodeActiveAndStandbyHostPartitions(DataOutputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#282]]]
-writeHostInfo(DataOutputStream;HostInfo) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#291]]]
-writeTopicPartitions(DataOutputStream;Set<TopicPartition>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#296]]]
+decode(ByteBuffer) : AssignmentInfo [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#308]]]
-decodeActiveTasks(AssignmentInfo;DataInputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#387]]]
-decodeStandbyTasks(AssignmentInfo;DataInputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#396]]]
-decodePartitionsByHost(AssignmentInfo;DataInputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#406]]]
-readTopicPartitions(DataInputStream) : Set<TopicPartition> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#416]]]
-decodeTopicIndexAndGet(DataInputStream) : Map<Integer,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#425]]]
-decodeHostPartitionMapUsingDictionary(DataInputStream;Map<Integer,String>) : Map<HostInfo,Set<TopicPartition>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#434]]]
-decodePartitionsByHostUsingDictionary(AssignmentInfo;DataInputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#445]]]
-decodeActiveAndStandbyHostPartitions(AssignmentInfo;DataInputStream) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#451]]]
-readTopicPartitions(DataInputStream;Map<Integer,String>) : Set<TopicPartition> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#458]]]
+hashCode() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#469]]]
+equals(Object) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#476]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/AssignmentInfo.java.html#492]]]
} 
@enduml
