@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.assignment.ClientState
class org.apache.kafka.streams.processor.internals.assignment.ClientState {
+  ClientState()
+  ClientState(Map<String,String>)
+  ClientState(int)
+  ClientState(int;Map<String,String>)
+  ClientState(Set<TaskId>;Set<TaskId>;Map<TaskId,Long>;Map<String,String>;int)
+  capacity()
+  incrementCapacity()
+  reachedCapacity()
+  activeTasks()
+  activeTaskCount()
+  activeTaskLoad()
+  assignActiveTasks(Collection<TaskId>)
+  assignActiveToConsumer(TaskId;String)
+  assignStandbyToConsumer(TaskId;String)
+  revokeActiveFromConsumer(TaskId;String)
+  prevOwnedActiveTasksByConsumer()
+  prevOwnedStandbyByConsumer()
+  prevOwnedStatefulTasksByConsumer(String)
+  assignedActiveTasksByConsumer()
+  revokingActiveTasksByConsumer()
+  assignedStandbyTasksByConsumer()
+  assignActive(TaskId)
+  unassignActive(TaskId)
+  standbyTasks()
+  hasStandbyTask(TaskId)
+  standbyTaskCount()
+  assignStandby(TaskId)
+  unassignStandby(TaskId)
+  assignedTasks()
+  assignedTaskCount()
+  assignedTaskLoad()
+  hasAssignedTask(TaskId)
+  prevActiveTasks()
+  addPreviousActiveTask(TaskId)
+  addPreviousActiveTasks(Set<TaskId>)
+  prevStandbyTasks()
+  addPreviousStandbyTask(TaskId)
+  addPreviousStandbyTasks(Set<TaskId>)
+  previousAssignedTasks()
+  previousOwnerForPartition(TopicPartition)
+  clientTags()
+  addOwnedPartitions(Collection<TopicPartition>;String)
+  addPreviousTasksAndOffsetSums(String;Map<TaskId,Long>)
+  initializePrevTasks(Map<TopicPartition,TaskId>;boolean)
+  maybeFilterUnknownPrevTasksAndPartitions(Map<TopicPartition,TaskId>;boolean)
+  computeTaskLags(UUID;Map<TaskId,Long>)
+  lagFor(TaskId)
+  prevTasksByLag(String)
+  statefulActiveTasks()
+  statelessActiveTasks()
+  hasUnfulfilledQuota(int)
+  hasMoreAvailableCapacityThan(ClientState)
+  consumers()
+  currentAssignment()
+  toString()
+  isStateful(TaskId)
+  initializePrevActiveTasksFromOwnedPartitions(Map<TopicPartition,TaskId>)
+  initializeRemainingPrevTasksFromTaskOffsetSums()
+  assertNotAssigned(TaskId)
} 
@enduml
