@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.processor.internals.assignment.ClientState"
class org.apache.kafka.streams.processor.internals.assignment.ClientState {
+ClientState() : ClientState [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#63]]]
+ClientState(Map<String,String>) : ClientState [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#67]]]
ClientState(int) : ClientState [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#71]]]
ClientState(int;Map<String,String>) : ClientState [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#75]]]
+ClientState(Set<TaskId>;Set<TaskId>;Map<TaskId,Long>;Map<String,String>;int) : ClientState [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#85]]]
capacity() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#98]]]
+incrementCapacity() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#102]]]
reachedCapacity() : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#106]]]
+activeTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#110]]]
+activeTaskCount() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#114]]]
activeTaskLoad() : double [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#118]]]
+assignActiveTasks(Collection<TaskId>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#122]]]
+assignActiveToConsumer(TaskId;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#126]]]
+assignStandbyToConsumer(TaskId;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#134]]]
+revokeActiveFromConsumer(TaskId;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#138]]]
+prevOwnedActiveTasksByConsumer() : Map<String,Set<TaskId>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#142]]]
+prevOwnedStandbyByConsumer() : Map<String,Set<TaskId>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#146]]]
+prevOwnedStatefulTasksByConsumer(String) : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#162]]]
+assignedActiveTasksByConsumer() : Map<String,Set<TaskId>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#166]]]
+revokingActiveTasksByConsumer() : Map<String,Set<TaskId>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#170]]]
+assignedStandbyTasksByConsumer() : Map<String,Set<TaskId>> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#174]]]
+assignActive(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#178]]]
+unassignActive(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#183]]]
+standbyTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#191]]]
hasStandbyTask(TaskId) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#195]]]
standbyTaskCount() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#199]]]
+assignStandby(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#203]]]
unassignStandby(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#208]]]
assignedTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#216]]]
+assignedTaskCount() : int [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#231]]]
assignedTaskLoad() : double [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#235]]]
hasAssignedTask(TaskId) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#239]]]
prevActiveTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#243]]]
-addPreviousActiveTask(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#247]]]
addPreviousActiveTasks(Set<TaskId>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#251]]]
prevStandbyTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#255]]]
-addPreviousStandbyTask(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#259]]]
addPreviousStandbyTasks(Set<TaskId>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#263]]]
previousAssignedTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#267]]]
+previousOwnerForPartition(TopicPartition) : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#276]]]
+clientTags() : Map<String,String> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#280]]]
+addOwnedPartitions(Collection<TopicPartition>;String) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#284]]]
+addPreviousTasksAndOffsetSums(String;Map<TaskId,Long>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#290]]]
+initializePrevTasks(Map<TopicPartition,TaskId>;boolean) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#295]]]
-maybeFilterUnknownPrevTasksAndPartitions(Map<TopicPartition,TaskId>;boolean) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#306]]]
+computeTaskLags(UUID;Map<TaskId,Long>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#321]]]
+lagFor(TaskId) : long [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#355]]]
+prevTasksByLag(String) : SortedSet<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#366]]]
+statefulActiveTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#378]]]
+statelessActiveTasks() : Set<TaskId> [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#382]]]
hasUnfulfilledQuota(int) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#386]]]
hasMoreAvailableCapacityThan(ClientState) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#390]]]
+consumers() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#411]]]
+currentAssignment() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#415]]]
+toString() : String [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#421]]]
-isStateful(TaskId) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#434]]]
-initializePrevActiveTasksFromOwnedPartitions(Map<TopicPartition,TaskId>) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#438]]]
-initializeRemainingPrevTasksFromTaskOffsetSums() : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#455]]]
-assertNotAssigned(TaskId) : void [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ClientState.java.html#474]]]
} 
@enduml
