@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.assignment.ConsumerProtocolUtils
class org.apache.kafka.streams.processor.internals.assignment.ConsumerProtocolUtils {
+ writeTaskIdTo(TaskId;DataOutputStream;int) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ConsumerProtocolUtils.java.html#18]]]
+ readTaskIdFrom(DataInputStream;int) : TaskId [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ConsumerProtocolUtils.java.html#34]]]
+ writeTaskIdTo(TaskId;ByteBuffer;int) : void [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ConsumerProtocolUtils.java.html#51]]]
+ readTaskIdFrom(ByteBuffer;int) : TaskId [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ConsumerProtocolUtils.java.html#68]]]
- getNamedTopologyOrElseNull(String) : String [[[././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/ConsumerProtocolUtils.java.html#86]]]
} 
@enduml
