@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.assignment.ConstrainedPrioritySet
class org.apache.kafka.streams.processor.internals.assignment.ConstrainedPrioritySet {
+  ConstrainedPrioritySet(BiFunction<UUID,TaskId,Boolean>;Function<UUID,Double>)
+  poll(TaskId;Function<UUID,Boolean>)
+  poll(TaskId)
+  offerAll(Collection<UUID>)
+  offer(UUID)
+  pollNextClient()
} 
@enduml
