@startuml
!pragma layout smetana
StandbyTaskAssignor <|-- org.apache.kafka.streams.processor.internals.assignment.DefaultStandbyTaskAssignor
class org.apache.kafka.streams.processor.internals.assignment.DefaultStandbyTaskAssignor {
+assign(Map<UUID,ClientState>;Set<TaskId>;Set<TaskId>;AssignorConfiguration.AssignmentConfigs) : boolean [[[./../../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/DefaultStandbyTaskAssignor.java.html#21]]]
} 
@enduml
