@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.processor.internals.assignment.StandbyTaskAssignmentUtils
class org.apache.kafka.streams.processor.internals.assignment.StandbyTaskAssignmentUtils {
+  StandbyTaskAssignmentUtils()
+  createLeastLoadedPrioritySetConstrainedByAssignedTask(Map<UUID,ClientState>)
+  pollClientAndMaybeAssignAndUpdateRemainingStandbyTasks(int;Map<UUID,ClientState>;Map<TaskId,Integer>;ConstrainedPrioritySet;TaskId;Logger)
+  computeTasksToRemainingStandbys(int;Set<TaskId>)
} 
@enduml
