@startuml
!pragma layout smetana
"ShutdownableThread" <|-- "kafka.examples.Consumer"
class kafka.examples.Consumer {
+Consumer(String;String;Optional<String>;boolean;int;CountDownLatch) : Consumer [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/Consumer.java.html#24]]]
get() : KafkaConsumer<Integer,String> [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/Consumer.java.html#53]]]
+doWork() : void [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/Consumer.java.html#58]]]
+name() : String [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/Consumer.java.html#72]]]
+isInterruptible() : boolean [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/Consumer.java.html#77]]]
} 
@enduml
