@startuml
!pragma layout smetana
java.lang.Object <|-- kafka.examples.KafkaProperties
class kafka.examples.KafkaProperties {
-KafkaProperties() : KafkaProperties [[[./../../../../../../.././qc/examples/src/main/java/kafka/examples/KafkaProperties.java.html#9]]]
} 
@enduml
