@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.producer.internals.BufferPool"
class org.apache.kafka.clients.producer.internals.BufferPool {
+BufferPool(long;int;Metrics;Time;String) : BufferPool [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#70]]]
+allocate(int;long) : ByteBuffer [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#111]]]
recordWaitTime(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#214]]]
-safeAllocateByteBuffer(int) : ByteBuffer [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#222]]]
allocateByteBuffer(int) : ByteBuffer [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#243]]]
-freeUp(int) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#251]]]
+deallocate(ByteBuffer;int) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#264]]]
+deallocate(ByteBuffer) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#281]]]
+availableMemory() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#289]]]
freeSize() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#299]]]
+unallocatedMemory() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#306]]]
+queued() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#318]]]
+poolableSize() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#330]]]
+totalMemory() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#337]]]
waiters() : Deque<Condition> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#342]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/BufferPool.java.html#350]]]
} 
@enduml
