@startuml
!pragma layout smetana
Future_RecordMetadata_ <|-- org.apache.kafka.clients.producer.internals.FutureRecordMetadata
class org.apache.kafka.clients.producer.internals.FutureRecordMetadata {
+  FutureRecordMetadata(ProduceRequestResult;int;long;int;int;Time)
+  cancel(boolean)
+  isCancelled()
+  get()
+  get(long;TimeUnit)
+  chain(FutureRecordMetadata)
+  valueOrError()
+  value()
+  timestamp()
+  isDone()
} 
@enduml
