@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.producer.internals.ProducerBatch
class org.apache.kafka.clients.producer.internals.ProducerBatch {
+ProducerBatch(TopicPartition;MemoryRecordsBuilder;long) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#63]]]
+ProducerBatch(TopicPartition;MemoryRecordsBuilder;long;boolean) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#67]]]
+tryAppend(long;byte[];byte[];Header[];Callback;long) : FutureRecordMetadata [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#82]]]
-tryAppendForSplit(long;ByteBuffer;ByteBuffer;Header[];Thunk) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#104]]]
+abort(RuntimeException) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#126]]]
+isDone() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#135]]]
+complete(long;long) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#140]]]
+completeExceptionally(RuntimeException;Function<Integer,RuntimeException>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#145]]]
-done(long;long;RuntimeException;Function<Integer,RuntimeException>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#155]]]
-completeFutureAndFireCallbacks(long;long;Function<Integer,RuntimeException>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#190]]]
+split(int) : Deque<ProducerBatch> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#219]]]
-createBatchOffAccumulatorForRecord(Record;int) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#275]]]
+isCompressed() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#288]]]
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#304]]]
hasReachedDeliveryTimeout(long;long) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#308]]]
+finalState() : FinalState [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#312]]]
attempts() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#316]]]
reenqueued(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#320]]]
queueTimeMs() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#327]]]
waitedTimeMs(long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#331]]]
drained(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#335]]]
isSplitBatch() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#339]]]
+inRetry() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#344]]]
+records() : MemoryRecords [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#348]]]
+estimatedSizeInBytes() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#352]]]
+compressionRatio() : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#356]]]
+isFull() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#360]]]
+setProducerState(ProducerIdAndEpoch;int;boolean) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#364]]]
+resetProducerState(ProducerIdAndEpoch;int;boolean) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#368]]]
+closeForRecordAppends() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#376]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#380]]]
+abortRecordAppends() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#391]]]
+isClosed() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#395]]]
+buffer() : ByteBuffer [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#399]]]
+initialCapacity() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#403]]]
+isWritable() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#407]]]
+magic() : byte [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#411]]]
+producerId() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#415]]]
+producerEpoch() : short [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#419]]]
+baseSequence() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#423]]]
+lastSequence() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#427]]]
+hasSequence() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#431]]]
+isTransactional() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#435]]]
+sequenceHasBeenReset() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#439]]]
} 
@enduml
