@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.producer.internals.ProducerBatch"
class org.apache.kafka.clients.producer.internals.ProducerBatch {
+ProducerBatch(TopicPartition;MemoryRecordsBuilder;long) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#82]]]
+ProducerBatch(TopicPartition;MemoryRecordsBuilder;long;boolean) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#86]]]
+tryAppend(long;byte[];byte[];Header[];Callback;long) : FutureRecordMetadata [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#105]]]
-tryAppendForSplit(long;ByteBuffer;ByteBuffer;Header[];Thunk) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#130]]]
+abort(RuntimeException) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#156]]]
+isDone() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#172]]]
+complete(long;long) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#183]]]
+completeExceptionally(RuntimeException;Function<Integer,RuntimeException>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#196]]]
-done(long;long;RuntimeException;Function<Integer,RuntimeException>) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#224]]]
-completeFutureAndFireCallbacks(long;long;Function<Integer,RuntimeException>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#259]]]
+split(int) : Deque<ProducerBatch> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#288]]]
-createBatchOffAccumulatorForRecord(Record;int) : ProducerBatch [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#344]]]
+isCompressed() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#357]]]
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#375]]]
hasReachedDeliveryTimeout(long;long) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#379]]]
+finalState() : FinalState [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#383]]]
attempts() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#387]]]
reenqueued(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#391]]]
queueTimeMs() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#398]]]
waitedTimeMs(long) : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#402]]]
drained(long) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#406]]]
isSplitBatch() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#410]]]
+inRetry() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#417]]]
+records() : MemoryRecords [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#421]]]
+estimatedSizeInBytes() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#425]]]
+compressionRatio() : double [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#429]]]
+isFull() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#433]]]
+setProducerState(ProducerIdAndEpoch;int;boolean) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#437]]]
+resetProducerState(ProducerIdAndEpoch;int;boolean) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#441]]]
+closeForRecordAppends() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#452]]]
+close() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#456]]]
+abortRecordAppends() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#473]]]
+isClosed() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#477]]]
+buffer() : ByteBuffer [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#481]]]
+initialCapacity() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#485]]]
+isWritable() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#489]]]
+magic() : byte [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#493]]]
+producerId() : long [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#497]]]
+producerEpoch() : short [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#501]]]
+baseSequence() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#505]]]
+lastSequence() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#509]]]
+hasSequence() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#513]]]
+isTransactional() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#517]]]
+sequenceHasBeenReset() : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java.html#521]]]
} 
@enduml
