@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.clients.producer.internals.TransactionManager
class org.apache.kafka.clients.producer.internals.TransactionManager {
+ TransactionManager(LogContext;String;int;long;ApiVersions) : TransactionManager [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#182]]]
+ initializeTransactions() : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#205]]]
initializeTransactions(ProducerIdAndEpoch) : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#209]]]
+ beginTransaction() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#233]]]
+ beginCommit() : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#240]]]
+ beginAbort() : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#248]]]
- beginCompletingTransaction(TransactionResult) : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#260]]]
+ sendOffsetsToTransaction(Map<TopicPartition,OffsetAndMetadata>;ConsumerGroupMetadata) : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#285]]]
+ maybeAddPartition(TopicPartition) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#310]]]
lastError() : RuntimeException [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#331]]]
isSendToPartitionAllowed(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#335]]]
+ transactionalId() : String [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#341]]]
+ hasProducerId() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#345]]]
+ isTransactional() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#349]]]
hasPartitionsToAdd() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#353]]]
isCompleting() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#357]]]
hasError() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#361]]]
isAborting() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#365]]]
transitionToAbortableError(RuntimeException) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#369]]]
transitionToFatalError(RuntimeException) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#380]]]
isPartitionAdded(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#390]]]
isPartitionPendingAdd(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#395]]]
producerIdAndEpoch() : ProducerIdAndEpoch [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#400]]]
+ maybeUpdateProducerIdAndEpoch(TopicPartition) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#404]]]
- setProducerIdAndEpoch(ProducerIdAndEpoch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#415]]]
- resetIdempotentProducerId() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#421]]]
- resetSequenceForPartition(TopicPartition) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#430]]]
- resetSequenceNumbers() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#435]]]
requestEpochBumpForPartition(TopicPartition) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#440]]]
- bumpIdempotentProducerEpoch() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#445]]]
bumpIdempotentEpochAndResetIdIfNeeded() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#463]]]
sequenceNumber(TopicPartition) : Integer [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#480]]]
producerIdAndEpoch(TopicPartition) : ProducerIdAndEpoch [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#485]]]
incrementSequenceNumber(TopicPartition;int) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#489]]]
addInFlightBatch(ProducerBatch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#496]]]
firstInFlightSequence(TopicPartition) : int [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#503]]]
nextBatchBySequence(TopicPartition) : ProducerBatch [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#514]]]
removeInFlightBatch(ProducerBatch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#519]]]
- maybeUpdateLastAckedSequence(TopicPartition;int) : int [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#525]]]
lastAckedSequence(TopicPartition) : OptionalInt [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#535]]]
lastAckedOffset(TopicPartition) : OptionalLong [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#539]]]
- updateLastAckedOffset(ProduceResponse.PartitionResponse;ProducerBatch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#543]]]
+ handleCompletedBatch(ProducerBatch;ProduceResponse.PartitionResponse) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#561]]]
+ maybeTransitionToErrorState(RuntimeException) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#572]]]
handleFailedBatch(ProducerBatch;RuntimeException;boolean) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#586]]]
- adjustSequencesDueToFailedBatch(ProducerBatch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#627]]]
hasInflightBatches(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#654]]]
hasStaleProducerIdAndEpoch(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#658]]]
hasUnresolvedSequences() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#662]]]
hasUnresolvedSequence(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#666]]]
markSequenceUnresolved(ProducerBatch) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#670]]]
maybeResolveSequences() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#680]]]
- isNextSequence(TopicPartition;int) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#719]]]
- setNextSequence(TopicPartition;int) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#723]]]
- isNextSequenceForUnresolvedPartition(TopicPartition;int) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#727]]]
nextRequest(boolean) : TxnRequestHandler [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#732]]]
retry(TxnRequestHandler) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#767]]]
authenticationFailed(AuthenticationException) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#772]]]
close() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#777]]]
coordinator(FindCoordinatorRequest.CoordinatorType) : Node [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#786]]]
lookupCoordinator(TxnRequestHandler) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#797]]]
setInFlightCorrelationId(int) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#801]]]
- clearInFlightCorrelationId() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#805]]]
hasInFlightRequest() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#809]]]
hasFatalError() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#814]]]
hasAbortableError() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#819]]]
transactionContainsPartition(TopicPartition) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#824]]]
hasPendingOffsetCommits() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#829]]]
hasPendingRequests() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#833]]]
hasOngoingTransaction() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#838]]]
canRetry(ProduceResponse.PartitionResponse;ProducerBatch) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#843]]]
isReady() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#913]]]
handleCoordinatorReady() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#917]]]
- transitionTo(State) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#928]]]
- transitionTo(State;RuntimeException) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#932]]]
- ensureTransactional() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#955]]]
- maybeFailWithError() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#960]]]
- maybeTerminateRequestWithError(TxnRequestHandler) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#977]]]
- enqueueRequest(TxnRequestHandler) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#989]]]
- lookupCoordinator(FindCoordinatorRequest.CoordinatorType;String) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#994]]]
- addPartitionsToTransactionHandler() : TxnRequestHandler [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1013]]]
- txnOffsetCommitHandler(TransactionalRequestResult;Map<TopicPartition,OffsetAndMetadata>;ConsumerGroupMetadata) : TxnOffsetCommitHandler [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1024]]]
- throwIfPendingState(String) : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1047]]]
- handleCachedTransactionRequestResult(Supplier<TransactionalRequestResult>;State;String) : TransactionalRequestResult [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1059]]]
canBumpEpoch() : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1084]]]
- completeTransaction() : void [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1092]]]
- isFatalException(Errors) : boolean [[[././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java.html#1640]]]
} 
@enduml
