@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.clients.producer.internals.TxnPartitionMap"
class org.apache.kafka.clients.producer.internals.TxnPartitionMap {
get(TopicPartition) : TxnPartitionEntry [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#33]]]
getOrCreate(TopicPartition) : TxnPartitionEntry [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#42]]]
contains(TopicPartition) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#46]]]
reset() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#50]]]
lastAckedOffset(TopicPartition) : OptionalLong [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#54]]]
lastAckedSequence(TopicPartition) : OptionalInt [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#63]]]
startSequencesAtBeginning(TopicPartition;ProducerIdAndEpoch) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/clients/producer/internals/TxnPartitionMap.java.html#72]]]
} 
@enduml
