@startuml
!pragma layout smetana
"ProductionExceptionHandler" <|-- "org.apache.kafka.streams.errors.DefaultProductionExceptionHandler"
class org.apache.kafka.streams.errors.DefaultProductionExceptionHandler {
+handle(ProducerRecord<byte[],byte[]>;Exception) : ProductionExceptionHandlerResponse [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/errors/DefaultProductionExceptionHandler.java.html#28]]]
+configure(Map<String,?>) : void [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/errors/DefaultProductionExceptionHandler.java.html#34]]]
} 
@enduml
