@startuml
!pragma layout smetana
StreamsException <|-- org.apache.kafka.streams.errors.InvalidStateStoreException
class org.apache.kafka.streams.errors.InvalidStateStoreException {
+ InvalidStateStoreException(String) : InvalidStateStoreException [[[././qc/streams/src/main/java/org/apache/kafka/streams/errors/InvalidStateStoreException.java.html#10]]]
+ InvalidStateStoreException(String;Throwable) : InvalidStateStoreException [[[././qc/streams/src/main/java/org/apache/kafka/streams/errors/InvalidStateStoreException.java.html#14]]]
+ InvalidStateStoreException(Throwable) : InvalidStateStoreException [[[././qc/streams/src/main/java/org/apache/kafka/streams/errors/InvalidStateStoreException.java.html#18]]]
} 
@enduml
