@startuml
!pragma layout smetana
"Configurable" <|-- "org.apache.kafka.streams.errors.ProductionExceptionHandler"
class org.apache.kafka.streams.errors.ProductionExceptionHandler {
handle(ProducerRecord<byte[],byte[]>;Exception) : ProductionExceptionHandlerResponse [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/errors/ProductionExceptionHandler.java.html#10]]]
} 
@enduml
