@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.streams.errors.StreamsUncaughtExceptionHandler"
class org.apache.kafka.streams.errors.StreamsUncaughtExceptionHandler {
handle(Throwable) : StreamThreadExceptionResponse [[[./../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/errors/StreamsUncaughtExceptionHandler.java.html#24]]]
} 
@enduml
