@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.streams.internals.metrics.ClientMetrics
class org.apache.kafka.streams.internals.metrics.ClientMetrics {
-ClientMetrics() : ClientMetrics [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#19]]]
+version() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#55]]]
+commitId() : String [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#59]]]
+addVersionMetric(StreamsMetricsImpl) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#63]]]
+addCommitIdMetric(StreamsMetricsImpl) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#72]]]
+addApplicationIdMetric(StreamsMetricsImpl;String) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#81]]]
+addTopologyDescriptionMetric(StreamsMetricsImpl;Gauge<String>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#90]]]
+addStateMetric(StreamsMetricsImpl;Gauge<State>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#100]]]
+addNumAliveStreamThreadMetric(StreamsMetricsImpl;Gauge<Integer>) : void [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#110]]]
+failedStreamThreadSensor(StreamsMetricsImpl) : Sensor [[[./../../../../../../../../../../.././qc/streams/src/main/java/org/apache/kafka/streams/internals/metrics/ClientMetrics.java.html#120]]]
} 
@enduml
