@startuml
!pragma layout smetana
"AuthenticateCallbackHandler" <|-- "org.apache.kafka.common.security.plain.internals.PlainServerCallbackHandler"
class org.apache.kafka.common.security.plain.internals.PlainServerCallbackHandler {
+configure(Map<String,?>;String;List<AppConfigurationEntry>) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/plain/internals/PlainServerCallbackHandler.java.html#42]]]
+handle(Callback[]) : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/plain/internals/PlainServerCallbackHandler.java.html#47]]]
authenticate(String;char[]) : boolean [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/plain/internals/PlainServerCallbackHandler.java.html#61]]]
+close() : void [[[./../../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/plain/internals/PlainServerCallbackHandler.java.html#73]]]
} 
@enduml
