@startuml
!pragma layout smetana
Callback <|-- org.apache.kafka.common.security.scram.ScramExtensionsCallback
class org.apache.kafka.common.security.scram.ScramExtensionsCallback {
+extensions() : Map<String,String> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/ScramExtensionsCallback.java.html#14]]]
+extensions(Map<String,String>) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/scram/ScramExtensionsCallback.java.html#19]]]
} 
@enduml
