@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.image.ClientQuotasImage"
class org.apache.kafka.image.ClientQuotasImage {
+ClientQuotasImage(Map<ClientQuotaEntity,ClientQuotaImage>) : ClientQuotasImage [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#58]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#62]]]
entities() : Map<ClientQuotaEntity,ClientQuotaImage> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#66]]]
+write(Consumer<List<ApiMessageAndVersion>>) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#70]]]
+describe(DescribeClientQuotasRequestData) : DescribeClientQuotasResponseData [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#78]]]
-matches(ClientQuotaEntity;Map<String,String>;Set<String>;boolean) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#140]]]
-toDescribeEntry(ClientQuotaEntity;ClientQuotaImage) : EntryData [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#165]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#178]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#185]]]
+toString() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClientQuotasImage.java.html#190]]]
} 
@enduml
