@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.image.ClusterImage"
class org.apache.kafka.image.ClusterImage {
+ClusterImage(Map<Integer,BrokerRegistration>) : ClusterImage [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#41]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#45]]]
+brokers() : Map<Integer,BrokerRegistration> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#49]]]
+broker(int) : BrokerRegistration [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#53]]]
+write(Consumer<List<ApiMessageAndVersion>>;MetadataVersion) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#57]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#66]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#71]]]
+toString() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterImage.java.html#78]]]
} 
@enduml
