@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.image.ClusterDelta"
class org.apache.kafka.image.ClusterDelta {
+ClusterDelta(ClusterImage) : ClusterDelta [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#43]]]
+changedBrokers() : HashMap<Integer,Optional<BrokerRegistration>> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#47]]]
+broker(int) : BrokerRegistration [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#51]]]
+finishSnapshot() : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#59]]]
+handleMetadataVersionChange(MetadataVersion) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#67]]]
+replay(RegisterBrokerRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#71]]]
+replay(UnregisterBrokerRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#76]]]
-getBrokerOrThrow(int;long;String) : BrokerRegistration [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#80]]]
+replay(FenceBrokerRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#94]]]
+replay(UnfenceBrokerRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#102]]]
+replay(BrokerRegistrationChangeRecord) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#110]]]
+apply() : ClusterImage [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#130]]]
+toString() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/ClusterDelta.java.html#154]]]
} 
@enduml
