@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.image.FeaturesImage"
class org.apache.kafka.image.FeaturesImage {
+FeaturesImage(Map<String,Short>;MetadataVersion) : FeaturesImage [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#47]]]
+isEmpty() : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#52]]]
+metadataVersion() : MetadataVersion [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#56]]]
+finalizedVersions() : Map<String,Short> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#60]]]
-finalizedVersion(String) : Optional<Short> [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#64]]]
+write(Consumer<List<ApiMessageAndVersion>>) : void [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#68]]]
+hashCode() : int [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#87]]]
+equals(Object) : boolean [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#92]]]
+toString() : String [[[./../../../../../../../../.././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java.html#100]]]
} 
@enduml
