@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.image.FeaturesDelta
class org.apache.kafka.image.FeaturesDelta {
+ FeaturesDelta(FeaturesImage) : FeaturesDelta [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#22]]]
+ changes() : Map<String,Optional<Short>> [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#26]]]
+ metadataVersionChange() : Optional<MetadataVersion> [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#30]]]
+ finishSnapshot() : void [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#34]]]
+ replay(FeatureLevelRecord) : void [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#42]]]
+ apply() : FeaturesImage [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#54]]]
+ toString() : String [[[././qc/metadata/src/main/java/org/apache/kafka/image/FeaturesDelta.java.html#86]]]
} 
@enduml
