@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.image.ProducerIdsDelta
class org.apache.kafka.image.ProducerIdsDelta {
+  ProducerIdsDelta(ProducerIdsImage)
+  setNextProducerId(long)
+  nextProducerId()
+  finishSnapshot()
+  handleMetadataVersionChange(MetadataVersion)
+  replay(ProducerIdsRecord)
+  apply()
} 
@enduml
