@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.image.TopicsImage
class org.apache.kafka.image.TopicsImage {
+  TopicsImage(Map<Uuid,TopicImage>;Map<String,TopicImage>)
+  isEmpty()
+  topicsById()
+  topicsByName()
+  getPartition(Uuid;int)
+  getTopic(Uuid)
+  getTopic(String)
+  write(Consumer<List<ApiMessageAndVersion>>)
+  equals(Object)
+  hashCode()
+  topicNameToIdView()
+  topicIdToNameView()
+  toString()
} 
@enduml
