@startuml
!pragma layout smetana
"Headers" <|-- "org.apache.kafka.common.header.internals.RecordHeaders"
class org.apache.kafka.common.header.internals.RecordHeaders {
+RecordHeaders() : RecordHeaders [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#35]]]
+RecordHeaders(Header[]) : RecordHeaders [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#39]]]
+RecordHeaders(Iterable<Header>) : RecordHeaders [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#43]]]
+add(Header) : Headers [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#59]]]
+add(String;byte[]) : Headers [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#67]]]
+remove(String) : Headers [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#72]]]
+lastHeader(String) : Header [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#85]]]
+headers(String) : Iterable<Header> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#97]]]
+iterator() : Iterator<Header> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#103]]]
+setReadOnly() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#107]]]
+toArray() : Header[] [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#111]]]
-checkKey(String) : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#115]]]
-canWrite() : void [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#120]]]
-closeAware(Iterator<Header>) : Iterator<Header> [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#125]]]
+equals(Object) : boolean [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#145]]]
+hashCode() : int [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#159]]]
+toString() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/header/internals/RecordHeaders.java.html#164]]]
} 
@enduml
