@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.common.security.auth.AuthenticationContext"
class org.apache.kafka.common.security.auth.AuthenticationContext {
securityProtocol() : SecurityProtocol [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/auth/AuthenticationContext.java.html#31]]]
clientAddress() : InetAddress [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/auth/AuthenticationContext.java.html#36]]]
listenerName() : String [[[./../../../../../../../../../../.././qc/clients/src/main/java/org/apache/kafka/common/security/auth/AuthenticationContext.java.html#41]]]
} 
@enduml
