@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.common.security.auth.KafkaPrincipalSerde
class org.apache.kafka.common.security.auth.KafkaPrincipalSerde {
+  serialize(KafkaPrincipal)
+  deserialize(byte[])
} 
@enduml
