@startuml
!pragma layout smetana
"TypeClassGenerator" <|-- "org.apache.kafka.message.ApiMessageTypeGenerator"
class org.apache.kafka.message.ApiMessageTypeGenerator {
+ApiMessageTypeGenerator(String) : ApiMessageTypeGenerator [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#79]]]
+outputName() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#86]]]
+registerMessageType(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#91]]]
+generateAndWrite(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#135]]]
-generate() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#140]]]
-generateListenerTypeEnumSet(Collection<String>) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#180]]]
-generateEnumValues() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#197]]]
-generateInstanceVariables() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#226]]]
-generateEnumConstructor() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#238]]]
-generateFromApiKey() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#255]]]
-generateNewApiMessageMethod(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#280]]]
-generateAccessor(String;String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#307]]]
-generateToString() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#315]]]
-generateHeaderVersion(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#324]]]
-generateListenerTypesEnum() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#394]]]
-write(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/ApiMessageTypeGenerator.java.html#406]]]
} 
@enduml
