@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.message.FieldType"
class org.apache.kafka.message.FieldType {
parse(String) : FieldType [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#381]]]
getBoxedJavaType(HeaderGenerator) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#429]]]
isArray() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#434]]]
isStructArray() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#441]]]
serializationIsDifferentInFlexibleVersions() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#448]]]
isString() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#455]]]
isBytes() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#462]]]
isRecords() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#469]]]
isFloat() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#476]]]
isStruct() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#483]]]
canBeNullable() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#490]]]
fixedLength() : Optional<Integer> [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#497]]]
isVariableLength() : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#501]]]
toString() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/FieldType.java.html#508]]]
} 
@enduml
