@startuml
!pragma layout smetana
MessageClassGenerator <|-- org.apache.kafka.message.MessageDataGenerator
class org.apache.kafka.message.MessageDataGenerator {
MessageDataGenerator(String) : MessageDataGenerator [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#22]]]
+outputName(MessageSpec) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#30]]]
+generateAndWrite(MessageSpec;BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#35]]]
generate(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#40]]]
write(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#55]]]
-generateClass(Optional<MessageSpec>;String;StructSpec;Versions) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#60]]]
-generateClassHeader(String;boolean;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#125]]]
-generateSubclasses(String;StructSpec;Versions;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#150]]]
-generateHashSet(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#175]]]
-generateHashSetZeroArgConstructor(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#196]]]
-generateHashSetSizeArgConstructor(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#204]]]
-generateHashSetIteratorConstructor(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#213]]]
-generateHashSetFindMethod(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#223]]]
-generateHashSetFindAllMethod(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#235]]]
-generateKeyElement(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#247]]]
-commaSeparatedHashSetFieldAndTypes(StructSpec) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#258]]]
-generateCollectionDuplicateMethod(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#266]]]
-generateFieldDeclarations(StructSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#282]]]
-generateFieldDeclaration(FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#295]]]
-generateFieldAccessors(StructSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#301]]]
-generateUnknownTaggedFieldsAccessor() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#316]]]
-generateFieldMutators(StructSpec;String;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#336]]]
-generateClassConstructors(String;StructSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#352]]]
-generateConstructorEpilogue(boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#374]]]
-generateShortAccessor(String;short) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#382]]]
-generateClassReader(String;StructSpec;Versions) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#391]]]
-primitiveReadExpression(FieldType) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#518]]]
-generateVariableLengthReader(Versions;String;FieldType;Versions;Versions;String;String;boolean;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#544]]]
-generateClassWriter(String;StructSpec;Versions) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#647]]]
-generateCheckForUnsupportedNumTaggedFields(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#817]]]
-primitiveWriteExpression(FieldType;String) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#827]]]
-generateVariableLengthWriter(Versions;String;FieldType;Versions;Versions;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#853]]]
-generateClassMessageSize(String;StructSpec;Versions) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#961]]]
-generateVariableLengthArrayElementSize(Versions;String;FieldType;Versions) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1021]]]
-generateFieldSize(FieldSpec;Versions;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1057]]]
-generateFixedLengthFieldSize(FieldSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1067]]]
-generateVariableLengthFieldSize(FieldSpec;Versions;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1089]]]
-generateStringToBytes(String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1260]]]
-generateClassEquals(String;StructSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1272]]]
-generateFieldEquals(FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1298]]]
-generateClassHashCode(StructSpec;boolean) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1334]]]
-generateFieldHashCode(FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1349]]]
-generateClassDuplicate(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1393]]]
-generateFieldDuplicate(Target) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1409]]]
-generateClassToString(String;StructSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1480]]]
-generateFieldToString(String;FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1497]]]
-generateFieldAccessor(FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1543]]]
-generateAccessor(String;String;String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1550]]]
-generateFieldMutator(String;FieldSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1558]]]
-generateSetter(String;String;String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1587]]]
-fieldFlexibleVersions(FieldSpec) : Versions [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java.html#1595]]]
} 
@enduml
