@startuml
!pragma layout smetana
java.lang.Object <|-- org.apache.kafka.message.MessageGenerator
class org.apache.kafka.message.MessageGenerator {
+  createTypeClassGenerators(String;List<String>)
+  createMessageClassGenerators(String;List<String>)
+  processDirectories(String;String;String;List<String>;List<String>)
+  capitalizeFirst(String)
+  lowerCaseFirst(String)
+  firstIsCapitalized(String)
+  toSnakeCase(String)
+  stripSuffix(String;String)
+  sizeOfUnsignedVarint(int)
+  main(String[])
} 
@enduml
