@startuml
!pragma layout smetana
MessageClassGenerator <|-- org.apache.kafka.message.MessageDataGenerator
class org.apache.kafka.message.MessageDataGenerator {
+  MessageDataGenerator(String)
+  outputName(MessageSpec)
+  generateAndWrite(MessageSpec;BufferedWriter)
+  generate(MessageSpec)
+  write(BufferedWriter)
+  generateClass(Optional<MessageSpec>;String;StructSpec;Versions)
+  generateClassHeader(String;boolean;boolean)
+  generateSubclasses(String;StructSpec;Versions;boolean)
+  generateHashSet(String;StructSpec)
+  generateHashSetZeroArgConstructor(String)
+  generateHashSetSizeArgConstructor(String)
+  generateHashSetIteratorConstructor(String)
+  generateHashSetFindMethod(String;StructSpec)
+  generateHashSetFindAllMethod(String;StructSpec)
+  generateKeyElement(String;StructSpec)
+  commaSeparatedHashSetFieldAndTypes(StructSpec)
+  generateCollectionDuplicateMethod(String)
+  generateFieldDeclarations(StructSpec;boolean)
+  generateFieldDeclaration(FieldSpec)
+  generateFieldAccessors(StructSpec;boolean)
+  generateUnknownTaggedFieldsAccessor()
+  generateFieldMutators(StructSpec;String;boolean)
+  generateClassConstructors(String;StructSpec;boolean)
+  generateConstructorEpilogue(boolean)
+  generateShortAccessor(String;short)
+  generateClassReader(String;StructSpec;Versions)
+  primitiveReadExpression(FieldType)
+  generateVariableLengthReader(Versions;String;FieldType;Versions;Versions;String;String;boolean;boolean)
+  generateClassWriter(String;StructSpec;Versions)
+  generateCheckForUnsupportedNumTaggedFields(String)
+  primitiveWriteExpression(FieldType;String)
+  generateVariableLengthWriter(Versions;String;FieldType;Versions;Versions;boolean)
+  generateClassMessageSize(String;StructSpec;Versions)
+  generateVariableLengthArrayElementSize(Versions;String;FieldType;Versions)
+  generateFieldSize(FieldSpec;Versions;boolean)
+  generateFixedLengthFieldSize(FieldSpec;boolean)
+  generateVariableLengthFieldSize(FieldSpec;Versions;boolean)
+  generateStringToBytes(String)
+  generateClassEquals(String;StructSpec;boolean)
+  generateFieldEquals(FieldSpec)
+  generateClassHashCode(StructSpec;boolean)
+  generateFieldHashCode(FieldSpec)
+  generateClassDuplicate(String;StructSpec)
+  generateFieldDuplicate(Target)
+  generateClassToString(String;StructSpec)
+  generateFieldToString(String;FieldSpec)
+  generateFieldAccessor(FieldSpec)
+  generateAccessor(String;String;String)
+  generateFieldMutator(String;FieldSpec)
+  generateSetter(String;String;String)
+  fieldFlexibleVersions(FieldSpec)
} 
@enduml
