@startuml
!pragma layout smetana
"TypeClassGenerator" <|-- "org.apache.kafka.message.MetadataRecordTypeGenerator"
class org.apache.kafka.message.MetadataRecordTypeGenerator {
+MetadataRecordTypeGenerator(String) : MetadataRecordTypeGenerator [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#16]]]
+outputName() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#23]]]
+registerMessageType(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#28]]]
+generateAndWrite(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#41]]]
-generate() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#46]]]
-generateEnumValues() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#71]]]
-generateInstanceVariables() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#87]]]
-generateEnumConstructor() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#94]]]
-generateFromApiKey() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#105]]]
-generateNewMetadataRecord() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#129]]]
-generateAccessor(String;String) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#154]]]
-generateToString() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#162]]]
-write(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataRecordTypeGenerator.java.html#171]]]
} 
@enduml
