@startuml
!pragma layout smetana
"TypeClassGenerator" <|-- "org.apache.kafka.message.MetadataJsonConvertersGenerator"
class org.apache.kafka.message.MetadataJsonConvertersGenerator {
+MetadataJsonConvertersGenerator(String) : MetadataJsonConvertersGenerator [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#15]]]
+outputName() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#22]]]
+registerMessageType(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#27]]]
+generateAndWrite(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#40]]]
-generateWriteJson() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#55]]]
-generateReadJson() : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/MetadataJsonConvertersGenerator.java.html#82]]]
} 
@enduml
