@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.message.StructRegistry"
class org.apache.kafka.message.StructRegistry {
StructRegistry() : StructRegistry [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#61]]]
register(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#69]]]
-addStructSpecs(Versions;List<FieldSpec>) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#87]]]
findStruct(FieldSpec) : StructSpec [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#126]]]
isStructArrayWithKeys(FieldSpec) : boolean [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#150]]]
commonStructNames() : Set<String> [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#166]]]
commonStructs() : Iterator<StructSpec> [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#173]]]
structs() : Iterator<StructInfo> [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/StructRegistry.java.html#189]]]
} 
@enduml
