@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.message.Target"
class org.apache.kafka.message.Target {
Target(FieldSpec;String;String;Function<String,String>) : Target [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#29]]]
+assignmentStatement(String) : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#37]]]
+nonNullableCopy() : Target [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#41]]]
+arrayElementTarget(Function<String,String>) : Target [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#59]]]
+field() : FieldSpec [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#82]]]
+sourceVariable() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#86]]]
+humanReadableName() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/Target.java.html#90]]]
} 
@enduml
