@startuml
!pragma layout smetana
"java.lang.Object" <|-- "org.apache.kafka.message.TypeClassGenerator"
class org.apache.kafka.message.TypeClassGenerator {
outputName() : String [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/TypeClassGenerator.java.html#28]]]
registerMessageType(MessageSpec) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/TypeClassGenerator.java.html#35]]]
generateAndWrite(BufferedWriter) : void [[[./../../../../../../../../.././qc/generator/src/main/java/org/apache/kafka/message/TypeClassGenerator.java.html#42]]]
} 
@enduml
